### ISSUE TITLE
Rethink simplify and ptype argument in hoist() and unnest_*()

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#1000]
After finding the issues `tidyr:::simplify_col()` (see #995, #996, #998, and #999) with the `simplify` and `ptype` argument I thought it might be worth to change the logic and simply get rid of the `simplify` argument. For example something like this might do the job

``` r
library(purrr)
library(vctrs)
library(rlang)

simplify_col <- function(x, nm, ptype = list(), transform = list()) {
  transform <- transform[[nm]]
  ptype <- ptype[[nm]]

  if (!is.null(transform)) {
    transform <- as_function(transform)
    x <- map(x, transform)
  }
  
  if (inherits(ptype, "AsIs")) {
    x
  } else if (is.null(ptype)) {
    tryCatch(
      vec_c(!!!x),
      vctrs_error_incompatible_type = function(e) x
    )
  } else {
    vec_c(!!!x, .ptype = ptype)
  }
}


# record style objects
x_rcrd <- rep(list(as.POSIXlt(Sys.time())), 2)
simplify_col(x_rcrd, nm = "rcrd", ptype = list(rcrd = x_rcrd[[1]]))
#> [1] "2020-07-16 09:31:21 UTC" "2020-07-16 09:31:21 UTC"
simplify_col(x_rcrd, nm = "rcrd", ptype = list(rcrd = I("")))
#> [[1]]
#> [1] "2020-07-16 09:31:21 UTC"
#> 
#> [[2]]
#> [1] "2020-07-16 09:31:21 UTC"

# list_of columns
x_list_of <- list("a", c("b", "c"))
simplify_col(
  x_list_of,
  nm = "list_of",
  ptype = list(list_of = list_of(.ptype = character())),
  transform = list(list_of = ~ list_of(.x, .ptype = character()))
)
#> <list_of<character>[2]>
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b" "c"
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This way:
* all prototypes work
* one got rid of an argument (and therefore the value of `simplify` cannot influence the action of `ptype` anymore)
* record style objects can be combined

In the case of `list_of` I don't really like casting every element to a `list_of` and then combining them afterwards while a simple `list_of(!!!x)` would be sufficient. Of course one could avoid this by giving control what should happen to the vector at the end (something like `transform_result`) but this would also make the user interface more complicated. For example something like

```r
simplify_col2 <- function(x, nm, ptype = list(), transform = list()) {
  transform <- transform[[nm]]
  ptype <- ptype[[nm]]

  if (!is.null(transform)) {
    transform <- as_function(transform)
    x <- map(x, transform)
  }
  
  if (is.function(ptype) || is_formula(ptype)) {
    ptype <- as_function(ptype)
    ptype(x)
  } else if (is.null(ptype)) {
    tryCatch(
      vec_c(!!!x),
      vctrs_error_incompatible_type = function(e) x
    )
  } else {
    vec_c(!!!x, .ptype = ptype)
  }
}
```

**Comment by hadley** [comment]
Could you use a `ptype` of `list()` to indicate that you don't want something simpler?

**Comment by lionel-** [comment]
I suspect `vec_simplify()` (which will be in vctrs 0.4.0) should assemble lists of size-1 elements into atomic vectors exclusively. Having a "list" target type would make things confusing.

If you want to create a `list_of()` from the list of elements, a "transform" is probably a better approach than simplification with a prototype.

**Comment by mgirlich** [comment]
> I suspect `vec_simplify()` (which will be in vctrs 0.4.0) should assemble lists of size-1 elements into atomic vectors exclusively. Having a "list" target type would make things confusing.

Just for clarification: what do you mean with atomic vector here? I thought atomic refers to vectors of type "logical", "integer", "double", "complex", "character", "raw". But I guess you also include other types.

> If you want to create a `list_of()` from the list of elements, a "transform" is probably a better approach than simplification with a prototype.

The thing I like about the `.ptype` argument is that you have a clear specification about the output type. To me it feels a bit confusing that one could not use it for all columns but only "vector" columns.
