### ISSUE TITLE
`crossing` crashes with fable input

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverse/tidyr#1004]
I'm not exactly sure what is causing the problem to try and simplify the `reprex`, but this causes my R session to crash. 

```
library(dplyr)
library(fable)
library(tidyr)

USAccDeaths %>% as_tsibble() %>% model(arima = ARIMA(value)) %>% forecast() %>% hilo(level = 95) %>% crossing(a=list(.))
```

**Comment by hadley** [comment]
You should file this with the fable developers

**Comment by TylerGrantSmith** [comment]
@hadley I don't think that it is.  Here is a smaller reprex that still crashes

```
x <- data.frame(bar = vctrs::new_rcrd(list(foo = 1:2)))
tidyr::crossing(x, y=list(x))
```

**Comment by TylerGrantSmith** [comment]
It seems to be an issue with `vctrs::vec_slice`, I will post the issue on the `vctrs` repo.

**Comment by lionel-** [comment]
Now tracked in rlang, thanks @TylerGrantSmith for investigating the cause!
