### ISSUE TITLE
one hot decode feature

### ISSUE THREAD

**Issue by Athospd** [tidyverse/tidyr#1013]
Once a colleague of mine asked how to "undo" one-hot encoding (or do one-hot decode, maybe =P). The solutions we found were never as simple as we thought it could be. It looks like a nice-to-have feature. 
And I came here to ask your opinion on that cuz judging by the solutions we found it looks like it belongs to this package:

``` r
library(tidyverse)
df <- tibble(
    id = c(1,2,3),
    
    x1 = c(1,0,0),
    x2 = c(0,1,0),
    x3 = c(0,0,1)
)

# way I
df %>%
    pivot_longer(c(x1:x3), names_to = "x") %>%
    filter(value == 1) %>%
    select(-value)
#> # A tibble: 3 x 2
#>      id x    
#>   <dbl> <chr>
#> 1     1 x1   
#> 2     2 x2   
#> 3     3 x3

# way II
df %>%
    nest(x = c(x1:x3)) %>%
    mutate(
        x = map_chr(x, ~names(which.max(unlist(.x))))
    )
#> # A tibble: 3 x 2
#>      id x    
#>   <dbl> <chr>
#> 1     1 x1   
#> 2     2 x2   
#> 3     3 x3

# way III (not optimal solution once it depends on paste("x",...)
df %>%
    rowwise() %>%
    mutate(
        x = paste0("x", which.max(c_across(x1:x3)))
    )
#> # A tibble: 3 x 5
#> # Rowwise: 
#>      id    x1    x2    x3 x    
#>   <dbl> <dbl> <dbl> <dbl> <chr>
#> 1     1     1     0     0 x1   
#> 2     2     0     1     0 x2   
#> 3     3     0     0     1 x3
```

<sup>Created on 2020-08-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package:  developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
