### ISSUE TITLE
dtidyr package

### ISSUE THREAD

**Issue by kendonB** [tidyverse/tidyr#1015]
We have the amazing package dtplyr that, among other things, helps us speed up `group_by %>% summarise`. Common operations that could be sped up big time in `tidyr` are `unnest` (https://www.r-bloggers.com/much-faster-unnesting-with-data-table/) and `pivot_wider/pivot_longer` (`dcast` and `melt`). Any plans to make a `dtidyr` package to supplement `dtplyr`?

**Comment by kendonB** [comment]
May depend on https://github.com/Rdatatable/data.table/issues/2146

**Comment by smingerson** [comment]
@kendonB, there is https://github.com/TysonStanley/tidyfast. It implements variants of `unnest_*()` and `pivot_*()` functions, among others.

**Comment by markfairbanks** [comment]
@kendonB @smingerson check out my package `tidytable`. Should cover all of your `tidyr` needs until something like "dtidyr" comes out.

@smingerson I actually contributed the `dt_pivot_*()` functions to `tidyfast`. The `tidytable` versions are the "new and improved" versions. They allow you to use all tidyselect helpers (`everything()`, `starts_with()`, `ends_with()`, etc.), and are also `rlang` compatible.

GitHub: https://github.com/markfairbanks/tidytable
Function List: https://markfairbanks.github.io/tidytable/reference/index.html

**Comment by hadley** [comment]
I don't have plans to do this at the moment, but it looks like there are plenty of other options to try.
