### ISSUE TITLE
tidyr 1.1.1 cannot be installed on centOS 7

### ISSUE THREAD

**Issue by FelixErnst** [tidyverse/tidyr#1016]
`tidyr` `1.1.1` cannot be installed on `centOS 7`

---

Starting from a `centOS 7` docker image, install dependencies of `tidyr`

Installing `1.1.0` from archive works
```
Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.0.tar.gz")'
```

Installing `1.1.1` does not.
```
Rscript -e 'install.packages("tidyr")'
...
opt/R/4.0.2/lib/R/site-library/cpp11/include/cpp11/as.hpp:77:39:   required from ‘cpp11::is_logical<T> cpp11::as_cpp(SEXP) [with T = bool; cpp11::is_logical<T> = bool; SEXP = SEXPREC*]’
cpp11.cpp:24:452:   required from here
/opt/R/4.0.2/lib/R/site-library/cpp11/include/cpp11/protect.hpp:202:38: error: using invalid field ‘cpp11::stop(const char*, Args ...)::__lambda2::__args’
   unwind_protect([&] { Rf_error(fmt, args...); });
                                      ^
make: *** [cpp11.o] Error 1
ERROR: compilation failed for package ‘tidyr’
* removing ‘/opt/R/4.0.2/lib/R/site-library/tidyr’
* restoring previous ‘/opt/R/4.0.2/lib/R/site-library/tidyr’
```

I guess this is due to new dependencies from the `cpp11` package and incompatibility with `gcc 4.8.5` shipping with `centOS 7`

Are you aware of this? Is that meant as `We are not "supporting" centOS 7 anymore`?

I am still testing, whether I can reverse confirm this by installing a newer `gcc` from source. In progress...

**Comment by hadley** [comment]
Please see details and work around in https://github.com/r-lib/cpp11/issues/69
