### ISSUE TITLE
Problem that all pivot function doesn't appear

### ISSUE THREAD

**Issue by mohamednei** [tidyverse/tidyr#1018]
When write the code below

library(tidyr)
library(dplyr)
library(readr)

pivoted <- grouping %>% pivot_wider(names_from = country_sku,
                                    values_from = Sales,
                                    values_fill = 0)

tidyr current version is 0.8.3 
I got this error
  could not find function "pivot_wider"

**Comment by rjpat** [comment]
Hi @mohamednei, the pivot_* functions were [released in tidyr 1.0.0](https://www.tidyverse.org/blog/2019/09/tidyr-1-0-0/#pivoting) so updating your package should correct this. Can update all the tidyverse packages and ensure you have the new helper packages in one go with the below;
`install.packages('tidyverse')`

**Comment by mohamednei** [comment]
I tried to install it but the only version installed as i mentioned above ,
Does there is a way ro install it manually by using download file?

**Comment by mohamednei** [comment]
i downloaded it manully but i got this error

Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.1.0 is being loaded, but >= 0.3.0 is required
>

**Comment by rjpat** [comment]
This just means your `{vctrs}` package is out of date and also needs to be updated. Does it give you any feedback when trying to install the `{tidyverse}`? Are you using any package management tools that could stop it from updating?
