### ISSUE TITLE
extract () function to separate a column

### ISSUE THREAD

**Issue by IvanaOsredek** [tidyverse/tidyr#1020]
Hello:)
I hope you might help.

My cdr3s_aa column in df looks like this: TRA:CILRGVYNNNDMRF;TRA:CAFMYNNDMRF;TRB:CATGGGRTSNEQFF;TRB:CASSLGGAYEQYF

I was thinking to use extract () to devide this column into two called alpha and beta. Alpha column would then have only TRA sequences where beta only TRB.

I got stuck on the regex, so could you please suggest how it could look like? This is how my code looks like now:

aa_frequency <- reactive_tcr1 %>% extract (cdr3s_aa, into = c("alpha", "beta"), regex = "([^TRA;])-([^TRB;])", remove = FALSE)

However, this doesn't find any groups. 

Thanks!

**Comment by batpigandme** [comment]
Hi Ivana,

This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

Thanks
