### ISSUE TITLE
Typo in expand_grid docs

### ISSUE THREAD

**Issue by mike-lawrence** [tidyverse/tidyr#1025]
In the Value section, it should say "Varies the first element slowest" (currently says "fastest"). I also suggest changing "Compared to expand.grid" to "Compared to expand.grid, expand_grid will:"

**Comment by MartaDiaz** [comment]
I have the same issue

**Comment by mike-lawrence** [comment]
@MartaDiaz can you please clarify? This issue is about a typo in the help page.
