### ISSUE TITLE
tidyr Version 1.1.1 does not build on CRAN any more

### ISSUE THREAD

**Issue by nevrome** [tidyverse/tidyr#1026]
I got a message today that our R package c14bazAAR does not complete CRAN checks any more. Indeed I see the following error message in (so far) r-devel-linux-x86_64-debian-clang, r-devel-linux-x86_64-debian-gcc and r-release-linux-x86_64.

> using R Under development (unstable) (2020-08-10 r79000)
> using platform: x86_64-pc-linux-gnu (64-bit)
> using session charset: ISO8859-15
> checking for file 'c14bazAAR/DESCRIPTION' ... OK
> this is package 'c14bazAAR' version '1.2.0'
> package encoding: UTF-8
> checking package namespace information ... OK
> checking package dependencies ... ERROR
> Package required but not available: 'tidyr'
> 
> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
> manual.
> DONE
> Status: 1 ERROR

This seems to be caused by a problem with tidyr:

![image](https://user-images.githubusercontent.com/10789038/89999674-661f9000-dc8f-11ea-9b3c-af7019c01714.png)

> using R Under development (unstable) (2020-08-10 r79000)
> using platform: x86_64-pc-linux-gnu (64-bit)
> using session charset: ISO8859-15
> checking for file 'tidyr/DESCRIPTION' ... OK
> this is package 'tidyr' version '1.1.1'
> package encoding: UTF-8
> checking package namespace information ... OK
> checking package dependencies ... OK
> checking if this is a source package ... OK
> checking if there is a namespace ... OK
> checking for executable files ... OK
> checking for hidden files and directories ... OK
> checking for portable file names ... OK
> checking for sufficient/correct file permissions ... OK
> checking serialization versions ... OK
> checking whether package 'tidyr' can be installed ... ERROR
> Installation failed.
> See '/home/hornik/tmp/R.check/r-devel-clang/Work/PKGS/tidyr.Rcheck/00install.out' for details.
> DONE
> See [https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/tidyr-00install.html](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/tidyr-00install.html) for details.

Is our issue indeed caused by a problem in tidyr?
Do you have a plan to fix this?
If so: Do you think this might be solved before 2020-08-26?

Thank you very much!

**Comment by hadley** [comment]
This has already been fixed with the latest version of cpp11 😄

**Comment by nevrome** [comment]
Ah - I see. The Errors both in tidyr and c14bazAAR seem to go away already. 

Thank you :+1:
