### ISSUE TITLE
Including an interleave function in tidyr

### ISSUE THREAD

**Issue by jdtrat** [tidyverse/tidyr#1027]
Hi! This is so exciting! My first Github Issue. I've found that I recently needed to combine two data frames, alternating rows from each. One time, I needed to do this with two different sized data frames and did not find any functions that worked as needed, so I wrote my own. I think it may be useful to others and hope to contribute it if there's interest. 

Below is my proposed solution. I've included a check argument for easy validation, and some examples to run:

## Function
``` r
interleave <- function(x, y, n, check = FALSE) {
  if (base::names(x) != base::names(y)) {
    stop("Column names are not equal. Cannot interleave.")
  }


  if (check) {

    # Add the source and row number for easy validation
    x <- x %>% dplyr::mutate(
      source = "x",
      row = dplyr::row_number()
    )
    y <- y %>% dplyr::mutate(
      source = "y",
      row = dplyr::row_number()
    )
  }

  # initialize counters
  i <- 1
  j <- 1
  combine <- NULL

  # if combine is NULL, then
  # just bind the first row of x
  # with the first n rows of y
  if (base::is.null(combine)) {
    xRow <- dplyr::slice(x, i)
    yRow <- dplyr::slice(y, j:(j + (n - 1)))
    combine <- dplyr::bind_rows(xRow, yRow)
    j <- j + n
  }

  # for every row in x, starting at 2,
  # get the n rows in y and bind them in order.
  # save as combine.
  for (i in 2:base::nrow(x)) {
    xRow <- dplyr::slice(x, i)
    yRow <- dplyr::slice(y, j:(j + (n - 1)))
    combine <- dplyr::bind_rows(combine, xRow, yRow)
    j <- j + n
  }

  return(combine)
}
```

<sup>Created on 2020-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Examples:

```r
# Interleave by every row:
yesData <- dplyr::tibble("response" = base::rep("yes", 5))
noData <- dplyr::tibble("response" = base::rep("no", 5))

responseData <- interleave(x = yesData, y = noData, n = 1)

# Interleave by every 2 rows
firstSet <- dplyr::tibble("data" = base::seq(1, 10))
secondSet <- dplyr::tibble("data" = base::seq(1, 20))

responseData2 <- interleave(x = firstSet, y = secondSet, n = 2)

# Sanity check
responseData2Check <- interleave(x = firstSet, y = secondSet, n = 2)

```

**Comment by DavisVaughan** [comment]
We are tracking this in vctrs and funs https://github.com/r-lib/vctrs/issues/1396, https://github.com/tidyverse/funs/issues/10#issuecomment-832568731

I think interleaving is low level enough and uncommon enough that only putting it in one of those two packages makes the most sense. TBH I think it is fairly uncommon to interleave data frames.
