### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by lozalojo** [tidyverse/tidyr#1030]
In new tidyr 1.1.1 version i get the following error when using extract: "Error in regexpr(regex, string, perl = TRUE) : 
  regular expression '^([:alpha:]{2})(_([:alpha:]{2}))?(([\.]+)([^\.]+))?$' invalid"
Previously worked fine, Ive tested going back to 1.1.0 and with that version, it works.

See following example:

``` r
library(tidyr)
locales <- data.frame(filename=c("af_ZA.UTF-8","sq_AL.UTF-8","ar_SA.UTF-8")) %>%
  tidyr::extract(filename,
                 into = c("language.iso_639_1", "v1", "country.iso_3166", "v2", "v3", "encoding"),
                 '^([:alpha:]{2})(_([:alpha:]{2}))?(([\\.]+)([^\\.]+))?$', remove = F
  )
```

<sup>Created on 2020-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
We changed regular expression engines to something a little stricter - your current expression is technically incorrect as you should be using `[[:alpha:]]`.
