### ISSUE TITLE
unnest_longer() doesn't work with single row nested data frames

### ISSUE THREAD

**Issue by ricardonfc** [tidyverse/tidyr#1034]
I'm sorry, I'm new to tidyr package and I would be grateful if someone could explain me this behaviour. So, I've noticed that unnest_longer() is not able to unnest single row nested data frames as unnest() do. Is it expected to behave like this?

Here is a small example:

```R
library(tidyr)
library(magrittr)

nested_a <- tibble(A = 'a', B = 'b', C = 'c')
test_a <- tibble( col = list(nested_a) )

test_a %>% tidyr::unnest_longer(col)

#> Error: Assigned data `map2(...)` must be compatible with existing data.
#> x Existing data has 1 row.
#> x Assigned data has 3 rows.
#> i Row updates require a list value. Do you need `list()` or `as.list()`?
#> Run `rlang::last_error()` to see where the error occurred.
```

It works with unnest():

```R
test_a %>% tidyr::unnest(col)

#> # A tibble: 1 x 3
#>   A     B     C    
#>   <chr> <chr> <chr>
#> 1 a     b     c  
```

```R
Also with nested data frames with 2+ rows:

nested_b <- tibble( A = c('a', 'a'), B = c('b', 'b'), C = c('c', 'c') )
test_b <- tibble( col = list(nested_b))

test_b %<>% tidyr::unnest_longer(col)
test_b %>% unpack(col)

#> # A tibble: 2 x 3
#>   A     B     C    
#>   <chr> <chr> <chr>
#> 1 a     b     c    
#> 2 a     b     c 
```

**Comment by hadley** [comment]
Hmmm, seems like a bug to me.

**Comment by DavisVaughan** [comment]
Seems to be because `tidyr:::simplify_col()` uses `is.list()` here when it should be using `vec_is_list()`. It is recognizing a data frame as a list by mistake. Hopefully an easy fix.

https://github.com/tidyverse/tidyr/blob/2fd80d51351cef55cbd0d5ae8ddde58a8fb6be48/R/rectangle.R#L371-L373
