### ISSUE TITLE
values_transform should accept a single function

### ISSUE THREAD

**Issue by smingerson** [tidyverse/tidyr#1035]
I would expect that providing a single function to `values_transform` in `pivot_longer()` would apply to each column selected for pivoting (x and y in my example). This would be consistent to the recent change in `pivot_wider()`, from the News: 

> arguments values_fn and values_fill can now be single values; you now only need
to use a named list if you want to use different values for different value columns (#739, #746). 
They also get improved errors if they're not of the expected type.

```r
library(tidyr)
packageVersion("tidyr")
#> [1] '1.1.0'

df <- data.frame(x = 1:5, y = letters[1:5], stringsAsFactors = FALSE)

pivot_longer(df, c(x, y), values_transform = as.character)
#> Error: Can't combine `x` <integer> and `y` <character>.
```
If I do `pivot_longer(df, c(x, y), values_transform = list(value = as.character))`, it works as expected. 

If you agree this is a desired change, I would be happy to submit a PR, and I will also create a similar issue for `values_ptypes` (where I always face the same confusion).

**Comment by hadley** [comment]
A PR would be great thanks!

**Comment by DavisVaughan** [comment]
Tracking in #1284
