### ISSUE TITLE
Hoist and pluck return different values when extracting NULL list-elements

### ISSUE THREAD

**Issue by mattwarkentin** [tidyverse/tidyr#1044]
Hi,

Unless I am doing something wrong, it seems like `purrr::pluck()` and `tidyr::hoist()` return different values when subsetting a `NULL` list element. The reason I posted the issue here is because I think `pluck()` does the expected behaviour, meanwhile `hoist()` is doing some coercion. When `hoist`ing a `NULL` list-element it seems to be getting coerced to `NA`.
``` r
library(tidyverse)

foo <- function() stop("This won't run")

safe_foo <- safely(foo)

safe_foo()
#> $result
#> NULL
#> 
#> $error
#> <simpleError in .f(...): This won't run>

pluck(safe_foo(), "result")
#> NULL
pluck(safe_foo(), "error")
#> <simpleError in .f(...): This won't run>

tibble(a = 1:3) %>% 
  mutate(b = map(a, safe_foo)) %>% 
  hoist(b, "result", "error")
#> # A tibble: 3 x 3
#>       a result error     
#>   <int> <lgl>  <list>    
#> 1     1 NA     <smplErrr>
#> 2     2 NA     <smplErrr>
#> 3     3 NA     <smplErrr>
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattwarkentin** [comment]
Actually, upon further inspection it seems like `pluck()` is just returning the `.default` value. I thought that only happened when a list-element didn't exist. Doesn't `result` exist in the list, it just happens to have the value `NULL`?
``` r
library(tidyverse)

foo <- function() stop("This won't run")

safe_foo <- safely(foo)

safe_foo()
#> $result
#> NULL
#> 
#> $error
#> <simpleError in .f(...): This won't run>

pluck(safe_foo(), "result", .default = "test")
#> [1] "test"
pluck(safe_foo(), "error", .default = "test")
#> <simpleError in .f(...): This won't run>

tibble(a = 1:3) %>% 
  mutate(b = map(a, safe_foo)) %>% 
  hoist(b, "result", "error")
#> # A tibble: 3 x 3
#>       a result error     
#>   <int> <lgl>  <list>    
#> 1     1 NA     <smplErrr>
#> 2     2 NA     <smplErrr>
#> 3     3 NA     <smplErrr>
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
Maybe related to https://github.com/tidyverse/purrr/issues/480

**Comment by DavisVaughan** [comment]
Worth mentioning that you can avoid the "simplification" of the `NULL` into `NA` by setting `simplify = FALSE`. So I don't consider this part a bug:

``` r
library(tidyr)

col <- list(
  list(a = NULL, b = 1),
  list(a = NULL, b = 2)
)

df <- tibble(col = col)

hoist(df, col, "a", "b")
#> # A tibble: 2 × 2
#>   a         b
#>   <lgl> <dbl>
#> 1 NA        1
#> 2 NA        2

hoist(df, col, "a", "b", .simplify = FALSE)
#> # A tibble: 2 × 2
#>   a      b        
#>   <list> <list>   
#> 1 <NULL> <dbl [1]>
#> 2 <NULL> <dbl [1]>
```

However, the type-instability mentioned above (with `integer()`) is a bug, but we won't be able to do anything without changes in purrr.
