### ISSUE TITLE
Documentation on 'values_fn' argument of 'pivot_wider' seems to be wrong

### ISSUE THREAD

**Issue by junghoon-shin** [tidyverse/tidyr#1049]
In the documentation of `pivot_wider`, the `values_fn` argument is described as follows.

> Optionally, a function applied to the `value` in each cell in the output. You will typically use this when the combination of `id_cols` and `value` column does not uniquely identify an observation.

I think it should be

> Optionally, a function applied to the `value` in each cell in the output. You will typically use this when the combination of `id_cols` and `name` column does not uniquely identify an observation.

**Comment by batpigandme** [comment]
That looks good. Would you like to submit a PR? Since we use roxygen2, the edit would go right in the param description in the file below:
https://github.com/tidyverse/tidyr/blob/501a757bf983a3eb6e82f53173672a92d828236f/R/pivot-wide.R#L49

**Comment by hadley** [comment]
Are you sure that's correct? It think it's the `value` column that matters here.

**Comment by junghoon-shin** [comment]
@hadley The `value` column(s) should contain data values specific to each combination of `id_cols` and `name` column values. Hence I think the `value` column has nothing to do with identifying an observation.

**Comment by junghoon-shin** [comment]
Distinguishing multiple value columns is the job of `names_sep` and `names_glue`.
