### ISSUE TITLE
'AND' logic when specifying columns with drop_na()

### ISSUE THREAD

**Issue by daranzolin** [tidyverse/tidyr#1054]
Using drop_na, I frequently want to drop NAs within multiple columns using AND logic instead of the default OR. 

For example, consider the `penguins` dataset from {palmerpenguins}. There are two rows where BOTH body_mass_g and sex are NA:

``` r
library(hacksaw)
library(palmerpenguins)

penguins %>% 
  keep_na(body_mass_g, sex)
#> # A tibble: 2 x 8
#>   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
#>   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
#> 1 Adelie  Torge…             NA            NA               NA          NA <NA> 
#> 2 Gentoo  Biscoe             NA            NA               NA          NA <NA> 
#> # … with 1 more variable: year <int>
```

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The following, however, removes *all* the NAs from sex, some of which I want to preserve:

``` r
library(tidyverse)
library(palmerpenguins)

penguins %>% 
  drop_na(body_mass_g, sex)
#> # A tibble: 333 x 8
#>    species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g
#>    <fct>   <fct>           <dbl>         <dbl>            <int>       <int>
#>  1 Adelie  Torge…           39.1          18.7              181        3750
#>  2 Adelie  Torge…           39.5          17.4              186        3800
#>  3 Adelie  Torge…           40.3          18                195        3250
#>  4 Adelie  Torge…           36.7          19.3              193        3450
#>  5 Adelie  Torge…           39.3          20.6              190        3650
#>  6 Adelie  Torge…           38.9          17.8              181        3625
#>  7 Adelie  Torge…           39.2          19.6              195        4675
#>  8 Adelie  Torge…           41.1          17.6              182        3200
#>  9 Adelie  Torge…           38.6          21.2              191        3800
#> 10 Adelie  Torge…           34.6          21.1              198        4400
#> # … with 323 more rows, and 2 more variables: sex <fct>, year <int>
```

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

My workaround is to sum the NAs via mutate and then filter. But my dream syntax 😊  would be something like:

```
penguins %>% 
  drop_na(body_mass_g, sex, .logic = "AND")
```
 Does this sound reasonable? Or perhaps a fringe case?

**Comment by daranzolin** [comment]
Quick follow-up: I implemented the reverse logic in `hacksaw::keep_na`:

``` r
library(hacksaw)
library(palmerpenguins)
library(tidyverse)

penguins %>% 
  select(species, body_mass_g, sex) %>% 
  keep_na(body_mass_g, sex)
#> # A tibble: 2 x 3
#>   species body_mass_g sex  
#>   <fct>         <int> <fct>
#> 1 Adelie           NA <NA> 
#> 2 Gentoo           NA <NA>

penguins %>% 
  select(species, body_mass_g, sex) %>% 
  keep_na(body_mass_g, sex, .logic = "OR")
#> # A tibble: 13 x 3
#>    species body_mass_g sex  
#>    <fct>         <int> <fct>
#>  1 Adelie           NA <NA> 
#>  2 Gentoo           NA <NA> 
#>  3 Adelie           NA <NA> 
#>  4 Adelie         3475 <NA> 
#>  5 Adelie         4250 <NA> 
#>  6 Adelie         3300 <NA> 
#>  7 Adelie         3700 <NA> 
#>  8 Adelie         2975 <NA> 
#>  9 Gentoo         4100 <NA> 
#> 10 Gentoo         4650 <NA> 
#> 11 Gentoo         4725 <NA> 
#> 12 Gentoo         4875 <NA> 
#> 13 Gentoo           NA <NA>
```

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I think dropping instead of keeping NAs in a similar fashion would be very useful.

**Comment by mgirlich** [comment]
With the new `across()` function from `dplyr` you can easily do the following

    library(dplyr)

    palmerpenguins::penguins %>% 
      filter(across(c(body_mass_g, sex), .fns = is.na))
    #> # A tibble: 2 x 8
    #>   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
    #>   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
    #> 1 Adelie  Torge…             NA            NA               NA          NA <NA> 
    #> 2 Gentoo  Biscoe             NA            NA               NA          NA <NA> 
    #> # … with 1 more variable: year <int>

<sup>Created on 2020-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Also see https://github.com/tidyverse/tidyr/issues/939

**Comment by hadley** [comment]
Thanks @mgirlich!

**Comment by e-leib** [comment]
I'm also looking for something similar to this, where I want to drop NA from body_mass_g AND sex (but for 7 columns). @mgirlich, thank you for that code, it is helpful for filtering for rows that have NAs in both of the columns, but I'm looking for the opposite, to _drop_ rows that have NAs in both columns as opposed to keep them.

**Comment by DavisVaughan** [comment]
vctrs is a bit of a lower level package, but it has something that could help here. `across()` returns a data frame, and `vec_equal_na()` on a data frame will return `TRUE` if the entire row contains missing values. So you could do something like:

``` r
library(vctrs)
library(dplyr, warn.conflicts = FALSE)

palmerpenguins::penguins %>% 
  filter(!vec_equal_na(across(c(body_mass_g, sex))))
#> # A tibble: 342 × 8
#>    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
#>    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
#>  1 Adelie  Torgersen           39.1          18.7               181        3750
#>  2 Adelie  Torgersen           39.5          17.4               186        3800
#>  3 Adelie  Torgersen           40.3          18                 195        3250
#>  4 Adelie  Torgersen           36.7          19.3               193        3450
#>  5 Adelie  Torgersen           39.3          20.6               190        3650
#>  6 Adelie  Torgersen           38.9          17.8               181        3625
#>  7 Adelie  Torgersen           39.2          19.6               195        4675
#>  8 Adelie  Torgersen           34.1          18.1               193        3475
#>  9 Adelie  Torgersen           42            20.2               190        4250
#> 10 Adelie  Torgersen           37.8          17.1               186        3300
#> # … with 332 more rows, and 2 more variables: sex <fct>, year <int>
```

<sup>Created on 2022-01-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment]
By now the functions `if_any()` and `if_all()` have been added which are perfect for filtering:

``` r
library(dplyr, warn.conflicts = FALSE)

palmerpenguins::penguins %>% 
  filter(!if_any(c(body_mass_g, sex), is.na)) %>%
  select(body_mass_g, sex)
#> # A tibble: 333 × 2
#>    body_mass_g sex   
#>          <int> <fct> 
#>  1        3750 male  
#>  2        3800 female
#>  3        3250 female
#>  4        3450 female
#>  5        3650 male  
#>  6        3625 female
#>  7        4675 male  
#>  8        3200 female
#>  9        3800 male  
#> 10        4400 male  
#> # … with 323 more rows

# or maybe you prefer the `if_all()` version
palmerpenguins::penguins %>% 
  filter(if_all(c(body_mass_g, sex), ~ !is.na(.x))) %>%
  select(body_mass_g, sex)
#> # A tibble: 333 × 2
#>    body_mass_g sex   
#>          <int> <fct> 
#>  1        3750 male  
#>  2        3800 female
#>  3        3250 female
#>  4        3450 female
#>  5        3650 male  
#>  6        3625 female
#>  7        4675 male  
#>  8        3200 female
#>  9        3800 male  
#> 10        4400 male  
#> # … with 323 more rows
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by e-leib** [comment]
@mgirlich Thank you, that is exactly what I was looking for! I had tried to do something like that, but was putting the '!' in the wrong place. Makes good sense to me now that it would go before the if_any. Thank you!
