### ISSUE TITLE
Nest page with code block rendering issue

### ISSUE THREAD

**Issue by erictleung** [tidyverse/tidyr#1055]
Brief description of the problem:

The documentation page for `nest()` has a code block that doesn't render correctly https://tidyr.tidyverse.org/reference/nest.html#new-syntax.

Currently, it looks like

```
library(tidyr)
nest &lt;- nest_legacy
unnest &lt;- unnest_legacy
```

These lines of code in the code (https://github.com/tidyverse/tidyr/blob/master/R/nest.R#L19-L23) don't look suspicious because the same syntax and issue with the `<` symbol doesn't appear to be a problem in another [`pkgdown` site](https://pkgdown.r-lib.org/reference/build_site.html#yaml-config) (source: https://github.com/r-lib/pkgdown/blob/master/R/build.r#L48-L55). I'd try to fix this but I'm unsure how.

**Comment by hadley** [comment]
I think this was a bug in pkgdown — it looks fine in the dev version which has been re-built more recently. I'll have a go at doing a manual rebuild and redploy of the site.

**Comment by hadley** [comment]
Looks good now :smile:
