### ISSUE TITLE
r programming group by not working after gather function

### ISSUE THREAD

**Issue by lis-stack** [tidyverse/tidyr#1057]
library(readxl)
emp <- read_excel("~/emp.xlsx", sheet = "Sheet2") 
view(emp)  
  
  
  emp_minor.long <-emp %>%
   gather(date, val, `36526`:`44075`, convert = TRUE) %>% # gathering dates and values
    mutate(date = excel_numeric_to_date(date)) %>%  convert excel dates to dates i.e. 43831 to 01/01/2000
group_by(i4Minor) %>%# not working  
  summarise_all(sum)#not working
  view(emp_minor.long)

**Comment by lis-stack** [comment]
this is after i mutated
4Minor                        date          val
  <chr>                          <date>      <dbl>
1 Agriculture                    2000-01-01 2613  
2 Forestry, fishing, and hunting 2000-01-01   80.3
3 Mining                         2000-01-01  126. 
4 Mining                         2000-01-01   73.7
5 Mining                         2000-01-01   38.7
6 Mining                         2000-01-01  115.

**Comment by romatik** [comment]
This is not an appropriate question for this forum. I recommend you ask at https://community.rstudio.com/, but be sure to prepare a reprex for your problem (more info here - https://reprex.tidyverse.org/).

Right now it's impossible to help you since only you have the file you are working with.
