### ISSUE TITLE
unnest_wider() and messages with unnamed lists

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/tidyr#1060]
Suppose you have a list with unnamed elements in a data frame column and you `unnest_wider()` that column. 

``` r
library(tidyverse)

tibble(
  x = list(
    list(1,2,3),
    list(4,5,6),
    list(7,8,9)
  )
) %>% 
  unnest_wider(x)
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> * `` -> ...3
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> * `` -> ...3
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> * `` -> ...3
#> # A tibble: 3 x 3
#>    ...1  ...2  ...3
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The message about New names is repeated as many times as the number of rows, which seems undesirable. I think either hiding that message overall or showing it once would be preferable.

**Comment by hadley** [comment]
And maybe have `names_prefix` argument to make it easier to control the default names?

**Comment by mine-cetinkaya-rundel** [comment]
So suppose you set `names_prefix = "var"`, would that result in something like

```r
#>    var_1  var_2  var_3
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9
```

**Comment by hadley** [comment]
Yeah, exactly (well you'd need `names_prefix = "var_"`)

**Comment by mine-cetinkaya-rundel** [comment]
Right, I think that would be helpful indeed.

**Comment by hadley** [comment]
What should the default be? I guess it's best to keep it as `...` — while not exactly useful, it preserves backward compatibility (and at least it won't be so ridiculously noisy).

**Comment by mine-cetinkaya-rundel** [comment]
Agreed, since matching the default of `pivot_wider()` doesn't make sense here, backwards compatibility makes more sense.

**Comment by hadley** [comment]
@jennybc pointed out it might make sense to derive the prefix from the column name, so it would start with `x` here.

**Comment by hadley** [comment]
But `names_prefix` still makes sense if you have a named list, so while that would be a useful feature, I don't think it solves this problem. But maybe I could just quiet these defaults message so you got `...1`, `...2` etc, and then if you set `names_prefix = "var"` you'd be `var...1`, `var...2`, etc. Not super helpful but still a big improvement over the current behaviour.

**Comment by mine-cetinkaya-rundel** [comment]
(Without consideration for the feasibility of implementation) What if

```r
tibble(
  x = list(
    list(1,2,3),
    list(4,5,6),
    list(7,8,9)
  )
) %>% 
  unnest_wider(x)
```

yielded 

```r
#>      x1    x2    x3
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9
```

because `names_prefix` is derived from the column name by default, but could be set to something else, e.g.

```r
tibble(
  x = list(
    list(1,2,3),
    list(4,5,6),
    list(7,8,9)
  )
) %>% 
  unnest_wider(x, names_prefix = "var_")
#>   var_1 var_2 var_3
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9
```

If the list was named, this would mean

``` r
library(tidyverse)

tibble(
  x = list(
    list(a = 1, b = 2, c = 3),
    list(a = 4, b = 5, c = 6),
    list(a = 7, b = 8, c = 9)
  )
) %>% 
  unnest_wider(x)
#> # A tibble: 3 x 3
#>      xa    xb    xc
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9
```

by default, or the user-defined `names_prefix` would be applied if provided.

I feel like this is a win in the named list situation as well, but not backwards compatible. I am not sure if there is a way to detect the list is named and not use the proposed default `names_prefix`.

**Comment by jennybc** [comment]
This is sort of a negative addition to the conversation (and appears to be a pre-existing problem), but when devising names for these new columns, you also have to worry about name collisions with existing columns. This is a semi-artificial example (although it's not crazy to imagine that there has been previous tidyverse name repair), but collisions seem even more likely the more human-friendly the names get.

``` r
library(tidyverse)

tibble(
  x = list(list(1,2,3), list(4,5,6), list(7,8,9)),
  ...3 = "oops"
) %>% 
  unnest_wider(x)
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> * `` -> ...3
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> * `` -> ...3
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> * `` -> ...3
#> Error: Names must be unique.
#> x These names are duplicated:
#>   * "...3" at locations 3 and 4.
#> ℹ Use argument `names_repair` to specify repair strategy.
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

**Comment by DavisVaughan** [comment]
I am fairly certain this is resolved with `names_sep`.

i.e. from this comment:
https://github.com/tidyverse/tidyr/issues/1060#issuecomment-781662812

we can do:

``` r
library(tidyverse)

tibble(
  x = list(
    list(1,2,3),
    list(4,5,6),
    list(7,8,9)
  )
) %>% 
  unnest_wider(x, names_sep = "_")
#> # A tibble: 3 × 3
#>     x_1   x_2   x_3
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9


tibble(
  x = list(
    list(a = 1, b = 2, c = 3),
    list(a = 4, b = 5, c = 6),
    list(a = 7, b = 8, c = 9)
  )
) %>% 
  unnest_wider(x, names_sep = "_")
#> # A tibble: 3 × 3
#>     x_a   x_b   x_c
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
#> 2     4     5     6
#> 3     7     8     9
```

<sup>Created on 2021-11-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I added a bit more documentation on this feature in #1200 
https://github.com/tidyverse/tidyr/pull/1200/files#diff-4bfe10332afd18de00bc29931f91c2641aff20bb6e646c97b7554667e7d3b35aR533

**Comment by hadley** [comment]
Given that there's a fix with `names_sep`, and removing the messages might be confusing if the names are different in different rows, I think it's ok to close this.
