### ISSUE TITLE
argument `data` with dots

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#1063]
While working on bringing some `tidyr` verbs to `dbplyr` I noticed that some functions have `data` as their argument but they also take dots. I think to fit the tidyverse style the argument should be `.data` instead. On the other hand these are mostly functions that exist for quite some time now so a breaking change might not be desired.

dots passed to methods -> not sure whether it should be changed here
* `pivot_longer()`, `pivot_wider()`
* `extract()`
* `replace_na()`

dots as normal argument
* `separate()`
* `separate_rows()`
* `unite()`
* `complete()`
* `drop_na()`
* `expand()`
* `fill()`

Also see
* expand throws an error if variable is called `d`: #1051
* Reconsider tidyr verbs given dplyr 1.0.0 features: #939

**Comment by hadley** [comment]
Yeah, I'm not sure if fixing this is worth it 😞  It's particularly challenging for generics, since downstream packages need a coordinated change.

**Comment by hadley** [comment]
I think unfortunately the payoff just isn't big enough for the amount of work we'll need to do, especially when considering the changes to downstream packages. This general problem is something we're considering in https://github.com/RConsortium/OOP-WG/, so hopefully we'll have a better solution in the future.
