### ISSUE TITLE
Documentation for expand_grid() is a bit unclear

### ISSUE THREAD

**Issue by torfason** [tidyverse/tidyr#1067]
The documentation in `help("expand_grid")` and possibly elsewhere somewhat confusing. It states that 

* " Compared to expand.grid ... [expand_grid()]  **Varies the first element fastest**. "

The actual behavior of `expand_grid()` (see reprex example below) is what I would call to vary the first element the **slowest** (the result equals the output of `dplyr::arrange()` with the same column order). Evidently some people understand this differently, so the fix may not be to simply change **fastest** to **slowest**, but in order to minimize confusion it would be helpful to include a more unambiguous description of this in the help.

I very much agree that the `expand_grid()` behavior is preferable to the `expand.grid()` behavior, so this issue pertains only to the documentation.

``` r
testthat::expect_equal(
  tidyr::expand_grid(x=1:3,y=1:2),
  dplyr::arrange(tidyr::expand_grid(x=1:3,y=1:2), x, y))

testthat::expect_equal(
  expand.grid(x=1:3,y=1:2),
  dplyr::arrange(expand.grid(x=1:3,y=1:2), x, y))
#> Error: expand.grid(x = 1:3, y = 1:2) not equal to dplyr::arrange(expand.grid(x = 1:3, y = 1:2), x, y).
#> Component "x": Mean relative difference: 0.5
#> Component "y": Mean relative difference: 0.6666667
```

**Comment by batpigandme** [comment]
I wonder if it might help to refer to order rather than speed, here, given that's the difference in output.
``` r
tidyr::expand_grid(x=1:3,y=1:2)                   
#> # A tibble: 6 x 2
#>       x     y
#>   <int> <int>
#> 1     1     1
#> 2     1     2
#> 3     2     1
#> 4     2     2
#> 5     3     1
#> 6     3     2

expand.grid(x=1:3, y=1:2)
#>   x y
#> 1 1 1
#> 2 2 1
#> 3 3 1
#> 4 1 2
#> 5 2 2
#> 6 3 2
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
Yeah, order would be a much better way of explaining it!
