### ISSUE TITLE
uncount() should error for non-integer weights

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#1069]
`uncount()` currently works with non-integer weights where it probably should not. Also the error message for negative weights is quite unclear.

``` r
library(tidyr)

# no error
tibble(x = c("a", "b"), n = c(1, 0.5)) %>% 
  uncount(n)
#> # A tibble: 1 x 1
#>   x    
#>   <chr>
#> 1 a

# unclear error message
tibble(x = c("a", "b"), n = c(1, -1)) %>% 
  uncount(n)
#> Error in rep(seq_nrow(data), w): invalid 'times' argument
```

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think it's traditional for R to round down counts, e.g. `rep(1:2, c(1, 0.5))`, but I think you're right that the tidyverse can do better here (barring FP challenges).
