### ISSUE TITLE
pivot_longer deletes value labels when processing more than one column

### ISSUE THREAD

**Issue by donnekgit** [tidyverse/tidyr#1083]
I'm not sure if the following is due to an issue with ```{tidyr}``` or an issue with my limited skills with R/tidyverse, so bear with me!  I am using R v4.0.3, RStudio v1.4.1094, ```{tidyr}``` v1.1 and Ubuntu 20.04.

I am importing (using ```{haven}```) data from an SPSS sav file, which comes in with a variable label for each column and value labels for each observation, similar to the generated example below.  The problem is that ```pivot_longer``` deletes the value labels if it is used to process more than one column of data.

```r
library(tidyverse)
library(labelled) # v2.7.0

# Set up a one-column tibble (gender) to match SPSS sav layout.
onecol=tibble(gender=as.numeric(c(1, 2, 3, 1, 2, 3)))
var_label(onecol)<-"What is your gender?"
val_labels(onecol)<-c(Male=1, Female=2, Transgender=3)
onecol
#> # A tibble: 6 x 1
#>            gender
#>         <dbl+lbl>
#> 1 1 [Male]       
#> 2 2 [Female]     
#> 3 3 [Transgender]
#> 4 1 [Male]       
#> 5 2 [Female]     
#> 6 3 [Transgender]

# Check that the value labels are there.  Yup.
onecol %>% 
  val_labels()
#> $gender
#>        Male      Female Transgender 
#>           1           2           3

# Do long version.
onelong<-onecol %>% 
  tibble::rownames_to_column("respondent") %>% # Convert row numbers to respondent ID.
  mutate(respondent=as.numeric(respondent)) %>% # Make them numeric.
  pivot_longer(!respondent,  # Leave respondent as is.
               names_to="variable", # Column headings become "variable".
               values_to="response") %>% # Column values become "response".
  remove_var_label()  # Remove the errant variable label.

# Check that the value labels are still there. Yup.
onelong %>% 
  val_labels()
#> $respondent
#> NULL
#> 
#> $variable
#> NULL
#> 
#> $response
#>        Male      Female Transgender 
#>           1           2           3
```

However, doing the same thing on a two-column tibble gives a different result:

```r
 # Set up twocol tibble (gender and ethnicity) to match SPSS sav layout.
twocol=tibble(gender=as.numeric(c(1, 2, 3, 1, 2, 3)), ethnicity=as.numeric(c(1, 2, 1, 3, 2, 3)))
var_label(twocol$gender)<-"What is your gender?"
val_labels(twocol$gender)<-c(Male=1, Female=2, Transgender=3)
var_label(twocol$ethnicity)<-"What is your ethnicity?"
val_labels(twocol$ethnicity)<-c(White=1, Black=2, Asian=3)
twocol
#> # A tibble: 6 x 2
#>            gender ethnicity
#>         <dbl+lbl> <dbl+lbl>
#> 1 1 [Male]        1 [White]
#> 2 2 [Female]      2 [Black]
#> 3 3 [Transgender] 1 [White]
#> 4 1 [Male]        3 [Asian]
#> 5 2 [Female]      2 [Black]
#> 6 3 [Transgender] 3 [Asian]

# Check that the value labels are there. Yup.
twocol %>% 
  val_labels()
#> $gender
#>        Male      Female Transgender 
#>           1           2           3 
#> 
#> $ethnicity
#> White Black Asian 
#>     1     2     3

# Do long version.
twolong<-twocol %>% 
  tibble::rownames_to_column("respondent") %>% # Convert row numbers to respondent ID.
  mutate(respondent=as.numeric(respondent)) %>% # Make them numeric.
  pivot_longer(!respondent,  # Leave respondent as is.
               names_to="variable", # Column headings become "variable".
               values_to="response") %>% # Column values become "response".
  remove_var_label()  # Remove the errant variable label.

# Oops! All the value labels are now missing....
twolong %>% 
  val_labels()
#> $respondent
#> NULL
#> 
#> $variable
#> NULL
#> 
#> $response
#> NULL
```

So data gets silently lost depending on how many columns are being processed.  Is this a bug?  The issue I was able to find that seems to have the closest relevance is [#648](https://github.com/tidyverse/tidyr/issues/648), which raised the possibility of having a ```labels_to``` option for ```pivot_longer```, but this was closed as being "currently out of scope for tidyr".  I respectfully suggest that being able to retain the value labels would be very useful, not least because it keeps data about what the selectable options were inside one file.

The following workaround adds the actual value labels to the tibble, though this only gives labels for the items that were actually chosen (ie it doesn't give any idea of what the labels were for items that were NOT chosen, as we get from ```var_labels()``` above).

```r
# Generate a separate version of the data showing value labels.
twolabs<-twocol %>% 
  labelled::unlabelled()

# Do long version of this.
twolabslong<-twolabs %>% 
  tibble::rownames_to_column("respondent") %>% 
  mutate(respondent=as.numeric(respondent)) %>%
  pivot_longer(!respondent,  # Leave respondent as is.
               names_to="variable", # Column headings become the variable.
               values_to="response")%>% 
  remove_var_label()  # Remove the errant variable label.

# Copy the labelled column over to the now-unlabelled long version.
twolong<-twolong %>% 
  mutate(resp_labels=twolabslong$response)
twolong
#> # A tibble: 12 x 4
#>    respondent variable  response resp_labels
#>         <dbl> <chr>        <dbl> <fct>      
#>  1          1 gender           1 Male       
#>  2          1 ethnicity        1 White      
#>  3          2 gender           2 Female     
#>  4          2 ethnicity        2 Black      
#>  5          3 gender           3 Transgender
#>  6          3 ethnicity        1 White      
#>  7          4 gender           1 Male       
#>  8          4 ethnicity        3 Asian      
#>  9          5 gender           2 Female     
#> 10          5 ethnicity        2 Black      
#> 11          6 gender           3 Transgender
#> 12          6 ethnicity        3 Asian
```

Is this the best workaround, or are there better options?

**Comment by hadley** [comment]
I have a bit of a hard time following your long example. Does this code capture the basic problem?

``` r
library(tidyr)

df <- tibble(
  id = 1:2,
  x = haven::labelled(1:2, labels = c("a" = 1, "b" = 2)),
  y = haven::labelled(1:2, labels = c("c" = 1, "d" = 2))
)
df
#> # A tibble: 2 x 3
#>      id         x         y
#>   <int> <int+lbl> <int+lbl>
#> 1     1     1 [a]     1 [c]
#> 2     2     2 [b]     2 [d]

df %>% pivot_longer(x:y, names_to = "var", values_to = "resp")
#> # A tibble: 4 x 3
#>      id var    resp
#>   <int> <chr> <int>
#> 1     1 x         1
#> 2     1 y         1
#> 3     2 x         2
#> 4     2 y         2
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by donnekgit** [comment]
Drat! I thought I'd done a really good example.  But yes, yours is more concise (!) and does indeed capture the problem.  After pivot_longer(), the labels have gone.

**Comment by hadley** [comment]
But what do you expect to happen in this case? We have conflicting labels for 1 — should it be a or c?

**Comment by donnekgit** [comment]
The label should be attached to the resp column, where the difference will still be meaningful.

**Comment by hadley** [comment]
Which label? There are two conflicting labels.

**Comment by donnekgit** [comment]
No, the line as a whole is unique. So something like:

#>      id var    resp
#>   <int> <chr> <int>
#> 1     1 x         1 [a]
#> 2     1 y         1 [c]
#> 3     2 x         2 [b]
#> 4     2 y         2 [d]

So whatever swivels 1 1 [a] (original) to be 1 x 1 (after pivot) should swivel the label as well: 1 x 1 [a].  2 2 [d] → 2 y 2 should swivel the label as well: 2 y 2 [d]. And so on.

In effect, this is what the workaround above does.

**Comment by hadley** [comment]
Ok, now I understand what the problem is — unfortunately what you're asking for is impossible because of the way that `labelled()` works. It associates a value with a label (e.g. "1" gets label "c"), so every value must have the same label, and there's currently no way to do what you want. So I think your technique of turning the labels in to their own column is the right way to solve this problem.
