### ISSUE TITLE
separate() fails with Arabic text

### ISSUE THREAD

**Issue by lizzhuntley** [tidyverse/tidyr#1085]
Greetings! Thank you in advance for your time!

In the dataframe _dict_ below, I am trying to separate the character strings in the _root_letters_ column so that:

1. Each letter will appear in its own column, AND
2. The words are parsed correctly for a right-to-left script, i.e.
     - the first letter of the word is correctly identified as the **right-most** letter in the string AND 
     - the direction of split goes from right-to left [although if the split defaults to start left and move right, this second issue could be fixed by reordering the columns]
     - ([please click here to see the desired outcome](https://www.dropbox.com/s/vmwp2fstj337tgj/ar_en_reprex_outcome.csv?dl=0)) using tidyr

Unfortunately, the `separate()` function doesn't seem to recognize the Arabic text (see the "bad offset" warnings in the output). 

Some workarounds have been kindly proposed in [RStudio Community](https://community.rstudio.com/t/separate-letters-into-columns-for-arabic-character-strings/91862) but I still end up with strange reverse-order when I try to open the edited dataframe in Excel.

I'd still like to know if tidyr can actually currently handle this (and if not, if such support for parsing of right-to-left texts could be added). Thank you!

```R
# Load packages
library(tidyr)

# Create sample dataframe
root_letters <- c("أ", "آب", "أباجور", "دار")
entry <- c(1:4)

dict <- data.frame(entry, root_letters)
dict # display dataframe
#>   entry root_letters
#> 1     1            أ
#> 2     2           آب
#> 3     3       أباجور
#> 4     4          دار

# Find the maximum number of letters in a root
long <- max(nchar(dict$root_letters))

# Separate function in tidyr package
dict_sep <- dict %>% separate(
     root_letters, # column to seprate
     "", # separate every character
     into = paste0("r", long:1), # names of new variables to create as character vector,
     remove = F, # keep original input column
     extra = "drop", # drop any extra values without a warning.
     fill = "left") # fill values on the left
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 1
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 2
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 3
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 4

dict_sep # display outcome
#>   entry root_letters   r6   r5   r4   r3 r2     r1
#> 1     1            أ <NA> <NA> <NA> <NA>         أ
#> 2     2           آب <NA> <NA> <NA> <NA>        آب
#> 3     3       أباجور <NA> <NA> <NA> <NA>    أباجور
#> 4     4          دار <NA> <NA> <NA> <NA>       دار
```

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(tidyr)

df <- tibble(
  id = 1:4,
  string = c("أ", "آب", "أباجور", "دار")
)
df %>% separate(string, "", into = paste0("r", 6:1), fill = "left")
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 1
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 2
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 3
#> Warning in gregexpr(pattern, x, perl = TRUE): PCRE error
#>  'bad offset into UTF string'
#>  for element 4
#> # A tibble: 4 x 7
#>      id r6    r5    r4    r3    r2    r1    
#>   <int> <chr> <chr> <chr> <chr> <chr> <chr> 
#> 1     1 <NA>  <NA>  <NA>  <NA>  ""    أ     
#> 2     2 <NA>  <NA>  <NA>  <NA>  ""    آب    
#> 3     3 <NA>  <NA>  <NA>  <NA>  ""    أباجور
#> 4     4 <NA>  <NA>  <NA>  <NA>  ""    دار
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I'm not yet sure how to fix this, but in the meantime, you can work around it by splitting the string yourself and then using `unnest_wider()`:

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  id = 1:4,
  string = c("أ", "آب", "أباجور", "دار")
)

df %>% 
  rowwise() %>% 
  mutate(
    letters = strsplit(string, ""),
    letters = list(setNames(letters, paste0("r", seq_along(letters))))
  ) %>% 
  unnest_wider(letters)
#> # A tibble: 4 x 8
#>      id string r1    r2    r3    r4    r5    r6   
#>   <int> <chr>  <chr> <chr> <chr> <chr> <chr> <chr>
#> 1     1 أ      أ     <NA>  <NA>  <NA>  <NA>  <NA> 
#> 2     2 آب     آ     ب     <NA>  <NA>  <NA>  <NA> 
#> 3     3 أباجور أ     ب     ا     ج     و     ر    
#> 4     4 دار    د     ا     ر     <NA>  <NA>  <NA>
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This prints incorrectly, but using `View()` in RStudio suggests the underlying data is ok.

**Comment by hadley** [comment]
`stringr::str_split()` (which is powered by stringi, which use ICU, which should give the correct result) orders characters in the same way as `split()`, so if that's not what you want, you'll need a `rev()`.

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  id = 1:4,
  string = c("أ", "آب", "أباجور", "دار")
)

stringr::str_split(df$string[[3]], stringr::boundary("character", locale = "ar"))
#> [[1]]
#> [1] "أ" "ب" "ا" "ج" "و" "ر"
strsplit(df$string[[3]], "")
#> [[1]]
#> [1] "أ" "ب" "ا" "ج" "و" "ر"
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment]
This will be resolved by the new family of separate functions proposed in https://github.com/tidyverse/tidyups/issues/23, since they'll be backed by stringi, not base R.
