### ISSUE TITLE
how separate() fill from a certain column when there are not enough pieces?

### ISSUE THREAD

**Issue by shitiezhu** [tidyverse/tidyr#1091]
Dear the tidyverse team,
In function `separate()`, the argument "fill" is descripted as following:
> If sep is a character vector, this controls what happens when there are not enough pieces. 
There are three valid options: 
    "warn" (the default): emit a warning and fill from the right 
    "right": fill with missing values on the right 
    "left": fill with missing values on the left

like above, there are only three options (actually only two, left and right) for the argument fill. If my data should fill an "NA" from a column in the middle, what should I do?

Thanks very much!

**Comment by hadley** [comment]
You'll need to write the code yourself, sorry.
