### ISSUE TITLE
In pivot_longer(), values_ptypes should allow a single ptype 

### ISSUE THREAD

**Issue by smingerson** [tidyverse/tidyr#1096]
Similar to #1035, values_ptypes should allow a single ptype to be provided, which will be applied to all value columns. 

``` r
library(tidyr) # dev version
#> Warning: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame'
#> when loading 'dplyr'
tib <- tibble(a = 1:5, b = rnorm(5))
pivot_longer(tib, everything(), values_ptypes = double())
#> Error in values_ptypes[[value]]: subscript out of bounds
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I would expect it to use the ptype provided. If there were multiple value columns, I would expect the ptype to be recycled. Happy to put together a PR.

**Comment by hadley** [comment]
But how do you tell if something is a prototype or not? (Since a list might be prototype)

**Comment by smingerson** [comment]
This is more complicated than I thought.

Switching the default to `NULL` would retain current behavior. Then the list ptype for all value columns would be specified as `values_ptypes = list()`. From my reading of [vctrs::vec_ptype()](https://vctrs.r-lib.org/reference/vec_ptype.html), every prototype should have a length of 0 (or at least `vec_size()` 0), so that could be used to identify whether the argument passed is a single ptype or a ptype for each value column.

**Comment by hadley** [comment]
Oh I like the idea to use length 0!

**Comment by DavisVaughan** [comment]
Tracking in #1284
