### ISSUE TITLE
pivot_wider() in long data set

### ISSUE THREAD

**Issue by GabrielSlPires** [tidyverse/tidyr#1097]
I'm trying to use pivot_wider() in a data set that has almost 10Gb. And I have 3 other files similar to the 10Gb one, which I used to discover the best way to deal with the data.

I have 3 columns, one with the IDs (id_cols = ObservationID), one with column headers (names_from = OriglName), and the other with row values (values_from = OrigValueStr). Unfortunately, that dataset has nonunique pairs of ID and column headers, so I had developed a try_catch to deal with list-cols.

The error happens when I user 'values_fn' in the code above:
```
y <- x %>%
        pivot_wider(id_cols = ObservationID,
                    names_from = OriglName,
                    values_from = OrigValueStr,
                    values_fn = length)
```
Which returns:
```
Error: Internal error in `compact_rep()`: Negative `n` in `compact_rep()`.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In nrow * ncol : NAs produced by integer overflow
```
When I use, rlang::last_error(), returns:
```
<error/rlang_error>
Internal error in `compact_rep()`: Negative `n` in `compact_rep()`.
Backtrace:
  1. global::try_file(try_root_depth)
  2. base::tryCatch(...) Scripts/functions/open_TRY.R:6:2
  3. base:::tryCatchList(expr, classes, parentenv, handlers)       
  4. base:::tryCatchOne(...)
  5. value[[3L]](cond)
 14. tidyr::pivot_wider(...)
 16. tidyr::pivot_wider_spec(...)
 17. vctrs::vec_init(val, nrow * ncol)
Run `rlang::last_trace()` to see the full context.
```
And, rlang::last_trace(), returns:
```
<error/rlang_error>
Internal error in `compact_rep()`: Negative `n` in `compact_rep()`.
Backtrace:
     x
  1. \-global::try_file(try_root_depth)
  2.   \-base::tryCatch(...) Scripts/functions/open_TRY.R:6:2      
  3.     \-base:::tryCatchList(expr, classes, parentenv, handlers) 
  4.       \-base:::tryCatchOne(...)
  5.         \-value[[3L]](cond)
  6.           \-`%>%`(...) Scripts/functions/open_TRY.R:22:6
  7.             +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  8.             \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  9.               \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
 10.                 \-`_fseq`(`_lhs`)
 11.                   \-magrittr::freduce(value, `_function_list`)
 12.                     +-base::withVisible(function_list[[k]](value))
 13.                     \-function_list[[k]](value)
 14.                       +-tidyr::pivot_wider(...)
 15.                       \-tidyr:::pivot_wider.data.frame(...)
 16.                         \-tidyr::pivot_wider_spec(...)
 17.                           \-vctrs::vec_init(val, nrow * ncol)
 18.                             \-(function () ...
```
I haven't found how to deal with that error, and the pivot_wider() works nicely with the other three datasets. Is there anything that I'm able to do?
These datasets I'm using are from TRY Plant Trait Database, so I cannot send them here.

**Comment by mrepetto94** [comment]
I'm having the same problem with a dataset of approx 2gb

**Comment by jml-science** [comment]
I'm having the same problem - same scenario, works nicely with three out of for datasets and this errors occurs with the biggest one...

**Comment by aaronrudkin** [comment]
Ran into this in a 62,000,000 x 3 dataset which is being pivoted into a ~1,000,000 x many column dataset.

`spread` produces the relatively useful error "Cannot allocate vector of size 493.3 Gb" (which at least tells me the issue is fundamentally a memory issue), while `pivot_wider` produces the same stack as above.

**Comment by hadley** [comment]
@DavisVaughan I'm guessing root cause is using an unsigned integer somewhere?

**Comment by DavisVaughan** [comment]
The error looks to be from:

```r
vctrs::vec_init(val, nrow * ncol)
```

and I also see:

```r
In addition: Warning message:
In nrow * ncol : NAs produced by integer overflow
```

So I assume that the initialized data structure is >2 billion rows and is just OOB for now since vctrs doesn't support long vectors

**Comment by hadley** [comment]
@DavisVaughan yeah, but surely it's a bug that the error is `` Internal error in `compact_rep()`: Negative `n` in `compact_rep()``` ?

**Comment by hadley** [comment]
Yeah:

``` r
vctrs::vec_init(character(), NA)
#> Error: Internal error in `compact_rep()`: Negative `n` in `compact_rep()`.
```

<sup>Created on 2021-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DavisVaughan** [comment]
I've actually fixed that in the dev version as of a few days ago:

```r
> vctrs::vec_init(character(), NA)
Error: `n` must be a positive integer.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by DavisVaughan** [comment]
Tracking in https://github.com/r-lib/vctrs/issues/1437

**Comment by johanzi** [comment]
For the ones interested to solve this issue rather than the message error it displays, you can use the bash command `join` by iterative merging across all the files you need to merge. It is not an R solution but it works.
