### ISSUE TITLE
Export str_separate() and friends

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#1103]
Need some prefix that makes it more clear that it's for use by other backends (e.g. dtplyr, dbplyr)

**Comment by hadley** [comment]
Need to think about how this is connected to https://github.com/tidyverse/tidyups/pull/15

**Comment by DavisVaughan** [comment]
Related to https://github.com/tidyverse/tidyr/issues/1202#issuecomment-963561093

**Comment by DavisVaughan** [comment]
Related to https://github.com/tidyverse/tidyr/issues/1166#issuecomment-964535368

**Comment by DavisVaughan** [comment]
@hadley is it now clear that people should use the upcoming low level stringr variants like `str_separate_by_wider()` instead?

**Comment by hadley** [comment]
Yeah, we can close this.
