### ISSUE TITLE
Error on named tidyselections in `pivot_longer()` and `pivot_wider()` 

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#1104]
As the `cols` argument supports the tidy-select syntax I thought I could use it to rename a column. But this didn't work as expected and when using a named vector in `cols` we get:

* a unclear error message when using a data frame
* a better error message when using a data frame
* a clearly unwanted result when the name actually exists as a column

I think it would be nice to allow renaming via `cols`

``` r
library(tidyr)

# unclear error message for data frame
data.frame(x = 1, y = 2) %>% 
  pivot_longer(c(z = y))
#> Error in `[.data.frame`(data, cols): undefined columns selected

# better for tibble
tibble(x = 1, y = 2) %>% 
  pivot_longer(c(z = y))
#> Error: Can't subset columns that don't exist.
#> x Column `z` doesn't exist.

# when the name actually exists we get something quite unwanted
data.frame(x = 1, y = 2, z = 3) %>% 
  pivot_longer(c(z = y))
#> # A tibble: 1 x 4
#>       x     y name  value
#>   <dbl> <dbl> <chr> <dbl>
#> 1     1     2 z         3
```

<sup>Created on 2021-03-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment]
Hmmmm, I'm not sure — I feel like that might be overloading `pivot_longer()` with slightly too much functionality.

**Comment by DavisVaughan** [comment]
We are going to wait until we get a tidy select release that will fix this, and then we can apply `allow_rename = FALSE` everywhere all at once. Needed in:

- `pivot_longer()` + spec helpers
- `pivot_wider()` + spec helpers
