### ISSUE TITLE
Feature request: export `vec_fill_fun`

### ISSUE THREAD

**Issue by gregorp** [tidyverse/tidyr#1106]
Especially now that `across()` is becoming well-established in `dplyr`, I really wish that a vector-version of `fill` was available. I find myself still using `zoo::na.locf` when I want to create a filled copy of a column without modifying the original, or in a few cases where I've been operating on a vector not in a data frame. I'd love it if `vec_fill_fun` could be exported, perhaps with a simpler name like `fill_vec`, for those times when I want a little more control than `fill` provides.

**Comment by DavisVaughan** [comment]
You could use `vctrs::vec_fill_missing()`

**Comment by gregorp** [comment]
Ah, thanks for the pointer.

**Comment by gregorp** [comment]
Though I will say, I'm confused a bit by the `vctrs` package -- this use-case seems at odds with the package purpose as described in the README, 

> vctrs is a developer-focussed package. Understanding and extending vctrs requires some effort from developers, but should be invisible to most users.
