### ISSUE TITLE
Name repairing doesn't work well with groups

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#1117]
name repairing is done in a separate step from `reconstruct_tibble()`. When grouping variables are renamed then the grouping information is lost for the renamed variables. For example, this happens in `pivot_wider()` and `unpack()`

``` r
library(dplyr)
library(tidyr)

fish_encounters %>%
  group_by(fish) %>% 
  pivot_wider(names_from = station, values_from = seen, names_repair = "unique") %>% 
  group_vars()
#> [1] "fish"

fish_encounters %>%
  rename(Rstr = fish) %>% 
  group_by(Rstr) %>% 
  pivot_wider(names_from = station, values_from = seen, names_repair = "unique") %>% 
  group_vars()
#> New names:
#> * Rstr -> Rstr...1
#> * Rstr -> Rstr...5
#> character(0)


df <- tibble(
  x = 1:3,
  y = tibble(x = 1:3, b = 3:1),
  z = tibble(X = c("a", "b", "c"), Y = runif(3), Z = c(TRUE, FALSE, NA))
)

df %>% 
  group_by(x) %>% 
  unpack(z, names_repair = "unique") %>% 
  group_vars()
#> [1] "x"
df %>% 
  group_by(x) %>% 
  unpack(y, names_repair = "unique") %>% 
  group_vars()
#> New names:
#> * x -> x...1
#> * x -> x...2
#> character(0)
```

<sup>Created on 2021-05-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This is quite an edge case but might still be worth to either fix it or at least error if grouping variables were renamed this way.

**Comment by DavisVaughan** [comment]
This is a general problem that has the potential to come up anywhere `reconstruct_tibble()` is used. I'm not entirely sure what the right solution is.

"Tracking" the group variables seems incredibly difficult, and not worth it.

The current behavior might be the best we can do.

**Comment by hadley** [comment]
I think this behaviour is ok — this is just a case where you really need to fix the problem upstream; repairing can only ever get you so far.
