### ISSUE TITLE
Separate Example using Regex

### ISSUE THREAD

**Issue by bms63** [tidyverse/tidyr#1118]
In the examples for the documentation, I noticed that the you can use separate without the regular expressions.  It gives the same results.  

![image](https://user-images.githubusercontent.com/10111024/117498330-a6265180-af47-11eb-8bc8-16f96692307a.png)

# Use regular expressions to separate on multiple characters:
```r
df <- data.frame(x = c(NA, "a?b", "a.d", "b:c"))
df %>% separate(x, c("A","B"), sep = "([.?:])"
```

```r
df <- data.frame(x = c(NA, "a?b", "a.d", "b:c"))
df %>% separate(x, c("A","B"))
```

**Comment by hadley** [comment]
Right, because the default value splits on any non-alphanumeric value.   If we change this I think it should be to something quite different, maybe like this:

``` r
library(tidyr)

df <- tibble(x = c("a1b", "c4d", "e9g"))
df %>% separate(x, c("A", "B"), sep = "[0-9]")
#> # A tibble: 3 × 2
#>   A     B    
#>   <chr> <chr>
#> 1 a     b    
#> 2 c     d    
#> 3 e     g
```

<sup>Created on 2021-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
