### ISSUE TITLE
pivot_longer - bad 

### ISSUE THREAD

**Issue by deschen1** [tidyverse/tidyr#1124]
Taking the following data:

```
library(tidyverse)
library(haven)

df <- data.frame(id = c(1,2,3),
                 x1 = labelled(x = c(1,2,3), label = "test1"),
                 x2 = labelled(x = c(4,5,6), label = "test2"),
                 x3 = labelled(x = c(7,8,9), label = "test3"))
```

and pivoting it into long format:

```
df2 <- df %>%
  pivot_longer(cols = -id)
```

results in a data frame where the `value` column would take the variable label of the labelled vectors from the first passed vector, i.e. `x1`. This might be considered consistent to take that information from the first passed vector. However, in the case of pivoting it will probably be a wrong and misleading assignment in most of the cases.

The ideal behaviour would be to either allow for a user-specified label or the option to omit the label.

Attributes from original data frame:
```
str(df)
'data.frame':	3 obs. of  4 variables:
 $ id: num  1 2 3
 $ x1: dbl+lbl [1:3] 1, 2, 3
   ..@ label: chr "test1"
 $ x2: dbl+lbl [1:3] 4, 5, 6
   ..@ label: chr "test2"
 $ x3: dbl+lbl [1:3] 7, 8, 9
   ..@ label: chr "test3"
```

Attributes from pivoted data frame:
```
str(df2)
tibble [9 x 3] (S3: tbl_df/tbl/data.frame)
 $ id   : num [1:9] 1 1 1 2 2 2 3 3 3
 $ name : chr [1:9] "x1" "x2" "x3" "x1" ...
 $ value: dbl+lbl [1:9] 1, 4, 7, 2, 5, 8, 3, 6, 9
   ..@ label: chr "test1"
```

The label is `test1` which is taking from the `x1` vector in `df`.

**Comment by hadley** [comment]
Based on feedback from users, we chose this behaviour because it is least likely to cause confusion. It's not something we're considering changing at this time, but we'll note your feedback in case we revisit decision in the future.

**Comment by deschen1** [comment]
OK, thanks. Fingers crossed that it will see an update at some point in the future. I would argue that the current behaviour does least confusion only under certain, narrow circumstances, i.e. when the labels of the to-be-pivoted columns don't differ. As soon as they do, the resulting label will most likely be wrong (even though users might not care much about the labels in many cases).
