### ISSUE TITLE
Example tabular representations are empty in online doc

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/tidyr#1135]
Just check: https://tidyr.tidyverse.org/reference/table1.html

![snap](https://user-images.githubusercontent.com/19862384/124798621-7990b500-df4b-11eb-9c7b-469dbf9b2247.png)

**Comment by hadley** [comment]
What is your question?

**Comment by ramiromagno** [comment]
I am sorry, I realise now that that is intended. I thought you meant to have those tables' contents shown in that code block...
