### ISSUE TITLE
extract with widths

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/tidyr#1136]
Sometimes the field to be extracted is better described by widths.   This is particularly the case when there are many fields and they vary in lengths.  Writing out the regex is awkward in such cases.  The example below is pretty simple but you could imagine a more complex case with real data that has many fields..

```
DF <- data.frame(a = "abc")
DF %>%  extract(a, c("x", "y", "z"), "(.)(.)(.)")

# this would be possible:
DF %>% extract(a, c("x", "y", "z"), c(1, 1, 1))

# or maybe this:
DF %>%  extract(a, c(x = 1, y = 1, z = 1))

```

**Comment by hadley** [comment]
`separate()` provides similar functionality, except that you provide the position of the breaks, not the widths:

``` r
library(tidyr)
DF <- data.frame(a = "abc")
DF %>% separate(a, c("x", "y", "z"), c(1, 2, 3))
#>   x y z
#> 1 a b c
```

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ggrothendieck** [comment]
OK. Note that `?separate` says `sep=` should be one less than the number of variables but if it actually works as in your example that would make it easier if you know the widths since then `sep=cumsum(widths)` would work.

**Comment by hadley** [comment]
This will get clearer once we separate (HA) out the two variants of separate. Some initial thoughts at https://github.com/tidyverse/tidyups/pull/15
