### ISSUE TITLE
replace_na does not warn or error when called on non-existent column

### ISSUE THREAD

**Issue by sfirke** [tidyverse/tidyr#1138]
Continuing with the reprex from #356:
```
library(tidyr)
df <- tibble::tibble(a = c(1, NA))
replace_na(df, list(a = 100, b = 0))
```
This returns `df` as-is, with no warning.  I would prefer it to warn that I called on a non-existent column, as is the case with other tidyverse functions.  Erroring would be fine too.

Context: I called `replace_na` and mis-named my variable, then was surprised to find the NAs were still there.

**Comment by hadley** [comment]
Hmmmm, not sure if it's worth changing this behaviour or not. Looks like we've ignoring unmatched columns since 2017, so making it an error is likely to break existing code, and it's not clear to me whether or not this is what folks expect in general.

**Comment by DavisVaughan** [comment]
I'm going to argue that this matches our behavior of `ptype` and `transform` in other functions like `unnest_wider()` and `pivot_longer()`, so we should just stay consistent with that

**Comment by sfirke** [comment]
Would you consider keeping the behavior the same but adding a warning? I
can't imagine a downside for the user, as they'll only see it if they have
made an incorrect call.
