### ISSUE TITLE
Add One hot encoding function

### ISSUE THREAD

**Issue by AntoniosBarotsis** [tidyverse/tidyr#1144]
I think it would make sense for `pivot_wider` did not support this. Add the option to pivot a single column and turn it's values to column names and use 0/1 for the values. 

Doesn't have to be it's own function either, it can be a call to `pivot_wider` like so:
```R
pivot_wider(
  names_from = col, 
  values_from = col, 
  values_fn = list(col = ~ 1),
  values_fill = list(col = 0)
)
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: it feels a little too closely tied to modelling so I think a different package would be a better home. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
