### ISSUE TITLE
Function request `replace_nan`

### ISSUE THREAD

**Issue by Moohan** [tidyverse/tidyr#1149]
As in the title, a function that would work similarly to `replace_na` but for `NaN` values.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: it feels a little too specific for tidyr. Unfortunately developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
