### ISSUE TITLE
unnest does not work for the AsIs class columns

### ISSUE THREAD

**Issue by xiangpin** [tidyverse/tidyr#1162]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
The newest `unnest` of `tidyr` does not work for the `I(list)` (`AsIs` class) columns.

```r
# insert reprex here
> da <- tibble::tibble(A=c(1, 2, 3), B=I(list(c(1, 2), c(2, 3), c(3, 4))))
> da
# A tibble: 3 × 2
      A B        
  <dbl> <I<list>>
1     1 <dbl [2]>
2     2 <dbl [2]>
3     3 <dbl [2]>
> da %>% tidyr::unnest(B)
# A tibble: 3 × 2
      A B        
  <dbl> <I<list>>
1     1 <dbl [2]>
2     2 <dbl [2]>
3     3 <dbl [2]>
```

Is this a bug? How to deal with the problem.

**Comment by DavisVaughan** [comment]
Tracking in https://github.com/r-lib/vctrs/issues/1463
