### ISSUE TITLE
Should `separate_by/at_longer()` get `extra` and `fill` arguments?

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/tidyr#1166]
If data with subfields is well formed then it works well with `separate_rows` but if you have messy data with inconsistent numbers of subfiields then it will choke.

```
DF <- data.frame(a = 1, b = c("2,3", "1,2,3"), c = "4,5,6")
separate_rows(DF, b, c)
## Error: Incompatible lengths: 2, 3.
## Run `rlang::last_error()` to see where the error occurred.
```

Some things that might be considered are:

  - it could optionally return an additional column indicating which rows were not processed because of inconsistencies.  This could be useful if the program wanted to later output the set of rows which were inconsistent as part of error reporting.

  - a repair facility where it would fill in missing subfields with NA or extend them with the last subfield or truncate long ones.

**Comment by DavisVaughan** [comment]
I think that handling any kind of padding like this is unfortunately at odds with our recycling rules, and would be hard to incorporate directly into tidyr.

It is also pretty difficult to decide whether you want to pad the front, pad the back, truncate the front, or truncate the back. And then deciding what you pad with is another option.

Ultimately I think this is out of scope for tidyr.

Eventually, a vector version of `separate_rows()` will be exported as `str_separate_by_longer()` which will be able to help with this. You'd be able to do something like this, adding in your custom logic for padding / truncating.

``` r
library(tidyverse)

DF <- tibble(a = 1:2, b = c("2,3", "1,2,3"), c = "4,5,6")

split <- mutate(
  DF, 
  across(
    c(b, c), 
    ~tidyr:::str_split_n(.x, pattern = "[^[:alnum:].]+")
  )
)

split
#> # A tibble: 2 × 3
#>       a b         c        
#>   <int> <list>    <list>   
#> 1     1 <chr [2]> <chr [3]>
#> 2     2 <chr [3]> <chr [3]>

list_pmax <- function(x) {
  rlang::exec(pmax, !!!x)
}
list_pad <- function(x, sizes) {
  x_sizes <- lengths(x)
  padding <- map(sizes - x_sizes, ~ rep(NA_character_, .x))
  map2(x, padding, c)
}

padded <- mutate(
  split,
  max_size = {
    cols <- across(c(b, c))
    sizes <- map(cols, lengths)
    list_pmax(sizes)
  },
  across(c(b, c), ~ list_pad(.x, max_size))
)

padded
#> # A tibble: 2 × 4
#>       a b         c         max_size
#>   <int> <list>    <list>       <int>
#> 1     1 <chr [3]> <chr [3]>        3
#> 2     2 <chr [3]> <chr [3]>        3

padded %>%
  select(-max_size) %>%
  unchop(c(b, c))
#> # A tibble: 6 × 3
#>       a b     c    
#>   <int> <chr> <chr>
#> 1     1 2     4    
#> 2     1 3     5    
#> 3     1 <NA>  6    
#> 4     2 1     4    
#> 5     2 2     5    
#> 6     2 3     6
```

<sup>Created on 2021-11-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
Hmm, but `separate()` has `extra` so maybe it is worth thinking about this a little more

**Comment by DavisVaughan** [comment]
At this point I think we should probably leave `separate()` alone, and instead consider this with `separate_by_longer()` and friends

**Comment by hadley** [comment]
I've added a note to consider this in the stringr <-> tidyr alignment tidyup.
