### ISSUE TITLE
FR for pivot_longer: allow specifying multiple observations per row without using regular expressions

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/tidyr#1170]
Currently, pivoting to longer multiple observations per row imply the use of regular expressions as in the help example:
```r
anscombe %>%
 pivot_longer(everything(),
   names_to = c(".value", "set"),
   names_pattern = "(.)(.)"
 )
# A tibble: 44 x 3
   set       x     y
   <chr> <dbl> <dbl>
 1 1        10  8.04
 2 2        10  9.14
 3 3        10  7.46
 4 4         8  6.58
 5 1         8  6.95
 6 2         8  8.14
 7 3         8  6.77
 8 4         8  5.76
 9 1        13  7.58
10 2        13  8.74
# ... with 34 more rows
```

When someone needs to pivot, a dataframe with multiple observations per row is not unusual. So, if one has to teach pivoting to R new users -which, and  even some experienced R users, probably have listened nothing about regular expressions-, arriving to this part of the lesson is a bit weird, unless switching to R base with:

```r
reshape(anscombe, varying = paste0(c("x", "y"), rep(1:4, each=2)), v.names = c("x", "y"), direction = "long")
# or
# reshape(anscombe, varying = list(paste0("x", 1:4), paste0("y", 1:4)), v.names = c("x", "y"), direction = "long")
     time  x     y id
1.1     1 10  8.04  1
2.1     1  8  6.95  2
3.1     1 13  7.58  3
4.1     1  9  8.81  4
5.1     1 11  8.33  5
6.1     1 14  9.96  6
7.1     1  6  7.24  7
8.1     1  4  4.26  8
9.1     1 12 10.84  9
10.1    1  7  4.82 10
11.1    1  5  5.68 11
1.2     2 10  9.14  1
2.2     2  8  8.14  2
3.2     2 13  8.74  3
4.2     2  9  8.77  4
5.2     2 11  9.26  5
6.2     2 14  8.10  6
7.2     2  6  6.13  7
8.2     2  4  3.10  8
9.2     2 12  9.13  9
10.2    2  7  7.26 10
11.2    2  5  4.74 11
1.3     3 10  7.46  1
2.3     3  8  6.77  2
3.3     3 13 12.74  3
4.3     3  9  7.11  4
5.3     3 11  7.81  5
6.3     3 14  8.84  6
7.3     3  6  6.08  7
8.3     3  4  5.39  8
9.3     3 12  8.15  9
10.3    3  7  6.42 10
11.3    3  5  5.73 11
1.4     4  8  6.58  1
2.4     4  8  5.76  2
3.4     4  8  7.71  3
4.4     4  8  8.84  4
5.4     4  8  8.47  5
6.4     4  8  7.04  6
7.4     4  8  5.25  7
8.4     4 19 12.50  8
9.4     4  8  5.56  9
10.4    4  8  7.91 10
11.4    4  8  6.89 11
```

So, why do not allow with `pivot_longer` to have the chance of avoiding the need of regex as can be done easily with `reshape`?

Thanks!

**Comment by iago-pssjd** [comment]
@DavisVaughan Thanks for looking at the issue.

> Typically it is easier to use a `names_sep` rather than `names_pattern`. Like, if anscombe had names separated by a `_` ...

Yes, no doubt of it, but often data bases have quite weird names, so one translates the "issue" to renaming the variables.

On your second comment, I fully agree with you and appreciate the benefits of `pivot_longer` a lot. Would not be possible to keep them while allowing an easier syntax? My question tried to suggest a more flexible `pivot_longer` more than mimic `reshape`.  Would not have sense something like the next?
```r
anscombe %>%
  pivot_longer(
    everything(),
    names_to = "set",
    values_to = c("x", "y"),
  )
```
maybe?...

Thanks!

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's worth the additional net complication to make this use case of `pivot_longer()` available to people who don't know regular expressions. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
