### ISSUE TITLE
separate with accented UTF characters

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/tidyr#1197]
With accented UTF characters separate seems to split at them.  We can fix that if we use the regex shown but it would be nice if this were the default.   Here `\p{L}` means any letter in any language.

```
library(dplyr)
library(tidyr)

d <- structure(list(month = c("Januar / Janvier", "Februar / Février", 
  "März / Mars")), row.names = c(NA, -3L), class = "data.frame") %>%
  mutate(month = iconv(month, to = "UTF8"))

# does not work as expected
d %>% separate(month, c("a", "b"))
##         a       b
## 1  Januar Janvier
## 2 Februar       F
## 3       M      rz
## Warning message:
## Expected 2 pieces. Additional pieces discarded in 2 rows [2, 3]. 

# it works if we use this sep=
d %>% separate(month, c("a", "b"), sep = "[^\\p{L}\\d]+")
##         a       b
## 1  Januar Janvier
## 2 Februar Février
## 3    März    Mars

R.version.string
## [1] "R version 4.1.1 Patched (2021-09-21 r80946)"

packageVersion("tidyr")
## [1] ‘1.1.3’

win.version()
## [1] "Windows 10 x64 (build 19042)"
```

**Comment by DavisVaughan** [comment]
`separate()` uses base R functions for string splitting with `perl = TRUE` set
https://github.com/tidyverse/tidyr/blob/89b409d30d0f91fb82558f2e80ede3d662782a2f/R/separate.R#L159

On my Mac, it seems that `perl = TRUE` only matches ASCII characters when `alnum` is used, but `perl = FALSE` matches a wider set of characters

``` r
x <- "Februar / Février"

# Something something...respects locale?
strsplit(x, split = "[^[:alnum:]]+", perl = FALSE)
#> [[1]]
#> [1] "Februar" "Février"

# Only respects ASCII alphabetical characters?
strsplit(x, split = "[^[:alnum:]]+", perl = TRUE)
#> [[1]]
#> [1] "Februar" "F"       "vrier"
```

However, this isn't always the case as we had at least one report (@cderv) where `perl = TRUE` was working "out of the box" for this example.

This seems to be expected behavior for the `perl = TRUE` case, as documented in https://www.pcre.org/original/doc/html/pcresyntax.html#SEC8

> In PCRE, POSIX character set names recognize only ASCII characters by default, but some of them use Unicode properties if PCRE_UCP is set. You can use \Q...\E inside a character class.

A runtime way to set `PCRE_UCP` seems to be to add the `(*UCP)` option to the front of the regex, like this:

``` r
x <- "Februar / Février"

strsplit(x, split = "(*UCP)[^[:alnum:]]+", perl = TRUE)
#> [[1]]
#> [1] "Februar" "Février"
```

So we could possibly make that the default `sep` for `separate()`, but I am not sure if that works everywhere (i.e. what if we are in a non-UTF8 supported locale?)

**Comment by ggrothendieck** [comment]
I think that unicode regexes must do table lookup whereas ascii ones do not so making unicode the default could slow this down.  Would have to do some benchmarking to see if it is material.

**Comment by DavisVaughan** [comment]
Incredibly naive benchmark looks ok!

``` r
library(tidyr)

df <- tibble(x = rep("A,B", 1e5))

bench::mark(
  old = separate(df, x, into = c("a", "b"), sep = "[^[:alnum:]]+"),
  new = separate(df, x, into = c("a", "b"), sep = "(*UCP)[^[:alnum:]]+"),
  iterations = 5
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 old           1.02s    1.17s     0.840     797MB     12.9
#> 2 new        980.44ms    1.14s     0.863     796MB     13.6
```

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
My main concern is that either approach will only work if `pcre_config()[[[1]]` is `TRUE`, and I'm not sure if that's TRUE in general. Maybe we could conditionally use `"[^\\p{L}\\d]+"` if PCRE UTF-8 support is available?

**Comment by DavisVaughan** [comment]
it looks like `pcre_config()[[2]]` rather than `[[1]]` might be even more specific to what we want

```Unicode properties	
Support for \p{xx} and \P{xx} in regular expressions. Desirable and used by some CRAN packages. As of PCRE2, always present with support for UTF-8.```

(based on the last sentence, it looks like it might always be TRUE if [[1]] is TRUE, but still)

**Comment by hadley** [comment]
Or maybe we should just wait for https://github.com/tidyverse/tidyups/issues/23?

**Comment by DavisVaughan** [comment]
I was literally about to ask you this exact question. Yes I think so, especially in light of the fact that you noticed that `\d` works differently with ICU than it does with base R's engine

**Comment by hadley** [comment]
Ok, added a note to think about it there.
