### ISSUE TITLE
`hoist()` isn't type stable due to `purrr::pluck()` behavior with empty elements

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#1203]
```r
library(tidyr)

col <- list(
  list(a = integer(), b = 1),
  list(a = integer(), b = 2)
)

df <- tibble(col = col)

# Resulting `a` column should be typed as <integer>
hoist(df, col, "a", "b")
#> # A tibble: 2 × 2
#>   a         b
#>   <lgl> <dbl>
#> 1 NA        1
#> 2 NA        2

# Partly because this doesn't return `integer()`
purrr::pluck(col, 1, "a")
#> NULL
```

See https://github.com/tidyverse/tidyr/issues/1044#issuecomment-954882201 for more information

I don't think there is anything we can do about this without a change in purrr.

**Comment by hadley** [comment]
With dev purrr:

``` r
library(tidyr)

col <- list(
  list(a = integer(), b = 1),
  list(a = integer(), b = 2)
)

df <- tibble(col = col)

# Resulting `a` column should be typed as <integer>
hoist(df, col, "a", "b")
#> # A tibble: 2 × 2
#>       a     b
#>   <int> <dbl>
#> 1    NA     1
#> 2    NA     2
```

<sup>Created on 2022-10-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
The bottom half of my comment here suggests we need to do something else too 
https://github.com/tidyverse/tidyr/issues/1044#issuecomment-954882201

**Comment by DavisVaughan** [comment]
Oh it looks like I added `list_init_empty()` after that comment, and that fixes the suggestion I made in that comment
