### ISSUE TITLE
behavior of `fill` option in the `separate()` function 

### ISSUE THREAD

**Issue by issactoast** [tidyverse/tidyr#1247]
Hi, I am was looking at the fill option in the separate() function, and thought the option works counter-intuitively from the user's perspective. Therefore, I would like to suggest the following change.

## Situation
Here is the description for the fill option in `separate()`;

fill | If `sep` is a character vector, this controls what happens when there are not enough pieces. 
There are three valid options:
- "warn" (the default): emit a warning and fill from the right
- "right": fill with missing values on the right
- "left": fill with missing values on the left

the fill option is related to the filling NAs and it controls the direction;

``` r
library(tidyverse)
df <- data.frame(x = c("x", "x y", "x y z"))
df %>% 
    separate(x, c("a", "b"), 
             extra = "drop",
             fill = "left")
#>      a b
#> 1 <NA> x
#> 2    x y
#> 3    x y
```

## Problem

If sep is a character vector, this controls what happens when there are not enough pieces

After reading the above description, users (at least I) might think this controls the fill the elements which is the result character vector after separate. This was what I expected;

``` r
library(tidyverse)
df <- data.frame(x = c("x", "x y", "x y z"))
df %>% 
    separate(x, c("a", "b"), 
             extra = "drop",
             fill = "left")
#>      a b
#> 1    x <NA> 
#> 2    x y
#> 3    x y
```

## Suggestion

1. (minor change) change the option name more obvious like `na_fill` and change the description;

na_fill | If `sep` is a character vector, this controls the directions of how missing values (NAs) are filled when there are not enough pieces. 

2. (major change bur better) change the code to fill option controls the filling direction for elements, not missing values. I think this is better since another option `extra` also controls the elements in the character vector.

Hope you consider this suggestion! 

Best,
Issac

**Comment by DavisVaughan** [comment]
- I think it is too late to change the argument name, that would break too much code
- It is also too late to change what `fill` actually fills, sorry, it would just break too much!

If you read down to the actual options, I think `"left"` tries to be pretty clear about the fact that it is for missing values:

> "left": fill with missing values on the left
