### ISSUE TITLE
Update repository description :)

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/tidyr#1257]
Given that `spread` and `gather` have been superseded for a long while now, it's probably about time to change this repository description:

> Easily tidy data with spread and gather functions.

![snap](https://user-images.githubusercontent.com/19862384/145302796-7014ff54-04d2-4b92-9dcd-ab8e53e08d53.png)

**Comment by DavisVaughan** [comment]
I changed it to 

> Tidy Messy Data

which is what we use in the Title of the DESCRIPTION file
https://github.com/tidyverse/tidyr/blob/7c0f97b9f6b8b2ababf784a1fa3c1a53b59784ed/DESCRIPTION#L2
