### ISSUE TITLE
Hoist removes duplicated names from list - even if they are not targeted at all

### ISSUE THREAD

**Issue by LukasWallrich** [tidyverse/tidyr#1259]
I am aware that hoist does not like duplicated names in lists. However, I now came across a behaviour (2 below) that led to a lot of debugging effort and should - in my view - either be changed or at least trigger a warning.

1) Requesting a duplicated name

This extracts "name" and silently deletes "idea" - I didn't expect that, but it is maybe the expected behaviour. However, I would suggest to at least document this explicitly.

```r
tibble(x = list(list("my" = "name", "my" = "idea", "your" = "victory"))) %>% hoist(x, "my")
```

**2) Requesting _another_ name with hoist  - the real issue**

This extracts "victory" and silently drops "idea" - in my understanding, all list elements but ["your"] should be left alone ... anything else should at least trigger a warning?

```r
tibble(x = list(list("my" = "name", "my" = "idea", "your" = "victory"))) %>% hoist(x, "your")
```

**Comment by DavisVaughan** [comment]
#1262 fixes the two issues here. It is still not completely perfect, but I think this is a big improvement for a small amount of work, and fixing the last issue shown below is much harder

``` r
library(tidyr)

df <- tibble(x = list(list("my" = "name", "my" = "idea", "your" = "victory")))

# First issue, fixed
hoist(df, x, "my")
#> # A tibble: 1 × 2
#>   my    x               
#>   <chr> <list>          
#> 1 name  <named list [2]>
hoist(df, x, "my")$x
#> [[1]]
#> [[1]]$my
#> [1] "idea"
#> 
#> [[1]]$your
#> [1] "victory"

# Second issue, fixed
hoist(df, x, "your")
#> # A tibble: 1 × 2
#>   your    x               
#>   <chr>   <list>          
#> 1 victory <named list [2]>
hoist(df, x, "your")$x
#> [[1]]
#> [[1]]$my
#> [1] "name"
#> 
#> [[1]]$my
#> [1] "idea"

# This doesn't work right, but is hard to fix
hoist(df, x, my1 = "my", my2 = "my")
#> # A tibble: 1 × 3
#>   my1   my2   x               
#>   <chr> <chr> <list>          
#> 1 name  name  <named list [1]>
hoist(df, x, my1 = "my", my2 = "my")$x
#> [[1]]
#> [[1]]$your
#> [1] "victory"

# Do this instead for now if you know you need both
hoist(hoist(df, x, my1 = "my"), x, my2 = "my")
#> # A tibble: 1 × 3
#>   my1   my2   x               
#>   <chr> <chr> <list>          
#> 1 name  idea  <named list [1]>
```

<sup>Created on 2021-12-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
