### ISSUE TITLE
Remove temporary backwards compat support for `list()` in `names_ptypes` and `values_ptypes` of `pivot_longer()`

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#1296]
See #1291 for even more details.

When we moved from default values of `names/values_ptypes = list()` to `names/values_ptypes = NULL` and allowed `names_ptypes = list()` to mean "use a list ptype for all columns", this caused breakage in extension packages that extended `pivot_longer()` and still had `list()` as their default value for these arguments.

So we temporarily special cased a value of `list()` for these two arguments to be identical to `NULL` to give the extension packages time to update to the new default. Documentation was updated to mention this special casing, and to state that it was temporary.

We'd like to remove this special casing once the packages are updated so that `names_ptypes = list()` will again mean "use a list ptype for all columns".

This issue tracks the status of the known packages that have this issue. Once they are all fixed, we can remove the special casing from the code and documentation:

- [x] dbplyr https://github.com/tidyverse/dbplyr/pull/744
- [x] sf https://github.com/r-spatial/sf/pull/1895
- [x] sparklyr https://github.com/sparklyr/sparklyr/pull/3221
- [x] tidyseurat https://github.com/stemangiola/tidyseurat/pull/49

Once these issues are all resolved, revert everything done in this PR https://github.com/tidyverse/tidyr/pull/1297

**Comment by mgirlich** [comment]
@DavisVaughan you haven't open the issues yet, have you? I'd like to tackle this in `dbplyr` soon.

**Comment by DavisVaughan** [comment]
I haven't opened any of these yet, if you want to do one for dbplyr that'd be great, and then I can take a look if you want

**Comment by DavisVaughan** [comment]
It looks like all 4 of the packages here have been updated on CRAN, so I think we can move on this
