### ISSUE TITLE
Many, if not all tidyr functions coerce data frame input to tibbles

### ISSUE THREAD

**Issue by eshom** [tidyverse/tidyr#1302]
Hi, first of all thanks for the great package.

The problem is that whenever you use tidyr, it takes your data frame and turns it into a tibble.
My expectation is that the I get the same object out, as I passed in (Like in `reshape2::melt()` for example).
At the very least, give us an argument or global option to set the return type.

If this is the desired behaviour, I don't agree with it, but that's okay. However, it should be documented.
I couldn't find mentions of this tibble coercion in the manual.

```r
mtcars |> tidyr::pivot_longer(cols = everything())
#> # A tibble: 352 × 2
#>    name   value
#>    <chr>  <dbl>
#>  1 mpg    21   
#>  2 cyl     6   
#>  3 disp  160   
#>  4 hp    110   
#>  5 drat    3.9 
#>  6 wt      2.62
#>  7 qsec   16.5 
#>  8 vs      0   
#>  9 am      1   
#> 10 gear    4   
#> # … with 342 more rows
```

<sup>Created on 2022-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
We experimented with this in the past but because many tidyr functions produce list columns and the data.frame method for `print()` doesn't do a great job with them, we've decided to stick with tibbles everywhere.
