### ISSUE TITLE
speed-up `separate` by extracting unique values first

### ISSUE THREAD

**Issue by lotard** [tidyverse/tidyr#1349]
`separate` is surprisingly slow in common simple situations - where the column to be separated has few unique values but the  tibble has many rows.

In such cases, it's WAY faster to extract unique values first, `separate` then `right_join`. In fact, I don't see the downside of doing it always - even when all rows are (almost completely) unique, this extract/separate/right_join procedure is equally slow as just calling `separate` directly.

Consider following code handling two extremes - one unique value and (almost) no repeat values in a tibble of 1M rows:

```r
# separating a column with one unique value (in a tibble with 1M rows)
tmp = tibble(name = rep("foo_bar",1e6))
system.time(tmp %>% separate(name, into = c("foo","bar"), sep ='_')) # 11.293 on my computer
system.time(tmp %>% select(name) %>% 
              distinct() %>% 
              separate(name, into = c("foo","bar"), sep ='_',remove = F) %>% 
              right_join(tmp,by='name'))  # 0.078 on my computer
# 100x speed-up!

# separating a column with almost no repeating values (in a tibble with 1M rows)
set.seed(43)
random.10mers = replicate(2e6,paste0(letters[sample(1:26, 10, replace = T)],collapse = ''))
tmp = tibble(foo = random.10mers[1:1e6], bar = random.10mers[(1e6+1):2e6]) %>% 
  transmute(name = paste(foo,bar,sep = "_"))
system.time(tmp %>% separate(name, into = c("foo","bar"), sep ='_')) # 15.010 on my computer
system.time(tmp %>% select(name) %>% 
              distinct() %>% 
              separate(name, into = c("foo","bar"), sep ='_',remove = F) %>% 
              right_join(tmp,by='name')) # 14.883 on my computer
# no (significant) slow-down
```

---

It might be related to PR [#1304](https://github.com/tidyverse/tidyr/pull/1304). Apologies if I failed to find out it's in the works already.

**Comment by hadley** [comment]
This seems like a reasonable optimisation, but it's not clear to me where it should live. Is tidyr the right place? Would stringr be better? Or stringi? Or should we expect that you turn these strings into factors? Unfortunately I think there are just too many unknowns for us to get traction on this problem, but it would be great to have a tidyverse wide solution.
