### ISSUE TITLE
Odd behaviour with `extract()` when some elements are absent

### ISSUE THREAD

**Issue by olivroy** [tidyverse/tidyr#1376]
When the pattern is not always respected, `extract()` does not behave smoothly.
 All new columns without a full match become `NA`. 
I think it would be better to at least have a warning for that.

---
I wonder if it would be possible to have similar arguments to `fill` and `extra` to extract(), similar to separate()

I know it is easy to solve with dplyr and a couple more steps, but I think that `extract()` provides a clean way to perform this task.
``` r
dat <- tibble::tibble(
  x = c("foo (1)", "foo1", "foo2 (2)", "foo3 (3)")
)
dat |> 
    tidyr::extract(
        x, 
        into = c("x1", "x2"),
        regex = "(.+) \\((\\d+)\\)",
        convert = TRUE
    )
#> # A tibble: 4 x 2
#>   x1       x2
#>   <chr> <int>
#> 1 foo       1
#> 2 <NA>     NA
#> 3 foo2      2
#> 4 foo3      3

# Using separate and its extra arguments can work for that.
dat |> 
  tidyr::separate(
    x, 
    into = c("x1", "x2"),
    sep = " "
  )
#> Warning: Expected 2 pieces. Missing pieces filled with `NA` in 1 rows [2].
#> # A tibble: 4 x 2
#>   x1    x2   
#>   <chr> <chr>
#> 1 foo   (1)  
#> 2 foo1  <NA> 
#> 3 foo2  (2)  
#> 4 foo3  (3)
#  
```
<sup>Created on 2022-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

You can silent the `separate()` warning by specifying `fill = "right"`. Maybe a similar argument could be useful in `extract()`

## Expected output
``` r
# With a warning
#> # A tibble: 4 x 2
#>   x1    x2   
#>   <chr> <chr>
#> 1 foo   1    
#> 2 foo1  <NA> 
#> 3 foo2  2    
#> 4 foo3  3
# with a code that would look like that.
dat |> 
    tidyr::extract(
        x, 
        into = c("x1", "x2"),
        regex = "(.+) \\((\\d+)\\)",
        convert = TRUE, 
        fill = "right"
    )
```

**Comment by hadley** [comment]
The problem is that your pattern doesn't match, and the expected behaviour in that case is that you get an `NA` at the output. Unfortunately there's no way for us to fill in the result from some of the match groups, because none of them get populated by the regexp engine.
