### ISSUE TITLE
Issue working with Arabic text in tidyverse

### ISSUE THREAD

**Issue by jic007** [tidyverse/tidyr#1383]
I got two laptops; one of them works fine and the other is having issues despite using the same code, data and packages

for example if I try to concatenate text using the below it just stores gibberish

library(fs)
library(tidyverse)
library(glue)
library(readxl)
library(janitor)
Sys.setlocale("LC_CTYPE", "arabic" )

ttt <- str_c("تحويل دفعة", 
            1:10)

tttt

the other issue when I try to use str_detec/str_extract it return falses while if I used grepl it works fine

any ideas??  
---

Brief description of the problem

```r
# insert reprex here
```

**Comment by hadley** [comment]
This looks more like a stringr issue?
