### ISSUE TITLE
Rectangling tools for tree like data frames

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#1384]
There are some nice rectangling tools in tidyr but I regularly miss a tool to rectangle/flatten tree like (or recursive) data frames. For example I want to get from

``` r
df <- tibble::tibble(
  id = 1:2,
  x = c("a", "b"),
  children = list(
    tibble::tibble(
      id = 3L,
      x = "c",
      children = list(
        tibble::tibble(
          id = 5L,
          x = "e",
          children = list(NULL)
        )
      )
    ),
    tibble::tibble(
      id = 4,
      x = "d",
      children = list(NULL)
    )
  )
)

df
#> # A tibble: 2 × 3
#>      id x     children        
#>   <int> <chr> <list>          
#> 1     1 a     <tibble [1 × 3]>
#> 2     2 b     <tibble [1 × 3]>
df$children
#> [[1]]
#> # A tibble: 1 × 3
#>      id x     children        
#>   <int> <chr> <list>          
#> 1     3 c     <tibble [1 × 3]>
#> 
#> [[2]]
#> # A tibble: 1 × 3
#>      id x     children
#>   <dbl> <chr> <list>  
#> 1     4 d     <NULL>
df$children[[1]]$children
#> [[1]]
#> # A tibble: 1 × 3
#>      id x     children
#>   <int> <chr> <list>  
#> 1     5 e     <NULL>
```

<sup>Created on 2022-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

to the following

``` r
tibble::tibble(
  id = c(1L, 2L, 3L, 5L, 4L),
  x = c("a", "b", "c", "e", "d"),
  level = c(1L, 1L, 2L, 2L, 3L),
  parent = c(NA, NA, 1L, 2L, 3L)
)
#> # A tibble: 5 × 4
#>      id x      level parent
#>   <int> <chr>  <int>  <int>
#> 1     1 a          1     NA
#> 2     2 b          1     NA
#> 3     3 c          2      1
#> 4     5 e          2      2
#> 5     4 d          3      3
```

<sup>Created on 2022-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Of course this can be done with the existing tools of tidyr but it is a bit tedious. It would be great to add `unnest_tree()` and `nest_tree()` to handle this kind of data.

**Comment by hadley** [comment]
Where do you encounter this sort of data? I've never seen it before, which makes me suspect this code is better off in a separate package.

**Comment by mgirlich** [comment]
Examples would be a directory structure or a category tree that you get from an API. You parse the JSON and you have this tree structure.
It is more specialised than the recently added `purrr::modify_tree()` (https://github.com/tidyverse/purrr/issues/720) but to me this feels like a nice addition.

**Comment by hadley** [comment]
Closing this for the above reasons; I think it's an interesting idea, but doesn't feel right for tidyr yet.
