### ISSUE TITLE
Extend drop_na() to drop_inf()

### ISSUE THREAD

**Issue by modche** [tidyverse/tidyr#1385]
Potential feature request:
Extend `drop_na()` to something like `drop_na(include_inf = TRUE)` to exclude also `Inf` values.
Michael

**Comment by DavisVaughan** [comment]
I think that is a little out of scope for tidyr. We are also planning on reconsidering whether we think `drop_na()` is still a meaningful function vs just doing `filter() + across()`. See #939 

I would just use something like this

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- tibble(x = c(1, 2, NaN, Inf, -Inf, NA))

filter(df, !is.infinite(x))
#> # A tibble: 4 × 1
#>       x
#>   <dbl>
#> 1     1
#> 2     2
#> 3   NaN
#> 4    NA
```

<sup>Created on 2022-08-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
