### ISSUE TITLE
Tidyselect within id_cols argument of pivot_wider throws error

### ISSUE THREAD

**Issue by lucylgao** [tidyverse/tidyr#1402]
Manually specifying `id_cols` within `pivot_wider` to be everything but the `names_from` columns and the `values_from` using the `tidyselect` syntax `c(-NAMES_FROM_COLUMN, -VALUES_FROM_COLUMN)` throws an error saying that the column NAMES_FROM_COLUMN doesn't exist. See example below. 

I realize that you can accomplish the same thing by not passing in an `id_cols` argument, but I thought I'd report this anyways since it appears to me like a bug. 

I am on version 1.2.0 of `tidyr`.

```r
# Tribble to be widened
(dat <- tribble(
  ~ID, ~VarNames, ~VarValues,
  "1", "Type1", 5, 
  "1", "Type2", 10, 
  "2", "Type1", 3,
  "2", "Type2", 1
))

# This throws an error
(dat %>% pivot_wider(id_cols = c(-VarNames, -VarValues), 
                     names_from=VarNames, 
                     values_from=VarValues))

# This works 
(dat %>% pivot_wider(id_cols = ID, 
                     names_from=VarNames, 
                     values_from=VarValues))

# This also works 
(dat %>% select(c(-VarNames, -VarValues)))
```

**Comment by DavisVaughan** [comment]
We want to ensure that the user can't accidentally _select_ `names_from` or `values_from` columns in `id_cols`, so when the `id_cols` tidyselect expression is evaluated, those columns have been removed from the data.

Unfortunately this comes with the restriction that you can't manually _unselect_ them either.

Practically I don't think this has any affect, as they are automatically removed already, but it does surface in edge cases like this one.

I don't think there is anything we can really do here to improve this though.

**Comment by lucylgao** [comment]
Ah, I see - it does make sense that you wouldn't want the user to select `names_from` or `values_from` columns as `id_cols`. Totally agree that the case I brought up is niche and isn't worth fixing at the expense of allowing that! 

Thank you for the response. I appreciate it!
