### ISSUE TITLE
Memory usage with separate very high and not released

### ISSUE THREAD

**Issue by Rengervn** [tidyverse/tidyr#1411]
Hi

I am loading a tsv-file of 51 Mb. I am quite astonished that RStudio uses 8Gb of RAM for this.
When I keep working, this RAM usage even increases more and more, making RStudio slower and slower.

This is the script (the tsv-file can be dowloaded [here ](https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=data/naio_10_cp15.tsv.gz)(a Eurostat data file).

```r
library(tidyverse)
supply <- read.table("naio_10_cp15.tsv",   sep = '\t', header = TRUE, fill = TRUE)  %>%
  as_tibble() %>%
  pivot_longer(2:last_col(), names_to = "Year", values_to = "Value") %>%
  mutate(Value = as.numeric(Value),
         Year = as.numeric(str_replace(Year, "X","" ))) %>%
  rename(X1 = 1) %>%
  separate(X1, into = c("X1", "X2", "X3", "X4", "X5"), sep = ",")
```
The last line takes very long and increases the memory usage on my Windows computer to around 8Gb. 

if I save the data in a RDS-file and load the table in a new R session, RAM is around 1.4 Gb instead of 8 Gb.

I tried garbage cleaning with gc(), but this had no effect.
I ran the script in the RGui and in RStudio with the same effect.
If I remove the data frame with `rm(supply),` the RAM usage gets a little bit less, but still around 7.5 Gb.

I am using R.40.4 on Windows 10 with 32Gb RAM.

Cheers
Renger

**Comment by DavisVaughan** [comment]
I think most of the pain is coming from `str_split_n()`, which uses base R functions that are quite slow.

The new `separate_wider_delim()` function in #1304 is much faster and less memory intensive.

i.e. this is from running these functions on a 100k row slice of your `supply` data

```r
> bench::bench_memory(separate_wider_delim(xx, X1, ",", names = c("X1", "X2", "X3", "X4", "X5")))
# A tibble: 1 × 2
  mem_alloc memory                
  <bch:byt> <list>                
1    26.1MB <Rprofmem [3,756 × 3]>
> bench::bench_memory(separate(xx, X1, into = c("X1", "X2", "X3", "X4", "X5"), sep = ","))
# A tibble: 1 × 2
  mem_alloc memory                  
  <bch:byt> <list>                  
1     798MB <Rprofmem [228,233 × 3]>
```

Since `separate()` is going to be superseded and we can't do much to improve the base R functions, I don't think there is much we can do there.
