### ISSUE TITLE
Use `pick()` instead of `cur_data()` conditionally in `complete()`

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#1421]
To avoid deprecation warnings in tests

Only need to do this since tidyr would go out before dplyr 1.1.0, then after dplyr 1.1.0 we can require that version in tidyr and remove the conditional code.

Should probably rename `the$dplyr_needs_multiple` to something like `the$at_least_dplyr_1_1_0` and reuse that

**Comment by DavisVaughan** [comment]
And `morph()` instead of `summarise()`. Basically, a full conditional rewrite in the grouped-df method 😄

**Comment by hadley** [comment]
Fixed in #1430
