### ISSUE TITLE
[Feature request] Teach `pivot_longer` to be aware of experimental design

### ISSUE THREAD

**Issue by Joao-O-Santos** [tidyverse/tidyr#1424]
I mostly work with experimental datasets, and data collection software frequently output wide datasets, that we need to `pivot_longer()`. Sometimes the names of both within- and between-participant conditions, as well as the trial number are present in the names.

``` r
library(tidyr)

# Legend:
#  - `wcx` stands for within-participants condition number x
#  - `bcx` stands for between-participants condition number x
#  - `tx` stands for trial number x
as_expected <- data.frame(pp = 1:2,
                          wc1_bc1_t1 = c(1, NA), wc1_bc1_t2 = c(1, NA),
                          wc2_bc1_t1 = c(1, NA), wc2_bc1_t2 = c(1, NA),
                          wc1_bc2_t1 = c(NA, 1), wc1_bc2_t2 = c(NA, 1),
                          wc2_bc2_t1 = c(NA, 1), wc2_bc2_t2 = c(NA, 1))
```

We usually want the output of `pivot_longer()` to have one row per trial that each participant was *expected* to perform. This means that we want the output to have as many rows as the number of participants `Np`, times the number of trials (`nt`) per within-participant conditions (`wc`) but not per between-participant conditions (`bc`). Meaning we want `nrow(dataset)` to equal `Np * nt * wc` (but not `Np * nt * wc * bc`).

``` r
# In this case we want eight rows (2 Np * 2 nt * 2 nwc)
```

When participants performed all the trials they were *expected* to perform we can get to what we want just by setting `values_drop_na = TRUE` in the `pivot_longer()` call.

``` r
expected <- pivot_longer(as_expected, -pp,
                         names_sep = "_", names_to = c("wc", "bc", "t"),
                         values_drop_na = TRUE)
expected_nrows <- length(unique(expected$pp)) * length(unique(expected$t)) *
                  length(unique(expected$wc))
print(nrow(expected) == expected_nrows)
#> [1] TRUE
print(expected)
#> # A tibble: 8 × 5
#>      pp wc    bc    t     value
#>   <int> <chr> <chr> <chr> <dbl>
#> 1     1 wc1   bc1   t1        1
#> 2     1 wc1   bc1   t2        1
#> 3     1 wc2   bc1   t1        1
#> 4     1 wc2   bc1   t2        1
#> 5     2 wc1   bc2   t1        1
#> 6     2 wc1   bc2   t2        1
#> 7     2 wc2   bc2   t1        1
#> 8     2 wc2   bc2   t2        1
```

However, sometimes, individual participants can have some missing values in one or more trials they were *expected* to perform but for some reason they didn't.

``` r
unexpected_na <- data.frame(pp = 1:2,
                            wc1_bc1_t1 = c(1, NA), wc1_bc1_t2 = c(1, NA),
                            wc2_bc1_t1 = c(1, NA), wc2_bc1_t2 = c(NA, NA),
                            wc1_bc2_t1 = c(NA, 1), wc1_bc2_t2 = c(NA, 1),
                            wc2_bc2_t1 = c(NA, 1), wc2_bc2_t2 = c(NA, 1))
```

If we set `values_drop_na = TRUE` then we lose some of those rows (making those missing values implicit as the manual warns us).

``` r
# This way we lose a row for participant one we wanted to keep.
option1 <- pivot_longer(unexpected_na, -pp,
                        names_sep = "_", names_to = c("wc", "bc", "t"),
                        values_drop_na = TRUE)
print(nrow(option1) == expected_nrows)
#> [1] FALSE
print(option1)
#> # A tibble: 7 × 5
#>      pp wc    bc    t     value
#>   <int> <chr> <chr> <chr> <dbl>
#> 1     1 wc1   bc1   t1        1
#> 2     1 wc1   bc1   t2        1
#> 3     1 wc2   bc1   t1        1
#> 4     2 wc1   bc2   t1        1
#> 5     2 wc1   bc2   t2        1
#> 6     2 wc2   bc2   t1        1
#> 7     2 wc2   bc2   t2        1
```

If we set `values_drop_na = FALSE` we get to make those missing values explicit, but we also have to keep all the missing values for the trials they were NOT expected to perform (i.e., the trials for the between-participant conditions they were not assigned to).

``` r
# This way we keep four extra rows per participant.
option2 <- pivot_longer(unexpected_na, -pp,
                        names_sep = "_", names_to = c("wc", "bc", "t"),
                        values_drop_na = FALSE)
print(nrow(option2) == expected_nrows)
#> [1] FALSE
print(option2)
#> # A tibble: 16 × 5
#>       pp wc    bc    t     value
#>    <int> <chr> <chr> <chr> <dbl>
#>  1     1 wc1   bc1   t1        1
#>  2     1 wc1   bc1   t2        1
#>  3     1 wc2   bc1   t1        1
#>  4     1 wc2   bc1   t2       NA
#>  5     1 wc1   bc2   t1       NA
#>  6     1 wc1   bc2   t2       NA
#>  7     1 wc2   bc2   t1       NA
#>  8     1 wc2   bc2   t2       NA
#>  9     2 wc1   bc1   t1       NA
#> 10     2 wc1   bc1   t2       NA
#> 11     2 wc2   bc1   t1       NA
#> 12     2 wc2   bc1   t2       NA
#> 13     2 wc1   bc2   t1        1
#> 14     2 wc1   bc2   t2        1
#> 15     2 wc2   bc2   t1        1
#> 16     2 wc2   bc2   t2        1
``` 

Do you think we could add an option to instruct `pivot_longer` to `values_drop_na` only for the between-participant conditions?
I don't know how such a feature could be implemented...
I reason if we have an argument where we can specify the between participants conditions, `pivot_longer` could then be taught not to remove rows for which there are non-NA values for any level of those conditions.
`pivot_longer()` should probably return an error if there are more than one non-NA values for more than one level of those conditions as that is by definition impossible for between-participant conditions.
``` r
# In essence this means ensuring the folowing tiblle is always empty:
#data %>%
#expand(nesting(participant_id, between_condX, between_condY, between_cond...),
#       within_conds, trial_number) %>%
# dplyr::anti_join(data)

# Which is the case for the expected dataset.
expected %>% expand(nesting(pp, bc), wc, t) %>% dplyr::anti_join(expected)
#> Joining, by = c("pp", "bc", "wc", "t")
#> # A tibble: 0 × 4
#> # … with 4 variables: pp <int>, bc <chr>, wc <chr>, t <chr>

# But not for the one with unexpected NAs
option1 %>% expand(nesting(pp, bc), wc, t) %>% dplyr::anti_join(option1)
#> Joining, by = c("pp", "bc", "wc", "t")
#> # A tibble: 1 × 4
#>      pp bc    wc    t    
#>   <int> <chr> <chr> <chr>
#> 1     1 bc1   wc2   t2
```

<sup>Created on 2022-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I apologize for the long-winded explanation but it is my first time opening a issue here and I didn't know how else to explain it.
My greatest gratitude to everyone working in `tidyverse` and specifically `tidyr`!

**Comment by DavisVaughan** [comment]
I'm not sure how tidyr could understand the difference between the two missing values in `wc2_bc1_t2 = c(NA, NA)`. Is it possible you could set the "unexpected" missing value to a different value?

Or, if you can come up with the full table of "expected" combinations of `pp, wc, bc, t`, then you could do a `pivot_longer()` with `values_drop_na = FALSE` to generate the full grid and then use a `semi_join()` against the table with the expected combinations to drop the ones that are unexpected. The key here is to remove the `value` from play entirely. Whether or not there was an `NA` doesn't matter if you know the combination of `pp, wc, bc, t` you are looking for.

I'm fairly certain that tidyr can't provide any more tooling to help you here, so I'm going to close this. Hopefully this is enough to help you.

**Comment by Joao-O-Santos** [comment]
@DavisVaughan 
I understand.
Thank you so much for taking the time to read and for the careful reply.
Just to clarify I never meant to say that the issue couldn't be solved without the feature, `tidyverse` packages provide enough tooling to address this use case.
I just suggested that since it is a very common use case in experimental sciences that it could be useful to add the feature (i.e., a single flag or function versus several sloc).

Once again, thanks for reading and replying so carefully.
Keep up the great work!
