### ISSUE TITLE
Unexpected behavior for filter

### ISSUE THREAD

**Issue by yuliaUU** [tidyverse/tidyr#1497]
I was filtering out a dataframe that has some NAs. here is a reproducible example of the data:

![image](https://github.com/tidyverse/tidyr/assets/54612866/e55ade81-f25b-42c5-b815-074865b5d42f)

```r
data <- data.frame(a=c(1:6),
                  b= c(NA,3,4,NA,3,5)) 
data
data|>  filter(b != 3)
```
![image](https://github.com/tidyverse/tidyr/assets/54612866/37fa1eb3-c0c7-4cbd-a0bf-25ed7a27a5bc)

When I was filtering all rows where `b !=3` - I was expecting to see rows where b is `NA`,`4` and `5`: but somehow that is not the case: NAs are not included in the output which is a bit illogical for me

**Comment by DavisVaughan** [comment]
This is actually a question about dplyr, not tidyr.

Nevertheless, take a look at these docs:
https://dplyr.tidyverse.org/reference/filter.html

In particular:

> Note that when a condition evaluates to NA the row will be dropped, unlike base subsetting with [.

In the case of `b != 3`, when `b` is `NA` this `NA != 3` comparison results in another `NA`, not `FALSE`, so the row is dropped (as the docs say).

We have been considering adding an option for this in dplyr though:
https://github.com/tidyverse/dplyr/issues/6560

**Comment by DavisVaughan** [comment]
In the meantime, we typically recommend that you use `| is.na(b)` to also include missing values

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data <- data.frame(a=c(1:6), b= c(NA,3,4,NA,3,5)) 

data |>
  filter(b != 3 | is.na(b))
#>   a  b
#> 1 1 NA
#> 2 3  4
#> 3 4 NA
#> 4 6  5
```

<sup>Created on 2023-05-10 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by yuliaUU** [comment]
Thanks @DavisVaughan for the explanations!
