### ISSUE TITLE
`separate_wider_delim` function remove `sf` class and return `tibble`

### ISSUE THREAD

**Issue by benjaminhlina** [tidyverse/tidyr#1498]
When using `separate_wider_delim` with a `sf` object, the function misbehaves and returns a tibble. If using `separate` the class of the `sf` object is retained. The same issue was documented in issue #1495 but no reprex was provided. This is using v1.3.0 of `tidyr` See reprex: 
``` r
# load packages 
suppressPackageStartupMessages({
  library(crawl) # loaded for example sf object 
  library(sf) # load sf 
  library(tidyr) # load separate functions  
})

# load harbor seal data 
data("harborSeal_sf")

# check out the sf object 
class(harborSeal_sf)
#> [1] "sf"         "data.frame"
# make up fake column to separate 

harborSeal_sf$fake <- "test_1"
# now use separate_wide_delim 

er <- harborSeal_sf |>
  separate_wider_delim(cols = fake, names = c("fake", "num"), delim = "_")
class(er)
#> [1] "tbl_df"     "tbl"        "data.frame"
# returns tibble not a sf object so it changes the object's class 

# if we use separate it keeps the objects class 
cr <- harborSeal_sf |>
  separate(col = fake, into = c("fake", "num"), sep = "_")

class(cr)
#> [1] "sf"         "data.frame"
```

<sup>Created on 2023-05-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by benjaminhlina** [comment]
What is the status of this @hadley? This seems to still be an issue along with multiple issues with the newer version of `separate_`. I  understand the rational for the newer functions, just feel the idea to push superseded on `seperate()` was premature considering the multiple issues the new functions face.

**Comment by olivroy** [comment]
The issue is probably with sf, as it doesn't provide a `separate_wider_delim()` method. https://r-spatial.github.io/sf/reference/tidyverse.html

**Comment by benjaminhlina** [comment]
Thanks @olivroy for the response. That overall makes sense, sorry I directed the issue at `{tidyr}` and not `{sf}`. I'll close this issue and open one on their end. Thanks :)
