### ISSUE TITLE
Feature request: `drop_unused` function to drop unused factor levels

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/tidyr#1508]
`tidyr::drop_na` is a really nice simple function to do a common task that could instead be done with `across`. 

Likewise, it'd be great to also have a similar function to drop unused factor levels. 

So instead of `data |> mutate(across(var, forcats::fct_drop))`, you could just go `data |> tidyr::drop_unused(var)`

**Comment by hadley** [comment]
You could just use the base `droplevels()` 😄

**Comment by davidhodge931** [comment]
`drop_unused` coded in the same way as `drop_na` would be way easier to use and have much more functionality than `droplevels` - but appreciate you have to prioritise :)
