### ISSUE TITLE
replace_na() does not work for matrices

### ISSUE THREAD

**Issue by privefl** [tidyverse/tidyr#1511]
```r
x <- c(0:2, NA)
tidyr::replace_na(x, 3)
## [1] 0 1 2 3
tidyr::replace_na(matrix(x, 2), 3)
##      [,1] [,2]
## [1,]    0    2
## [2,]    1   NA
```

I have {tidyr} v1.2.1.

**Comment by hadley** [comment]
Yes, it only works with data frames or vectors, sorry.

**Comment by privefl** [comment]
Yes, but a matrix is also a vector, so.. And I get a matrix as output, so I would expect this to have worked somehow.
Maybe an error/warning would be nice.

**Comment by jranke** [comment]
There used to be a `replace_na` function somewhere that supported matrices. Silently not doing anything for matrices was not what I expected. I think a warning would be warranted.
