### ISSUE TITLE
unite fails with internal error if the columns don't exist

### ISSUE THREAD

**Issue by jwilliman** [tidyverse/tidyr#1512]
While using `tidyr::unite` on a list of dataframes I came across the following error. I'm only reporting it because it asked me to!

The list of dataframes was messy, so I was looking for a way of combining columns that may or may not exist. I'd be happy for unite to throw a warning, or error, to tell me that there were no input columns selected.

``` r
tidyr::unite(mtcars, "hello", contains("missing_column"))
#> Error in `df_append()`:
#> ! `after` must be a whole number, not an integer `NA`.
#> ℹ This is an internal error that was detected in the tidyr package.
#>   Please report it at <https://github.com/tidyverse/tidyr/issues> with a reprex
#>   (<https://tidyverse.org/help/>) and the full backtrace.
#> Backtrace:
#>     ▆
#>  1. ├─tidyr::unite(mtcars, "hello", contains("missing_column"))
#>  2. └─tidyr:::unite.data.frame(mtcars, "hello", contains("missing_column"))
#>  3.   └─tidyr:::df_append(after = after)
#>  4.     └─tidyr:::check_number_whole(after, min = 0L, max = n, .internal = TRUE)
#>  5.       └─tidyr:::.rlang_types_check_number(...)
#>  6.         └─tidyr (local) .stop(x, what, ...)
#>  7.           └─tidyr:::stop_input_type(...)
#>  8.             └─rlang::abort(message, ..., call = call, arg = arg)
```

<sup>Created on 2023-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I think its a bug on our end, thanks!

**Comment by GuiFabre** [comment]
Hello, I get the same error. Not to mention that the error is not consistent. Sometimes it works, sometimes not.

The problem might come from the fact it use unite( -1 , [...] ) instead of unite( 2:last_col() , [...] ) or something. 

Best :

![image](https://github.com/tidyverse/tidyr/assets/51246435/6496faf5-9af6-4b6c-94a6-7b4556b0bff1)

**Comment by jospueyo** [comment]
Same error here. I came because the error told me to do so.

``` r
library(tidyverse)

df <- tibble(
  a_1 = 3,
  a_2 = 4
)

df |> 
  unite(b, starts_with("b"))
#> Error in `df_append()`:
#> ! `after` must be a whole number, not an integer `NA`.
#> ℹ This is an internal error that was detected in the tidyr package.
#>   Please report it at <https://github.com/tidyverse/tidyr/issues> with a reprex
#>   (<https://tidyverse.org/help/>) and the full backtrace.
#> Backtrace:
#>     ▆
#>  1. ├─tidyr::unite(df, b, starts_with("b"))
#>  2. └─tidyr:::unite.data.frame(df, b, starts_with("b"))
#>  3.   └─tidyr:::df_append(after = after)
#>  4.     └─tidyr:::check_number_whole(after, min = 0L, max = n, .internal = TRUE)
#>  5.       └─tidyr:::.rlang_types_check_number(...)
#>  6.         └─tidyr (local) .stop(x, what, ...)
#>  7.           └─tidyr:::stop_input_type(...)
#>  8.             └─rlang::abort(message, ..., call = call, arg = arg)
```

<sup>Created on 2024-02-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
Dup of https://github.com/tidyverse/tidyr/issues/1548

**Comment by jana-purkiss** [comment]
> Same error here. I came because the error told me to do so.
> 
> library(tidyverse)
> 
> df <- tibble(
>   a_1 = 3,
>   a_2 = 4
> )
> 
> df |> 
>   unite(b, starts_with("b"))
> #> Error in `df_append()`:
> #> ! `after` must be a whole number, not an integer `NA`.
> #> ℹ This is an internal error that was detected in the tidyr package.
> #>   Please report it at <https://github.com/tidyverse/tidyr/issues> with a reprex
> #>   (<https://tidyverse.org/help/>) and the full backtrace.
> #> Backtrace:
> #>     ▆
> #>  1. ├─tidyr::unite(df, b, starts_with("b"))
> #>  2. └─tidyr:::unite.data.frame(df, b, starts_with("b"))
> #>  3.   └─tidyr:::df_append(after = after)
> #>  4.     └─tidyr:::check_number_whole(after, min = 0L, max = n, .internal = TRUE)
> #>  5.       └─tidyr:::.rlang_types_check_number(...)
> #>  6.         └─tidyr (local) .stop(x, what, ...)
> #>  7.           └─tidyr:::stop_input_type(...)
> #>  8.             └─rlang::abort(message, ..., call = call, arg = arg)
> Created on 2024-02-12 with [reprex v2.0.2](https://reprex.tidyverse.org)

I have this exact error; has this been fixed, or is there a work around?

**Comment by DavisVaughan** [comment]
Should be fixed with the latest version of tidyr, but please open a new issue if not
