### ISSUE TITLE
"align both" in separate_wider_*

### ISSUE THREAD

**Issue by jospueyo** [tidyverse/tidyr#1515]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

I would appreciate a new option in argument `too_few` which should be something similar to `"align_both"` to fill all the new columns instead of the firsts or the lasts. This might be useful, for instance, when importing spreadsheets where people used scalars and ranges in the same column, like in the example. This option would avoid the extra step with `mutate` done in the example.

``` r
library(tidyverse)

df <- tibble(
  a = c("1 - 5", 3, "2 - 6", 7)
)

(df <- df |> 
  separate_wider_delim(
    cols = a,
    delim = " - ",
    names = c("a_low", "a_high"),
    too_few = "align_start"
  ))
#> # A tibble: 4 × 2
#>   a_low a_high
#>   <chr> <chr> 
#> 1 1     5     
#> 2 3     <NA>  
#> 3 2     6     
#> 4 7     <NA>

df |> 
  mutate(a_high = if_else(is.na(a_high), a_low, a_high))
#> # A tibble: 4 × 2
#>   a_low a_high
#>   <chr> <chr> 
#> 1 1     5     
#> 2 3     3     
#> 3 2     6     
#> 4 7     7
```

<sup>Created on 2023-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
This feels a bit too hard to generalise to me — I think something like `too_few = "fill"` might work nicely in your example, but what if there are three columns in the output and two values in the input?

**Comment by jospueyo** [comment]
I buy your point. But maybe, and just thinking out loud, it might work as a rowwise `fill()`?

**Comment by hadley** [comment]
You could make you code a bit simpler by using `coalesce()`: 

```R
df |> 
  mutate(a_high = coalesce(a_low, a_high))
```

We don't have many functions that work across columns because of the challenge of what to do if they're incompatible types.
