### ISSUE TITLE
Solutions for a crowded namespace: selective removal of items? Any better ideas?

### ISSUE THREAD

**Issue by vertesy** [tidyverse/tidyr#1544]
Hello, 

I use tidyverse, and bc its a dependency for many packages, frankly, it's not really a choice.

### The problem
The global namespace often gets crowded with lot's of unneccesary variables.

This is a problem with autocomplete, bc rarely used items, often takes precedence over key base functions, for example
- typing  `ta` and hit autocomplete should result in `table()`, but once I load `tidyr` the default complete becomes `table1` which is some random example datset
- Another example r is `pr` autocompletes to `presidential` instead of `print()`. 
- I believe most people use these example datasets much much less frequently then core functions.
- Such namespace crowding makes autocomplete often useless, thus shaving off minutes every working hour.

---
### Examples

![image](https://github.com/tidyverse/tidyr/assets/5101911/2fada7ba-0330-4940-ba26-629f8fa88bf4)

![image](https://github.com/tidyverse/tidyr/assets/5101911/16be7652-be72-4ffc-9325-b4880952666b)

### Looking for a solution

1. ~Not loading tidyverse packages is not a reasonable option~
2. ~I cannot remove by rm(table1), it stays~
3. I can manually overwrite a long list of these with `table1 <- NULL`, which makes it disappear from the autocomplete list, but they stay in global namespace
4. How would you deal with this? Do u have a better solution?

### What would be a better long term solution
1. I think many package creators are lenient and spam the workspace (I am no exception). At least the separation of data objects should be loadable independently, such as done for `Seurat` and `SeuratData`.  For a lack of a better idea, I would like to propose that you separate `tidyr` and `tidyrData`, or `tidyverseData` into separate packages. I use tidyverse every day, I don't think I ever used these data objects.

Thank you for your time! 

--- 
ps. you can see another bug on the screenshot: displayed package assignment is often wrong (in RstudioServer Desert Rose): `prcomp` is from `stats` and not from `MarkdownReports`.

**Comment by DavisVaughan** [comment]
I don't have a great solution but I don't think there is really much we can do about this. I'm not sure it is reasonable to think that typing in `pr` should always result in `print()` - I think it is reasonable for package authors and IDE developers to hope that you will type in a few more characters to narrow the search further.

I also don't think we can move the data to another package at this point. Teachers often rely on these example data sets being loaded alongside the package.

**Comment by vertesy** [comment]
Ok, well that's disappointing, but life isn’t a cakewalk... 

My first example acutely pinpoints that typing _any number of characters_ for `table()` can result in weird auto completion, so hanging onto `pr...` is beside the point. 
I think the auto-completion feature changed in the meanwhile for better ordering. 

Many other packages separate data from code, eg `Seurat` and `seurat-data` (ofc you can make the case that it's big data). It is just an example.

I guess "teachers" (people) would need to do: `require(tidyr); require(tidyr_data)`.  Selective removal may be an alternative.

May I ask, **how many data objects are loaded automatically in the environment** by `tidyr` and `tidyverse`?
