### ISSUE TITLE
keep getting the error while running RStudio R 4.3.3 on MacOS Big Sur

### ISSUE THREAD

**Issue by Ge-Desmond** [tidyverse/tidyr#1547]
Error in `rethrow_id_cols_oob()`:
! `i` must be a single string, not an integer vector.
ℹ This is an internal error that was detected in the tidyr package.
  Please report it at <https://github.com/tidyverse/tidyr/issues> with a reprex and the full backtrace.
---

Backtrace:
     ▆
  1. ├─... %>% arrange(Cell_line, Drug, Oxygen, Fluence, logPS)
  2. ├─dplyr::arrange(., Cell_line, Drug, Oxygen, Fluence, logPS)
  3. ├─tidyr::pivot_wider(...)
  4. ├─tidyr:::pivot_wider.data.frame(...)
  5. │ └─tidyr:::build_wider_id_cols_expr(...)
  6. │   └─tidyr:::select_wider_id_cols(...)
  7. │     ├─rlang::try_fetch(...)
  8. │     │ └─base::withCallingHandlers(...)
  9. │     └─tidyselect::eval_select(...)
 10. │       └─tidyselect:::eval_select_impl(...)
 11. │         ├─tidyselect:::with_subscript_errors(...)
 12. │         │ └─base::withCallingHandlers(...)
 13. │         └─tidyselect:::vars_select_eval(...)
 14. │           └─tidyselect:::loc_validate(pos, vars, call = error_call)
 15. │             └─vctrs::vec_as_location(pos, n = length(vars), call = call)
 16. ├─vctrs (local) `<fn>`()
 17. │ └─vctrs:::stop_subscript_oob(...)
 18. │   └─vctrs:::stop_subscript(...)
 19. │     └─rlang::abort(...)
 20. │       └─rlang:::signal_abort(cnd, .file)
 21. │         └─base::signalCondition(cnd)
 22. ├─tidyselect (local) `<fn>`(`<vctrs___>`)
 23. │ └─rlang::cnd_signal(cnd)
 24. │   └─rlang:::signal_abort(cnd)
 25. │     └─base::signalCondition(cnd)
 26. └─rlang (local) `<fn>`(`<vctrs___>`)
 27.   └─handlers[[1L]](cnd)
 28.     └─tidyr:::rethrow_id_cols_oob(...)
 29.       └─tidyr:::check_string(i, .internal = TRUE)
 30.         └─tidyr:::stop_input_type(...)
 31.           └─rlang::abort(message, ..., call = call, arg = arg)

**Comment by DavisVaughan** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks
