### ISSUE TITLE
unnest_longer with multiple cols - values_to=glue::glue({col}_long) not working

### ISSUE THREAD

**Issue by werkstattcodes** [tidyverse/tidyr#1555]
I am trying to unnest ("make longer") two columns at the same time ("in parallel").
The values of these columns should be unnested to two new columns.

The [pertaining documentation](https://tidyr.tidyverse.org/reference/unnest_longer.html) reads as:

values_to: A string giving the column name (or names) to store the unnested values in. _If multiple columns are specified in col, this can also be a glue string containing "{col}" to provide a template for the column names._ The default, NULL, gives the output columns the same names as the input columns.

Adapting the example from the documentation site, I get however an error. 
Many thanks!

```r
library(tidyverse)

df <- tibble(
  x = 1:2,
  y = list(1:2, 3:4),
  z = list(5:6, 7:8)
)

df %>%
  unnest_longer(c(y, z), values_to=glue::glue("{col}_long"))
  
 Error: glue cannot interpolate functions into strings.
* object 'col' is a function.
```

**Comment by DavisVaughan** [comment]
You don't need `glue()`, just pass the string

``` r
library(tidyverse)

df <- tibble(
  x = 1:2,
  y = list(1:2, 3:4),
  z = list(5:6, 7:8)
)

df %>%
  unnest_longer(c(y, z), values_to = "{col}_long")
#> # A tibble: 4 × 3
#>       x y_long z_long
#>   <int>  <int>  <int>
#> 1     1      1      5
#> 2     1      2      6
#> 3     2      3      7
#> 4     2      4      8
```

<sup>Created on 2024-10-24 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
