### ISSUE TITLE
`drop_na()` loses extra classes for `tbl_df`s

### ISSUE THREAD

**Issue by d-morrison** [tidyverse/tidyr#1556]
When I add a subclass to a `tbl_df`, `drop_na()` removes that class:

``` r
iris |> 
  dplyr::as_tibble() |> 
  structure(class = c("pop_data", "tbl_df", "tbl", "data.frame")) |>  
  tidyr::drop_na()  |>   
  class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```

In contrast, it doesn't remove subclasses from `data.frame`s:
``` r

iris |> 
  structure(class = c("pop_data", "data.frame")) |>  
  tidyr::drop_na() |>   
  class()
#> [1] "pop_data"   "data.frame"
```

<sup>Created on 2024-07-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
This is a specific case of https://github.com/tidyverse/tidyr/issues/943
