### ISSUE TITLE
Feature request: `fill(.direction = "sandwich")`

### ISSUE THREAD

**Issue by jl5000** [tidyverse/tidyr#1562]
It would be useful if there was an option for fill to only populate missing values if they are sandwiched by identical values before and after (with an option to decide the maximum number of  sequential NAs for the filling to happen) - this is a common use case. Current solutions I've found seem to require the `zoo` package. 

It might also be worth considering some kind of tolerance for numerics, or being able to provide a callback as a function of the two sandwich values for more niche use cases. 

---

Reprex courtesy of Mario Reyes: https://stackoverflow.com/questions/51704128/na-filling-only-if-sandwiched-by-the-same-value-using-dplyr

``` r
tibble::tibble(id= 1:12,
       var1 = letters[1:12],
       var2 = c(NA,rep("A",2),rep(NA,2),rep("A",2),rep(NA,2),rep("B",2),NA))
#> # A tibble: 12 x 3
#>       id var1  var2 
#>    <int> <chr> <chr>
#>  1     1 a     <NA> 
#>  2     2 b     A    
#>  3     3 c     A    
#>  4     4 d     <NA> 
#>  5     5 e     <NA> 
#>  6     6 f     A    
#>  7     7 g     A    
#>  8     8 h     <NA> 
#>  9     9 i     <NA> 
#> 10    10 j     B    
#> 11    11 k     B    
#> 12    12 l     <NA>
```

<sup>Created on 2024-07-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I think this is probably getting a bit too specific for tidyr, but you can dip down and use vctrs functions to recreate the zoo example

``` r
library(vctrs)
library(dplyr)

df_in <- tibble(id= 1:12,
  var1 = letters[1:12],
  var2 = c(NA,rep("A",2),rep(NA,2),rep("A",2),rep(NA,2),rep("B",2),NA))

df_in
#> # A tibble: 12 × 3
#>       id var1  var2 
#>    <int> <chr> <chr>
#>  1     1 a     <NA> 
#>  2     2 b     A    
#>  3     3 c     A    
#>  4     4 d     <NA> 
#>  5     5 e     <NA> 
#>  6     6 f     A    
#>  7     7 g     A    
#>  8     8 h     <NA> 
#>  9     9 i     <NA> 
#> 10    10 j     B    
#> 11    11 k     B    
#> 12    12 l     <NA>

dplyr::mutate(
  df_in,
  var_new = if_else(
    vec_fill_missing(var2, "down") == vec_fill_missing(var2, "up"),
    vec_fill_missing(var2, "down"),
    NA_character_
  )
)
#> # A tibble: 12 × 4
#>       id var1  var2  var_new
#>    <int> <chr> <chr> <chr>  
#>  1     1 a     <NA>  <NA>   
#>  2     2 b     A     A      
#>  3     3 c     A     A      
#>  4     4 d     <NA>  A      
#>  5     5 e     <NA>  A      
#>  6     6 f     A     A      
#>  7     7 g     A     A      
#>  8     8 h     <NA>  <NA>   
#>  9     9 i     <NA>  <NA>   
#> 10    10 j     B     B      
#> 11    11 k     B     B      
#> 12    12 l     <NA>  <NA>
```

I think an arbitrary callback is something we'd like to avoid, as it would be much too slow when there are many groups. The implementation of `vec_fill_missing()` (used by `fill()`) is in C for performance.
