### ISSUE TITLE
spread with drop=FALSE and additional columns

### ISSUE THREAD

**Issue by JerryWho** [tidyverse/tidyr#193]
Let's say I have the following data.frame:

``` R
df <- data.frame(year=rep(1:5,3), blood=rep(c("A", "B", "0"), 5), count=1:15)
df$blood <- factor(df$blood, levels=c("A", "B", "AB", "0"))

df
       year blood count
1     1     A     1
2     2     B     2
3     3     0     3
4     4     A     4
5     5     B     5
6     1     0     6
7     2     A     7
8     3     B     8
9     4     0     9
10    5     A    10
11    1     B    11
12    2     0    12
13    3     A    13
14    4     B    14
15    5     0    15
```

As you can see the value "AB" doesn't appear in the data.frame.

So I have to use `drop=FALSE` when spreading the data:

``` R
 spread(df, blood, count, drop=FALSE)
  year  A  B AB  0
1    1  1 11 NA  6
2    2  7  2 NA 12
3    3 13  8 NA  3
4    4  4 14 NA  9
5    5 10  5 NA 15
```

So let's say there's an additional column `year2`:

``` R
df$year2 <- df$year * 2
spread(df, blood, count, drop=FALSE)

   year year2  A  B AB  0
1     1     2  1 11 NA  6
2     1     4 NA NA NA NA
3     1     6 NA NA NA NA
4     1     8 NA NA NA NA
5     1    10 NA NA NA NA
6     2     2 NA NA NA NA
7     2     4  7  2 NA 12
8     2     6 NA NA NA NA
9     2     8 NA NA NA NA
.....
```

We get for every combination of year and year2 a line in the resulting data.frame. That's no what I've expected to get.

So I tried to add the functionality in https://github.com/JerryWho/tidyr/tree/missingvalues.
Now I get

``` R
 spread(df, blood, count, drop=FALSE, other_col_as_one = TRUE)
  year year2  A  B AB  0
1    1     2  1 11 NA  6
2    2     4  7  2 NA 12
3    3     6 13  8 NA  3
4    4     8  4 14 NA  9
5    5    10 10  5 NA 15
```

Can I achieve this result with the orignal version of tidyr? Otherwise you can maybe add this functionality into the official version.

**Comment by hadley** [comment]
I'd rather make `drop = FALSE` simply do the right thing

**Comment by jennybc** [comment]
Isn't this multi-spread (#149)? Maybe that's not exactly true, but it has an awful lot of overlap with the middle bit of those examples.

```r
df %>% 
  unite(year_comb, year, year2) %>% 
  spread(blood, count, drop=FALSE) %>% 
  separate(year_comb, c("year", "year2"))
#>   year year2  A  B AB  0
#> 1    1     2  1 11 NA  6
#> 2    2     4  7  2 NA 12
#> 3    3     6 13  8 NA  3
#> 4    4     8  4 14 NA  9
#> 5    5    10 10  5 NA 15
```

**Comment by JerryWho** [comment]
@hadley : Yes, I would prefer this, too. I wasn't sure whether the current behaviour was supposed to be the right one. So I didn't want to break anything.

@jennybc Yes, you're right. This is a work around for my problem.

**Comment by hadley** [comment]
I think the basic problem is that in some places in tidyr internals `drop = FALSE` means fill in missing factor levels, and in other places it means fill in missing combinations. Maybe it would make sense to call the second case `expand`. I think it will be an easy fix, so let me try it out.

**Comment by hadley** [comment]
No, it's more complicated than I thought because as well as `id()` (where I think the fix is easy), I also need to update `split_labels()`, which isn't so easy.

...

Ok, I have it mostly working I just don't see how to compute the labels when `expand = FALSE` and `drop = FALSE`. Hopefully a new strategy will be obvious in the morning

**Comment by hadley** [comment]
The key challenge is illustrated with this example:

```R
df <- tibble(
  x1 = factor(c("a", "b"), levels = c("a", "b", "c")), 
  x2 = c("b", "a"), 
  k = c("A", "B"),
  v = 1:2
)
spread(df, key = "k", value = "v", drop = FALSE, expand = FALSE)
```

We want to include a spot for `x1` level "c" in the output, but what value of `x2` do we fill in for it? `NA`?

**Comment by hadley** [comment]
I've checked in my work so far into a local branch and I'll come back to later. Please chime in if you have any insights!

**Comment by pgramme** [comment]
Thanks! I would be happy to see a fix for this too. Agreed with @hadley 's proposition to add the `expand` parameter (maybe default to FALSE). In addition to the factors with missing levels, also the missing combinations of variables should not be filled unless `expand=TRUE`.

In the reprex below, I would like some combination of parameters to `spread(...)` which would give back the pre-`gather(...)` data.

Note that in this case, this implies to include the missing level `z` for the variable being spread but not for the other variables.

``` r
library(tidyr)
set.seed(1)

# A simple data frame in horizontal tidy format
df_h = tibble::tibble(id=1:2, name=letters[id], u_name=LETTERS[id], 
                  x=runif(2), y=runif(2), z=NA_real_)
df_h
#> # A tibble: 2 x 6
#>      id name  u_name     x     y     z
#>   <int> <chr> <chr>  <dbl> <dbl> <dbl>
#> 1     1 a     A      0.266 0.573    NA
#> 2     2 b     B      0.372 0.908    NA

# Verticalised version of df_h: only some columns are verticalised, with na.rm
df_v = df_h %>% gather("var", "val", x, y, z, factor_key=T, na.rm=T)
df_v
#> # A tibble: 4 x 5
#>      id name  u_name var     val
#> * <int> <chr> <chr>  <fct> <dbl>
#> 1     1 a     A      x     0.266
#> 2     2 b     B      x     0.372
#> 3     1 a     A      y     0.573
#> 4     2 b     B      y     0.908

# Would like to recover initial data frame df_h but additional rows were created
df = df_v %>% spread(var, val, drop=F)
df
#> # A tibble: 8 x 6
#>      id name  u_name      x      y     z
#>   <int> <chr> <chr>   <dbl>  <dbl> <dbl>
#> 1     1 a     A       0.266  0.573    NA
#> 2     1 a     B      NA     NA        NA
#> 3     1 b     A      NA     NA        NA
#> 4     1 b     B      NA     NA        NA
#> 5     2 a     A      NA     NA        NA
#> 6     2 a     B      NA     NA        NA
#> 7     2 b     A      NA     NA        NA
#> 8     2 b     B       0.372  0.908    NA

# NB: spread(..., drop=F) is currently equivalent to
df_v %>% complete(id, name, u_name, var) %>% spread(var, val)
# I would like the future implem (expand=F or yet another param?) to act like
df_v %>% complete(nesting(id, name, u_name), var) %>% spread(var, val)
```

**Comment by hadley** [comment]
This is solvable with the in-development `pivot()` function:

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidyr)

df <- tibble(
  year = rep(1:5,3),
  year2 = year * 2,
  blood = factor(rep(c("A", "B", "0"), 5), levels = c("A", "B", "AB", "0")),
  count = 1:15
)

spec <- df %>% 
  expand(blood) %>% 
  mutate(
    col_name = paste0("group_", blood), 
    measure = "count"
  )
spec
#> # A tibble: 4 x 3
#>   blood col_name measure
#>   <fct> <chr>    <chr>  
#> 1 A     group_A  count  
#> 2 B     group_B  count  
#> 3 AB    group_AB count  
#> 4 0     group_0  count

df %>% pivot(spec)
#> # A tibble: 5 x 6
#>    year year2 group_A group_B group_AB group_0
#>   <int> <dbl>   <int>   <int>    <int>   <int>
#> 1     1     2       1      11       NA       6
#> 2     2     4       7       2       NA      12
#> 3     3     6      13       8       NA       3
#> 4     4     8       4      14       NA       9
#> 5     5    10      10       5       NA      15
```

<sup>Created on 2019-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
