### ISSUE TITLE
Provide a `gather()` generic?

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/tidyr#195]
Similar to how ggvis provides custom methods for dplyr generics, I'd like to provide a `gather()` method in plotly.

This doesn't seem possible currently given that [`gather()` is not a generic and assumes the first argument is a data frame/table.](https://github.com/hadley/tidyr/blob/164b9bffc75a431224845da0b80526f94686c5b3/R/gather.R#L49-L53)

There may be a better way, but it seems the easiest solution would be to export a `gather()` generic, and essentially copy it's current body to a `gather.data.frame` method. Does that sound reasonable? If so, I'd be happy to send a pull request.

**Comment by hadley** [comment]
I think the only current problem is:

```R
  if (n_dots(...) == 0) {
    gather_cols <- setdiff(colnames(data), c(key_col, value_col))
  } else {
    gather_cols <- unname(dplyr::select_vars(colnames(data), ...))
  }
```

so analogous to `dplyr::select()`, I think this implies we need a `gather_vars()` generic.

**Comment by hadley** [comment]
`gather()` is now a generic (since we're moving to tidy eval)
