### ISSUE TITLE
complete() reorders the data.frame

### ISSUE THREAD

**Issue by sfirke** [tidyverse/tidyr#196]
I wrote a function that calls `dplyr::count()` with `sort = TRUE` like this:

```
z <- factor(c("a", "c", "c"), levels = letters[1:3])
dat <- data.frame(z)
dat %>% count(z, sort = TRUE)
       z     n
  (fctr) (int)
1      c     2
2      a     1
```

But then when I add `complete()` to my pipeline it resorts the data.frame in the order of the factor:

```
dat %>% count(z, sort = TRUE) %>% complete(z)
       z     n
  (fctr) (int)
1      a     1
2      b    NA
3      c     2

```

I can work around this by resorting after `complete`.  But the data.frame reordering was unexpected behavior; I figured `complete` would add the missing factor levels to the bottom of the data.frame.

**Comment by hadley** [comment]
No, it attempts to add them "in place"

**Comment by krlmlr** [comment]
Maintaining the order will be difficult anyway for SQL backends (#240).
