### ISSUE TITLE
gather silent fail/unexpected results with problem/non-unique variable names

### ISSUE THREAD

**Issue by npjc** [tidyverse/tidyr#214]
``` r
library(dplyr)
library(tidyr)
library(purrr)

df <- data_frame(x = 1:3, y = letters[x])
bind_cols(df, df) %>% 
  # tibble::repair_names() %>% # if you repair the names first it works as in (3) below.
  gather(variable, value, everything())

#> Source: local data frame [12 x 4]
#> 
#>        x     y variable value
#>    <int> <chr>    <chr> <chr>
#> 1      1     a        x     1
#> 2      2     b        x     2
#> 3      3     c        x     3
#> 4      1     a        y     a
#> 5      2     b        y     b
#> 6      3     c        y     c
#> 7      1     a        x     1
#> 8      2     b        x     2
#> 9      3     c        x     3
#> 10     1     a        y     a
#> 11     2     b        y     b
#> 12     3     c        y     c
```

I expected the following behaviour:
1. (maybe) warn me that there are problem/duplicate variable names
2. if i did insist to gather variables with the same name into the same key/value output then it should do that  
   _or_
3. do the `repair_names()` thing of making everything unique by adding suffix prior to gather.

**Comment by hadley** [comment]
I think we're attacking this problem upstream - e.g. `bind_cols()` no longer duplicate columns names.

I think our general principle is to avoid constructing invalid data frames, so we don't have to assertively check in every function.
