### ISSUE TITLE
feature request: drop_all_NA_rows / cols

### ISSUE THREAD

**Issue by t-kalinowski** [tidyverse/tidyr#230]
I'm not sure how common this use case is, but i find myself doing some version of this on almost every project.

```
drop_all_NA_rows <- function(df) {
  keep <- !apply(is.na(df), 1, all)
  df[keep, , drop = FALSE]
}

drop_all_NA_cols <- function(df, except = NULL) {
  maybe_drop <- !(names(df) %in% except)
  df[maybe_drop] <- lapply(df[maybe_drop], function(col)
    if (all(is.na(col))) NULL else col)
  df
}
```

This is usually done after reading in an excel file (typically with `readxl` or `openxlsx`) or a text file with `readr`. Most of the logs / tables / field forms I deal with, when read in, come with a bunch of empty rows and columns that are meaningless. 

This is particularly common with Excel files, or a text file that at some point in the recent past was an Excel files.

**Comment by jennybc** [comment]
There is a `drop_NA()` function in the most recent tidyr release. See #194. That implements `drop_all_NA_rows()`. You could use `dplyr::select_if()` with `anyNA()` to achieve `drop_all_NA_cols()` (except for the `except` part 😁).

**Comment by t-kalinowski** [comment]
Thank you for the link! I wasn't aware of `drop_na()`. It does something a little different however. It in essence look across rows with  `any(is.na(.))`, instead of `all(is.na(.)`. A small example:

```
library(tidyr)
df <- tibble::frame_data(
  ~x, ~y, ~z,
   1,  1,  1,
   2,  2,  2,
   3,  NA, 3,
  NA, NA, NA
)

drop_na(df) # drops rows 3 and 4
drop_all_NA_rows(df) # drops only row 4
```

Perhaps a name like `drop_empty_rows()` would be more evocative?

**Comment by hadley** [comment]
You should be able to do this now with `dplyr::filter_all()`
