### ISSUE TITLE
spread: formal argument "sep" matched by multiple actual arguments

### ISSUE THREAD

**Issue by andrewhn** [tidyverse/tidyr#234]
Hi,

I am getting the following error from the snippet below. Removing one or two of the dummy creation/spread steps achieves the expected result. For some reason, the third spread results in the error.

```
Error in paste(wed = c(2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L,  : 
  formal argument "sep" matched by multiple actual arguments
```

``` r
require(dplyr)
require(lubridate)
require(tidyr)

d <- data.frame(dt=seq(ymd_hm('2015-07-01 00:00'), ymd_hm('2016-07-01 00:00'), by='1 hour'))

reg <- d %>%
  mutate(hr=paste0("hr_", as.character(hour(dt))),
         day=tolower(format(dt, "%a")),
         mth=tolower(format(dt, "%b")),
         dummy=1) %>%
  spread(mth, dummy, fill=0) %>%
  mutate(dummy=1) %>%
  spread(day, dummy, fill=0) %>%
  mutate(dummy=1) %>%
  spread(hr, dummy, fill=0)
```

**Comment by andrewhn** [comment]
I may be doing something dumb here, but if I change the ``%b`` to ``%B``, it works as is ...

```r
> intersect(tolower(format(d$dt, "%a")), tolower(format(d$dt, "%b"))) 
character(0)
```

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

Additionally, can you please use the reprex package to generate the reprex? 

(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
