### ISSUE TITLE
Doc: tidyr::extract_numeric() documentation references nonexistant routine 

### ISSUE THREAD

**Issue by cswarth** [tidyverse/tidyr#248]
The [documentation for tidyr::extract_numeric() ](https://cran.r-project.org/web/packages/tidyr/tidyr.pdf) 

```
DEPRECATED: please use readr::parse_numeric() instead.
```

This should instead reference `parse_number()` as `parse_numeric()` is deprecated.

Also there is an index entry for `parse_numeric()` in the [readr documents](https://cran.r-project.org/web/packages/readr/readr.pdf) but it is not mentioned elsewhere in the document.

**Comment by hadley** [comment]
Fixed a while back, I think.
