### ISSUE TITLE
nest fails when list variable is present but not nested

### ISSUE THREAD

**Issue by drsimonj** [tidyverse/tidyr#249]
In a data frame with a list variable, `nest()` will work when the list variable is included but throws the following error when it is not: `Error in grouped_df_impl(data, unname(vars), drop): Column `x` can't be used as a grouping variable because it's a list`. Appears to be because dplyr cannot group list-cols.

Reproducible example:

``` r
library(tibble)
library(tidyr)

d <- tibble(
  x = list(c(1, 2), c(3, 4)),
  y = c(1, 2),
  z = c(3, 4)
)

# Nesting the list variable (x) works
d %>% nest(x, y)
#> # A tibble: 2 x 2
#>       z             data
#>   <dbl>           <list>
#> 1     3 <tibble [1 x 2]>
#> 2     4 <tibble [1 x 2]>

# Not nesting the list variable results in error
d %>% nest(y, z)
#> Error in grouped_df_impl(data, unname(vars), drop): Column `x` can't be used as a grouping variable because it's a list
```

**Comment by Deleetdk** [comment]
Running your code crashes R/RS entirely for me.

**Comment by drsimonj** [comment]
Just the error for me. In case it's relevant, here's my session info (after fresh install of `tidyr` from GitHub):

```r
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.6.1.9000 tibble_1.2      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9.1    withr_1.0.2      digest_0.6.10    dplyr_0.5.0      assertthat_0.1   grid_3.3.1       plyr_1.8.4       R6_2.1.2        
 [9] gtable_0.2.0     DBI_0.4-1        git2r_0.15.0     magrittr_1.5     scales_0.4.1     httr_1.2.1       ggplot2_2.2.0    curl_0.9.7      
[17] lazyeval_0.2.0   devtools_1.12.0  tools_3.3.1      munsell_0.4.3    colorspace_1.2-7 memoise_1.0.0    knitr_1.15.1
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by drsimonj** [comment]
Thanks and done! Issue is clearer with dplyr update (see update to issue). Perhaps this is not an issue that tidyr can get around?

**Comment by hadley** [comment]
Yeah, looks like it will need to wait until dplyr can handle list columns as grouping vars.

**Comment by qcao** [comment]
Still cannot seem to handle it...
