### ISSUE TITLE
unnest does not work with empty data frame

### ISSUE THREAD

**Issue by feuerbach** [tidyverse/tidyr#253]
```R
library(tidyr)
tibble::tibble(a = character(), b = list()) %>% unnest()
#> Error in rep(1:nrow(data), n[[1]]): invalid 'times' argument
```

**Comment by feuerbach** [comment]
The commit above prevents the crash, but it seems to drop the "nested" column (even if I set `.drop = FALSE`.)

While testing it, I discovered another crash condition (perhaps deserving its own issue?)

```
> data.frame(a=c("def"), b=I(list(c()))) %>% unnest()
 
 Error: no data to combine, all elements are NULL 
```

**Comment by krlmlr** [comment]
Obviously the code wasn't prepared for length-0 data, you might need to add special handling for this case somewhere, and perhaps also a test for the expected behavior.

**Comment by gdbassett** [comment]
I run into this regularly as well `nest()` will create a list with `NULL` entries that cannot be unnested().

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by gdbassett** [comment]
``` r
library(magrittr)
data.frame(a=c("def"), b=I(list(c()))) %>% tidyr::unnest()
#> Error in combine_all(args[[1]]): no data to combine, all elements are NULL
```

**Comment by hadley** [comment]
In the dev version, that gives me:

``` r
library(tidyr)
tibble::tibble(a = "def", b = list(c())) %>% unnest()
#> Error in combine_all(args[[1]]): no data to combine, all elements are NULL
```

which seems right to me

**Comment by hadley** [comment]
But that's not an empty data frame. Here's a real reprex

``` r
library(tidyr)
tibble::tibble(a = character(), b = list()) %>% unnest()
#> Error in rep(1:nrow(data), n[[1]]): invalid 'times' argument
```

**Comment by hadley** [comment]
I've cleaned up the issue title/comment thread to focus on key components of problem. Thanks for the correspondence so far :smile:
