### ISSUE TITLE
Issue with complete and grouped_df

### ISSUE THREAD

**Issue by carlganz** [tidyverse/tidyr#256]
With a regular ungrouped data.frame, using a factor or a character variable when using `complete` gives the same results. When using grouped_df with character it doesn't generate any new values, because (I suspect) it only looks for unique character values that exist within each group, not across the whole data.frame. I believe (could be wrong) that using a character variable in `complete` for a grouped data.frame will always return the same data.frame, which sort of defeats the purpose of `complete`.

``` R
library(tidyr)
library(dplyr)

df <- data.frame(stringsAsFactors=FALSE,
                 v1=c(1,1,2,3,4),
                 v2=c("A","B","B","A","C"), 
                 v3=rnorm(5,0,1))

df %>% complete(v1, v2) # works

df %>% mutate(v2=as.factor(v2)) %>% complete(v1,v2) # works

df2 <- df %>% group_by(v1) 

df2 %>% complete(v1, v2) # doesn't really work

df2 %>% mutate(v2=as.factor(v2)) %>% complete(v1,v2) # works
```

I  can see that this may not be a bug per se since it isn't immediately clear what the intended behavior of `complete` is when used with `group_by`, but there should probably be a note in the documentation about how the two interact.

Thanks

**Comment by lenakba** [comment]
Using `complete()` on data frames grouped by character vectors *does* work, i.e. it arguably returns the correct result. However, using it on data frames grouped by a factor vector returns incorrect results. Example data frames:

```r
# Create a simple frame
d = data_frame(
  foo = LETTERS[1:3],
  bar = c("Hello", "Good bye", "Hello"),
  x = 1:3
)

# Two data frames both grouped by `foo`,
# one where `foo` is a character vector and
# one where it is a factor vector
d_chr = d %>% group_by(foo)
d_fac = d %>% mutate(foo=factor(foo)) %>% group_by(foo)
```

Using `complete()` on `d_chr` works, i.e. it basically returns `d_chr`:

```r
> d_chr %>% complete(foo, bar, fill=list(x=0))
Source: local data frame [3 x 3]
Groups: foo [3]

    foo      bar     x
  <chr>    <chr> <dbl>
1     A    Hello     1
2     B Good bye     2
3     C    Hello     3
```

Using `complete()` on `d_fac` returns:

```r
> d_fac %>% complete(foo, bar, fill=list(x=0))
Source: local data frame [9 x 3]
Groups: foo [3]

     foo      bar     x
  <fctr>    <chr> <dbl>
1      A    Hello     1
2      B    Hello     0
3      C    Hello     3
4      A Good bye     0
5      B Good bye     2
6      C Good bye     0
7      A    Hello     1
8      B    Hello     0
9      C    Hello     3
```

The expected/correct result would be the data frame we obtain by using `do()`:

```r
> d_fac %>%
+ do(complete(., foo, bar, fill=list(x=0)))
Source: local data frame [9 x 3]
Groups: foo [3]

     foo      bar     x
  <fctr>    <chr> <dbl>
1      A    Hello     1
2      B    Hello     0
3      C    Hello     0
4      A Good bye     0
5      B Good bye     2
6      C Good bye     0
7      A    Hello     0
8      B    Hello     0
9      C    Hello     3
```

**Comment by hadley** [comment]
I'd argue that the current behaviour is correct in both cases. 

You shouldn't expect `df %>% group(x) %>% complete(y)` to be the same as `df %>% complete(x, y)` because it in the grouped case it only completes within a group. 

The factor case is arguably correct because `complete()` is a wrapper around `expand()`, which automatically uses factor levels, not values that are present.
