### ISSUE TITLE
Semantics of nesting?

### ISSUE THREAD

**Issue by vspinu** [tidyverse/tidyr#260]
What is the mnemonic for `nesting`?  It's unrelated to `nest` function and it's not particularly suggestive (to me at least). I would rather think about it as `existing`, suggesting that only existing combinations are kept.

Also it's not particularly clear from the doc that `expand` is doing crossing by default. That is `    expand(mtcars, vs, cyl)` and  `expand(mtcars, crossing(vs, cyl))` are the same thing. There are no examples for the use of `crossing`.

**Comment by hadley** [comment]
Nesting vs crossed factors in statistics. It's very obvious to me 🤓
