### ISSUE TITLE
Make sure spread() and gather() use proper encoding

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyr#263]
- [ ] spread() should warn when creating columns where the names cannot be represented in the native encoding
- [ ] gather() should convert character columns to UTF-8

On Ubuntu, I can "emulate" Windows with a latin1 encoding using `Sys.setlocale("LC_CTYPE", "en_US.iso88591")`; on OS X `Sys.setlocale("LC_CTYPE", "en_US.iso8859-1")` worked for me (note the dash). `Sys.setlocale("LC_CTYPE", "C")` sets R to ASCII-only mode. `system("locale -a", intern = TRUE)` lists all installed locales.

**Comment by hadley** [comment]
Do you have a simple reprex for this issue?

**Comment by pgensler** [comment]
I think ```separate``` may have this issue as well? See comment 16 on that thread for an example.
https://community.rstudio.com/t/split-uneven-length-vectors-to-columns-with-tidyr/2704/16

**Comment by krlmlr** [comment]
@hadley: Looks like `spread()` and `gather()` work as expected in non-UTF-8 locales.

@pgensler: The description you linked to feels like a different issue.
