### ISSUE TITLE
Please allow secure access to Web site

### ISSUE THREAD

**Issue by paulmenzel** [tidyverse/tidyr#264]
Currently accessing the [tidyr Web site over HTTPS](https://tidyr.tidyverse.org/) a warning is shown, as the certificate is for the GitHub domains.

> tidyr.tidyverse.org uses an invalid security certificate.
>
> The certificate is only valid for the following names:
>   www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com  
>
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

Quickly searching the Web, I found the following two link, where the second one, is just about normal GitHub Pages.

1. https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/
2. https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by hadley** [comment]
I'll do this en masse when github provides a direct way to use https for custom domains.
