### ISSUE TITLE
hms columns coerced to double when using fill, only if dataframe is grouped

### ISSUE THREAD

**Issue by dpastoor** [tidyverse/tidyr#277]
Edited based on hadley's request for brevity:

* issue 1: in a grouped context - any hms coerced to double
* issue 2: when hms column is the _grouping_ column, all rows rearranged in order for the coerced double

Example as of tidyr 0.6.1 and dplyr 0.5

```
library(tidyverse)
df <- tibble::data_frame(
  GROUP = c("A", "A", "A", "B", "B", "B"), 
  TIME = hms::hms(hours = c(1:3, 1:3)),
  TO_FILL  = c(1, 2, 3, 1, NA, 3)) 

# this does not impact the time column
df %>% fill(TO_FILL)

# this will turn the TIME column into double, even though not even filled
df %>% group_by(GROUP) %>% fill(TO_FILL)

# this will turn the TIME column into double, AND rearrange the data so it is descending by time
df %>% group_by(GROUP) %>% fill(TO_FILL)
```

The final output (demonstrating both issues 1/2) results look like: 
```
> df %>% group_by(TIME) %>% fill(TO_FILL)
Source: local data frame [6 x 3]
Groups: TIME [3]

  GROUP  TIME TO_FILL
  <chr> <dbl>   <dbl>
1     A  3600       1
2     B  3600       1
3     A  7200      2
4     B  7200       2
5     A 10800       3
6     B 10800       3
```

Original comment tracked at https://gist.github.com/dpastoor/59d1f325df9177eb7db82fb566427842

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem - you don't need to include two complete copies of the code. And please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.

**Comment by dpastoor** [comment]
Sorry, the point was to have a code chunk easy to copy on the top, where you could see the whole bit, with the interleaved output below. 

Normally I don't include such expansive output, but I wanted to capture the tibble output to show the coercion to seconds was not a printing artifact.

The intent is, given an `hms` extraneous column, even when not involved in grouping or filling operations, the coercion behavior occurs. 


I also found another bug, related to arrangement, when using the hms column as the grouping column, in which both coercion and rearrangement of data occurs. Both bugs are demonstrated in a (hopefully) better named, smaller example below.

```
library(tidyverse)
df <- tibble::data_frame(
  GROUP = c("A", "A", "A", "B", "B", "B"), 
  TIME = hms::hms(hours = c(1:3, 1:3)),
  TO_FILL  = c(1, NA, 3, 1, 2, 3)) 

# this does not impact the time column
df %>% fill(TO_FILL)

# this will turn the TIME column into double, even though not even filled
df %>% group_by(GROUP) %>% fill(TO_FILL)

# this will turn the TIME column into double, AND rearrange the data so it is descending by time
df %>% group_by(GROUP) %>% fill(TO_FILL)

> df %>% group_by(TIME) %>% fill(TO_FILL)
Source: local data frame [6 x 3]
Groups: TIME [3]

  GROUP  TIME TO_FILL
  <chr> <dbl>   <dbl>
1     A  3600       1
2     B  3600       1
3     A  7200      NA
4     B  7200       2
5     A 10800       3
6     B 10800       3
```

**Comment by hadley** [comment]
Can you please _edit_ your original comment. The point is to make an issue that I can skim quickly when I come back to the problem.

**Comment by dpastoor** [comment]
@hadley done, deleted second comment and updated first comment - I know you are busy with other things, is this something you'll be looking into soon? There are a number of FDA projects with time series data that the intent was to migrate to tidyr (with fill), however if this is not on short term radar, we will just hold off. Happy to help try to track down the cause if that will help in any capacity.

**Comment by hadley** [comment]
Could you please use the reprex package so I can see both the input and output in the issue?

**Comment by dpastoor** [comment]
in the original comment, I did that, but you said it was too verbose and to remove it :-)

The original reprex and session_info are still retained in the above gist. However, importantly, this seems to be resolved with new versions of the tidyverse packages.

Showing the output to confirm the correct behavior in new versions:

``` r
library(tidyverse)

df <- tibble::data_frame(ID = rep(c("A", "B"), each = 5), TIME = hms::hms(hours = 1:10),
                         some_na  = c(1, NA, 3:10)) 

df %>% group_by(ID) %>% fill(some_na)
#> # A tibble: 10 x 3
#> # Groups:   ID [2]
#>       ID     TIME some_na
#>    <chr>   <time>   <dbl>
#>  1     A 01:00:00       1
#>  2     A 02:00:00       1
#>  3     A 03:00:00       3
#>  4     A 04:00:00       4
#>  5     A 05:00:00       5
#>  6     B 06:00:00       6
#>  7     B 07:00:00       7
#>  8     B 08:00:00       8
#>  9     B 09:00:00       9
#> 10     B 10:00:00      10
```


select session info components:

```
 hms          0.3        2016-11-22 CRAN (R 3.4.0)
 dplyr      * 0.7.0      2017-06-09 CRAN (R 3.4.0)   
tidyr      * 0.6.3      2017-05-15 CRAN (R 3.4.0)  
```


Suggest this be closed?

**Comment by hadley** [comment]
Great!
