### ISSUE TITLE
unnest drops rows with NULL values in nested column

### ISSUE THREAD

**Issue by azeloc** [tidyverse/tidyr#282]
should tidyr::unnest drop the first row of the tibble below? one can answer "yes" because "d" should be NA, not a NULL value, but dropping rows without a warning seems an issue to me.

``` 
dplyr::tibble(
    a = c(1,1),
    b = list(d = NULL, e = c(1,2,3)), 
    c = c(2,2)) %>%
tidyr::unnest(b) 
```

**Comment by hadley** [comment]
I think the behaviour is correct - you get the same number of rows as the length of the value.
