### ISSUE TITLE
Gather not playing nicely with columns whose names are numbers

### ISSUE THREAD

**Issue by bushal01** [tidyverse/tidyr#289]
Was using gather with a dataframe whose column names were "1974","1978","1982" and so on.  When specifying the columns to gather, the following would not work:

gather(df, year, acres_farmed, 1974:1982)
gather(df, year, acres_farmed, c(1974, 1978, 1982))
gather(df, year, acres_farmed, c('1974', '1978', '1982'))
gather(df, year, acres_farmed, '1974':'1982')

Eventually had to change the column names to "x1974","x1978","x1982" and then the first option worked:

gather(df, year, acres_farmed, x1974:x1982)

**Comment by lionel-** [comment]
does this work?

```
gather(df, year, acres_farmed, `1974`:`1982`)
```

**Comment by bushal01** [comment]
Yes, that does.

**Comment by lionel-** [comment]
That's the way to do it because pure numbers are not valid symbols in R. Maybe it would make sense to if `"string1":"string2"` worked. But this issue belongs in dplyr, if you'd like to open one over there.
