### ISSUE TITLE
expand() missing factor values with zero-row data.frame

### ISSUE THREAD

**Issue by stephematician** [tidyverse/tidyr#290]
Is there a reason that expand() does not expand a data.frame with zero rows?

    df <- data.frame(y=factor('A', levels=c('A','B')))
    df %>% expand(y)

    # A tibble: 2 × 1
           y
      <fctr>
    1      A
    2      B

    df %>% filter(FALSE) %>% expand(y)

    NULL

In terms of "filling in" missing values I would have expected that the last two commands would produce the same result.

**Comment by colearendt** [comment]
Duplicate of #270 and proposed fix in PR #285
