### ISSUE TITLE
drop_na for column names with symbols  

### ISSUE THREAD

**Issue by kertcher** [tidyverse/tidyr#291]
df <- data.frame(replicate(2, sample(0:1,50,rep=TRUE)))
df[1,1] <- NA 
colnames(df) <- c("ID#", "Num")
tidyr::drop_na(df, ID#)
# getting a "+" sign 
tidyr::drop_na(df, 'ID#')
# Error: All select() inputs must resolve to integer column positions..... 
tidyr::drop_na(df, 1) 
# Column index works, but it goes against the elegance of tidyr. Is it possible to add an argument for specifying a column name(s) in quotation 'AS IN R base'?

**Comment by jennybc** [comment]
Can you work on the formatting? It sounds superficial, but it truly makes your issue easier for others to process and ultimately do something about.

General tips for formatting things in Markdown on GitHub:

https://guides.github.com/features/mastering-markdown/

An R package built specifically for this:

https://github.com/jennybc/reprex#readme

**Comment by hadley** [comment]
The solution is to use backticks:

```R
tidyr::drop_na(df, `ID#`)
```
