### ISSUE TITLE
tidyr and tidyeval

### ISSUE THREAD

**Issue by uhlitz** [tidyverse/tidyr#293]
`select()` and `gather()` work nicely with `!!quo()`, whereas `spread()` does not. It returns `Error: Invalid column specification`. Example:

    library(tidyverse)
    mtcars %>% 
        mutate(name = row.names(.)) %>% 
        as_tibble() %>% 
        select(cyl, mpg, !!quo(name)) %>% 
        gather(key, value, -!!quo(name)) %>% 
        spread(key, !!quo(value))

versions:

    dplyr      * 0.5.0.9004 2017-04-18 Github (tidyverse/dplyr@68bece7)
    rlang        0.0.0.9017 2017-04-18 Github (hadley/rlang@8fd2651)
    tidyr      * 0.6.1.9000 2017-04-18 Github (tidyverse/tidyr@41ac9cc)

**Comment by lionel-** [comment]
tidyr hasn't been ported to tidyeval yet, but it's on the todo list.

**Comment by lionel-** [comment]
I'm working on it right now ;)

**Comment by lionel-** [comment]
ETA today or tomorrow

**Comment by lionel-** [comment]
here it is. You're welcome to test it:

```r
devtools::install_github("lionel-/tidyr", ref = "port-rlang")
```

**Comment by stanstrup** [comment]
Yeah! Seems to work in my test that failed me before. Thanks!

**Comment by lionel-** [comment]
Now merged on master.

**Comment by benalmer** [comment]
Hi, I'm facing the same issue although I have updated my packages. Could you please help?
Thanks!

**Comment by lionel-** [comment]
`devtools::install_github("tidyverse/tidyr")`, or wait next week when it's on CRAN.
