### ISSUE TITLE
nest() converts NA to NULL in nested table

### ISSUE THREAD

**Issue by JMLuther** [tidyverse/tidyr#294]
nest() converts NA to NULL, when included in a nested table, resulting in some unexpected results.
If this is an intended feature I haven't been able to find any documentation on how to avoid it. 

Here is a small reproducible example, using the listviewer to examine the nested table:
```
dfTest <- data_frame(id = rep(1:3, each=3),
                     time = rep(1:3, 3),
                     y = c(rnorm(8), NA))
dfTest %>% tidyr::nest(-id, .key=data) %>% 
  listviewer::jsonedit()
```
tidyr_0.6.1
dplyr_0.5.0.9002
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by JMLuther** [comment]
Thanks Hadley. This is not a real issue. 
nest() does not really convert to NULL.
However, the listviewer does show the result as 'NULL'
