### ISSUE TITLE
Reshape two columns of data with spread

### ISSUE THREAD

**Issue by jstitlow** [tidyverse/tidyr#296]
Sorry, not a bug, just a suggestion. 

This doesn't work using the spread function:
spread <- (df,Gentoype,D)
Error: duplicate identifiers for rows (1,2,3...etc)

![image](https://cloud.githubusercontent.com/assets/5816582/25250079/277a3252-260c-11e7-8920-b4d2f59c49fc.png)

But this does:
spread <- (df,Gentoype,D)

![image](https://cloud.githubusercontent.com/assets/5816582/25250470/9fefc232-260d-11e7-8dbf-97b3659a10f8.png)

Is there a way to ignore the identifiers when the values are not correlated, and just fill the new columns directly?

maybe this:
spread <- (df,Genotype,D, Literal=TRUE)

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by markdly** [comment]
@jstitlow you can use `rownames_to_column()` to achieve the desired effect.  Here's a short reprex based on the original post to demonstrate:

``` r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats

df <- tribble(
  ~D, ~Genotype,
   1, "GFP",
   3, "GFP",
   5, "GFP",
   2, "WT",
   4, "WT"
)

# won't work as Genotype values are not unique
df %>%
  spread(Genotype, D)
#> Error: Duplicate identifiers for rows (1, 2, 3), (4, 5)

# for desired result, add rowname column before spreading
df %>%
  rownames_to_column() %>%
  spread(Genotype, D)
#> # A tibble: 5 x 3
#>   rowname   GFP    WT
#> *   <chr> <dbl> <dbl>
#> 1       1     1    NA
#> 2       2     3    NA
#> 3       3     5    NA
#> 4       4    NA     2
#> 5       5    NA     4
```

**Comment by hadley** [comment]
@markdly thanks for the reprex and workaround!
