### ISSUE TITLE
drop_na() option to drop rows with ALL NA's

### ISSUE THREAD

**Issue by noamross** [tidyverse/tidyr#298]
Per [this conversation](https://twitter.com/noamross/status/857609829480792064), it would be useful to have a function, or possibly an option in `drop_na()`, to drop rows from a data set that are _all_ NA, or which a range of columns are all NA (as opposed to one or more being NA).  Possible use cases include reading in excel sheets where rows are left blank as spacers for formatting purposes, or cases where some records have indexing values, but no actual data. 

@jennybc has a quick implementation here: https://gist.github.com/jennybc/a5c0710ec9d024cbd5c289a3d7569267

`janitor::drop_empty_rows()` works for the case where all the values are NA.

**Comment by hadley** [comment]
You should be able to do this now with `dplyr::filter_all()`
