### ISSUE TITLE
Documentation request: please clarify ""Each row must have the same number of entries." from help(unnest)

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/tidyr#299]
In the current CRAN version of tidyr (0.6.1 as of 2017-04-30) help(unnest) includes the text "Each row must have the same number of entries."  There does not seem to be enough context to clearly establish what this limitation means.  It does not seem to mean that each entry of the list column being expanded must have a vector of the same length as shown by the ragged example below.

The ability to expand ragged columns is useful, so it would be nice if the documentation did not make it appear to be prohibited.

```r
library("tidyr")
packageVersion('tidyr')
# [1] ‘0.6.1’
# help(unnest)
# # "Each row must have the same number of entries."
d <- data.frame(name= c('a','b'))
d$value <- list(c(1,2),3)
unnest(d, value)
 # name value
 # 1    a     1
 # 2    a     2
 # 3    b     3
```

I've thought about it a bit and I think the text means if you specify more than one list column to expand the must match each other on vector length in each row.

**Comment by hadley** [comment]
I clarified the docs based on another email thread. Hopefully it's at least a bit better now.
