### ISSUE TITLE
Feature request: drop unused factor levels before complete

### ISSUE THREAD

**Issue by nickbond** [tidyverse/tidyr#306]
I have a situation where I have filtered a very large categorical (factor), and would like to use complete to generate all combinations from only the filtered levels with levels of another variable. It would be great to have a droplevels=T option to omit levels that do not occur in the vector of values.

I appreciate this could initially seem to be at odds with the intention of adding missing combinations in the first place. 

Many thanks, Nick

**Comment by hadley** [comment]
This seems out of scope for tidyr. Why not apply `droplevels()` yourself beforehand?

**Comment by nickbond** [comment]
Thanks Hadley... Makes sense. Good suggestion as always.
