### ISSUE TITLE
FR: separate into list column

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyr#309]
Both `separate()` and `separate_rows()` could be implemented using a simpler verb, e.g., `split()`, that separates into a list column that contains tibbles. This would be basically `separate()` minus `unnest()` in other words, `. %>% split(...) %>% unnest()` would be the same as `. %>% separate()` or `. %>% separate_rows()`, depending on the arguments to `split()`.

This would give the user more flexibility, e.g., for implementing `separate_n()` (#283).

**Comment by hadley** [comment]
We also a verb that unnests into columns with similar arguments to separate.

**Comment by hadley** [comment]
I wonder if the correct behaviour is for `unnest()` to have an argument that controls the direction of unnesting for 1d vectors. It would default to "rows" for unnamed vectors, and "cols" for named vectors. It would be "both" for 2d objects, and I need to think about if "rows" or "cols" makes sense for data frames.

We'd need a parallel operation for `nest()`. Currently `direction = "both"` but it certainly seems useful to have rows and cols directions (and maybe one of those corresponds to the original behaviour?)

**Comment by hadley** [comment]
I'm starting to play with this, and when I remove all the options related to the new columns, I basically end up with this:

```R
str_separate <- function(x, sep = "[^[:alnum:]]+") {
  if (is.numeric(sep)) {
    strsep(x, sep)
  } else if (is_character(x)) {
    stringi::stri_split_regex(x, sep)
  } else {
    abort("`sep` must be either numeric or character")
  }
}
```

So what advantage would this function have over `df %>% mutate(x = str_split(x, ","))`?

**Comment by krlmlr** [comment]
The new verb would allow for a more concise syntax, without repeating `x`.

Also, we might want to separate into a tibble column instead.

**Comment by hadley** [comment]
I don't think not repeating `x` is sufficient justification for a new verb (especially since you might want to preserve `x` so we'd need an option for that).

I think separating into a df-col would be a composite operation. I don't think we want different verbs for separating into rows, cols, a list-col, and a df-col. Instead, you'd use `mutate()` + `str_split()` and then a more powerful `unnest()` would allow you to choose between rows, cols, or a df-col.
