### ISSUE TITLE
FR: nest_if()

### ISSUE THREAD

**Issue by amarchin** [tidyverse/tidyr#310]
In the spirit of the dplyr functions `mutate_if()` and `select_if()` I think could be nice to have a function `nest_if()` that can handle the columns to nest according to a logical predicate.

For instance if I had a tibble with both factor and double columns I could nest only the double ones with `nest_if(my_tbl, is.double)`.

**Comment by hadley** [comment]
I think that's a good idea, but out of scope for tidyr at the moment. At some in the future, we'll probably think systematically about `_if`, `_at`, and `_any` variants for all verbs.
