### ISSUE TITLE
extract fails on empty data.frame

### ISSUE THREAD

**Issue by antoine-sachet** [tidyverse/tidyr#313]
Reproducible example using tidyr 0.6.3.9000:

```
df <- data.frame(col1=character(0))
tidyr::extract(df, col1, into="col2", regex="(whatever)")
```

Expected behaviour: should return an empty data.frame with a new empty column "col2".

Actual behaviour: fails with error: 
`Error in names(l) <- enc2utf8(into) : 
  'names' attribute [1] must be the same length as the vector [0]`

Why it should be fixed: this makes an otherwise valid pipeline fail when the result of a filter happens to be empty. This requires boiler-plate to guard against empty data when programming with `extract`.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by olsgaard** [comment]
I am having the same problem. reproducable example using `reprex`

``` r
df <- data.frame(col1 = c("q123", "abc"))
tidyr::extract(df, col1, into = "col2", regex = "[0-9]+", remove = FALSE)
#> Error in names(l) <- enc2utf8(into): 'names' attribute [1] must be the same length as the vector [0]
```

When I choose "rerun with Debug", the error is in `extract_.data.frame`, where `l` is a *List of 0*

---

I am also running `tidyr 0.6.3`, in a corporate setting, so updating is non-trivial. Does 0.7.1 fix the issue or are we interfacing with tidyr in the wrong way?

**Comment by hadley** [comment]
@olsgaard Thanks for the reprex!

**Comment by hadley** [comment]
More minimal reprex:

```R
df <- data.frame(x = c("q123", "abc"))
extract(df, x, "y", regex = ".")
```

I think the problem is that there's no grouping defined in the regular expression and the error message doesn't help you discover that.

**Comment by hadley** [comment]
Ok, there were actually two problems here. It looks like the motivating issue is actually a small stringi bug; so I'll file over there.
