### ISSUE TITLE
unnest drops empty rows

### ISSUE THREAD

**Issue by Nihasa** [tidyverse/tidyr#316]
Example:
```
tribble(
    ~test1, ~testdata,
    1, tibble(
        day = integer(0), month = integer(0)
        ),
    2, tibble(
        day = 1, month = 12
    )
) %>% unnest

```
row 1 is dropped, but data outside the list column should be kept with the list column values returning null or NA. My workaround for the time being is to join on the original table but it would be better imo if this worked out of the box. I had hoped that was would be covered by `.drop = FALSE`  but not. Is there something that can overcome this?

**Comment by hadley** [comment]
unnesting gives you one row for each element, and there are 0 elements, so this is correct.

**Comment by Nihasa** [comment]
It seems a little counter-intuitive to me that the data frame containing a list element has its rows dictated by that list element. I would have expected the result to be a data frame with all the original rows, but those that have no elements in the list column contain an NA of the appropriate type.

As I said, it's not that difficult to arrive at my desired output by using a join, but I'm sure that I'm not clever enough to be the first person to make the assumption that the parent frame structure would be preserved.

**Comment by jennybc** [comment]
I have also puzzled over this. It feels like this conversation gets at this question: What is `NA` for a list-column?
