### ISSUE TITLE
Behavior of empty nest call without groups.

### ISSUE THREAD

**Issue by Ax3man** [tidyverse/tidyr#323]
By default, `nest` operates on all non-grouped columns. Therefore, these are equivalent:

```
mtcars %>% group_by(cyl) %>% nest()

mtcars %>% group_by(cyl) %>% nest(everything())
```

Without grouping, I would therefore expect to get a 1x1 tibble with the complete data in that cell. Instead it returns the original dataframe with a `data` filled with 1x0 tables. These are therefore not equivalent:

```
mtcars %>% nest()

mtcars %>% nest(everything())
```

This can be inconvenient in programming when a grouping of `NULL` can be supplied (i.e. no grouping).

Would it make sense to by default always nest all non-grouping variables?

**Comment by hadley** [comment]
Those now appear to be consistent in the dev version, although I don't remember making that change and I can't point to a news bullet that seems related 😬
