### ISSUE TITLE
separate() wtih a "number of pieces to return" argument?

### ISSUE THREAD

**Issue by adeldaoud** [tidyverse/tidyr#329]
Hi

A request feature: Can one add "number of pieces to return"  argument to separate() in tidyr? This argument is available in str_split, and makes tidying data easier, as I do not have to manually count how many separate columns I will need. 

Best,

**Comment by jennybc** [comment]
Can you post an example with what you want vs. what you currently get? Because I suspect there is usage of existing arguments that might get the job done.

**Comment by adeldaoud** [comment]
```
library(dplyr); library(tidyr); library(stringr)
# define dataframe
df <- data.frame(x = c("a", "a b", "a b c", NA))

# current options in separate, I have to explicity define the nr of new columns I want: c("A", "B", "C") 
## in complicated situations, I will not know this before hand. 
df %>% separate(x, c("A", "B", "C"), extra = "merge", fill = "left")

# using str_split instead to specify n=inf to get the desired columns automatically
m <- str_split_fixed(df$x, pattern=" ", n =Inf)
as_data_frame(m)


# Any ideas?
```

**Comment by jennybc** [comment]
Ah OK I see. Do you really have no idea of the possible maximum for `n`?

If not, you could pre-compute it like so (probably close to what you are already doing):

``` r
library(tidyverse)
df <- data_frame(x = c("a", "a b", "a b c", NA))
n <- max(lengths(strsplit(df$x, " ")))
df %>%
  separate(x, LETTERS[seq_len(n)], extra = "merge", fill = "left")
#> # A tibble: 4 x 3
#>       A     B     C
#> * <chr> <chr> <chr>
#> 1  <NA>  <NA>     a
#> 2  <NA>     a     b
#> 3     a     b     c
#> 4  <NA>  <NA>  <NA>
```

Or use `str_split_fixed()` and column bind the result back in. This is an example of something that would be nice to make easier, "multi-mutate": generating multiple new columns at once from existing columns.

**Comment by adeldaoud** [comment]
Thanks for the input. Yes, this is about what I am doing as a work around. Your solution is more general. 

Would be nice if tidyr had this build in so one could just specify n = inf argument, similar to str_split_fixed.

**Comment by hadley** [comment]
You need to supply the variable names somehow, so this feels out of scope for tidyr currently.
