### ISSUE TITLE
.Internal(inspect(...)) in test-gather.R

### ISSUE THREAD

**Issue by BillDunlap** [tidyverse/tidyr#339]
I was wondering why tests/testthat/test-gather.R, c. line 124, uses
      object_bit_set <- function(x) {
         grepl("\\[OBJ", capture.output(.Internal(inspect(x)))[1])
      }
instead of base::is.object to see if something is an "object". 

What sorts of inputs would cause those functions to give different results?

**Comment by lionel-** [comment]
@kevinushey it seems you wrote this test in reshape2 in 2014 ;)

**Comment by kevinushey** [comment]
I think I just didn't know that `is.object()` was the right way to test this back then. :) The test should almost surely just use `is.object()`.
