### ISSUE TITLE
extracting a regex that might have multiple matches

### ISSUE THREAD

**Issue by tcovert** [tidyverse/tidyr#345]
I see in the code for `extract` that only the first match of a regular expression is captured.  Is there a sensible way to do what `extract` does on a column in which one expects the regular expression to match multiple times?  Here's an example of what I am trying to accomplish:
```
t <- as_tibble(list(z = c("a1", "a2b3", "a4b5c6")))
long_t <- extract(t, z, c("y"), regex = regex("(\\d)"), matchID = c("matchID"), remove = FALSE)
```
I realize the `matchID` keyword doesn't actually exist, but if it did, it would give us the following for long_t:
```
# A tibble: 6 x 3
      z     y     matchID
  <chr>     <chr>   <dbl>
1    a1         1       1
2    a2b3       2       1
3    a2b3       3       2
4    a4b5c6     4       1
5    a4b5c6     5       2
6    a4b5c6     6       3
```

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
