### ISSUE TITLE
Better error for replace_na

### ISSUE THREAD

**Issue by eibanez** [tidyverse/tidyr#356]
It would be nice to improve the following error to say something like "b is not a valid column." Not a big deal, but it would be nice from a debugging perspective.

```
> library(tidyr)
> data = data_frame(a = c(1:3, NA))
> data2 <- data %>%
+   replace_na(list(a = 100, b = 0))
Error: `x` must be a vector
```

**Comment by hadley** [comment]
Minimal reprex:

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-15

library(tidyr)
df <- tibble::tibble(a = c(1, NA))
replace_na(df, list(a = 100, b = 0))
#> Error: `x` must be a vector
```

**Comment by rlionheart92** [comment]
I suspect that this was closed as it is not possible? However, could the error message be changed to something more informative; along the lines of:
``Error: All columns/vectors for replacement should be valid.``
I had this error come up in some code I was modifying and it wasn't immediately obvious what was the issue,

**Comment by hadley** [comment]
@rlionheart92 please open a new issue with reprex

**Comment by eibanez** [comment]
I think this was fixed. The code above no longer errors and the function ignores replacement values that are invalid.
