### ISSUE TITLE
`gather_` no longer supports spaces in `key_col`

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/tidyr#361]
sample code:

    d = data_frame(a = 1:10, b = letters[1:10], c = sample(LETTERS, 10))
    gather_(d, "the variable", "the result")

This worked just fine until version 0.71

**Comment by lionel-** [comment]
I can't reproduce. Could you post your `devtools::session_info()` after loading tidyr from a fresh session please?

**Comment by lionel-** [comment]
Scratch that, I can reproduce.

**Comment by lionel-** [comment]
That's because the SE versions are inconsistent in the way they treat non syntactic names. For example `nest_()` supports them but not `unnest_()`. If you find more discrepancies with pre-tidy eval versions, please let us know.
