### ISSUE TITLE
spread with bit64::integer64 fails with missing combination

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [tidyverse/tidyr#363]
There is problem with integer64 vector (from bit64 package, but originated in data retrieved via odbc package) and tidyr::spread.
 
Missing values are replaced by large value.
 
It's related to known (?) behavior of bit64 package, e.g.: https://stackoverflow.com/questions/21627741/fread-fails-with-missing-values-in-integer64-columns
or bit64 package documentation:

> further limitations
> • subscripting non-existing elements and subscripting with NAs is currently not supported. Such
> subscripting currently returns 9218868437227407266 instead of NA (the NA value of the underlying
> double code). Following the full R behaviour here would either destroy performance
> or require extensive C-coding. 
 
```{r}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(bit64))

ex_df <- data_frame(id = c(1, 1, 2, 2), var = c("A", "B", "A", "B"), val = as.integer64(1:4))

ex_df
#> # A tibble: 4 x 3
#>      id   var             val
#>   <dbl> <chr> <S3: integer64>
#> 1     1     A               1
#> 2     1     B               2
#> 3     2     A               3
#> 4     2     B               4

# With all combination it's ok
ex_df %>% spread(var, val)
#> # A tibble: 2 x 3
#>      id               A               B
#> * <dbl> <S3: integer64> <S3: integer64>
#> 1     1               1               2
#> 2     2               3               4

# after removing one of them isn't ok:
ex_df %>% slice(-1) %>% spread(var, val)
#> # A tibble: 2 x 3
#>      id                   A               B
#> * <dbl>     <S3: integer64> <S3: integer64>
#> 1     1 9218868437227407266               2
#> 2     2                   3               4

# forcing fill doesn't change anything
ex_df %>% slice(-1) %>% spread(var, val, fill = as.integer64(0))
#> # A tibble: 2 x 3
#>      id                   A               B
#> * <dbl>     <S3: integer64> <S3: integer64>
#> 1     1 9218868437227407266               2
#> 2     2                   3               4

# NA in data stays NA:
ex_df %>% slice(-1) %>% mutate(val = na_if(val, 4)) %>% spread(var, val)
#> # A tibble: 2 x 3
#>      id                   A               B
#> * <dbl>     <S3: integer64> <S3: integer64>
#> 1     1 9218868437227407266               2
#> 2     2                   3              NA
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by tentacles-from-outer-space** [comment]
Done. All packages are in current CRAN (=no devel/github) versions at the time of writing.

**Comment by hadley** [comment]
I suspect this is the root cause:

```R
structure(NA_real_, class = "integer64")
#> integer64
#> [1] 9218868437227407266
```

**Comment by hadley** [comment]
I think this is actually a bug in bit64. It looks like some code is missing in the `[` method:

``` r
bit64::as.integer64(1)[NA]
#> integer64
#> [1] 9218868437227407266
```

Would you mind passing the bug on to the maintainer of bit64?
