### ISSUE TITLE
Feature request: enable fixed() for functions which use regular expressions in `tidyr`

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/tidyr#365]
In package `stringr` there are functions, such as `fixed()`, `regex()`, which can modify of patterns as either fixed or as regular expressions. Unfortunately, these functions only work with other functions from `stringr`. 

For instance, say, we have:
```
df <- data.frame(str = "a||b||c")
```

It would be convenient and the syntax would be more consistent if `fixed()`, `regex()`, etc. would work with other `tidyverse` packages including `tidyr` and instead of writing:

```
separate(df, str, c("A", "B", "C"), sep = "\\|\\|" )
```

there was a posibility to write:

```
separate(df, str, c("A", "B", "C"), sep = fixed("||"))
```

Can I hope to have this feature implemented in `tidyr` (and, maybe, other `tidyverse` packages)?

**Comment by hadley** [comment]
Unfortunately tidyr uses stringi for performance reasons, so it's not possible at this time.
