### ISSUE TITLE
Inconsistent interface for separate(into = c(...))

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyr#367]
This is especially confusing for beginners: Why do we need to use quotes when calling `separate()`, but not for `unite()` or `spread()` or `gather()`?

``` r
suppressPackageStartupMessages(library(tidyverse))
table3 %>% 
  separate(
    rate,
    into = c("cases", "population")
  )
#> # A tibble: 6 x 4
#>   country      year cases  population
#> * <chr>       <int> <chr>  <chr>     
#> 1 Afghanistan  1999 745    19987071  
#> 2 Afghanistan  2000 2666   20595360  
#> 3 Brazil       1999 37737  172006362 
#> 4 Brazil       2000 80488  174504898 
#> 5 China        1999 212258 1272915272
#> 6 China        2000 213766 1280428583
```

It would be more natural to be able to write just

```r
table3 %>% 
  separate(rate, cases, population)
```

CC @MehranHosseini.

**Comment by lionel-** [comment]
The new convention in the tidyverse is that bare symbols must refer to existing objects. New columns are not existing yet.

**Comment by krlmlr** [comment]
What's the new recommended way to `gather()`?

```r
data %>% gather("key", "value", -existing, -keys)
```

?

**Comment by lionel-** [comment]
Yup, exactly. However we're not gonna change tidyr to enforce that syntax, it would cause too much trouble.

**Comment by hadley** [comment]
We might consider as part of new multi-gather/spread verbs.
