### ISSUE TITLE
Selecting columns in gather dependent on vector class

### ISSUE THREAD

**Issue by junoslukan** [tidyverse/tidyr#374]
When selecting columns with a data expression, a warning is given when using `c(x, y)`, but not when using an `x:y` expression.

Using the example from the help page:

```R
library(dplyr)
# From http://stackoverflow.com/questions/1181060
stocks <- tibble(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)
```

Then using the first form gives a warning:

```R
stocks %>% gather(stock, price, c(2,3,4))
```

> Warning message:
In if (!is.finite(x)) return(FALSE) :
  the condition has length > 1 and only the first element will be used

While using the second one, results in no warnings:

```R
stocks %>% gather(stock, price, 2:4)
```

As far as I can tell, the only difference is the class of the vector specifying the columns: being a numeric vector in the first case and a more specific integer vector in the second one.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by markdly** [comment]
Just adding a minimal `reprex` based on information provided by OP:
``` r
library(dplyr)
library(tidyr)
# From http://stackoverflow.com/questions/1181060
set.seed(123)
stocks <- tibble(
  time = as.Date('2009-01-01') + 0:1,
  X = rnorm(2, 0, 1),
  Y = rnorm(2, 0, 2),
  Z = rnorm(2, 0, 4)
)

stocks %>% gather(stock, price, c(2,3,4))
#> Warning in if (!is.finite(x)) return(FALSE): the condition has length > 1
#> and only the first element will be used
#> # A tibble: 6 x 3
#>         time stock      price
#>       <date> <chr>      <dbl>
#> 1 2009-01-01     X -0.5604756
#> 2 2009-01-02     X -0.2301775
#> 3 2009-01-01     Y  3.1174166
#> 4 2009-01-02     Y  0.1410168
#> 5 2009-01-01     Z  0.5171509
#> 6 2009-01-02     Z  6.8602599

stocks %>% gather(stock, price, 2:4)
#> # A tibble: 6 x 3
#>         time stock      price
#>       <date> <chr>      <dbl>
#> 1 2009-01-01     X -0.5604756
#> 2 2009-01-02     X -0.2301775
#> 3 2009-01-01     Y  3.1174166
#> 4 2009-01-02     Y  0.1410168
#> 5 2009-01-01     Z  0.5171509
#> 6 2009-01-02     Z  6.8602599
```

**Comment by hadley** [comment]
Yet more minimal reprex:

``` r
library(tidyr)

df <- tibble::tibble(x = 1, y = 2, z = 3)
df %>% gather("key", "value", c(2, 3))
#> Warning in if (!is.finite(x)) return(FALSE): the condition has length > 1
#> and only the first element will be used
#> # A tibble: 2 x 3
#>       x   key value
#>   <dbl> <chr> <dbl>
#> 1     1     y     2
#> 2     1     z     3
df %>% gather("key", "value", 2:3)
#> # A tibble: 2 x 3
#>       x   key value
#>   <dbl> <chr> <dbl>
#> 1     1     y     2
#> 2     1     z     3
```

Created on 2017-11-17 by the [reprex package
(0.1.1.9000)](https://cran.r-project.org/package=reprex).

**Comment by hadley** [comment]
The root cause of this problem is in the tidyselect package, so I've moved the issue over there. Thanks!
