### ISSUE TITLE
separate fails on UTF-8 column, but works on 'unknown'?

### ISSUE THREAD

**Issue by pgensler** [tidyverse/tidyr#382]
Not sure if this is due to encoding/ base-r, but worth mentioning:
Seems like when a string is encoded as UTF-8, you get a warning, and it does not work, but with a
'unknown' encoded column, this works. This is on OS X High Sierra 10.13.1

``` r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
library(magrittr)
#> 
#> Attaching package: 'magrittr'
#> The following object is masked from 'package:purrr':
#> 
#>     set_names
#> The following object is masked from 'package:tidyr':
#> 
#>     extract
library(stringr)
library(stringi)
x <- tibble::tribble(
  ~id,                                                                                           ~value,
  390639,  "RATINGS: 4   MEAN: 3.83/5.0   WEIGHTED AVG: 3.39/5   IBU: 35   EST. CALORIES: 204   ABV: 6.8%",
  99472,                           "RATINGS: 89   WEIGHTED AVG: 3.64/5   EST. CALORIES: 188   ABV: 6.25%",
  361258,   "RATINGS: 8   MEAN: 3.7/5.0   WEIGHTED AVG: 3.45/5   IBU: 85   EST. CALORIES: 213   ABV: 7.1%"
)
#Returns UTF-8
Encoding(x$value)
#> [1] "UTF-8" "UTF-8" "UTF-8"

#try to seperate
x %>%
  mutate(split = str_split(value, "  ")) %>%
  unnest(split) %>%
  separate(split, c("type", "valeur"), ": ")
#> Warning: Too many values at 3 locations: 1, 2, 3
#> # A tibble: 3 x 4
#>       id
#> *  <dbl>
#> 1 390639
#> 2  99472
#> 3 361258
#> # ... with 3 more variables: value <chr>, type <chr>, valeur <chr>

###Try with data as 'unknown'
good_data <- tibble::tribble(
  ~id,  ~value,
  390639, "RATINGS: 4   MEAN: 3.83/5.0   WEIGHTED AVG: 3.39/5   IBU: 35   EST. CALORIES: 204   ABV: 6.8%",
  99472, "RATINGS: 89   WEIGHTED AVG: 3.64/5   EST. CALORIES: 188   ABV: 6.25%",
  361258, "RATINGS: 8   MEAN: 3.7/5.0   WEIGHTED AVG: 3.45/5   IBU: 85   EST. CALORIES: 213   ABV: 7.1%"
)
#Returns 'unknown'
Encoding(good_data$value)
#> [1] "unknown" "unknown" "unknown"


good_data %>%
  mutate(split = str_split(value, "  ")) %>%
  unnest(split) %>%
  separate(split, c("type", "valeur"), ": ")
#> # A tibble: 16 x 4
#>        id
#>  *  <dbl>
#>  1 390639
#>  2 390639
#>  3 390639
#>  4 390639
#>  5 390639
#>  6 390639
#>  7  99472
#>  8  99472
#>  9  99472
#> 10  99472
#> 11 361258
#> 12 361258
#> 13 361258
#> 14 361258
#> 15 361258
#> 16 361258
#> # ... with 3 more variables: value <chr>, type <chr>, valeur <chr>
```

You may need to paste ```x``` in a text editor to see the whitespace which is not filled in with a dot. Let me know if you need anything else.

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem (e.g. eliminate extraneous library calls, reduce the size of the date) . Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by pgensler** [comment]
OK, so this is completely my fault......it seems like ```stringr's str_split``` fails due to bad whitespace (ie: http://www.fileformat.info/info/unicode/char/00a0/index.htm)

So maybe the better question to ask is if there is a function within the tidyverse that aims at detecting chars like this? The string is coded as UTF-8 (according to base-r), and clearly there is an issue, so there has to be some function that can detect that?

rvest  has a function to repair the encoding, but  not necessarily detecting it, other than simply doing something like this: 
```
str_detect(the_string, "\u00A0")
```
Otherwise, it's pretty hard to detect, and I don't you want to build custom error handling for every tidy verse package. Maybe this is more along the lines of simply UTF-8 handling with r-lib/infrastructure: https://github.com/r-lib ??

**Comment by hadley** [comment]
Not currently.
