### ISSUE TITLE
gather (tidyverse) error - object '0' not found

### ISSUE THREAD

**Issue by gireeshkbogu** [tidyverse/tidyr#388]
Hi, 
I am trying to gather the following input but having an error. 
How could I avoid this problem?

```
input <- tribble(
  ~E, ~T, ~C,
  0, "W", 221,
  1, "W", 6,
  98,"W",18,
  99,"W",109,
  0,"V",66,
  98,"V",3,
  99,"V",26,
  0,"U",59,
  98,"U",3,
  99,"U",26
)
```

```
gather(`0`,`99`, input, key = "E", value = "C")
```

```
Error in gather(`0`, `99`, input, key = "E", value = "C") : 
  object '0' not found
```

**Comment by cderv** [comment]
The formulation is not correct. Usage of `gather` is : 
```r
gather(data, key = "key", value = "value", ..., na.rm = FALSE,
  convert = FALSE, factor_key = FALSE)
```
in your code,  what do you want to do with the two first arguments ? 

See [`gather` help file](http://tidyr.tidyverse.org/reference/gather.html) more example of use.

Know that you can find more people to help for this kind of question on [SO](https://stackoverflow.com/questions/tagged/r).

**Comment by gireeshkbogu** [comment]
thanks. I think I am confused spread with gather. Now it's good.
