### ISSUE TITLE
nest() unexpected output

### ISSUE THREAD

**Issue by Monduiz** [tidyverse/tidyr#389]
In collapsing rows into a list with nest(), the output is not what I would expect. The result is a list like this: 

> list(X1 = c("..."))

I would have expected:
> c("...")

I am not sure what to do with list(X1=c("..."). 

As an example using the [CNN dataset](https://drive.google.com/uc?export=download&id=0BwmD_VLjROrfTHk4NFg2SndKcjQ):

```
library(tidyverse)
library(readr)

test <- read_tsv("cnn/stories/0a0a4c90d59df9e36ffec4ba306b4f20f3ba4acb.story", 
                 col_names = FALSE)

test2 <- test %>%
  nest(X1, .key = articles)
```

To get the expected output, I would have to do:

```
test3 <- test %>% 
  do(X1 = unique(unlist(.$X1)))
```

Maybe I am understanding the use case of nest() wrong but I was expecting it to do just that.

**Comment by cderv** [comment]
Hi, 

If you want some help with your use case, you can go on [community.rstudio.com](https://community.rstudio.com/) or on [Stackoverflow](https://stackoverflow.com/). Then if you find an issue with `nest` you can post it here.

To help get more precise on what is the problem thanks to  with a real [`reprex`](http://reprex.tidyverse.org/), I put your file on a gist that you can read directly.

Here what we get. Not sure to see what you wish. You can use this or create your own gist to provide more example.  

``` r
url <- "https://gist.githubusercontent.com/cderv/1c2332f050b74dcdd8749d93f12a1857/raw/04307b030c54d9ae8958891ef24483bf1e0fa1ff/0a0a4c90d59df9e36ffec4ba306b4f20f3ba4acb.story"

library(tidyverse)
test <- read_tsv(url, col_names = F)
#> Parsed with column specification:
#> cols(
#>   X1 = col_character()
#> )

test
#> # A tibble: 25 x 1
#>                                                                             X1
#>                                                                          <chr>
#>  1 "(CNN) -- Can a movie actually convince you to support torture? Can a movie
#>  2 "Some scoff at the notion that movies do anything more than entertain. They
#>  3 Anyone who doubts the potential influence that movies can have on public op
#>  4 "The first, \"Zero Dark Thirty,\" is about the pursuit and killing of Osama
#>  5 "Critics of \"Zero Dark Thirty\" fear that audiences will accept as true th
#>  6                             Peter Bergen: Did torture really net bin Laden?
#>  7 "Opposition to the film escalated last week as three senior U.S. senators -
#>  8 "The hostility toward \"Promised Land\" shows us that it's not just politic
#>  9                                          How concerned is the gas industry?
#> 10 It has set up a rapid response team to counter publicity for the film by us
#> # ... with 15 more rows

test %>%
  nest(X1, .key = articles)
#> # A tibble: 1 x 1
#>            articles
#>              <list>
#> 1 <tibble [25 x 1]>

test %>% 
  do(X1 = unique(unlist(.$X1)))
#> # A tibble: 1 x 1
#>           X1
#>       <list>
#> 1 <chr [22]>
```

Created on 2017-12-08 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

Hope it can help

**Comment by Monduiz** [comment]
Thank you for the reprex tip! You are right, this is better addressed on stackoverflow.
