### ISSUE TITLE
Documentation for fill does not match function

### ISSUE THREAD

**Issue by zelite** [tidyverse/tidyr#401]
In the documentation for the fill function, there's all this talk about 

>Specification of columns to expand. To find all unique combinations of x, y and z, including those not found in the data, supply each variable as a separate argument. To find only the combinations that occur in the data, use nest: expand(df, nesting(x, y, z)).

This does not seem to fit the use case for the fill function, so I guess its in the wrong place.

I have tidyr version 0.7.2 on my system. In the repository the problem is also present:

https://github.com/tidyverse/tidyr/blob/bb69f870188c8ad47184a0ba000c3498dcfe0747/man/fill.Rd#L12

**Comment by hadley** [comment]
Ooops, thanks!
