### ISSUE TITLE
Any way to ignore delimiter chars encapsulated in a quoted string?

### ISSUE THREAD

**Issue by ripkrizbi** [tidyverse/tidyr#404]
Hi, consider this field in a column I'd like to separate:

```r
x <- tibble::tribble(~a, 
"ID=TYPE,Number=A,Type=String,Description=\"One, two, three, four, five, or six.\"")
```

If I try to separate it by a simple comma delimiter

```r
tidyr::separate(x, a, into = c('b', 'c', 'd', 'e'), sep = ",")
```

I'm having problems with the extra commas in the quoted string and instead of ending up with four columns I get nine - is there a way to avoid this somehow?

```r
# A tibble: 1 x 4
  b       c        d           e                                 
  <chr>   <chr>    <chr>       <chr>                             
1 ID=TYPE Number=A Type=String "Description=\"One"
Warning message:
Expected 4 pieces. Additional pieces discarded in 1 rows [1]. 
```

thank you!

**Comment by hadley** [comment]
Unfortunately this is out of scope for tidyr. You'll need to use something more general.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
