### ISSUE TITLE
spread fail if input table has only key and value columns in v0.8.0

### ISSUE THREAD

**Issue by zhukunism** [tidyverse/tidyr#408]
`data.table(x=c("a","b"),y=c(1,2))%>%spread(x,y)`
This works in 0.7.2, but not in 0.8.0, which gives the error below:
` Error: Duplicate identifiers for rows (1, 3, 4)`

A temporary (and inconvenient ..) solution is adding a dummy column:
`data.table(x=c("a","b"),y=c(1,2))%>%mutate(DummyCol=1)%>%spread(x,y)%>%mutate(DummyCol=NULL`

Is this change intended or just a bug?

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment]
This works for me

``` r
library(tidyr)

data.frame(x = c("a", "b"), y = c(1, 2)) %>% spread(x, y)
#>   a b
#> 1 1 2
```

Created on 2018-02-19 by the [reprex package
(0.1.1.9000)](https://cran.r-project.org/package=reprex).

**Comment by zhukunism** [comment]
I think it works for data.frame, but not data.table. Here is the reprex output:
``` r
library(tidyr)                                           
data.table(x = c("a", "b"), y = c(1, 2)) %>% spread(x, y)
#> Error in data.table(x = c("a", "b"), y = c(1, 2)): could not find function "data.table"
```

**Comment by batpigandme** [comment]
@zhukunism the error above suggests you don't have data.table loaded. Either way, this is unrelated to this issue.

**Comment by zhukunism** [comment]
@batpigandme sorry, forgot to import the library ...
```
library(tidyr)                                           
library(data.table)                                      
data.table(x = c("a", "b"), y = c(1, 2)) %>% spread(x, y)
#> Error: Duplicate identifiers for rows (1, 3, 4)
```
