### ISSUE TITLE
gather() no longer keeps key values

### ISSUE THREAD

**Issue by Hydr0Ge0Dude** [tidyverse/tidyr#409]
#**The gather() function no longer works as expected.**
#*This example should be reproducible with R 3.4.3 64-bit on Windows 10*

#*As of tidyr version 0.8.0, the key column is not present in the output, as demonstrated by the following two examples:*

#load packages
library(dplyr); library(tidyr)

#make example data frame
mydf <- data.frame("Type" = rep(LETTERS,1),stringsAsFactors = F)
mydf$Meas_1 <- 2*seq(1:nrow(mydf))
mydf$Meas_2 <- sqrt(mydf$Meas_1)

#attempt to gather columns.
gatherdf <- gather(mydf,Type)

#*This works in tidyr 0.7.2, but it no longer works in tidyr 0.8.0*

#*In the earlier version, three columns would result representing, Type,
#Value Name, and Value, albeit with misleading column names*

#*In version 0.8.0, only two columns are produced; key values are no longer present*

#example with Iris dataset also returns expected results in version 0.7.2, but
#does not return expected results in 0.8.0
gatheriris <- gather(iris,Species)

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by batpigandme** [comment]
## reprex with tidyr 0.7.2
``` r
suppressPackageStartupMessages(library(dplyr))
library(tidyr)

mydf <- data.frame("Type" = rep(LETTERS, 1), stringsAsFactors = F)
mydf$Meas_1 <- 2 * seq(1:nrow(mydf))
mydf$Meas_2 <- sqrt(mydf$Meas_1)

gatherdf <- gather(mydf, Type)

head(gatherdf)
#>   Type   Type value
#> 1    A Meas_1     2
#> 2    B Meas_1     4
#> 3    C Meas_1     6
#> 4    D Meas_1     8
#> 5    E Meas_1    10
#> 6    F Meas_1    12
```
## reprex with 0.8.0
``` r
suppressPackageStartupMessages(library(dplyr))
library(tidyr)

mydf <- data.frame("Type" = rep(LETTERS, 1), stringsAsFactors = F)
mydf$Meas_1 <- 2 * seq(1:nrow(mydf))
mydf$Meas_2 <- sqrt(mydf$Meas_1)

gatherdf <- gather(mydf, Type)

head(gatherdf)
#>     Type value
#> 1 Meas_1     2
#> 2 Meas_1     4
#> 3 Meas_1     6
#> 4 Meas_1     8
#> 5 Meas_1    10
#> 6 Meas_1    12
```
Created on 2018-02-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
This is documented in the NEWS:

> `spread()`, `separate()`, `extract()` (#255), and `gather()` (#347) now replace existing variables rather than creating an invalid data frame with duplicated variable names (matching the semantics of mutate).

**Comment by batpigandme** [comment]
@hadley 🤦🏼‍♀️ I literally read that and then proceeded to make this reprex… ⚾️ batting 1,000 today! 🙃

**Comment by Hydr0Ge0Dude** [comment]
@hadley How can the different groups from each of the columns be differentiated without the second identifier column? It seems like there is inadequate data in the resultant data frame. Please explain.

**Comment by hadley** [comment]
@Hydr0Ge0Dude use a unique column name
