### ISSUE TITLE
Feature Request: separate_rows() to support fill for unequal length vectors

### ISSUE THREAD

**Issue by cpfaff** [tidyverse/tidyr#413]
He

This one here works nicely. 

```r
df <- data.frame(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("1", "2,3,4", "5,6"),
  stringsAsFactors = FALSE
)

separate_rows(df, y, z, convert = TRUE)
```

however that here fails (uneven on the first element):

```r
df <- data.frame(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("1,2", "2,3,4", "5,6"),
  stringsAsFactors = FALSE
)

separate_rows(df, y, z, convert = TRUE)
```

It would be really helpful if `separate_rows()` could get an option to handle uneven length vectors in the separate columns like the `separate()` function wich handles uneven lengths just filling up.

All the best

**Comment by batpigandme** [comment]
I'm not sure about the feasibility of this FR, but could you please edit the title to reflect the actual feature you're requesting? It's much easier for maintainers to evaluate and triage issues and feature requests at-a-glance that way. 

Thanks,

Mara

**Comment by hadley** [comment]
I don't see how this could work. What happens if one column has two elements and another has three. I think if you want this sort of behaviour you'll need to implement it yourself by using `strsplit()` (or `str_split()`), manipulating the lengths to match, then using `unnest()`.

**Comment by cpfaff** [comment]
ok thanks.

**Comment by cpfaff** [comment]
Just in case somebody comes across this with the same need:

The package splitstackshape does an awesome job here. 
  
```r
mydf <- data.frame(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("1", "2,3,4", "5,6"),
  stringsAsFactors = FALSE
)
```

```r
mydf %>%
cSplit(splitCols = 1:ncol(.), sep = ",", direction = "long", makeEqual = T) %>% unique
  x    y  z                                                                                                                                                                                                                                 
1  1    a  1
2 NA <NA> NA
3  2    d  2
4 NA    e  3
5 NA    f  4
6  3    g  5
7 NA    h  6  

```
