### ISSUE TITLE
My nest statement is getting bizarre results.

### ISSUE THREAD

**Issue by Divya1608** [tidyverse/tidyr#425]
Rscript: nest(data=vgroup,  -country,-topic).... but this is returning 'topic' gone into the tibble nest & 'year' column at the top level when it should have gone into the tibble instead of 'topic' --- because'topic' is mentioned in the nest statement as -topic.

**Comment by batpigandme** [comment]
Hi Divya,

This question might be a better fit for community.rstudio.com, where there are more people there to help (and we can determine whether or not it's actually a bug in the package, or a problem with the code). 

Regardless of where you're posting, without knowing what your data looks like, or the code you're using, it's difficult to say what's wrong. Could you please include a [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

Thanks,

Mara

**Comment by Divya1608** [comment]
Thank you so much for replying.

As per your suggestion, I will ask my question at the R community.

Regards,
