### ISSUE TITLE
replace_na() not pipeable? 

### ISSUE THREAD

**Issue by foundinblank** [tidyverse/tidyr#427]
`y <- replace_na(df$x, 0)` works

`y <- df %>% replace_na(x, 0)` does not. 

Seems like a no-brainer to have this pipeable...or is it a brainer? ;)

**Comment by lionel-** [comment]
Pipeable does not mean that a function can refer to data. You can pipe with any sort of function. In the case of `replace_na()`, it's a normal function (i.e. not a quoting function) that takes a vector and not a data frame. It's meant to be used within `mutate()` for example, which takes a data frame and evaluates its arguments in the data.

**Comment by foundinblank** [comment]
Thank you, @lionel- I see now that I can do 

`y <- df %>% replace_na(list(x = 0))` 

but that seems kludgy. I feel it's more intuitive to have `replace_na(x, 0)` - what would that be called? Tidy code?

**Comment by lionel-** [comment]
You have to distinguish between data frame verbs (like `mutate()` and vector verbs (like `replace_na()`). The way to do this is:

```r
df %>% mutate(x = replace_na(x))
```

We are thinking about a more systematic way of approaching the data frame vs vector issue, but nothing concrete yet.

**Comment by foundinblank** [comment]
That's a good problem - how to clearly explain data frame v. vector verbs. In the meantime, the examples at the end of each vector verb could include a mutate example, as that'd be the most familiar usage scenario for most people who use tidyverse but don't understand the distinction yet between the two verb types. 

I've put in a pull request for this.
