### ISSUE TITLE
gather for matrix class

### ISSUE THREAD

**Issue by yonicd** [tidyverse/tidyr#437]
is it possible to mimic `reshape2::melt.matrix` in `tidyr::gather`?

i wrote this function that does it, but wondered if it is already possible and I missed an obvious solution.

```
#' @export 
#' @importFrom dplyr as_data_frame bind_cols select
#' @importFrom tidyr gather
gather.matrix <- function(data){
  
  s <- dim(data)
  nm <- dimnames(data)
  
  if(is.null(nm)){
    new_list <- lapply(s,seq,from=1)
  }else{
    new_list <- mapply(function(x,s){
      if(is.null(x)){
        seq(1,s)
      }else{
        x
      }
    },x=nm,s=s,SIMPLIFY = FALSE)
  }
  
  data%>%
    dplyr::as_data_frame()%>%
    tidyr::gather()%>%
    dplyr::bind_cols(.,expand.grid(new_list,stringsAsFactors = FALSE))%>%
    dplyr::select(Var1,Var2,value)
}
```

examples

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)
library(reshape2)
#> 
#> Attaching package: 'reshape2'
#> The following object is masked from 'package:tidyr':
#> 
#>     smiths
library(mrgtable)
#> Loading required package: texPreview
#> 
#> Attaching package: 'mrgtable'
#> The following objects are masked from 'package:tidyr':
#> 
#>     %>%, gather
#> The following object is masked from 'package:dplyr':
#> 
#>     %>%

mat <- diag(2)

mat%>%reshape2::melt()
#>   Var1 Var2 value
#> 1    1    1     1
#> 2    2    1     0
#> 3    1    2     0
#> 4    2    2     1

mat%>%tidyr::gather()
#> Error in UseMethod("gather_"): no applicable method for 'gather_' applied to an object of class "c('matrix', 'double', 'numeric')"

mat%>%as_data_frame()%>%tidyr::gather()
#> # A tibble: 4 x 2
#>     key value
#>   <chr> <dbl>
#> 1    V1     1
#> 2    V1     0
#> 3    V2     0
#> 4    V2     1

mat%>%mrgtable::gather()
#> # A tibble: 4 x 3
#>    Var1  Var2 value
#>   <int> <int> <dbl>
#> 1     1     1     1
#> 2     2     1     0
#> 3     1     2     0
#> 4     2     2     1

rownames(mat) <- c('a','b')

mat%>%reshape2::melt()
#>   Var1 Var2 value
#> 1    a    1     1
#> 2    b    1     0
#> 3    a    2     0
#> 4    b    2     1
mat%>%mrgtable::gather()
#> # A tibble: 4 x 3
#>    Var1  Var2 value
#>   <chr> <int> <dbl>
#> 1     a     1     1
#> 2     b     1     0
#> 3     a     2     0
#> 4     b     2     1
```

**Comment by jennybc** [comment]
No, I don't think `gather()` already addresses this.

Since I digested this, I'll contribute another way to do it while I'm here:

``` r
library(tidyverse)

mat <- diag(2)
rownames(mat) <- c('a','b')
colnames(mat) <- c('X','Y')

list(
  Var1 = if (is.null(rownames(mat))) row(mat) else rownames(mat)[row(mat)],
  Var2 = if (is.null(colnames(mat))) col(mat) else colnames(mat)[col(mat)],
  value = mat
  ) %>% 
  map_dfc(as.vector)
#> # A tibble: 4 x 3
#>   Var1  Var2  value
#>   <chr> <chr> <dbl>
#> 1 a     X        1.
#> 2 b     X        0.
#> 3 a     Y        0.
#> 4 b     Y        1.
```

Created on 2018-03-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yonicd** [comment]
I like that better ;). Any chance that can be a method since not all data is born a data.frame?

**Comment by jennybc** [comment]
This isn't the first request for matrix method for verb X (gather, in this case). So far, that has been a non-starter, i.e. the recommendation is to make the input into a suitable data frame and use the existing tools. Perhaps it is worth someone collecting all the verbs for which people really want matrix methods, so the scope of it is more clear.

**Comment by hadley** [comment]
I think this is out of scope for tidyr since it only works with data frames.

**Comment by briatte** [comment]
I ended up here after exploring ways to melt a matrix using `tidyr` (and `tibble`), and failing to do so.

I understand @hadley's point above, `tidyr` is data frames-only, yet the GitHub repo for `reshape2` [indicates](https://github.com/hadley/reshape) that it is "retired" and recommends using `tidyr` instead. In effect, many packages that deal with matrices (such as [`broom`](https://github.com/dgrtwo/broom)) use both `reshape2` and `tidyr` specifically for the `matrix` methods included in the former.

(StackOverflow also has a few questions about [melting arrays](https://stackoverflow.com/questions/51866344/how-to-replace-reshape2melt-for-an-array-with-tidyr), which now seems to be doable with `dplyr` by [using `tbl_cube`](https://stackoverflow.com/questions/51866344/how-to-replace-reshape2melt-for-an-array-with-tidyr).)

FWIW, here's another "gather.matrix" method from [a StackOverflow question](https://stackoverflow.com/questions/29429421/tidyrgather-vs-reshape2melt-on-matrices):

```r
set.seed(42)
mat <- matrix(runif(6), 3)
mat2 <- mat
colnames(mat2) <- letters[1:2]
rownames(mat2) <- letters[3:5]

# ---- the problem

melt(mat)
melt(mat2)
gather(mat) # fails
gather(mat2) # fails

# ---- the solution
gather.matrix <- function(mat) {
  if (is.null(dimnames(mat))) {
    grid <- expand.grid(seq.int(nrow(mat)), seq.int(ncol(mat)))
  } else {
    grid <- expand.grid(dimnames(mat))
  }
  cbind(grid, value = as.vector(mat))
}

all.equal(melt(mat), 
          gather.matrix(mat))
#[1] TRUE
all.equal(melt(mat2), 
          gather.matrix(mat2))
#[1] TRUE
```

Note -- replacing `expand.grid` with `tidyr::crossing` does speed up the code above, but it changes the variable names in the result.
