### ISSUE TITLE
accept data as vector?

### ISSUE THREAD

**Issue by datarichard** [tidyverse/tidyr#438]
Hi, apologies if this is not the place for this. According to the documentation, replace_na should accept vectors. However when I try:

```
ans <- c(NA, 1, 2, 3)
ans %>% replace_na(0)
```

I get an error message:

> Error in UseMethod("replace_na") : 
>   no applicable method for 'replace_na' applied to an object of class "c('double', 'numeric')"
> 

I expect to get a vector with:
0 1 2 3

**Comment by cderv** [comment]
what version to you have ? With 0.8 it is working fine. 
``` r
library(tidyr)
packageVersion("tidyr")
#> [1] '0.8.0'
ans <- c(NA, 1, 2, 3)
ans %>% replace_na(0)
#> [1] 0 1 2 3
```

Created on 2018-03-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by datarichard** [comment]
Ah, my bad. It is working on my updated machine. Sorry for trouble.
