### ISSUE TITLE
unlist a column with a list of dates

### ISSUE THREAD

**Issue by arunkundgol** [tidyverse/tidyr#450]
https://stackoverflow.com/questions/50043087/unlist-a-column-with-a-list-of-dates-in-dplyr
```
x <- seq(from= as.POSIXct('2011-01-01 14:00:00'),length.out=100,by = "hour")

y <- seq(from= as.POSIXct('2012-01-01 14:00:00'),length.out=100,by = "hour")
df <- data.frame(x,y)
When I try to create a list for each row, and then unnest it. I get the following error. 
df %>% rowwise() %>% mutate(sequence = list(seq.POSIXt(x,y,"10 min"))) %>% unnest(sequence)
Error: Each column must either be a list of vectors or a list of data frames [sequence]
```
Even after converting the dataframe to tibble format, We still receive the same error. The error seems to be reproducible. The version of R used was 3.4.0

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```
If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks
