### ISSUE TITLE
Attributes of non key-value columns in spread

### ISSUE THREAD

**Issue by stephematician** [tidyverse/tidyr#451]
Is there a reason that column attributes are voided when using `spread()`? e.g.

    D <- data.frame(x=c(1,2), y=c('A','B'), z=c(6,7))
    attributes(D$x) <- list(a='b')
    sapply(spread(D, y, z), attributes)

Gives:

    $x
    NULL
    
    $A
    NULL
    
    $B
    NULL

**Comment by batpigandme** [comment]
Hi,

So, I believe this is related to the handling of attributes in dplyr as well. On that front, there are several issues open that might be worth looking at:
https://github.com/tidyverse/dplyr/issues/3259
https://github.com/tidyverse/dplyr/issues/2752

**Comment by hadley** [comment]
Because attributes aren't preserved when subsetting:

``` r
df <- data.frame(x=c(1,2), y=c('A','B'), z=c(6,7))
attributes(df$x) <- list(a='b')
attributes(df[1:2, ]$x)
#> NULL
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
