### ISSUE TITLE
gather - support omitting key column

### ISSUE THREAD

**Issue by edvaldig** [tidyverse/tidyr#455]
Would it be possible to give the user the ability to omit the key column when calling gather?

In a few separate occasions I've been dealing with dataframes like the following:
```
> glimpse(data)
Observations: 600,000
Variables: 500
$ id                   <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1...
$ some_long_column_1   <fct> N840, NA, S430, NA, NA, R104, NA, K628, Z466, K409, R040, Z4...
$ some_long_column_2   <fct> K449, NA, R51, NA, NA, R074, NA, K610, R798, K449, J47, R33,...
$ some_long_column_3   <fct> K219, NA, R471, NA, NA, M0690, NA, K603, R55, NA, J310, N40,...
$ some_long_column_4   <fct> J00, NA, R31, NA, NA, J441, NA, K029, R101, NA, J181, K210, ...
$ some_long_column_5   <fct> C443, NA, R040, NA, NA, J440, NA, H024, N419, NA, I259, K20,...
$ some_long_column_6   <fct> D223, NA, K30, NA, NA, J383, NA, NA, N40, NA, NA, I64, M0699...
```
I need to get all unique codes from all the columns pr. ID, like so: 

`df %>%
  gather(variable, value, -id, na.rm = T) %>%
  distinct()`
however, in those cases where one doesn't care about which column a value comes from, there is a significant unnecessary overhead in including and populating the key column. I propose making a change to gather for supporting skipping the key column. One such solution would be to send in NULL or NA as key parameter:
`df %>%
  gather(key = NULL, value, -id, na.rm = T) %>%
  distinct()`

**Comment by hadley** [comment]
If you just want the unique values from the columns, I'd use a different approach to `gather()` — e.g. `df %>% select(-id) %>% map(unique) %>% unlist() %>% unique()`

**Comment by edvaldig** [comment]
Thanks for the response. In the solution described above I need to keep the link between the id column and its observed values, which is what gather already does (-id). The solution you proposed in that regard could look like:
`df %>% 
    nest(-id) %>% 
    mutate(data = map(data, purrr::compose(enframe, unique, unlist))) %>% 
    unnest() %>% 
    select(-name)`

using nest, or with split:

`sampledata %>% 
    split(.$id) %>% 
    map(select, -id) %>% 
    map(unlist) %>% 
    map(unique) %>% 
    map_df(~ data_frame(value = .), .id = "id")`

The gather function just feels more natural for the work:

`df %>% 
    gather(variable, value, -id, na.rm = T) %>% 
    select(-variable) %>% 
    distinct()`

Just to provide context, the only problem I had with it was the extra memory needed for populating and returning the variable column
