### ISSUE TITLE
feature request: extract() adapted for list-column of atomic vectors

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/tidyr#457]
tidyr::extract() transfers regex capture groups "into" new columns in a dataframe, what an awesome feature.

I often need to "extract" the elements of atomic vectors in a list-column into new columns. Below I show my workaround implemented in the extract_list() function using a combination of unnest()+spread():

For efficiency, my feature request is that extract_list() below be built into tidyr:

```{r}
library(tidyverse)
df <- data_frame(y=c("a","b","c"), x=list(c(1,2,3), c(4,5,6,-1), c(7,8,9)))
df
```
y, x // [chr,list]
"a", c(1,2,3)
"b", c(4,5,6,-1)
"c", c(7,8,9)

```{r}
extract_list <- function(df,col) {
  col <- enquo(col)
  df %>% 
    mutate(.l=map(!!col,~str_c("X",1:length(.x)))) %>% 
    unnest(!!col,.l) %>%
    spread(.l,!!col)
}
```

```{r}
extract_list(df,x)
```
y,X1,X2,X3,X4 // [chr,int,int,int,int]
"a",1,2,3,NA
"b",4,5,6,-1
"c",7,8,9,NA

**Comment by hadley** [comment]
I think you're asking for `unnest_col()` which is part of #418

**Comment by dan-reznik** [comment]
looks like this was released today as `tidyr::unnest_wider()` yaaaay
