### ISSUE TITLE
Column names differ depending on the version of R using spread

### ISSUE THREAD

**Issue by adamhsparks** [tidyverse/tidyr#458]
I'm getting different column names depending on the R version installed starting with 3.5.0 when using `spread`.

```r

xmlforecast <- xml2::read_xml("ftp://ftp.bom.gov.au/anon/gen/fwo/IDQ11295.xml")

areas <-
  xml2::xml_find_all(xmlforecast, ".//*[@type='location']")
xml2::xml_find_all(areas, ".//*[@type='forecast_icon_code']") %>%
  xml2::xml_remove()

extract_values <- function(y) {
  values <- xml2::xml_children(y)
  attrs <- unlist(as.character(xml2::xml_attrs(values)))
  values <- unlist(as.character(xml2::xml_contents(values)))
  
  time_period <- unlist(t(as.data.frame(xml2::xml_attrs(y))))
  time_period <-
    time_period[rep(seq_len(nrow(time_period)), each = length(attrs)), ]
  
  sub_out <- cbind(time_period, attrs, values)
  row.names(sub_out) <- NULL
  return(sub_out)
}

parse_areas <- function(x) {
  aac <- as.character(xml2::xml_attr(x, "aac"))
  
  # get xml children for the forecast (there are seven of these for each area)
  forecast_periods <- xml2::xml_children(x)
  
  sub_qld <-
    lapply(X = forecast_periods, FUN = extract_values)
  sub_qld <- do.call(rbind, sub_qld)
  sub_qld <- cbind(aac, sub_qld)
  return(sub_qld)
}

qld <- lapply(X = areas, FUN = parse_areas)
qld <- as.data.frame(do.call("rbind", qld))

names(qld)

qld <- tidyr::spread(qld, key = attrs, value = values)

names(qld)
```

With R 3.4.3 the names are:
```r
c("aac", "index", "start-time-local", "end-time-local", "start-time-utc", 
"end-time-utc", "\"air_temperature_maximum\", \"Celsius\"", "\"air_temperature_minimum\", \"Celsius\"", 
"precipitation_range", "precis", "probability_of_precipitation"
)
```

And with R 3.5.0 the names are

```r
c("aac", "index", "start-time-local", "end-time-local", "start-time-utc", 
"end-time-utc", "type = \"air_temperature_maximum\", units = \"Celsius\"", 
"type = \"air_temperature_minimum\", units = \"Celsius\"", "precipitation_range", 
"precis", "probability_of_precipitation")
```

It appears to be platform independent.

I've written a check into the function to overcome this issue, https://github.com/ropensci/bomrang/blob/devel/R/get_precis_forecast.R#L239, is there something more appropriate?

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by kbodwin** [comment]
Working on this reprex for Tidy Dev Day!

**Comment by kbodwin** [comment]
Note:  My guess is that when you are extracting the attributes into a variable in the line

```
attrs <- unlist(as.character(xml2::xml_attrs(values)))
```

this extraction works differently in different versions of the xml2 package.  Perhaps the oldest version returns values like

```
\"air_temperature_maximum\", \"Celsius\"
```
an intermediate version values like
```
type = \"air_temperature_maximum\", units = \"Celsius\"
```
and the most current version (which I used) values like
```
c(type = \"air_temperature_maximum\", units = \"Celsius\")
```
which is what I see when I run your original code.

In any case, the issue is not with `spread()`. :)

**Comment by hadley** [comment]
Thanks @kbodwin!

**Comment by adamhsparks** [comment]
Sorry, I've not had time to get to this, been dealing with bugs in other packages, but I'm probably now as lost as Hadley was initially. If the issue isn't with spread, it's with xml2? Odd, since I tested all of this using two versions of R on the same day, much as you did here and I don't think those versions of that package were different. Guess I'll just keep digging deeper then. Thanks, for working on this further, @kbodwin, sorry to have bothered you with this, @Hadley.
