### ISSUE TITLE
nest with a grouped data frame Gives Unexpected Results

### ISSUE THREAD

**Issue by billdenney** [tidyverse/tidyr#463]
When using `nest` with a `group_df`, the grouping columns are kept outside the nested results silently.  I would either expect for the columns to be moved inside the nested data.frame or to have a warning and for them to be kept outside.  Also, if grouping columns are maintained outside of the nested structure, I would expect the result to be a `group_df` rather than losing the `group_df` class.

Specifically, I would expect a warning when creating `d3` below that not all grouping columns were requested in the nesting and the additional grouping columns were added.  (I think that this is more consistent.)

Or

I would expect the results to be like `d4` (without having the `ungroup` call) and for the the class of `d4$data[[1]]` to be a `group_df` with only column `B` as the grouping column for `d4$data[[1]]`.

``` r
library(tidyr)                     
#> Warning: package 'tidyr' was built under R version 3.4.4
library(dplyr)                     
#> Warning: package 'dplyr' was built under R version 3.4.4
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
                                   
d <- data.frame(A=rep(1:2, each=4),
B=rep(1:4, each=2),                
C=1:8)                             
d2 <-                              
d %>%                              
group_by(A, B)                     
class(d2)                          
#> [1] "grouped_df" "tbl_df"     "tbl"        "data.frame"
names(d2)                          
#> [1] "A" "B" "C"
                                   
d3 <-                              
d2 %>%                             
nest(-A)                           
#> Warning: package 'bindrcpp' was built under R version 3.4.4
class(d3)                          
#> [1] "tbl_df"     "tbl"        "data.frame"
names(d3)                          
#> [1] "A"    "B"    "data"
names(d3$data[[1]])                
#> [1] "C"
                                   
d4 <-                              
d2 %>%                             
ungroup() %>%                      
nest(-A)                           
class(d4)                          
#> [1] "tbl_df"     "tbl"        "data.frame"
names(d4)                          
#> [1] "A"    "data"
names(d4$data[[1]])                
#> [1] "B" "C"
```

Since this seems to be a `nest` issue, I'm reporting it here rather than in `dplyr`.  If preferred, please move it to `dplyr`.

**Comment by hadley** [comment]
I think the current behaviour is correct, but it needs better documentation.

**Comment by billdenney** [comment]
I can work on a PR for the documentation.  Would you like a message (or warning) that the grouping levels are kept outside the nesting or nothing noting that the difference between the argument list and the output?

**Comment by hadley** [comment]
I'm work on improving the docs for how `nest()` works with `grouped_df` objects as part of my overhaul of `nest()`/`unnest()`.
