### ISSUE TITLE
Separate outputs empty separator error for each row independently

### ISSUE THREAD

**Issue by schmeing** [tidyverse/tidyr#471]
Calling separate for example like this:
data %>% separate(string, paste0("string",1:5), sep="")

prints "empty search patterns are not supported" for every line in the data.frame, overloads and ultimately crashes the R session for large data.frames.

**Comment by batpigandme** [comment]
Regardless of the size of your data frame, the error message you're getting, `empty search patterns are not supported` is because you have your separator set to nothing – i.e. an empty search pattern. 

If you want to separate all the characters of a string, you can use [`stringr::str_split()`](https://stringr.tidyverse.org/reference/str_split.html) which can take a pattern argument of `""`. Note, however, that this will return a list, so you'll need to do some further wrangling to get to where I _think_ you're trying to go there (it's hard to tell without a full reproducible example).

**Comment by schmeing** [comment]
Thank you for the information. However, I already solved it with str_split, unnest, mutate and spread. This is not really handy, but not the reason for this bug report.

I think no matter what input you put into a function it should not crash your whole R session and in my case RStudio right with it. The minimum fix for this issue would be to simply put the error message once and don't go into every single row, which crashes R due to overload.

I like tidyr especially because it is beginner friendly and therefore I reported the behaviour as it is exactly the opposite.

**Comment by batpigandme** [comment]
> I like tidyr especially because it is beginner friendly and therefore I reported the behaviour as it is exactly the opposite.

Agreed, though it sounds like (from your description above) this might be an IDE-related issue (or something a bit more abstract, i.e. an error that occurs repeatedly ultimately crashes the session), though I'm not 100% sure.

**Comment by schmeing** [comment]
Good point. I should also report this to RStudio.
I tried it with R in the terminal and instead of crashing it simply gives me:
"There were 50 or more warnings (use warnings() to see the first 50)"
Nevertheless reporting the same error message in every row for something row independent is still not very helpful.

**Comment by batpigandme** [comment]
> Nevertheless reporting the same error message in every row for something row independent is still not very helpful.

You might want to rephrase the title of your issue to reflect that! 👍 It'll be easier to triage and take care of that way.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(tidyr)
df <- data.frame(x = c("abc", "def"))
df %>% separate(x, c("x", "y"), "")
#> Warning in stringi::stri_split_regex(value, sep, n_max): empty search
#> patterns are not supported

#> Warning in stringi::stri_split_regex(value, sep, n_max): empty search
#> patterns are not supported
#>      x    y
#> 1 <NA> <NA>
#> 2 <NA> <NA>
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

This suggests it's actually a stringi problem.

**Comment by hadley** [comment]
https://github.com/gagolews/stringi/issues/337
