### ISSUE TITLE
Long-term stability of nest()?

### ISSUE THREAD

**Issue by dmcglinn** [tidyverse/tidyr#473]
I really like the functionality that `tidyr::nest()` provides and I would like to develop an R package that uses it but I am concerned about the long-term stability of this data structure. I am still new to the tidyverse so as an outsider I don't have a good sense of how stable this part of the codebase is. If anyone could comment I would really appreciate it. Thanks in advance!

**Comment by hadley** [comment]
Lists of data frames aren't going away, if anything we'll be providing more tools to create them and work with them.
