### ISSUE TITLE
Allow separate to fill with specified value

### ISSUE THREAD

**Issue by thomascjohnson** [tidyverse/tidyr#476]
Currently, if you are separating into n columns but you have fewer than n separated items, you have to choose between warning the user, filling in from the left or filling in from the right. It would be nice to be able to avoid the warning and specify to fill with NA, or 0, "whatever"... or whatever. Is there a reason this isn't the current functionality?

**Comment by hadley** [comment]
I think that would make the interface to `separate()` to complex. It's already at the limit of what I consider good practice.
