### ISSUE TITLE
spread overwrites existing column with identical key value

### ISSUE THREAD

**Issue by SportsTribution** [tidyverse/tidyr#478]
I was trying to do some data analysis on database table column pairs

<details>
DF <- data.frame(TABLE=c('TA','TB'),COLUMN=c('ID','TABLE'),value=c(1,1))
spread(DF,COLUMN,value)

gives

  ID TABLE
1  1    NA
2 NA     1

same for tibble.

Should be in my opinion an ERROR or at least a WARNING.

(Hope I didn't make any mistakes)
</details>

**Comment by markdly** [comment]
@SportsTribution, a warning in this situation sounds reasonable to me as another tidyr user - I didn't know this was possible but will be on the lookout for it now! 😄 

I imagine the maintainers / owners will probably want an example to be included as a [reprex](https://reprex.tidyverse.org/) so I've added one below based on your example to try and help keep the issue moving along.

**Issue**: 
If spread generates a new column with the same name as an existing column, the existing column is 'overwritten' without warning:

``` r
library(tidyverse)
df <- tibble(
  a = c(7, 7),
  key = c("a", "b"),
  value = c(1, 2)
) 
df %>% spread(key, value)
#> # A tibble: 1 x 2
#>       a     b
#>   <dbl> <dbl>
#> 1     1     2
```

Also, the number of rows after spreading appear to be based on original column values that are overwritten 

``` r
df %>% 
  mutate(a = c(8, 7)) %>% 
  spread(key, value)
#> # A tibble: 2 x 2
#>       a     b
#>   <dbl> <dbl>
#> 1    NA     2
#> 2     1    NA
```

**Comment by hadley** [comment]
@markdly thanks for generating a reprex here, it's much appreciated!

**Comment by hadley** [comment]
This is resolved by `pivot()` which uses the new tidyverse standard rules for duplicated function names:

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidyr)

df <- tibble(
  a = c(7, 7),
  key = c("a", "b"),
  value = c(1, 2)
) 
spec <- pivot_spec_wide(df, key, value)
spec
#> # A tibble: 2 x 3
#>   col_name measure key  
#>   <chr>    <chr>   <chr>
#> 1 a        value   a    
#> 2 b        value   b

df %>% pivot(spec)
#> New names:
#> a -> a..1
#> a -> a..2
#> # A tibble: 1 x 3
#>    a..1  a..2     b
#>   <dbl> <dbl> <dbl>
#> 1     7     1     2
  
df %>% 
  mutate(a = c(8, 7)) %>% 
  pivot(spec)
#> New names:
#> a -> a..1
#> a -> a..2
#> # A tibble: 2 x 3
#>    a..1  a..2     b
#>   <dbl> <dbl> <dbl>
#> 1     8     1    NA
#> 2     7    NA     2
```

<sup>Created on 2019-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Need to turn this into a test to make sure the problem does not re-occur if the code is refactored in the future.
