### ISSUE TITLE
Enhancing complete/expand to work with tables in database

### ISSUE THREAD

**Issue by kmace** [tidyverse/tidyr#479]
It would be really great to use the complete verb with a data.frame that is sitting in database.

such as:

```
total_counts = tbl(con, 'SOMETHING.TOTALCOUNTS')
total_counts %>%
  complete(Race, Gender, SmokingStatus, fill = list(num_total = 0))
```

Right now it throws the error:

```
Error in UseMethod("complete_") : no applicable method for 'complete_' applied to an object of class "c('tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

**Comment by kmace** [comment]
Please let me know if this should rather be in dbplyr. Since the function is in tidyr, I thought it fit best here.

**Comment by karldw** [comment]
@kmace, I'd be a fan of this feature too! It's already mentioned in https://github.com/tidyverse/tidyr/issues/379

**Comment by hadley** [comment]
Currently a database backend is out of scope for tidyr.
