### ISSUE TITLE
crossing behaves differently with vectors and tibbles

### ISSUE THREAD

**Issue by alexpghayes** [tidyverse/tidyr#490]
It appears that duplicate elements of vectors are dropped before generating permutations, but duplicate elements of tibbles are not. This is especially concerning in the case of vectors because it is likely to introduce silent errors when calculating permutation statistics (i.e. some of the data just won't be used in the calculation).

``` r
library(tidyverse)

x <- c(1, 2, 2)
z <- tibble(d = x)

y <- tibble(b = 4:6)

crossing(x, y)
#> # A tibble: 6 x 2
#>       x     b
#>   <dbl> <int>
#> 1     1     4
#> 2     1     5
#> 3     1     6
#> 4     2     4
#> 5     2     5
#> 6     2     6

crossing(y, z)
#> # A tibble: 9 x 2
#>       b     d
#>   <int> <dbl>
#> 1     4     1
#> 2     4     2
#> 3     4     2
#> 4     5     1
#> 5     5     2
#> 6     5     2
#> 7     6     1
#> 8     6     2
#> 9     6     2
```

Created on 2018-08-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
I'm reasonably certain this is a bug, but probably needs a bit more thinking and consideration of existing code and test cases.

**Comment by hadley** [comment]
Looking `crossing()` now, the semantics look very blurry. I suspect the whole idea needs to be rethought, probably as part of #557 and #448.

**Comment by hadley** [comment]
No difference in the dev version:

``` r
library(tidyr)
library(tibble)

x <- c(1, 2, 2)
y <- tibble(b = 4:6)

crossing(x, y)
#> # A tibble: 6 x 2
#>       x   y$b
#>   <dbl> <int>
#> 1     1     4
#> 2     1     5
#> 3     1     6
#> 4     2     4
#> 5     2     5
#> 6     2     6
crossing(df = tibble(x = x), y)
#> # A tibble: 6 x 2
#>    df$x   y$b
#>   <dbl> <int>
#> 1     1     4
#> 2     1     5
#> 3     1     6
#> 4     2     4
#> 5     2     5
#> 6     2     6
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

We will need to consider automatically unpacking unnamed tibbles.
