### ISSUE TITLE
Using complete with a subset of levels silently drops observations

### ISSUE THREAD

**Issue by gowerc** [tidyverse/tidyr#493]
Based upon the description of complete  its purpose is to add missing observations for specific combinations of variable values. I believe therefore it is not very intuitive for it to silently drop observations if certain levels are not present,  for example:

```
library(tidyr)
library(dplyr)

iris %>% 
    as_data_frame() %>% 
    mutate( Species = as.character(Species)) %>% 
    complete( Species = c("versicolor", "virginica"))
```

This code silently drops all observations with Species = setosa

I would propose either changing the function to use a full_join()  to ensure the original data is preserved or at the very least adding a warning/message so the user is aware that data has been lost. 

I am happy to make a PR if people agree this is a beneficial change.

**Comment by gowerc** [comment]
Happy to make a PR if people agree this is a beneficial change

**Comment by hadley** [comment]
I think the right way to handle this is to `union()` the supplied value with the existing values. A PR would be greatly appreciated 😄

**Comment by Ryo-N7** [comment]
Going to work on this for tidy-dev-day.
@batpigandme please add a tidy-dev-day label.

**Comment by batpigandme** [comment]
@Ryo-N7 All set 👍
