### ISSUE TITLE
FR: separate() not a character but a vector

### ISSUE THREAD

**Issue by grayskripko** [tidyverse/tidyr#494]
There is a great tidyr::separate() function. I couldn't find a similar function in tidyverse when the target column is a list of vectors, not a character. The best way to solve it [that I found](https://community.rstudio.com/t/split-a-column-each-element-is-a-vector-to-multiple-columns/14009)  isn't obvious and quite complex

```{r}
library(tidyverse)
tribble(
    ~a,
    1:3,
    1:3 * 10) %>%
    `[<-`(, c('d', 'e', 'f'), map(transpose(.$a), unlist))
#> # A tibble: 2 x 4
#>   a             d     e     f
#>   <list>    <dbl> <dbl> <dbl>
#> 1 <int [3]>     1     2     3
#> 2 <dbl [3]>    10    20    30
```

It could be a special case of ```separate(sep = NULL)``` and I think it is a very intuitive name for the function but probably is a messy design decision. 
Such a function requires a complement version as ```unite()```

**Comment by moodymudskipper** [comment]
I believe this is closer to `unnest` than `separate`. I'd be happy to see more development around `unnest` as it could make things much less awkward than some gather/spread combinations.

I believe the following would be the idiomatic way.

```
df %>% rowid_to_column("id")  %>%
  unnest() %>%
  group_by(id) %>%
  mutate(key=paste0(letters[4:6])) %>%
  spread(key,a) %>%
  bind_cols(df,.) %>%
  select(-id)
# # A tibble: 2 x 4
#           a     d     e     f
#      <list> <dbl> <dbl> <dbl>
# 1 <int [3]>     1     2     3
# 2 <dbl [3]>    10    20    30
```

 I tend to use helper functions for my own cases, as I propose below :

```
vecs2rows <- function(x,nms = NULL){
  map(x,~setNames(invoke(tibble,.),
                  if (is.null(nms)) seq_along(.) else nms))
}

df  %>%
  mutate_at('a', vecs2rows, letters[1:3]) %>% 
  unnest() %>%
  bind_cols(df,.)
# # A tibble: 2 x 4
#           a    a1     b     c
#      <list> <dbl> <dbl> <dbl>
# 1 <int [3]>     1     2     3
# 2 <dbl [3]>    10    20    30
```

For it to become a one liner, we would need a boolean parameter to keep the original column, and another parameter to unnest vectors horizontally.

**Comment by hadley** [comment]
This will probably become `unnest_cols()`, #418
