### ISSUE TITLE
Request: .tidy = TRUE to spread to indicate that rows are a primary key

### ISSUE THREAD

**Issue by alexpghayes** [tidyverse/tidyr#497]
I find myself doing the following a bunch:

```r
maize <- tibble(
  treatment = c("bio", "bio", "bio", "bio", "bio", "bio", "bio", "bio", "chem", "chem", "chem", "chem", "chem", "chem", "chem", "chem"),
  moths = c(37, 42, 12, 32, 97, 68, 14, 29, 41, 45, 18, 106, 107, 171, 12, 30)
)

maize %>% 
  mutate(id = row_number()) %>% 
  spread(treatment, moths) %>% 
  select(-id)
```

when there are repeated `treatment`s. If the data is tidy, then the row is implicitly a primary key, and it's a couple extra lines of code to add the `id` and then remove it. Thoughts on a `.tidy = TRUE` argument to specify that the data is tidy and the row can be used as a primary key?

**Comment by hadley** [comment]
It feels to me like the solution here should be some "magic" variable like `.rowid`, but there's no place in the current interface where this would fit. So I'll consider this as part of #149

**Comment by hadley** [comment]
Do you mean this?

``` r
library(tidyverse)

maize <- tibble(
  treatment = c("bio", "bio", "bio", "bio", "bio", "bio", "bio", "bio", "chem", "chem", "chem", "chem", "chem", "chem", "chem", "chem"),
  moths = c(37, 42, 12, 32, 97, 68, 14, 29, 41, 45, 18, 106, 107, 171, 12, 30)
)

maize %>% 
  group_by(treatment) %>% 
  mutate(id = row_number()) %>% 
  spread(treatment, moths) %>% 
  select(-id)
#> # A tibble: 8 x 2
#>     bio  chem
#>   <dbl> <dbl>
#> 1    37    41
#> 2    42    45
#> 3    12    18
#> 4    32   106
#> 5    97   107
#> 6    68   171
#> 7    14    12
#> 8    29    30
```

<sup>Created on 2019-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
But even then I'm not sure why you'd want to drop `id` since it seems like useful data to preserve.

**Comment by alexpghayes** [comment]
I did mean the original code - there were missing observations. Perhaps some of the dissonance is that I think of `tidyverse` functions as working on `tidy` data, but `tidy` data / pedagogy is sort of silent (or implicit) on whether or not you need a primary key. So I have data that looks tidy, so I expect things to "work" (do what I expect), but without a primary key this expectation is violated.

Unique row id feels like the right solution. Might be a good idea to add some comments on this to the documentation?

**Comment by hadley** [comment]
Yeah, I think spelling out the need for unique identifiers is going to be important, and is mostly a documentation problem (although the `measure.vars` vs `id.vars` from `reshape::melt()` are more evocative of this concern than anything that has come since, and probably worth reviving in some form).

**Comment by hadley** [comment]
Discovered that tidying the built-in Anscombe's quartet is a good example of this, so I've added that to the vignette. I'll add more explanation as I re-write the vignette.
