### ISSUE TITLE
New spread-gather name pair ideas

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#498]
* widen + lengthen
* elongate + broaden
* stretch + compress
* ravel + unravel
* cast + melt

**Comment by epetrovski** [comment]
"widen + lengthen" would be consistent with the terminology of econometrics. A plus for people from the social sciences.

BTW, is this possibly related to #149?

**Comment by albertotb** [comment]
What about pivot + melt? Same terminology is used in Pandas if I'm not mistaken.

**Comment by JoFAM** [comment]
I would like to propose `gather` and `spread`, as that's what I've been teaching my students the past year and don't want to have to change my exercises and slides yet again. I went from `cast`-`melt` to `dcast/acast`-`melt` to `spread-gather` in about 6 years. 

But if you want to change, please decide quickly so textbooks, exercises and so on can be updated in time and we don't teach our students yet again something that won't be standard any longer next year.

**Comment by lionel-** [comment]
collect + disperse

It'd be nice if the names reflected the nature of the operation in addition to its reshaping properties.

**Comment by hadley** [comment]
Thanks all. After some though I think the best approach is going to be use a suffix to indicate the directionality, e.g. `_wide()`, `_long()`. I'm still not sure what the core name will be but I'm currently leaning towards `pivot_` and I'm likely to do some informal user testing before CRAN release.
