### ISSUE TITLE
data is not getting saved into data frame.(web Scrapping)

### ISSUE THREAD

**Issue by nitisethi28** [tidyverse/tidyr#508]
install.packages("rvest")
library(rvest)
install.packages("dplyr")
library(dplyr)
install.packages("tibble")
library(tibble)
google <-read_html("https://bidplus.gem.gov.in/bidresultlists")
x<-google %>%
  html_nodes(".block")%>%
  html_text()
x
class(x)
x1<-gsub( "                                                            ", "", x) 
x1
x2<-gsub("                                                        ","",x1)
x2
x3<-gsub("            ","",x2)
x3
x4<-gsub("    ","",x3)
x4
x5<-gsub("  ","",x4)
x5
x6<-gsub("\n","",x5)
x6

install.packages("qdapRegex")
library(qdapRegex)

final_df<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

install.packages("data.table")
library(data.table)
for(i in x6)
{
  BIDNO<-rm_between(x6[i], " BID NO: ", "Status", extract=TRUE)
  Status<-rm_between(x6[i], " Status: ", "Quantity Required", extract=TRUE)
  Quantity_Required<-rm_between(x6[i], " Quantity Required: ", "Department Name And Address", extract=TRUE)
  Department_Name_And_Address<-rm_between(x6[i], "Department Name And Address: ", "Start Date", extract=TRUE)
  Start_Date<-rm_between(x6[i], "Start Date: ", "End Date", extract=TRUE)
  #End_Date<-rm_between(x6[i], "End Date: ", "Technical Evaluation", extract=TRUE)
  
  #df<-data.frame(BIDNO,Status,Quantity_Required,Department_Name_And_Address,Start_Date)
  
  df<-DataFrame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

  #d  f<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_Address","Start_Date")
}
qw
View(qw)
df1<-data.frame(rbind(final_df, df))

View(final_df)

**Comment by nitisethi28** [comment]
install.packages("rvest")
library(rvest)
install.packages("dplyr")
library(dplyr)
install.packages("tibble")
library(tibble)
google <-read_html("https://bidplus.gem.gov.in/bidresultlists")
x<-google %>%
  html_nodes(".block")%>%
  html_text()
x
class(x)
x1<-gsub( "                                                            ", "", x) 
x1
x2<-gsub("                                                        ","",x1)
x2
x3<-gsub("            ","",x2)
x3
x4<-gsub("    ","",x3)
x4
x5<-gsub("  ","",x4)
x5
x6<-gsub("\n","",x5)
x6

install.packages("qdapRegex")
library(qdapRegex)

final_df<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

install.packages("data.table")
library(data.table)
for(i in x6)
{
  BIDNO<-rm_between(x6[i], " BID NO: ", "Status", extract=TRUE)
  Status<-rm_between(x6[i], " Status: ", "Quantity Required", extract=TRUE)
  Quantity_Required<-rm_between(x6[i], " Quantity Required: ", "Department Name And Address", extract=TRUE)
  Department_Name_And_Address<-rm_between(x6[i], "Department Name And Address: ", "Start Date", extract=TRUE)
  Start_Date<-rm_between(x6[i], "Start Date: ", "End Date", extract=TRUE)
  #End_Date<-rm_between(x6[i], "End Date: ", "Technical Evaluation", extract=TRUE)
  
  #df<-data.frame(BIDNO,Status,Quantity_Required,Department_Name_And_Address,Start_Date)
  
  df<-DataFrame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

  #d  f<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_Address","Start_Date")
}
qw
View(qw)
df1<-data.frame(rbind(final_df, df))

View(final_df)

**Comment by batpigandme** [comment]
From what I can tell, I don't think you're using tidyr here. Either way, this sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (Before doing so, you might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer. As you have things currently, it's very hard to read your code because of the lack of formatting).

**Comment by nitisethi28** [comment]
install.packages("reprex")
 library(reprex)
 install.packages("rvest")
library(rvest)
install.packages("dplyr")
library(dplyr)
install.packages("tibble")
library(tibble)
google <-read_html("https://bidplus.gem.gov.in/bidresultlists")
x<-google %>%
html_nodes(".block")%>%
html_text()
x
class(x)
x1<-gsub( " ", "", x)
x1
x2<-gsub(" ","",x1)
x2
x3<-gsub(" ","",x2)
x3
x4<-gsub(" ","",x3)
x4
x5<-gsub(" ","",x4)
x5
x6<-gsub("\n","",x5)
x6

install.packages("qdapRegex")
library(qdapRegex)

final_df<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

install.packages("data.table")
library(data.table)
for(i in x6)
{
BIDNO<-rm_between(x6[i], " BID NO: ", "Status", extract=TRUE)
Status<-rm_between(x6[i], " Status: ", "Quantity Required", extract=TRUE)
Quantity_Required<-rm_between(x6[i], " Quantity Required: ", "Department Name And Address", extract=TRUE)
Department_Name_And_Address<-rm_between(x6[i], "Department Name And Address: ", "Start Date", extract=TRUE)
Start_Date<-rm_between(x6[i], "Start Date: ", "End Date", extract=TRUE)
#End_Date<-rm_between(x6[i], "End Date: ", "Technical Evaluation", extract=TRUE)

#df<-data.frame(BIDNO,Status,Quantity_Required,Department_Name_And_Address,Start_Date)

df<-DataFrame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

#df<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_Address","Start_Date")
}


df1<-data.frame(rbind(final_df, df))
View(final_df)
