### ISSUE TITLE
web scrapping

### ISSUE THREAD

**Issue by nitisethi28** [tidyverse/tidyr#509]
library(reprex)
 install.packages("rvest")
library(rvest)
install.packages("dplyr")
library(dplyr)
install.packages("tibble")
library(tibble)
google <-read_html("https://bidplus.gem.gov.in/bidresultlists")
x<-google %>%
html_nodes(".block")%>%
html_text()
x
class(x)
x1<-gsub( " ", "", x)
x1
x2<-gsub(" ","",x1)
x2
x3<-gsub(" ","",x2)
x3
x4<-gsub(" ","",x3)
x4
x5<-gsub(" ","",x4)
x5
x6<-gsub("\n","",x5)
x6

install.packages("qdapRegex")
library(qdapRegex)

final_df<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

install.packages("data.table")
library(data.table)
for(i in x6)
{
BIDNO<-rm_between(x6[i], " BID NO: ", "Status", extract=TRUE)
Status<-rm_between(x6[i], " Status: ", "Quantity Required", extract=TRUE)
Quantity_Required<-rm_between(x6[i], " Quantity Required: ", "Department Name And Address", extract=TRUE)
Department_Name_And_Address<-rm_between(x6[i], "Department Name And Address: ", "Start Date", extract=TRUE)
Start_Date<-rm_between(x6[i], "Start Date: ", "End Date", extract=TRUE)
#End_Date<-rm_between(x6[i], "End Date: ", "Technical Evaluation", extract=TRUE)

#df<-data.frame(BIDNO,Status,Quantity_Required,Department_Name_And_Address,Start_Date)

df<-DataFrame("BIDNO","Status","Quantity_Required","Department_Name_And_Address","Start_Date")

#df<-data.frame("BIDNO","Status","Quantity_Required","Department_Name_Address","Start_Date")
}

df1<-data.frame(rbind(final_df, df))
View(final_df)

_Originally posted by @nitisethi28 in https://github.com/tidyverse/tidyr/issues/508#issuecomment-430967076_

**Comment by hadley** [comment]
This question is not appropriate for github. Please follow the advice given in the original issue.
