### ISSUE TITLE
complete() sets some decimal values to NA()

### ISSUE THREAD

**Issue by Z3tt** [tidyverse/tidyr#510]
Hi together,

I started a [discussion in the RStudio community forum](https://community.rstudio.com/t/complete-sets-some-values-to-na/16547/5) since I spotted an unusual behavior of `complete()`. Here is a reproducible example:

``` r
library(tidyverse)
dat <- tibble(group = c("A", "A", "A", "B", "B", "B"), 
              beta = c(0.012, 0.013, 0.014, 0.012, 0.013, 0.014), 
              D = c(0.174, 0.16, 0.158, 0.204, 0.182, 0.164))
dat
#> # A tibble: 6 x 3
#>   group  beta     D
#>   <chr> <dbl> <dbl>
#> 1 A     0.012 0.174
#> 2 A     0.013 0.16 
#> 3 A     0.014 0.158
#> 4 B     0.012 0.204
#> 5 B     0.013 0.182
#> 6 B     0.014 0.164
dat %>% complete(nesting(group), beta = full_seq(beta, 0.0005, tol = 5*1e-03))
#> # A tibble: 10 x 3
#>    group   beta      D
#>    <chr>  <dbl>  <dbl>
#>  1 A     0.012   0.174
#>  2 A     0.0125 NA    
#>  3 A     0.013  NA    
#>  4 A     0.0135 NA    
#>  5 A     0.014   0.158
#>  6 B     0.012   0.204
#>  7 B     0.0125 NA    
#>  8 B     0.013  NA    
#>  9 B     0.0135 NA    
#> 10 B     0.014   0.164
```

<sup>Created on 2018-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note that, beside the NA's which are introduced correctly for each intermediate step (i.e. 0.0125 and 0.0135), the values for 0.013 were set to NA as well. 

A workaround is to get rid of decimal numbers by multiplying the original D values and transforming them back afterwards:

``` r
library(tidyverse)
dat <- tibble(group = c("A", "A", "A", "B", "B", "B"), 
              beta = c(0.012, 0.013, 0.014, 0.012, 0.013, 0.014), 
              D = c(0.174, 0.16, 0.158, 0.204, 0.182, 0.164))
dat %>%  
    complete(nesting(group), beta = full_seq(beta*1e3, 0.0005*1e3) / 1e3)
#> # A tibble: 10 x 3
#>    group   beta      D
#>    <chr>  <dbl>  <dbl>
#>  1 A     0.012   0.174
#>  2 A     0.0125 NA    
#>  3 A     0.013   0.16 
#>  4 A     0.0135 NA    
#>  5 A     0.014   0.158
#>  6 B     0.012   0.204
#>  7 B     0.0125 NA    
#>  8 B     0.013   0.182
#>  9 B     0.0135 NA    
#> 10 B     0.014   0.164
```

<sup>Created on 2018-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

We couldn't not find the source of this behaviour but from my point of view it is an important issue since it might silently remove values from your data set.

EDIT: Might be related to [issue #2432 of dplyr](https://github.com/tidyverse/dplyr/issues/2432)

**Comment by hadley** [comment]
This is just the challenge of working with floating point numbers:

``` r
beta1 <- c(0.012, 0.013, 0.014, 0.012, 0.013, 0.014)
beta2 <- tidyr::full_seq(beta1, 0.0005, tol = 5*1e-03)

beta1[[2]]
#> [1] 0.013
beta2[[3]]
#> [1] 0.013
beta1[[2]] - beta2[[3]]
#> [1] -1.734723e-18
```

<sup>Created on 2018-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I don't know how to resolve it but generally it's very difficult to join doubles, and you'll need to round or similar.
