### ISSUE TITLE
Use `""` for new variable creation in docs

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidyr#517]
Branching this off from #515 

Per @hadley's comment https://github.com/tidyverse/tidyr/issues/515#issuecomment-436288022
> We should change the tidyr documentation to consistently use `""` when creating new variables. For backwards compatibility, we can't ever eliminate the old behaviour (except in the eventual successors for `gather()` and `spread()`), but we can steer people away from it.

**Comment by yanlesin** [comment]
I would like to tackle this issue
