### ISSUE TITLE
unite broken in 0.8.2 when no cols specified

### ISSUE THREAD

**Issue by fabiangehring** [tidyverse/tidyr#518]
After the update to tidyr 0.8.2 unite does not work anymore with no cols specified.
In 0.8.1 in works as expected

```r
dat <- tibble(a = 1, b = 2)
unite(dat)
# Error in is_character(x, encoding = encoding, n = 1L) : 
#  argument "expr" is missing, with no default
```

**Comment by batpigandme** [comment]
You need to specify a second argument for the name of a new column as a string or symbol. 
https://tidyr.tidyverse.org/reference/unite.html
