### ISSUE TITLE
nest() looses group_by() groups

### ISSUE THREAD

**Issue by ratnanil** [tidyverse/tidyr#524]
Apparently, using `tidyr::nest()` let's the `data.frame` forget it's grouping variables (see my [SO question](https://stackoverflow.com/q/53855897/4139249)). I'm not sure if this _is_ an issue, I just thought I'd post this here (my question [has been answered on SO](https://stackoverflow.com/a/53856537/4139249)).

``` r
library(dplyr)
library(purrr)
library(tidyr)

mtcars %>% 
  group_by(cyl) %>%
  nest() %>%
  groups()
#> NULL

```
The groups are gone. In order to use the grouping variables within a `map()` function call, for example, I need to reset the groups again. 

``` r
mtcars %>% 
  group_by(cyl) %>%
  nest() %>%
  group_by(cyl) %>%
  mutate(wt_mean = map_dbl(data,~mean(.x$wt)/cyl))
#> # A tibble: 3 x 3
#> # Groups:   cyl [3]
#>     cyl data               wt_mean
#>   <dbl> <list>               <dbl>
#> 1     6 <tibble [7 x 10]>    0.520
#> 2     4 <tibble [11 x 10]>   0.571
#> 3     8 <tibble [14 x 10]>   0.500

Created on 2018-12-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

```

**Comment by yutannihilation** [comment]
You will get able to use `group_map()` with the next version of dplyr :) (But, I don't understand why you need more than `map2()` or `pmap()` as answered on SO...)

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  group_by(cyl) %>%
  group_map(function(data, group_info) {
    tibble::tibble(wt_mean = mean(data$wt) / group_info$cyl)
  })
#> # A tibble: 3 x 2
#> # Groups:   cyl [3]
#>     cyl wt_mean
#> * <dbl>   <dbl>
#> 1     4   0.571
#> 2     6   0.520
#> 3     8   0.500
```

<sup>Created on 2018-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ratnanil** [comment]
Nice, looking forward to this update! 

The workarounds from the SO answer work fine; I just wasn't sure if this was the expected / desired behaviour of `nest()`.

**Comment by hadley** [comment]
Nesting turns each group into a single row, so I don't think preserving the grouping would be practically useful. (Especially since you'll be able to do the `nest()`/`mutate()` + `map()`/`unnest()` pattern with `group_map()`)
