### ISSUE TITLE
Add type-based replacement option to replace_na.data.frame

### ISSUE THREAD

**Issue by markroepke** [tidyverse/tidyr#527]
I am suggesting that type-based replacement be added as an option to `replace_na.data.frame` method. Specifically, in addition to being able pass a list of variable names and replacement values to the `replace` parameter, add functionality to pass a list of variable types and replacement values.

I think this is useful because I, and I assume other users, have use cases where they may have too many variables to list individually and have different replacement values dependent on variable type.

Below is an example of what I am talking about.

---

Assume we have `tbl` as:

```r
tbl <- tibble::tibble(
  w = c(1L, 2L, NA), 
  x = c("A", "B", NA), 
  y = c(TRUE, FALSE, NA), 
  z = c(1, 2, NA)
) 

> tbl
# A tibble: 3 x 4
      w x     y         z
  <int> <chr> <lgl> <dbl>
1     1 A     TRUE      1
2     2 B     FALSE     2
3    NA NA    NA       NA
```

And we want to replace `NA` values based on variable type using something like:

```r
new_tbl <- replace_na.data.frame(
  tbl,
  replace = list("integer" = 0L, "character" = "none", "double" = 0, "logical" = FALSE), 
  by_type = TRUE
)
```

And we return: 

```r
> new_tbl
# A tibble: 3 x 4
      w x     y         z
  <int> <chr> <lgl> <dbl>
1     1 A     TRUE      1
2     2 B     FALSE     2
3     0 none  FALSE     0
```

---

If you feel this may be a useful addition, I am happy to make a pull request following the guidelines (styling, tests, etc.). I have written the following as a possible design/implementation:

```r
replace_na.data.frame <- function(data, replace = list(), by_type = FALSE, ...) {
  stopifnot(is_list(replace))
  
  if (!by_type) {
    replace_vars <- intersect(names(replace), names(data))
    
    for (var in replace_vars) {
      check_replacement(replace[[var]], var)
      data[[var]][!is_complete(data[[var]])] <- replace[[var]]
    }
    
  } else {
    replace_types <- intersect(lapply(data, typeof), names(replace))
    replace_vars <- names(data)[lapply(data, typeof) %in% replace_types]
    
    for (var in replace_vars) {
      for (type in replace_types) {
        if (typeof(data[[var]]) == type) {
          check_replacement(replace[[type]], type)
          data[[var]][!is_complete(data[[var]])] <- replace[[type]]
        }
      }
    }
  }
  
  data
}
```

Any feedback on the above would be greatly appreciated. I want to ensure consistency in design and implementation, so I am definitely very flexible on both.

**Comment by hadley** [comment]
I think this is sufficiently specialised it's not worth including in tidyr. Also, if you have just a few column types, it's already pretty easy to do with purrr + tidyr:

``` r
library(tidyverse)

tbl <- tibble::tibble(
  w = c(1L, 2L, NA), 
  x = c("A", "B", NA), 
  y = c(TRUE, FALSE, NA), 
  z = c(1, 2, NA)
)

tbl %>% 
  modify_if(is.character, replace_na, "none") %>% 
  modify_if(is.integer, replace_na, 0L) %>% 
  modify_if(is.numeric, replace_na, 0) %>% 
  modify_if(is.logical, replace_na, FALSE)
#> # A tibble: 3 x 4
#>       w x     y         z
#>   <dbl> <chr> <lgl> <dbl>
#> 1     1 A     TRUE      1
#> 2     2 B     FALSE     2
#> 3     0 none  FALSE     0
```

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
In general, I don't think there's any API that I'd be happy with that described types using strings, because it's fundamentally rather limited. See https://vctrs.r-lib.org for more of my latest thinking about working with types in R.

**Comment by hadley** [comment]
It's also likely that we'll have some helpers in `mutate()` for this. Maybe something like:

```R
tbl %>% 
  mutate(
    cols_if(is.character, replace_na, "none"),
    cols_if(is.integer, replace_na, 0L),
    cols_if(is.numeric, replace_na, 0),
    cols_if(is.logical, replace_na, FALSE)
  )
```

cc @lionel-

**Comment by markroepke** [comment]
Thanks for responding. I hindsight, I definitely see your point about the describing types using strings not being ideal. I was probably a bit blinded by the implementation of the describing colnames using strings, which obviously makes a lot more sense.

For what it's worth as you seem to be considering different implementations of this, I ran some benchmarking using rbenchmark on various options out of curiosity. These may help fuel/guide the direction:

```r
tbl <- tibble::tibble(
  w = rep(c(1L, 2L, NA), 100000), 
  x = rep(c("A", "B", NA), 100000), 
  y = rep(c(TRUE, FALSE, NA), 100000), 
  z = rep(c(1, 2, NA), 100000)
)

benchmark("dplyr" = {
  tbl %>% 
    mutate_if(is.character, replace_na, "none") %>% 
    mutate_if(is.integer, replace_na, 0L) %>%
    mutate_if(is.numeric, replace_na, 0) %>%
    mutate_if(is.logical, replace_na, FALSE)
  },
  "purrr" = {
    tbl %>% 
      modify_if(is.character, replace_na, "none") %>% 
      modify_if(is.integer, replace_na, 0L) %>% 
      modify_if(is.numeric, replace_na, 0) %>% 
      modify_if(is.logical, replace_na, FALSE)
  },
  "by_type" = {
    tbl %>% 
      replace_na.data.frame(
        replace = list("integer" = 0L, "character" = "none", "double" = 0, "logical" = FALSE), 
        by_type = TRUE
    )
  },
  replications = 1000,
  columns = c("test", "replications", "elapsed",
              "relative", "user.self", "sys.self")
)
#>      test replications elapsed relative user.self sys.self
#> 3 by_type         1000  18.532    1.000    14.305    4.205
#> 1   dplyr         1000  36.646    1.977    30.886    5.761
#> 2   purrr         1000  37.056    2.000    30.726    6.264
```

I realize the string-based solution I've proposed is not ideal, but it may contain something useful given the above.

**Comment by hadley** [comment]
@markroepke unfortunately that's very really useful as if we decided that performance was a problem here we would optimise it (most of the time is taken up by `replace_na()`, which we could relatively easily rewrite in C if it was deemed to be a bottleneck).
