### ISSUE TITLE
nest() fails on tibble which is grouped by a column name starting with two dots

### ISSUE THREAD

**Issue by ghost** [tidyverse/tidyr#541]
If asked to nest a tibble one of whose column names is two dots followed by a digit, and which has been grouped by that column, nest() gives the error "Error in .f(.x[[i]], ...) : the ... list does not contain N elements", where N seems to be the same as the digit. Nesting an equivalent tibble where the column name doesn't start with two dots seems to be OK.

This doesn't matter to me (it happened when I tried to nest a tibble returned by the updated version of read_excel(), which now replaces blannk names by double-dotted ones), but I thought I ought to report it. Apologies for not doing a proper repex: it seems to require pandoc, which doesn't install on my system. 

``` r
library(tidyverse)
t <- dplyr::tribble(~a, ~b, ~c, "a", "b", "c")

t %>% 
  dplyr::group_by(a) %>% 
  tidyr::nest()
#> # A tibble: 1 x 2
#>   a     data            
#>   <chr> <list>          
#> 1 a     <tibble [1 × 2]>

t <- dplyr::tribble(~`..2`, ~b, ~c, "a", "b", "c")

t
#> # A tibble: 1 x 3
#>   ..2   b     c    
#>   <chr> <chr> <chr>
#> 1 a     b     c

t %>% 
  dplyr::group_by(`..2`) %>%
  tidyr::nest()
#> Error in .f(.x[[i]], ...): the ... list does not contain 2 elements
```
<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by batpigandme** [comment]
Thanks for the report, @TVD1000.

Adding a full reprex:

``` r
library(tidyverse)
t <- dplyr::tribble(~a, ~b, ~c, "a", "b", "c")

t %>% 
  dplyr::group_by(a) %>% 
  tidyr::nest()
#> # A tibble: 1 x 2
#>   a     data            
#>   <chr> <list>          
#> 1 a     <tibble [1 × 2]>

t <- dplyr::tribble(~`..2`, ~b, ~c, "a", "b", "c")

t
#> # A tibble: 1 x 3
#>   ..2   b     c    
#>   <chr> <chr> <chr>
#> 1 a     b     c

t %>% 
  dplyr::group_by(`..2`) %>%
  tidyr::nest()
#> Error in .f(.x[[i]], ...): the ... list does not contain 2 elements
```
<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by batpigandme** [comment]
Incidentally, it does work with three dots before the numeral 3 `...3`:
``` r
library(tidyverse)
t <- dplyr::tribble(~`...2`, ~b, ~c, "a", "b", "c")

t
#> # A tibble: 1 x 3
#>   ...2  b     c    
#>   <chr> <chr> <chr>
#> 1 a     b     c

t %>% 
  dplyr::group_by(`...2`) %>%
  tidyr::nest()
#> # A tibble: 1 x 2
#>   ...2  data            
#>   <chr> <list>          
#> 1 a     <tibble [1 × 2]>

t <- dplyr::tribble(~`...3`, ~b, ~c, "a", "b", "c")

t
#> # A tibble: 1 x 3
#>   ...3  b     c    
#>   <chr> <chr> <chr>
#> 1 a     b     c

t %>% 
  dplyr::group_by(`...3`) %>%
  tidyr::nest()
#> # A tibble: 1 x 2
#>   ...3  data            
#>   <chr> <list>          
#> 1 a     <tibble [1 × 2]>
```
<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
Dear Original Poster (who has deleted their account 20 mins after posting) or other readxl-ers,

If you want readxl to repair names so that they are syntactic, instead of just unique, you can specify that at import time: `read_excel(..., .name_repair = "universal")`. "universal" here means the column names should "work everywhere", i.e. they are unique and syntactic.

@batpigandme Yeah going from 2 dots to 3 dots takes the name from nonsyntactic to syntactic.

**Comment by batpigandme** [comment]
Thx, Jenny. Imma go ahead and close this issue, then.

**Comment by jennybc** [comment]
I've reopened because it's not clear to me that the ability to nest should require that the column name by syntactic. Even if it should, the error message should convey that.

**Comment by hadley** [comment]
@jennybc is there anything tidyr needs to do or are we just waiting for the tibble update?

**Comment by jennybc** [comment]
Just wait for tibble.

It's coming, i.e. revdeps are done, so now it's down to final discussion & checks:
https://github.com/tidyverse/tibble/pull/584
