### ISSUE TITLE
uncount could be faster for non-tibbles

### ISSUE THREAD

**Issue by HughParsonage** [tidyverse/tidyr#543]
Possibly out-of-scope, but I noticed that using `tidyr::uncount` was significantly slower when supplied with a non-tibble. The slowness can be overcome simply by converting back and forth. The difference between the time of `uncount` on a non-tibble and the time of converting to a tibble, then using `uncount`, and converting back, is considerable for a typical data set, so it may be worth doing this conversion automatically.

I can offer to do a PR if you would like; however, I'm not sure of the idiomatic way to convert a 'data.frame-like object' to a tibble and back again within the tidyverse.

``` r
library(data.table)
library(bench)
library(hutils)
library(tidyr)

DT <- data.table(w = rep_len(round(rlnorm(1000, 2, 1)), 1e6))
bench::mark(uncount(DT, w), 
            hutils::weight2rows(DT, "w", discard_weight.var = TRUE),
            as.data.table(uncount(tibble::as_tibble(DT), w)))
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 3 x 10
#>   expression         min        mean      median         max `itr/sec`
#>   <chr>         <bch:tm>    <bch:tm>    <bch:tm>    <bch:tm>     <dbl>
#> 1 uncount(D~ 10586.825ms 10586.825ms 10586.825ms 10586.825ms    0.0945
#> 2 "hutils::~   707.205ms   707.205ms   707.205ms   707.205ms    1.41  
#> 3 as.data.t~   126.449ms   239.212ms   126.844ms   576.710ms    4.18  
#> # ... with 4 more variables: mem_alloc <bch:byt>, n_gc <dbl>, n_itr <int>,
#> #   total_time <bch:tm>
```

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
I don't think converting back and forth between different types to work around performance issues is a good idea.

**Comment by HughParsonage** [comment]
Is that because you think:
1. the performance hit is too small or too obscure to bet worth the extra code, 
2. conversion risks other bugs, or
3. the core performance issue should be fixed, regardless of type?

**Comment by hadley** [comment]
All three, but mostly it just feels like a bad programming practice to fix a problem using the side-effects of a seemingly unrelated function call. Reading the code later on, how would you know that the purpose of converting back-and-forth to a tibble was to improve performance? Also it requires using `vctrs::vec_cast()` to do it correctly, and putting a relatively new function in a commonly used package seems risky.
