### ISSUE TITLE
Possible extract() + rematch2 happiness

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyr#548]
From a twitter thread: https://twitter.com/JennyBryan/status/1093268402196500480

Excerpts relevant to this:

@clauswilke: "often I'd like to apply a regex to a column in a data frame and turn the captured groups into new columns"

@gaborcsardi: "IMO my <https://github.com/r-lib/rematch2> package gives you a nicer interface, e.g. returning matches and groups in a data frame"

@jennybc: "I love rematch2 for named capture groups! It would be cool if, one day, `tidyr::extract()` could tap into that to introduce a ?data frame column?"

**Comment by hadley** [comment]
So that these are equivalent?

```
df <- data.frame(x = c(NA, "a-b", "a-d", "b-c", "d-e"))

df %>% extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")

df %>% extract2(x, "(?<A>[[:alnum:]]+)-(?<B>[[:alnum:]]+)")
```

**Comment by jennybc** [comment]
Yeah, but maybe also where the new columns are in a data frame column?

``` r
library(tidyverse)

df <- tibble(x = c(NA, "a-b", "a-d", "b-c", "d-e"))

df %>% extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
#> # A tibble: 5 x 2
#>   A     B    
#>   <chr> <chr>
#> 1 <NA>  <NA> 
#> 2 a     b    
#> 3 a     d    
#> 4 b     c    
#> 5 d     e

# df %>% extract2(x, "(?<A>[[:alnum:]]+)-(?<B>[[:alnum:]]+)")

# dplyr >= 0.9
# df %>% 
#   mutate(m = rematch2::re_match(x, "(?<A>[[:alnum:]]+)-(?<B>[[:alnum:]]+)"))

df$m <- df$x %>% 
  rematch2::re_match("(?<A>[[:alnum:]]+)-(?<B>[[:alnum:]]+)") %>% 
  select(-starts_with("."))
df
#> # A tibble: 5 x 2
#>   x     m$A   $B   
#>   <chr> <chr> <chr>
#> 1 <NA>  <NA>  <NA> 
#> 2 a-b   a     b    
#> 3 a-d   a     d    
#> 4 b-c   b     c    
#> 5 d-e   d     e
```

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Can you imagine a case where the results went into rows?

``` r
library(tidyverse)

df <- tibble(id = 1:5, x = c(NA, "a-b", "a-d", "b-c", "d-e"))

df %>% 
  extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)") %>% 
  gather(,,-id)
#> # A tibble: 10 x 3
#>       id key   value
#>    <int> <chr> <chr>
#>  1     1 A     <NA> 
#>  2     2 A     a    
#>  3     3 A     a    
#>  4     4 A     b    
#>  5     5 A     d    
#>  6     1 B     <NA> 
#>  7     2 B     b    
#>  8     3 B     d    
#>  9     4 B     c    
#> 10     5 B     e
```

Or even into a list-col?

``` r
out <- df %>% 
  mutate(x = transpose(rematch2::re_match(x, "(?<A>[[:alnum:]]+)-(?<B>[[:alnum:]]+)")[1:2]))
out
#> # A tibble: 5 x 2
#>      id x         
#>   <int> <list>    
#> 1     1 <list [2]>
#> 2     2 <list [2]>
#> 3     3 <list [2]>
#> 4     4 <list [2]>
#> 5     5 <list [2]>
out$x[[2]]
#> $A
#> [1] "a"
#> 
#> $B
#> [1] "b"
```

**Comment by jennybc** [comment]
Yeah I guess it's all on the table and ends up being a question of which operations are common enough to package nicely vs. build as needed through composition.

**Comment by hadley** [comment]
Oh I think this will almost just work once we have [`morph()`](https://github.com/tidyverse/dplyr/issues/3721):

```R
df <- df %>% 
  morph(rematch2::re_match(x, "(?<A>[[:alnum:]]+)-(?<B>[[:alnum:]]+)")
```

We'd just need a thin wrapper around `re_match()` that dropped the `.` columns by default

**Comment by hadley** [comment]
I think this can now live in stringr — I think my vision is that `extract()`, `separate()` and `separate_rows()` will become less important because you'll be able to access their features with only slightly more complicated syntax that significantly increases your expressive power.

**Comment by clauswilke** [comment]
Thanks, I completely agree. I would always naturally look for these types of functions in stringr first and then get confused that they're not there.
