### ISSUE TITLE
Should gathering operation preserve groups?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/tidyr#550]
`tidyr::gather()` is the only verb in dplyr/tidyr that does not maintain groups in the output tibble. Perhaps its successor should keep them, here are some considerations:

- Duality of behaviour between grouped and non-grouped tibbles increases the usefulness of a single verb.

- Grouping variables often act as identifiers which are useful for further data manipulation.

- Consistently maintaining groups in all verbs makes the result more predictable.

- In general, it seems that consistently maintaining groups in reshaping functions, and excluding them in transformative functions (with implicit selections, erroring out otherwise) makes the components more easily composable for grouped tibbles (see for instance the rstudio::conf talk about passing dots to tidyverse components).

**Comment by lionel-** [comment]
A related issue is whether the `key` variable should automatically become a grouping variable. Once `gather()` / its successor gains support for df-cols, this would allows a neat pattern of repeated gathering because the key variables would be automatically maintained:

```r
spread
#> # A tibble: 1 x 2
#>   mean$mpg  $cyl $disp median$mpg  $cyl $disp
#>      <dbl> <dbl> <dbl>      <dbl> <dbl> <dbl>
#> 1     20.1  6.19  231.       19.2     6  196.

spread %>% gather("fn")
#> # A tibble: 2 x 4
#> # Groups:   fn [2]
#>   fn       mpg   cyl  disp
#>   <chr>  <dbl> <dbl> <dbl>
#> 1 mean    20.1  6.19  231.
#> 2 median  19.2  6     196.

spread %>% gather("fn") %>% gather("var")
#> # A tibble: 6 x 3
#> # Groups:   fn, var [6]
#>   fn     var    value
#>   <chr>  <chr>  <dbl>
#> 1 mean   mpg    20.1
#> 2 mean   cyl     6.19
#> 3 mean   disp  231.
#> 4 median mpg    19.2
#> 5 median cyl     6
#> 6 median disp  196.
```

**Comment by hadley** [comment]
Will implement for `pivot_longer()`/`pivot_wider()`

**Comment by hadley** [comment]
Regroup on intersection of grouping variables in input and columns in output.
