### ISSUE TITLE
Unexpected result calling `nest()` on `grouped_df` object, variable dropped but not nested

### ISSUE THREAD

**Issue by stufield** [tidyverse/tidyr#551]
Unexpected result when calling `nest()` on a `grouped_df` object **AND** passing a _different_ variable from the one used to generate the `grouped_df` object. 

The variable passed in the `nest()` call (`gear`) is dropped from the data (expected), but it is **not** part of the nesting in the output (unexpected).  The `gear` variable is absent from `data[[1]]`, but it is also absent from the `df`. See the `reprex` below. This could be related to #463, but I don't think so.

Perhaps separate branch is could resolve this conflict via splitting out a new `nest.grouped_df()` method?

``` r
library(magrittr)
library(tibble)
suppressMessages(library(tidyr))
suppressMessages(library(dplyr))
```

Assume you used dplyr::group\_by() upstream, forgot to
ungroup and then wanted to tidyr::nest() on `gear`:

``` r
df <- mtcars %>%
  as_tibble() %>%
  group_by(cyl) %>%
  nest(-gear)
df
#> # A tibble: 3 x 2
#>     cyl data             
#>   <dbl> <list>           
#> 1     6 <tibble [7 × 9]> 
#> 2     4 <tibble [11 × 9]>
#> 3     8 <tibble [14 × 9]>

"cyl" %in% names(df)
#> [1] TRUE
```

As expected, `gear` is dropped from the nested data frames under `data`:

``` r
names(df$data[[1]])   # no `gear` variable ... as expected
#> [1] "mpg"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "carb"
```

However, it is *not* part of the nesting structure of `df`:

``` r
"gear" %in% names(df)
#> [1] FALSE
```

I *think* this is what I would expect:

``` r
mtcars %>%
  as_tibble() %>%
  nest(-cyl, -gear)
#> # A tibble: 8 x 3
#>     cyl  gear data             
#>   <dbl> <dbl> <list>           
#> 1     6     4 <tibble [4 × 9]> 
#> 2     4     4 <tibble [8 × 9]> 
#> 3     6     3 <tibble [2 × 9]> 
#> 4     8     3 <tibble [12 × 9]>
#> 5     4     3 <tibble [1 × 9]> 
#> 6     4     5 <tibble [2 × 9]> 
#> 7     8     5 <tibble [2 × 9]> 
#> 8     6     5 <tibble [1 × 9]>
```

<sup>Created on 2019-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       macOS Mojave 10.14.3        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Denver              
#>  date     2019-02-10                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.0)
#>  backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.0)
#>  bindr         0.1.1   2018-03-13 [1] CRAN (R 3.5.0)
#>  bindrcpp    * 0.2.2   2018-03-29 [1] CRAN (R 3.5.0)
#>  callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.0)
#>  cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.0)
#>  devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.0)
#>  dplyr       * 0.7.8   2018-11-10 [1] CRAN (R 3.5.0)
#>  evaluate      0.12    2018-10-09 [1] CRAN (R 3.5.0)
#>  fansi         0.4.0   2018-10-05 [1] CRAN (R 3.5.0)
#>  fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.0)
#>  glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.0)
#>  highr         0.7     2018-06-09 [1] CRAN (R 3.5.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.0)
#>  knitr         1.21    2018-12-10 [1] CRAN (R 3.5.1)
#>  magrittr    * 1.5     2014-11-22 [1] CRAN (R 3.5.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.0)
#>  pillar        1.3.1   2018-12-15 [1] CRAN (R 3.5.0)
#>  pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.0)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.0)
#>  processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.0)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.0)
#>  purrr         0.3.0   2019-01-27 [1] CRAN (R 3.5.2)
#>  R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.0)
#>  Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.0)
#>  remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.0)
#>  rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.2)
#>  rmarkdown     1.11    2018-12-08 [1] CRAN (R 3.5.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.0)
#>  stringi       1.2.4   2018-07-20 [1] CRAN (R 3.5.0)
#>  stringr       1.3.1   2018-05-10 [1] CRAN (R 3.5.0)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.0)
#>  tibble      * 2.0.1   2019-01-12 [1] CRAN (R 3.5.2)
#>  tidyr       * 0.8.2   2018-10-28 [1] CRAN (R 3.5.0)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.0)
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.0)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 3.5.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.0)
#>  xfun          0.4     2018-10-23 [1] CRAN (R 3.5.0)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.0)
#> 
#> [1] /Users/sfield/r_libs
#> [2] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

**Comment by hadley** [comment]
Can you explain a bit more why you think this is different to #463?

The current behaviour is clearly wrong. But I'm not sure what should happen when you do `df %>% group_by(a) %>% nest(b)`. Who wins? Should it be an error if the nesting variables don't include the grouping variables?

**Comment by hadley** [comment]
I'm leaning towards explicit specification clobbering the defaults from grouping. I think that's easy to understand, especially with the new syntax.

**Comment by hadley** [comment]
Ah I've carefully re-read #463, and understand it better now, and it's indeed a different problem.

**Comment by stufield** [comment]
I think the behavior I was envisioning was not `a` or `b` winning, but nesting on both, i.e.

```
expect_equal(
  df %>% group_by(a) %>% nest(b),
  df %>% nest(-a, -b)
)
```

Which requires the user to know (and be aware of the implications), of nesting a `grouped_df` with a different grouping variable. As per your suggestion, I tend to favour explicit specification as it does require the user to act with intent. However, in this case they may not know they need to be explicit. Perhaps throw a warning explaining what's about to happen? Or if that's too permissive, as you initially suggest, throw an error and force the user either:

1. explicitly include *both* nesting variables
1. un-group the `df` prior to nesting (if that's the desired result)

What do you think?

**Comment by hadley** [comment]
It seems surprising to me that `nest(b)` becomes `nest(-b)` when applied to a grouped df?

**Comment by stufield** [comment]
That seems to be the case (tho admittedly it's the only behavior I've ever known):

```
identical(
  nest(group_by(mtcars, cyl)), 
  nest(mtcars, -cyl)
)
```

**Comment by hadley** [comment]
I think I'm most comfortable with only using the grouping vars — i.e. either you use `df %>% group_by(a, b) %>% nest()`, or you use `df %>% nest(-a, -b)`, you don't try to use both.

**Comment by stufield** [comment]
Should there perhaps be a warning to the user to notify them they're attempting to do something that's not recommended?

**Comment by hadley** [comment]
I'm assuming that if you deliberate set nesting variables you want to override the grouping variables. I think a warning here would cause frustration.

**Comment by stufield** [comment]
Sorry to drag this out :(, but current behavior does the opposite ... fails to override the grouping variable (`cyl`) with the nesting variable (`gear`). This seems to contradict the user's intent, no?

**Comment by hadley** [comment]
That’s not my understanding of the current behaviour, so could you please create a new issue with reprex?

**Comment by stufield** [comment]
Will do.
