### ISSUE TITLE
tidyr::nest() needs to learn about dplyr 0.8.0

### ISSUE THREAD

**Issue by pachamaltese** [tidyverse/tidyr#556]
As explained in https://github.com/cienciadedatos/r4ds/issues/68 and the references therein, installing the current `tidyverse` version from CRAN on a fresh R setup (i.e. building to gh-pages via Travis CI or just new laptop) breaks the code from the examples exposed in `model-many.Rmd` from R4DS 

The issue that I make reference to is from the spanish R4DS translation and its causes were very tricky to detect.

**Comment by lionel-** [comment]
🔥🥔
