### ISSUE TITLE
Vignette on turning implicit missingness into explicitness

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#560]
Using `expand()`, `crossing()` and `nesting()`.

**Comment by hadley** [comment]
The documentation for those functions also needs review.

**Comment by hadley** [comment]
And vice-versa, and why it matters.

**Comment by njtierney** [comment]
I explain implicit and explicit missings this when I teach `naniar`, I can have a crack at doing this if you like?

**Comment by hadley** [comment]
@njtierney yeah, that'd be awesome!

**Comment by njtierney** [comment]
OK no problems, do you have a time / date you'd like this done by?

**Comment by hadley** [comment]
No rush, but if you want to get it in the next release, a draft in 2-3 weeks would be about right.

**Comment by hadley** [comment]
Superseded by https://r4ds.hadley.nz/missing-values.html. Unlike pivoting, I don't think we'll need a separate vignette that goes into more detail.
