### ISSUE TITLE
Nesting tibbles after grouping by multiple factor variables produces NULL elements

### ISSUE THREAD

**Issue by eElor** [tidyverse/tidyr#563]
_Yesterday I submitted this by [stackoverflow](https://stackoverflow.com/questions/54928621/nesting-tibbles-after-grouping-by-factor-variables-produces-null-elements-in-r), but it might belong here as well:_

I was reviewing some of my old R code when I stumbled upon several errors.

After running each line and playing around with my data I discovered that `nest()`ing tibbles `dplyr::group`(ed)`_by` factor variables produced one or more `NULL` elements.

Here an example with the mtcars data:

```
library(dplyr)
library(tidyr)

mtcars %>% 
  as_tibble() %>% 
  select(cyl, carb, mpg) %>% 
  mutate(cyl = factor(cyl),
         carb = factor(carb)) %>% 
  group_by(cyl, carb) %>% 
  nest()

# A tibble: 9 x 3
# cyl   carb  data            
# <fct> <fct> <list>          
#   1 6     4     <NULL>          
#   2 4     1     <tibble [5 x 1]>
#   3 6     1     <tibble [3 x 1]>
#   4 8     2     <NULL>          
#   5 8     4     <NULL>          
#   6 4     2     <tibble [6 x 1]>
#   7 8     3     <NULL>          
#   8 6     6     <NULL>          
#   9 8     8     <NULL> 
```

I thought `nest()` is taking factors `as.numeric()` and "getting confused" when different variables present same-named groups. But then I tried:

```
mtcars %>% 
  as_tibble() %>% 
  select(cyl, carb, mpg) %>%  
  mutate(cyl = factor(cyl) %>% as.numeric(),
         carb = factor(carb) %>% as.numeric()) %>% 
  group_by(cyl, carb) %>% 
  nest()
```

and got the same result as when nesting with non-factorial variables:

```
# A tibble: 9 x 3
# cyl  carb data            
# <dbl> <dbl> <list>          
#   1     2     4 <tibble [4 x 1]>
#   2     1     1 <tibble [5 x 1]>
#   3     2     1 <tibble [2 x 1]>
#   4     3     2 <tibble [4 x 1]>
#   5     3     4 <tibble [6 x 1]>
#   6     1     2 <tibble [6 x 1]>
#   7     3     3 <tibble [3 x 1]>
#   8     2     5 <tibble [1 x 1]>
#   9     3     6 <tibble [1 x 1]>
```

Compare with:

```
mtcars %>% 
  as_tibble() %>% 
  select(cyl, carb, mpg) %>% 
  group_by(cyl, carb) %>% 
  nest()

# A tibble: 9 x 3
# cyl  carb data            
# <dbl> <dbl> <list>          
#   1     6     4 <tibble [4 x 1]>
#   2     4     1 <tibble [5 x 1]>
#   3     6     1 <tibble [2 x 1]>
#   4     8     2 <tibble [4 x 1]>
#   5     8     4 <tibble [6 x 1]>
#   6     4     2 <tibble [6 x 1]>
#   7     8     3 <tibble [3 x 1]>
#   8     6     6 <tibble [1 x 1]>
#   9     8     8 <tibble [1 x 1]>
```

Since my code used to work fine until last month, I wonder if `tidyr` was updated lately and the way of handling factor groups by `nest()` was changed?

Is it generally advisable not to nest data grouped by factor variables or rather not to `group_by()` on factor variables?

In the [issue ](https://github.com/tidyverse/tidyr/issues/554) mentioned by aosmith (stackoverflow), @hadley references to **`group_nest()`** which seems to resolve the problem (but it reorders the tibble!). Nevertheless, I still wonder why `nest()` is producing `NULL`...

```
mtcars %>% 
  as_tibble() %>% 
  select(cyl, carb, mpg) %>% 
  mutate(cyl = factor(cyl),
         carb = factor(carb)) %>% 
  group_by(cyl, carb) %>%
  group_nest() %>% 
  unnest %>% 
  all.equal(.,
            mtcars %>% 
              as_tibble() %>% 
              select(cyl, carb, mpg) %>% 
              mutate(cyl = factor(cyl),
                     carb = factor(carb)))

# [1] TRUE
```

**Comment by hadley** [comment]
Already fixed in the dev version, which is currently in the CRAN submission process.

**Comment by eElor** [comment]
thank you
