### ISSUE TITLE
Polish pivoting vignette

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#566]
`pivot_long()`:

* [ ] early example of `names_sep`
* [x] example of duplicated column names

`pivot_wide()`:

* [ ] needs a better description of how important matching is, and why thinking about the keys is often useful and example of using `keys`
* [x] example of generating a list-col, and how you might use `values_collapse`.
* [x] example of multiple `values_from`

**Comment by MilesMcBain** [comment]
Two things I noticed:

* https://github.com/tidyverse/tidyr/blob/master/vignettes/pivot.Rmd#L254: This was a bit jarring. I didn't know the default for `names_to` is `"name"` . I almost thought it was a typo for `.name`. It might help to show some intermediate output here.
* https://github.com/tidyverse/tidyr/blob/master/vignettes/pivot.Rmd#L279: What's going on with the `1`? Is that getting used as a `sep`? How does that work?

**Comment by hadley** [comment]
@MilesMcBain I think I'm missing another spec function that makes dealing with multivalue data more straightforward. When I split the spec into a line for each step and attempt to explain what's happening, it doesn't feel very compelling. (FYI `separate()` can take a vector of integers to separate by position rather than splitting by a regexp)

**Comment by hadley** [comment]
See discussion in #586.

**Comment by hadley** [comment]
Ok, new `names_sep` argument makes the multi-value code much simpler. But now we need a simpler example of `names_sep` much earlier. And can probably reconsider the introduction of the spec, since it's now needed for many fewer cases.
