### ISSUE TITLE
Ensure pivot_wide() with multiple values has correct column order

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#569]
``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)
input <- tribble(
  ~hw,   ~name,  ~mark,   ~pr,
  "hw1", "anna",    95,  "ok",
  "hw1", "alan",    90, "meh",
  "hw1", "carl",    85,  "ok",
  "hw2", "alan",    70, "meh",
  "hw2", "carl",    80,  "ok"
)

spec <- input %>% 
  expand(hw, .value = c("mark", "pr")) %>% 
  mutate(
    .name = paste0(hw, "_", .value)
  )


input %>% pivot_wide(spec = spec) %>% names()
#> [1] "name"     "hw1_mark" "hw2_mark" "hw1_pr"   "hw2_pr"
spec$.name
#> [1] "hw1_mark" "hw1_pr"   "hw2_mark" "hw2_pr"
```

<sup>Created on 2019-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by jackdolgin** [comment]
I'm not sure if this question is exactly addressing this closed issue, but is it possible to specify the order of the names_from column's values; i.e. I might want the created columns to go from left to right in alphabetical order, but pivot_wide I believe orders based on the row order of the names_from column; I could always arrange alphabetically and then pivot_wide, but was wondering if I can do both inside the pivot_wide function.
