### ISSUE TITLE
Name repair for pivot_long()/pivot_wide()

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#571]
Need `name_repair` argument that defaults to `check_unique`

**Comment by hadley** [comment]
Waiting for https://github.com/r-lib/vctrs/issues/227

**Comment by hadley** [comment]
Note that `pivot_long()` needs to be able to take input with duplicated column names: https://github.com/tidyverse/tidyr/issues/472.

**Comment by castobary** [comment]
Hello!
I have installed `tidyr` package
I'm trying to call the function `pivot_long()`, it's not working

Error in `pivot_long()` : could not find function "pivot_long"

what can I do?

**Comment by batpigandme** [comment]
You need to have the development version installed. 
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
