### ISSUE TITLE
V1 column when spread() key contains an empty string

### ISSUE THREAD

**Issue by trannhatanh89** [tidyverse/tidyr#578]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
I believe this is not a bug. I found that when there is an empty string in the key column, `spread` will create a column named "V1". However, there is no warning when this happens, and if a person does not know about this behavior, they may have to spend a lot of time troubleshooting, especially with a big dataset. (I just did, when working with a big genomic dataset containing one un-annotated gene. I thought a NA or duplicate caused it.) May you consider adding a warning when this happens, please?

```r
tb <- tibble::tibble(key = c("A", "B", "C", ""),
             value = c(1, 2, 3, 4),
             other = c("w", "x", "y", "z"))
print(tb)
#> # A tibble: 4 x 3
#>   key   value other
#>   <chr> <dbl> <chr>
#> 1 A         1 w    
#> 2 B         2 x    
#> 3 C         3 y    
#> 4 ""        4 z
tidyr::spread(tb, key = key, value = value)
#> # A tibble: 4 x 5
#>   other    V1     A     B     C
#>   <chr> <dbl> <dbl> <dbl> <dbl>
#> 1 w        NA     1    NA    NA
#> 2 x        NA    NA     2    NA
#> 3 y        NA    NA    NA     3
#> 4 z         4    NA    NA    NA
```

**Comment by hadley** [comment]
This is fixed in `pivot_long()`:

``` r
tb <- tibble::tibble(
  key = c("A", "B", "C", ""),
  value = c(1, 2, 3, 4),
  other = c("w", "x", "y", "z")
)

tidyr::pivot_wide(tb, names_from = key, values_from = value)
#> Error: Column 4 must be named.
#> Use .name_repair to specify repair.
```

<sup>Created on 2019-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

More discussion about interface will happen in #571

**Comment by trannhatanh89** [comment]
Thank you. Now I learn that the feature is called "name repair".
