### ISSUE TITLE
Consider pivot_longer() and pivot_wider() as function names

### ISSUE THREAD

**Issue by enricoferrero** [tidyverse/tidyr#579]
Perhaps you can consider pivot_longer() and pivot_wider() as alternative names for the two new functions pivot_long() and pivot_wide().

The advantage of the *er names is that they would express more clearly that the functions make the data longer and wider, respectively.

Currently, with e.g. pivot_long() I have to stop and think: is this for long data or to make data long?

**Comment by duttashi** [comment]
I do not see how changing the existing nomenclature makes any difference. If this is the case, then I can very well argue that `pivot_long()` or `pivot_wide()` are essentially methods. And a method in its fundamental sense is supposed to do something. And if the reader is confused, they can always look at the package vignette.

**Comment by hadley** [comment]
I agree that the extra "er" makes it very clear that function names describe the transformation, not the input. One or two extra letters are a small cost to pay for this nicety, especially given that you generally won't have to type them because of auto-complete.

**Comment by akruchte** [comment]
Another alternative set of names possibly worth consideration would be lengthen() / widen(). These are quite a bit shorter than the pivot names and still very clear to me at least. Lengthen might be problematic with the similarity to length though.

**Comment by gvelasq** [comment]
I would suggest keeping `pivot_long()` and `pivot_wide()` unchanged.

The `_long` and `_wide` suffixes are also being considered for directional variants of `unnest()` in #418. It would be optimal to use the same suffixes for both sets of functions. In the context of `unnest()` it seems to me that `unnest_longer()` and `unnest_wider()` would be somewhat confusing compared to the proposed `unnest_long()` and [`unnest_wide()`](https://github.com/ivelasq/wizehiver/blob/master/R/unnest_wide.R). The use of `long` and `wide` also has a precedent in [Stata](https://www.stata.com/support/faqs/data-management/reshape-command/), where the analogous functions have been `reshape long` and `reshape wide` for two decades.

`pivot_long()` and `pivot_wide()` would have immediate appeal to those with experience in Excel (`pivot_*`) and Stata (`_long`/`_wide`). If other verbs besides `pivot` are being considered, two that would appeal to R users would be:

1. `reshape_long()` / `reshape_wide()` (at the risk of being too similar to Stata)
2. `cast_long()` / `cast_wide()`

**Comment by hadley** [comment]
`unnest_longer()` and `unnest_wider()` both make sense to me. `lengthen()` and `widen()` would be ok by themselves, but don't connect to the `unnest()` case.

I think `reshape_` is unsuitable as a prefix as it will be too confusing with `reshape()`, and I don't think `cast_` is evocative enough to be worth considering. 

Thanks for all the feedback!
