### ISSUE TITLE
Consider argument order in pivot_wide()

### ISSUE THREAD

**Issue by mikmart** [tidyverse/tidyr#582]
Currently the `keys` argument to `pivot_wide()` takes up the "prime" argument spot as the first argument specified when the function is called after a pipe. As a result, `names_from` and `values_from` (which are virtually always needed) must always be explicitly named; this can be helpful for educational purposes but I suspect will quickly become a hindrance for an experienced user.

`keys` is currently not mentioned in [the vignette](https://tidyr.tidyverse.org/dev/articles/pivot.html) (as noted in #566), and was not even present in the predecessor function `spread()`. Considering this, I would assume that it won't be commonly used, and as such placing it as the primary argument to `pivot_wide()` seems unwarranted.

Moving `keys` to come after `names_from` and `values_from` would place commonly used parameters at better positions, and for simple use cases make `pivot_wide()` a drop-in replacement for `spread()`:

```r
# I would like to be able to just write
fish_encounters %>% 
  pivot_wide(station, seen)

# ... and get the behaviour of
fish_encounters %>% 
  spread(station, seen)
```

**Comment by hadley** [comment]
I think the succinctness of `spread()` here is not a feature, and always naming the arguments is to be preferred. I am leaving this open because I'm considering adding `...` to the function specifically for the purposes of forcing full names for all the arguments.

**Comment by mikmart** [comment]
Alright. I tend to find that once I have the behaviour of a function internalized, having to type out the names of the first 1-2 arguments only serves to increase the thought-to-code time, creating more friction in the coding process; but keeping in mind recent discussions on issues with `spread()`/`gather()` arguments I can see the point for forced names, too.

In the defense of allowing unnamed arguments, I can only suggest that perhaps the `key`/`value` argument naming in `spread()` wasn't intuitive and as such writing out `spread(key = foo, value = bar)` didn't really improve the situation; but with `pivot_wide()`'s more descriptive argument names both auto-complete and optionally writing out the names could go a long way to making the function easier to use, while still allowing succinct code for those who prefer it.

**Comment by hadley** [comment]
I think the main problem is that it's a relatively weak association that column names should come before cell values.

**Comment by hadley** [comment]
Currently `pivot_wide()` looks like this:

```R
pivot_wider <- function(df,
                       keys = NULL,
                       names_from = name,
                       values_from = value,
                       names_prefix = "",
                       names_sep = "_",
                       values_fill = NULL,
                       values_collapse = NULL,
                       spec = NULL) {
}
```

I wonder if it would be more natural to group all names and values arguments together, to give:

```R
pivot_wider <- function(df,
                       keys = NULL,
                       names_from = name,
                       names_prefix = "",
                       names_sep = "_",
                       values_from = value,
                       values_fill = NULL,
                       values_collapse = NULL,
                       spec = NULL) {
}
```

This would remove all hope of positional matching, but it makes the argument list easier to understand IMO. @mikmart, as a lover of positional matching 😄 what do you think of this reasoning?

**Comment by mikmart** [comment]
Based on discussion in #586 I think the latter is certainly the more natural grouping when thinking about even slightly more complex pivot specs.

I still think it's a shame for the simple case, but to be honest, since `spread()` is going to stick around anyway that can be the way to do the quick-and-dirty, positional matching simple reshape.

**Comment by mikmart** [comment]
That said, would you reconsider making `spread()` have a consistent row order (discussed in #453)? 

Currently if you care about the row order `spread()` must always be followed by `arrange()` if the number of possible combinations of values of the row identifiers can vary.

**Comment by hadley** [comment]
@mikmart I wish I could, but my experience is that people tend to depend on row order in surprising ways, so any change is likely to be backward incompatible (and the whole point of the new functions is to avoid backward incompatible changes)

**Comment by mikmart** [comment]
Alright, understood!
