### ISSUE TITLE
spread maybe has a bug 

### ISSUE THREAD

**Issue by wulixin** [tidyverse/tidyr#584]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
> stocks <- data.frame(
+   time = as.Date('2009-01-01') + 0:9,
+   X = rnorm(10, 0, 1),
+   Y = rnorm(10, 0, 2),
+   Z = rnorm(10, 0, 4)
+ )
> stocks
         time          X          Y         Z
1  2009-01-01 -0.4545060  2.1050124  1.076616
2  2009-01-02  1.0298911  0.5081425 -4.560988
3  2009-01-03  0.5318201  2.5830543 -1.164639
4  2009-01-04  1.4276927 -2.1041378 -9.936661
5  2009-01-05  0.3193185 -0.6793617  3.058740
6  2009-01-06 -0.4518234 -2.2737251  5.355483
7  2009-01-07  0.3244748 -0.7545446 -3.582594
8  2009-01-08 -0.3781826 -0.5399882 -2.373769
9  2009-01-09  1.2116687 -0.7371234  2.808421
10 2009-01-10 -0.3754020  2.2082233  4.304402
> stocksm <- stocks %>% gather(stock, price, -time)
> stocksm
         time stock      price
1  2009-01-01     X -0.4545060
2  2009-01-02     X  1.0298911
3  2009-01-03     X  0.5318201
4  2009-01-04     X  1.4276927
5  2009-01-05     X  0.3193185
6  2009-01-06     X -0.4518234
7  2009-01-07     X  0.3244748
8  2009-01-08     X -0.3781826
9  2009-01-09     X  1.2116687
10 2009-01-10     X -0.3754020
11 2009-01-01     Y  2.1050124
12 2009-01-02     Y  0.5081425
13 2009-01-03     Y  2.5830543
14 2009-01-04     Y -2.1041378
15 2009-01-05     Y -0.6793617
16 2009-01-06     Y -2.2737251
17 2009-01-07     Y -0.7545446
18 2009-01-08     Y -0.5399882
19 2009-01-09     Y -0.7371234
20 2009-01-10     Y  2.2082233
21 2009-01-01     Z  1.0766161
22 2009-01-02     Z -4.5609881
23 2009-01-03     Z -1.1646392
24 2009-01-04     Z -9.9366614
25 2009-01-05     Z  3.0587400
26 2009-01-06     Z  5.3554831
27 2009-01-07     Z -3.5825940
28 2009-01-08     Z -2.3737693
29 2009-01-09     Z  2.8084214
30 2009-01-10     Z  4.3044020
> stocksm %>% spread(stock, price)
Error in synthetic.instrument(primary_id = primary_id, currency = currency,  : 
  object 'price' not found
#that I tidy other data also has this problem.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by Zedseayou** [comment]
I can't reproduce this:



    library(tidyr)

    stocks <- data.frame(
      time = as.Date('2009-01-01') + 0:9,
      X = rnorm(10, 0, 1),
      Y = rnorm(10, 0, 2),
      Z = rnorm(10, 0, 4)
    )

    stocksm <- stocks %>% gather(stock, price, -time)
    stocksm %>% spread(stock, price)
    #>          time          X          Y          Z
    #> 1  2009-01-01  0.7546124 -1.7562835 -1.5311400
    #> 2  2009-01-02 -1.0945458  2.5403986  2.2665297
    #> 3  2009-01-03  0.9223195  3.4876179  1.1012539
    #> 4  2009-01-04  1.6570021  2.0620447 -0.6354323
    #> 5  2009-01-05  0.8853738 -0.5533283 -7.1345170
    #> 6  2009-01-06  0.2135895 -0.1801193  5.7532033
    #> 7  2009-01-07 -0.5482357  2.6733594  4.8810415
    #> 8  2009-01-08  0.3795339 -0.3704957  5.1011669
    #> 9  2009-01-09  1.5656029  1.1638675  2.9434247
    #> 10 2009-01-10  0.4106435  1.6134500 -7.6977539

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
A careful reading of the error message leads me to suspect that the author is actually calling `FinancialInstrument::spread()`

**Comment by wulixin** [comment]
Thanks, that maybe I loaded dplyr and FinancialInstrument packages at the same time .
