### ISSUE TITLE
Allow multiple value_from cols in pivot_wide()

### ISSUE THREAD

**Issue by mikmart** [tidyverse/tidyr#586]
In the spirit of \#149, could `pivot_wide()`’s `values_from` support selecting multiple columns?

Specifically, if `values_from` has more than one column, the names given by the `names_from` columns could additionally be suffixed with the names of the `values_from` columns (similar to how scoped dplyr verbs suffix variable names with function names, if given multiple variables and functions simultaneously). This would allow behaviour similar to using data.table’s `dcast()` with multiple `value.var`’s.

``` r
library(dplyr)
library(tidyr)
library(data.table)

# a common use case would be to format summary statistics
long_table <- survival::transplant %>% 
  group_by(sex) %>% 
  count(abo) %>% 
  mutate(pct = n / sum(n) * 100) %>% 
  ungroup()

# hmm.. I'd like to have the stats by sex side-by-side
long_table
#> # A tibble: 8 x 4
#>   sex   abo       n   pct
#>   <fct> <fct> <int> <dbl>
#> 1 m     A       185 41.4 
#> 2 m     B        51 11.4 
#> 3 m     AB       24  5.37
#> 4 m     O       187 41.8 
#> 5 f     A       140 38.0 
#> 6 f     B        52 14.1 
#> 7 f     AB       17  4.62
#> 8 f     O       159 43.2

# can get the desired shape but suboptimal new column names with dcast
dcast(setDT(long_table), ... ~ sex, value.var = c("n", "pct"))
#>    abo n_m n_f     pct_m     pct_f
#> 1:   A 185 140 41.387025 38.043478
#> 2:   B  51  52 11.409396 14.130435
#> 3:  AB  24  17  5.369128  4.619565
#> 4:   O 187 159 41.834452 43.206522

# the same with `pivot_wide()` requires a manual spec
long_table %>% 
  expand(sex, .value = c("n", "pct")) %>% 
  mutate(.name = paste(sex, .value, sep = "_")) %>% 
  pivot_wide(long_table, spec = .)
#> # A tibble: 4 x 5
#>   abo     m_n m_pct   f_n f_pct
#>   <fct> <int> <dbl> <int> <dbl>
#> 1 A       185 41.4    140 38.0 
#> 2 B        51 11.4     52 14.1 
#> 3 AB       24  5.37    17  4.62
#> 4 O       187 41.8    159 43.2
```

While creating a manual spec for `pivot_wide()` to achieve this is not complicated (and is more flexible), when trying out different `names_from` columns, the extra lines of code and variable name duplication add up quickly; this shows especially when doing quick ad-hoc analyses and looking to just glance at the summary statistics in a neater format.

``` r
# if `values_from` could take multiple columns, the above would simplify to:
pivot_wide(long_table, names_from = sex, values_from = c(n, pct))

# and a different `names_from` only requires 1 more line
pivot_wide(long_table, names_from = abo, values_from = c(n, pct))
```

The fairly hefty downside with this approach would be that if using multiple `values_from` columns, the new column names would no longer only depend on the `names_from` argument. I would argue that the added flexibility outweighs this, though.

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Oh I see - if there are multiple `values_from` columns, you append those names to `col_names`. That seems like it should be straightforward to implement.

But doesn't that imply that `pivot_long()` also needs a more flexible specification in order to continue to be symmetric?

**Comment by mikmart** [comment]
Yeah it does feel like that's the implication. However, I'm having a much harder time thinking about what the parameterization should look like for `pivot_long()`.

I think part of the problem is that with `pivot_wide()` we are creating new columns with a very regular structure; but with `pivot_long()` we need to parse the new structure from the existing, potentially very irregular column names, which is where the manual specs come in extremely handy.

**Comment by mikmart** [comment]
Here’s my motivating example for thinking about what the symmetry would look like for `pivot_long()`. I’m still thinking about this but thought I’d share my reference point.

Say we have data on start and end dates of study periods for people:

``` r
library(dplyr)
library(tidyr)

# typical clinical trial data format
df <- tibble::tribble(
  ~person, ~p1_start_date, ~p1_end_date, ~p2_start_date, ~p2_end_date,
  1,   "2019-02-28", "2019-03-07", "2019-03-10", "2019-03-19",
  2,   "2019-03-09", "2019-03-15", "2019-03-20", NA,
) %>% mutate_if(is.character, as.Date)

df
#> # A tibble: 2 x 5
#>   person p1_start_date p1_end_date p2_start_date p2_end_date
#>    <dbl> <date>        <date>      <date>        <date>     
#> 1      1 2019-02-28    2019-03-07  2019-03-10    2019-03-19 
#> 2      2 2019-03-09    2019-03-15  2019-03-20    NA
```

In order to work with these data, it can be useful to have period as a column:

``` r
spec <- pivot_long_spec(df, cols = -person) %>% 
  extract(name, into = c("period", ".value"), "p(.)_(.+)", convert = TRUE)

want <- df %>% 
  pivot_long(spec = spec)

want
#> # A tibble: 4 x 4
#>   person period end_date   start_date
#>    <dbl>  <int> <date>     <date>    
#> 1      1      1 2019-03-07 2019-02-28
#> 2      1      2 2019-03-19 2019-03-10
#> 3      2      1 2019-03-15 2019-03-09
#> 4      2      2 NA         2019-03-20
```

Now, we could use the proposed multiple `values_from` to easily reshape `want` to `df`:

``` r
want %>% 
  pivot_wide(
    names_from = period,
    names_prefix = "p",
    values_from = c(start_date, end_date)
  )
```

Does this imply that there should be a simple way to `pivot_long()` from `df` to `want`, too? What would that look like?

``` r
df %>% 
  pivot_long(
    cols = -person,
    names_to = ...,
    values_to = ...
  )
```

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mikmart** [comment]
One option could be to directly mirror the `pivot_wide()` parameters; but I’m not sure it would be clear what these parameter values do if you’re not specifically thinking about this from the point of view of the inverse transform of a `pivot_wide()`... :thinking:

``` r
df %>% 
  pivot_long(
    cols = -person,
    names_to = "period",
    names_prefix = "p",
    names_sep = "_", # split by this into length(names_to) + 1 parts
    values_to = NULL # as in "taken from suffix"
  )
```

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
I like that proposal, but I think in general, you'd need `names_to` to be a vector, with some sentinel to indicate that it gives the name of a value:

```R
df %>% 
  pivot_long(
    cols = -person,
    names_to = c("period", ".value"),
    names_prefix = "p", # remove this prefix from the col names
    names_sep = "_", # split by this into length(names_to) + 1 parts
  )
```

(if `.values` occurred in `names_to` then `values_to` would be automatically be set to `NULL`)

And maybe `names_sep` could be passed to `separate()` so you could still provide an integer specification. Then you'd only need the manual spec if you needed `extract()`. Should `names_prefix` be a regular expression?

Then (ignoring the type transformations and other minor fixes) the multiple value column examples in the vignette would become:

```R
family %>%
  pivot_long(-family, names_to = c(".value", "child"), names_sep = "_")

anscombe %>% 
  pivot_long(names_to = c(".value", "graph"), names_sep = 1)

pnl %>%
  pivot_long(-(x:b), names_to = c(".value", "time"), names_sep = 1)
```

That seems pretty compelling to me.

**Comment by hadley** [comment]
Oh and it means you can solve the billboard reshaping in a single call:

```R
billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    names_prefix = "wk",
    values_to = "rank",
    ptype = list(rank = integer())
  )
```

**Comment by hadley** [comment]
Oh and `ptype` should be `values_type`

**Comment by hadley** [comment]
This was very straightforward to implement, and considerably improves the expressiveness of `pivot_longer()`. Thanks for the idea @mikmart!

**Comment by hadley** [comment]
Whoops, haven't fixed the motivating issue yet.

**Comment by mikmart** [comment]
This looks great! The addition of the `".value"` sentinel was definitely the piece to make it work.

**Comment by mikmart** [comment]
By the way, now that `names_sep` essentially powers the `separate()`-based spec workflow, perhaps we could also just add `names_pattern` (or `names_regex`?) to support the `extract()` route as well?

Then `names_prefix` would be a special case and could probably be dropped:
```r
billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    names_pattern = "wk(.+)",
    values_to = "rank",
    values_type = list(rank = integer())
  )

who %>% 
  pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = c("diagnosis", "gender", "age"),
    names_pattern = "new_?(.*)_(.)(.*)",
    values_to = "count"
  )

```

**Comment by hadley** [comment]
I was actually wondering about a new `separate()` specification so that you could do `names_prefix = "new_?", names_sep = c("_". 1)` — that would peel off the piece up to `_`, then a single character.

**Comment by hadley** [comment]
For the motivating `pivot_wider()` issue, are you sure the value names should go at the end and not at the beginning? All the examples in the vignette have the value names first.

**Comment by mikmart** [comment]
Personally whenever I've wanted to have multiple value columns I've wanted them to come last, essentially preserving the little grouped data rectangles from the long form in the wide form. But this comes from mostly formatting summary statistics by group in a table, so it may not generalize to other use-cases.

**Comment by mikmart** [comment]
Perhaps `pivot_wider()` could also have some way of specifying where the value names should go, mirroring the `.value` sentinel in `pivot_longer()`?

```r
us_rent_income %>% 
  pivot_wider(
    names_from = c(variable, .value),
    values_from = c(estimate, moe)
  )

us_rent_income %>% 
  pivot_wider(
    names_from = c(.value, variable),
    values_from = c(estimate, moe)
  )
```

**Comment by hadley** [comment]
@mikmart I'm going to this this issue since the original problem is fixed, and it's getting long and hard for me to follow. Can you please move anything I haven't yet implemented into new issues?

**Comment by mikmart** [comment]
Okay, will do!
