### ISSUE TITLE
Cannot load version wih pivot commands

### ISSUE THREAD

**Issue by KenatRSF** [tidyverse/tidyr#590]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Neither Update tidyr nor Install package from RStudio will load version with pivot commands. I am using R3.5.3. ?? pivot_wide gives "No results found"

```r
# insert reprex here
```

**Comment by batpigandme** [comment]
This is because it's only in the development version on GitHub, as they're still experimental. See the README for instructions on installing with devtools.
