### ISSUE TITLE
Parsing new columns from old column names in pivot_longer()

### ISSUE THREAD

**Issue by mikmart** [tidyverse/tidyr#594]
https://github.com/tidyverse/tidyr/commit/3268807babf9a545cad1560003cab0160d939004 added a `names_sep` argument to `pivot_longer()` to make it easier to support `separate()` based spec construction (https://github.com/tidyverse/tidyr/issues/586#issuecomment-475364183).

For even further added flexibility, it would be nice to have a `names_pattern`/`names_regex` argument to support `extract()` based spec construction:

```r
who %>% 
  pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = c("diagnosis", "gender", "age"),
    names_pattern = "new_?(.*)_(.)(.*)",
    values_to = "count"
  )
```

An alternative (or additional?) improvement could be a vector `names_sep` that can specify splitting by both separators and positions (https://github.com/tidyverse/tidyr/issues/586#issuecomment-475598589).

**Comment by mikmart** [comment]
Something I just realized is that `names_pattern` could be used both for selecting the columns that match it as `cols` and parsing the new `names_to` columns from the capture groups.

If both `cols` and `names_pattern` are given the resulting column selection should probably either be the intersection of the matched columns and `cols` or only use the given `cols`.

**Comment by mikmart** [comment]
If there was also some way to specify the types of the `names_to` columns, in combination with #593, I'm having a very hard time of thinking of a situation where I would need to use a pivot spec directly.

One option could be to include the prototype in `names_to`:
```r
billboard %>% 
  pivot_longer(
    names_pattern = "wk(.+)",
    names_to = c(week = integer()), 
    values_to = "rank",
    values_type = list(rank = integer())
  )
```

?Or even?:
```r
billboard %>% 
  pivot_longer(
    names_pattern = "wk(.+)",
    names_to = c(week = integer()), 
    values_to = c(rank = integer())
  )
```

**Comment by jestarr** [comment]
Something like this could be helpful.  Some of my column names are described in the prefix before an `"_",` and I currently have been using `str_extract` in a `mutate` to fix them.

**Comment by hadley** [comment]
I'm not sure about `names_pattern`. Using it as an alternative to `cols` seems like a cool idea, but it means that `cols` is no longer required, which seems potentially confusing (or at least hard to explain in the docs). But even without that behaviour, it seems useful as a way of avoiding `extract()`, and hence doing.

The only problem with `col_ptypes()` is that it wouldn't have the same names as the columns in `cols`. Is that confusing?

**Comment by hadley** [comment]
Maybe `cols` could default to `everything()`?

**Comment by mikmart** [comment]
Yeah I think `everything()` makes sense as a default for `cols`.

Do you think it would be straightforward enough to say if both `cols` and `names_pattern` are supplied, the intersection of the two is taken as the selection? That would work directly with an `everything()` default.

**Comment by mikmart** [comment]
A regex to parse the names has the benefit that when **stringi** gets named capture groups it could potentially be expanded to cover 3 roles: column selection depending on the match, column parsing by capture group, and column naming with the name of the group.

**Comment by hadley** [comment]
Type discussion moved to #600

**Comment by hadley** [comment]
@mikmart I'll keep thinking about it, but your suggestion feels a bit too flexible to me, and would require a bunch of careful error handling to consider various unexpected interactions. For example, what happens if the intersection of `everything()` and `names_pattern` is nothing? What if the user manually supplied `cols` and it doesn't match? What if they supply `names_to` and `names_pattern` has named groups? Generally, I think it's a bad idea to have this level of complex interaction between function arguments.
