### ISSUE TITLE
Linking between pivot_* docs and gather/spread docs

### ISSUE THREAD

**Issue by martinjhnhadley** [tidyverse/tidyr#596]
The new `pivot_*` functions solve a clear need. Both in providing advanced features to `tidyr` and hopefully in simplifying folks' workflows. However, IMO it's important that users do not feel overwhelmed or that the existing functions will be deprecated. 

In particular, I think the following should be communicated to users:

- We acknowledge folks found `spread`/`gather` difficult to memorise and use, as mentioned in the vignette.
- We assure users that `spread`/`gather` are not going to be deprecated. They do not need to use the new `pivot_*`
- We tell users that new things are possible with the `pivot_*` functions
- We tell new users who meet `pivot_*` first that `spread`/`gather` exist, to reduce confusion when reading old SO answers etc.
- We provide more examples real dataset examples of how to switch between `spread`/`gather` and the `pivot_*` functions.

Here are places where I think that we need to add notes or examples, there might be more I've not considered.

- `spread`/`gather` docs pages
- `pivot_*` docs pages

**Comment by hadley** [comment]
Would you be interested in contributing something to the pivot vignette too? I was thinking maybe a spread/gather vs pivot_long/pivot_wide section at the end. (I don't think it belongs at the start, because enough people found spread/gather confusing that it's not the right place to start the description)

**Comment by martinjhnhadley** [comment]
I’ll happily make some suggestions for the vignette. I agree it’s a necessary thing, and definitely doesn’t belong at the beginning of the document.
