### ISSUE TITLE
Add hint about where to get CSVs used in Pivoting vignette

### ISSUE THREAD

**Issue by cwickham** [tidyverse/tidyr#605]
`pew.csv` and `billboard.csv` are used in the Pivoting vignette without any hints on where to find them if you want to follow along.  

Could they be moved somewhere that will get installed with the package?  Or can you add a link about where to find them on GitHub?

I guess this is also true of the Tidy Data vignette.

**Comment by hadley** [comment]
I think I'll just turn them into package datasets
