### ISSUE TITLE
".value" always need to come first in names_to? 

### ISSUE THREAD

**Issue by kuriwaki** [tidyverse/tidyr#607]
The new pivot functions are amazing. One issue - In the multiple observations per row case, does the special variable `".value"` always have to come first as in the code and datasets in the vignette?

Here is an example with two datasets; only the variable naming conventions are different. My own dataset is in the second case, but I want output that looks like the output of `pivot_longer` in the first case with my existing dataset.  I thought I could simply swap the content of the `name_to` vector and get the same output, but it seems not (and I couldn't find this documented).

``` r

library(tibble)
library(tidyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# data
samp <- tibble(
  i = 1:4,
  y_t1 = rnorm(4),
  y_t2 = rnorm(4),
  z_t1 = rep(3, 4),
  z_t2 = rep(-2, 4),
)
samp
#> # A tibble: 4 x 5
#>       i   y_t1   y_t2  z_t1  z_t2
#>   <int>  <dbl>  <dbl> <dbl> <dbl>
#> 1     1 -0.702 -0.315     3    -2
#> 2     2  0.196  0.156     3    -2
#> 3     3  0.777 -1.64      3    -2
#> 4     4  1.06  -0.185     3    -2

# pivot - expected behavior
pivot_longer(samp, -i, names_to = c(".value", "time"), names_sep = "_")
#> # A tibble: 8 x 4
#>       i time       y     z
#>   <int> <chr>  <dbl> <dbl>
#> 1     1 t1    -0.702     3
#> 2     1 t2    -0.315    -2
#> 3     2 t1     0.196     3
#> 4     2 t2     0.156    -2
#> 5     3 t1     0.777     3
#> 6     3 t2    -1.64     -2
#> 7     4 t1     1.06      3
#> 8     4 t2    -0.185    -2


# sometimes variables are named like this
samp2 <- samp %>% 
  rename(t1_y = y_t1, t2_y = y_t2, t1_z = z_t1, t2_z = z_t2)

# why can't this recover the  same output as the first pivot?
pivot_longer(samp2, -i, names_to = c("time", ".value"), names_sep = "_")
#> # A tibble: 8 x 4
#>       i .value       y     z
#>   <int> <chr>    <dbl> <dbl>
#> 1     1 y       -0.315    NA
#> 2     1 z       NA        -2
#> 3     2 y        0.156    NA
#> 4     2 z       NA        -2
#> 5     3 y       -1.64     NA
#> 6     3 z       NA        -2
#> 7     4 y       -0.185    NA
#> 8     4 z       NA        -2
```

<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Hmmm weird, definitely a bug!

**Comment by romatik** [comment]
@kuriwaki, why do you need `samp2`? The bug happens with just changing the order in `names_to`:
``` r
library(tibble)
library(tidyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# data
samp <- tibble(
  i = 1:4,
  y_t1 = rnorm(4),
  y_t2 = rnorm(4),
  z_t1 = rep(3, 4),
  z_t2 = rep(-2, 4),
)

# pivot - expected behavior
pivot_longer(samp, -i, names_to = c(".value", "time"), names_sep = "_")
#> # A tibble: 8 x 4
#>       i time       y     z
#>   <int> <chr>  <dbl> <dbl>
#> 1     1 t1     0.306     3
#> 2     1 t2    -0.215    -2
#> 3     2 t1     1.27      3
#> 4     2 t2     0.601    -2
#> 5     3 t1     0.903     3
#> 6     3 t2    -1.99     -2
#> 7     4 t1    -0.512     3
#> 8     4 t2     0.777    -2
pivot_longer(samp, -i, names_to = c("time", ".value"), names_sep = "_")
#> # A tibble: 8 x 4
#>       i .value    t1    t2
#>   <int> <chr>  <dbl> <dbl>
#> 1     1 t1         3    NA
#> 2     1 t2        NA    -2
#> 3     2 t1         3    NA
#> 4     2 t2        NA    -2
#> 5     3 t1         3    NA
#> 6     3 t2        NA    -2
#> 7     4 t1         3    NA
#> 8     4 t2        NA    -2
```

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kuriwaki** [comment]
@romatik , I thought that was expected behavior; I surmised that the order of the `names_to` vector determines what side of the `"_"` stays as multiple columns and which gets spread out into a new column. I read `names_to = c(".value", "time"), names_sep = "_")` to mean that the _left_ handside of "\_"  should become kept in multiple columns and the _right_ handside of "\_" to be spread out into a new column (which we will name "time").   But I may have misunderstood the intent.

The reason I'm bringing up the naming convention of `samp2` as an example is because that's how my data is, and therefore how I noticed the issue in the first place.

**Comment by romatik** [comment]
OK, after second look I see your point. 
I do believe your understanding of how `.value` works is correct, but I also think think that my example shows the same buggy behaviour as your example with `samp2`. 

In other words, the correct behaviour in my second example is to have three columns: "time", "t1" and "t2". "time" column should have "x" and "y" in it and both "t1" and "t2" shouldn't have `NA`'s in them.

I'll take a closer look at the code of `pivot_longer` as I have a strong suspicion where this error is coming from.
