### ISSUE TITLE
can't install any tidyverse

### ISSUE THREAD

**Issue by mkapplebee** [tidyverse/tidyr#609]
I am at a complete standstill because as part of updating to a new version of R, I have gotten stuck trying to re-install tidyr and dplyr.  I burned down my house with re-installations of various versions of R and RStudio, to no avail.  The one constant - installation freezes here:
![image](https://user-images.githubusercontent.com/10427352/56072520-bd84b780-5d4c-11e9-8958-172d5b8df60f.png)

The other phenotype is that installation produces these files in the library instead of files with the name of the package: 
![image](https://user-images.githubusercontent.com/10427352/56072549-181e1380-5d4d-11e9-8847-471a490e27ee.png)

Installation seems to freeze any time I try to install anything with "tidyr" in it - be it "tidyr", "tidyverse", or dplyr (freezes after printing "package ‘tidyselect’ successfully unpacked and MD5 sums checked")

Please help - my projects are dead in the water right now as I have no working version of R that can run my scripts (that all use tidyr and dplyr).

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? There are more people that can help you out there, and if it turns out to be a bug in tidyr, we can always come back and re-open this issue.

Thanks.

**Comment by mkapplebee** [comment]
I started [there ](https://community.rstudio.com/t/packages-not-loading-since-updating-rstudio/28397/4) when I thought it was associated with Rstudio, but since I have now seen on multiple versions of RStudio and even when I run on the plain R console, and this seems particular to installing 'tidyr' and not other packages, this seems to be a tidyr-specific issue.

**Comment by mkapplebee** [comment]
So I was able to install 'tidyr' on another machine in the R-3.4.4 console.

Also, on the PC where this is occuring, the install freezes when it starts unpacking some files. The step where R and RStudio freeze on my main computer (always after printing 'trying URL '......tidyr_0.8.3.zip') is where it starts unpacking and checking "MD5 sums"  (starting with utf8).  

Any ideas what could be causing R to freeze at the unpacking stage?

Again, I am not running into this issue when I install other packages. I can even install ggplot2. This seems isolated to installing tidyr-containing packages.

**Comment by mkapplebee** [comment]
Resolution (for anyone else who runs into this):

In the RGui (but not RStudio), I let the "Program not responding" screen sit for ~25 minutes (while googling things on my old laptop) and the installation actually completed. I have now gotten 'tidyr' to successfully install on R-3.5.3 and R-3.4.2.

**Comment by HassnainAftabAli** [comment]
@mkapplebee I encountered the same problem. It wasn't responding for a while. On getting tired of waiting, I hit ctrl+C a couple of times trying to cancel the installation and it suddenly continued installing. (Might be useful for someone else running into the same issue).
