### ISSUE TITLE
demo("dadmom", package = "tidyr") fails [easy fix]

### ISSUE THREAD

**Issue by jmcastagnetto** [tidyverse/tidyr#618]
The `dadmomw.dta` file is now available via HTTPS not HTTP.

``` r
demo("dadmom", package = "tidyr")
#> 
#> 
#>  demo(dadmom)
#>  ---- ~~~~~~
#> 
#> > library(tidyr)
#> 
#> > library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> > dadmom <- foreign::read.dta("http://www.ats.ucla.edu/stat/stata/modules/dadmomw.dta")
#> Error in foreign::read.dta("http://www.ats.ucla.edu/stat/stata/modules/dadmomw.dta"): not a Stata version 5-12 .dta file
```

<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Fix is quick: just modify the url in https://github.com/tidyverse/tidyr/blob/17bb14c2586b924786512ea1281862186f0c5951/demo/dadmom.R#L4

(I'm too lazy to make a fork for a 1 char fix :-)

**Comment by cderv** [comment]
When I try I get a Invalide certificate Error in my browser. And R sees this too (error message in french sorry...)
``` r
foreign::read.dta("https://www.ats.ucla.edu/stat/stata/modules/dadmomw.dta")
#> Warning in download.file(file, tmp, quiet = TRUE, mode = "wb"):
#> InternetOpenUrl failed: 'Le nom de l'h<U+00F4>te du certificat n'est pas valide ou
#> ne correspond pas'
#> Error in download.file(file, tmp, quiet = TRUE, mode = "wb"): cannot open URL 'https://www.ats.ucla.edu/stat/stata/modules/dadmomw.dta'
```
Does it work for you without error ? 

<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>


> (I'm too lazy to make a fork for a 1 char fix :-)

Know that you can do this without explicitly making a fork by using the github interface for such a PR.
https://help.github.com/en/articles/editing-files-in-another-users-repository

This is very useful for such edition (and lazy people) ! 😉

**Comment by jmcastagnetto** [comment]
Same error in R on Ubuntu Linux 18.04, but works when putting an exception on Firefox. The reason is because the cert has a different subdomain, so the line that works is:

``` r
dadmom <- foreign::read.dta("https://stats.idre.ucla.edu/stat/stata/modules/dadmomw.dta")
```
<sup>Created on 2019-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Tested the whole code from `dadmom.R` and works without error, submitted a PR the lazy way :-)

``` r
library(tidyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dadmom <- foreign::read.dta("https://stats.idre.ucla.edu/stat/stata/modules/dadmomw.dta")
dadmom %>%
  gather(key, value, named:incm) %>%
  separate(key, c("variable", "type"), -2) %>%
  spread(variable, value, convert = TRUE)
#>    famid type    in  nam
#> 1      1   cd 30000 <NA>
#> 2      1   cm 15000 <NA>
#> 3      1   ed    NA Bill
#> 4      1   em    NA Bess
#> 5      2   cd 22000 <NA>
#> 6      2   cm 18000 <NA>
#> 7      2   ed    NA  Art
#> 8      2   em    NA  Amy
#> 9      3   cd 25000 <NA>
#> 10     3   cm 50000 <NA>
#> 11     3   ed    NA Paul
#> 12     3   em    NA  Pat
```

<sup>Created on 2019-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
