### ISSUE TITLE
Extract Function error in drop && length(x)

### ISSUE THREAD

**Issue by Kaz272** [tidyverse/tidyr#621]
When trying to use the extract function I get the following error:

Error in drop && length(x) == 1L : invalid 'x' type in 'x && y'

Example is directly from the tidyr extract documentation
```r
df <- data.frame(x = c(NA, "a-b", "a-d", "b-c", "d-e"))

df %>% extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
```
R version 3.6, Tidyr version 0.8.3

**Comment by jennybc** [comment]
Your error suggests you are actually calling `magrittr::extract()` above and not `tidyr::extract()`.

This usually means you have attached tidyr and *then* attached magrittr, thereby masking `tidyr::extract()` with `magrittr::extract()`.

You need to either re-order the `library()` calls or, for a more proper solution to this whole class of problem, look into facilities offered by the [conflicted package](https://conflicted.r-lib.org) or the facilities newly added in R 3.6 for [managing search path conflicts](https://developer.r-project.org/Blog/public/2019/03/19/managing-search-path-conflicts/index.html)

**Comment by Kaz272** [comment]
@jennybc Ah, that was the issue. Thank you, closing issue.

**Comment by jennybc** [comment]
For posterity.

``` r
library(tidyr)
library(magrittr)

df <- data.frame(x = c(NA, "a-b", "a-d", "b-c", "d-e"))

# what you want
df %>% tidyr::extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
#>      A    B
#> 1 <NA> <NA>
#> 2    a    b
#> 3    a    d
#> 4    b    c
#> 5    d    e

# what you're getting
df %>% magrittr::extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
#> Error in drop && length(x) == 1L: invalid 'x' type in 'x && y'

# I attach conflicted in my .Rprofile, to catch these situations
df %>% extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
#> [conflicted] `extract` found in 2 packages.
#> Either pick the one you want with `::` 
#> * magrittr::extract
#> * tidyr::extract
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("extract", "magrittr")
#> * conflict_prefer("extract", "tidyr")
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
