### ISSUE TITLE
nest in dev version: strange printing of nested tibble?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/tidyr#622]
Apologies if this is too early notice, as it concerns the development version, but I wanted to make sure the point had been noticed: using nest with version `0.8.3.9000` will create a df that contain `tibble()`s in the data column, but whose printing is quite unusual, and unlike the nice version one had before?

    library(tidyverse)

    df <- tibble(x = c(1, 1, 1, 2, 2, 3), y = 1:6, z = 6:1)
    df %>% nest(data=c(y, z))
    #> # A tibble: 3 x 2
    #>       x             data
    #>   <dbl>   <list<df[,2]>>
    #> 1     1 1, 2, 3, 6, 5, 4
    #> 2     2       4, 5, 3, 2
    #> 3     3             6, 1

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
It’s a known issue in the vctrs package.
