### ISSUE TITLE
Error in pivot_longer vignette billboard dataset

### ISSUE THREAD

**Issue by ogorodriguez** [tidyverse/tidyr#627]
I get the following error when trying to follow the vignette for pivot_longer/wider [here](https://github.com/tidyverse/tidyr/blob/master/vignettes/pivot.Rmd).

When I run this part:

```{r}
billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    values_to = "rank",
    values_drop_na = TRUE
  )
```

I get this error:

_Error in pivot_longer(., cols = contains("week"), names_to = "week", values_to = "rank", : unused argument (values_drop_na = TRUE)_

This is the traceback:

8. function_list[[k]](value)
7. withVisible(function_list[[k]](value))
6. freduce(value, `_function_list`)
5. `_fseq`(`_lhs`)
4. eval(quote(`_fseq`(`_lhs`)), env, env)
3 .eval(quote(`_fseq`(`_lhs`)), env, env)
2 .withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1. billboard %>% pivot_longer(cols = contains("week"), names_to = "week", values_to = "rank", values_drop_na = TRUE)

I have only copy and pasted code mainly.  The datasets used are found [here...](https://github.com/tidyverse/tidyr/blob/master/data-raw/billboard.csv)

Thanks in advance.

**Comment by hadley** [comment]
The vignette is generate automatically so if you’re having problems something has probably gone wrong with your install of the package.
