### ISSUE TITLE
Support using `fill = NaN` in `spread()`

### ISSUE THREAD

**Issue by mikemc** [tidyverse/tidyr#628]
Currently, calling `spread()` with `fill = NaN` instead fills with `NA`:
```r
library(tidyverse)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
#> Registered S3 method overwritten by 'rvest':
#>   method            from
#>   read_xml.response xml2
tb <- tibble(Other = c("o1", "o1", "o2"), Key = c("k1", "k2", "k1"), 
    Val = c(5, 8, 10))
tb %>%
    spread(Key, Val, fill = Inf)
#> # A tibble: 2 x 3
#>   Other    k1    k2
#>   <chr> <dbl> <dbl>
#> 1 o1        5     8
#> 2 o2       10   Inf
tb %>%
    spread(Key, Val, fill = NaN)
#> # A tibble: 2 x 3
#>   Other    k1    k2
#>   <chr> <dbl> <dbl>
#> 1 o1        5     8
#> 2 o2       10    NA

Created on 2019-05-14 by the reprex package (v0.2.1)
```

@hadley 's reply to #274 for `fill()` seems relevant but I would argue is actually a reason for supporting a user's ability to fill with NaN's: Because NA and NaN are different, if a user wants to fill with NaNs for some application, they should be able to, since they can't just use NA as a substitute. E.g., the NaNs denote cases of 0/0, and not simply "missing".

Edit: A workaround is to use `complete()` first,
```r
tb %>%
    complete(Other, Key, fill = list(Val = NaN)) %>%
    spread(Key, Val)
#> # A tibble: 2 x 3
#>   Other    k1    k2
#>   <chr> <dbl> <dbl>
#> 1 o1        5     8
#> 2 o2       10   NaN
```
I do see an argument for forcing the user to do this, since `fill =NaN` in spread will convert existing NAs to NaN as well as filling them in for missing rows, which is somewhat dangerous---but this argument applies to `spread(..., fill = 0)` just as well as to `spread(..., fill = NaN)`.

**Comment by hadley** [comment]
Already fixed in `pivot_wider()`

``` r
library(tidyverse)
tb <- tibble(
  Other = c("o1", "o1", "o2"), 
  Key = c("k1", "k2", "k1"), 
  Val = c(5, 8, 10)
)

tb %>% pivot_wider(
  names_from = Key, 
  values_from = Val, 
  values_fill = list(Val = NaN)
)
#> # A tibble: 2 x 3
#>   Other    k1    k2
#>   <chr> <dbl> <dbl>
#> 1 o1        5     8
#> 2 o2       10   NaN
```

<sup>Created on 2019-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
