### ISSUE TITLE
col_ptypes argument in pivot_longer is hard to remember and not intuitive

### ISSUE THREAD

**Issue by atusy** [tidyverse/tidyr#630]
I just started to learn pivot_longer and pivot_wider yesterday based on vignette.
There, I found two typos about `col_ptypes`.
One is `col_types` and another is `col_ptype` (PR #629).
This means it is hard to remember argument name even for developers!

In addition, the meaning of `ptypes` is not intuitive for beginners.
Users have to read the document to understand (or guess) that `ptypes` stands for `prototypes`.

What about changing `col_ptypes` to `types_to`, which is consistent to other arguments: `names_to` and `values_to`.

If `col_ptypes` is preferred, I'd suggest describe "`ptypes` stands for `prototypes`"  in vignette.

**Comment by hadley** [comment]
Thanks for spotting this inconsistency 😄

**Comment by hadley** [comment]
Actually I think this inconsistency is ok: we use `types` in readr, and `ptypes` in tidyr. But I think you're right that the name is wrong - it actually needs to be two arguments: `names_ptypes` and `values_ptypes`.

**Comment by hadley** [comment]
I agree this isn't very user friendly yet, and it will probably be a while before it is. However, prototypes are important because they provide a consistent underlying, as described in https://vctrs.r-lib.org. This theory be used in more and more places in the tidyverse in the coming years.

**Comment by atusy** [comment]
LGM!
I totally agree with importance of prototype.
That is why I also suggested to explicitly describe what "ptypes" is.
Thanks for adding it to the document.

> A prototype (or ptype for short)" https://github.com/tidyverse/tidyr/commit/7f4af5c29862b9f4e981069d6d9e8a9a9ec45866#diff-c546cafc69f35d7bb37ad33d449bef7eR49
