### ISSUE TITLE
Better description

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#632]
Currently it's 

> An evolution of 'reshape2'. It's designed specifically for data tidying (not general reshaping or aggregating) and works well with 'dplyr' data pipelines.

which doesn't seem very informative

**Comment by jl5000** [comment]
Had a go at #636

**Comment by Nowosad** [comment]
Probably the package title ("Easily Tidy Data with 'spread()' and 'gather()' Functions") also should be updated due to the recent changes (e.g. `pivot_` functions).

**Comment by hadley** [comment]
@Nowosad good point - thanks!
