### ISSUE TITLE
Could not find function "pivot_wider"

### ISSUE THREAD

**Issue by mehrgoltiv** [tidyverse/tidyr#635]
I'm trying to use pivot_wider to spread long data into wide format, but do so for multiple values (RT & response). When I run the code, raw %>% pivot_wider(names_from = trialcode, values_from = c(latency, response)), I get an error message that states, 

"Error in pivot_wider(., names_from = trialcode, values_from = c(latency,  : 
  could not find function "pivot_wider""

I have the appropriate packages loaded, I believe (tidyr, dplyr, readr). My tidyverse packages are also up to data (I checked using tidyverse_update). 

Any insights on what could be going wrong? I also tried specifying that this function comes from tidyr (tidyr::pivot_longer) but it gave me this error:  Error: 'pivot_wider' is not an exported object from 'namespace:tidyr'. 

Thanks!

**Comment by batpigandme** [comment]
`pivot_wider()` is not yet in the released version of tidyr. See the README for how to install the dev version from GitHub.
