### ISSUE TITLE
replace_na error

### ISSUE THREAD

**Issue by sethmund** [tidyverse/tidyr#639]
Having trouble with the `replace_na()` function.

```
dat <- data.frame(test=c(1,2,3,NA))

dat %>% mutate(test = tidyr::replace_na(test,""))

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘vctrs’ 0.1.0 is being loaded, but >= 0.1.0.9002 is required
```

Trying to update `vctrs` and `rlang` packages throws the error:

```
ERROR: failed to lock directory 'C:/Program Files/R/R-3.5.2/library' for modifying
Try removing 'C:/Program Files/R/R-3.5.2/library/00LOCK-rlang'
```

I can't get past this step.

**Comment by sethmund** [comment]
Also I've tried removing and re-installing all associated libraries and obviously 00LOCK-rlang, no luck.

**Comment by cderv** [comment]
Hi, 

did you try to install all from cran or from github ? 

This seems like an installation process issue with different version from package. You should try reinstall everything from CRAN to have last stable version.

For getting help on such questions, do not hesitate to go on community.rstudio.com. There is lot of people to share experience with and get help.

**Comment by sethmund** [comment]
I tried selectively re-installing from CRAN to clear the error but had to eventually remove every package and re-install. Dev tidyr is now unstable for me.
