### ISSUE TITLE
unnest fails on data.frame: can't slice scalar

### ISSUE THREAD

**Issue by AdvikS** [tidyverse/tidyr#644]
Thanks so much for all your work on tidyr! I'm very excited for the new `pivot_` functions. 

I've been using the development version (commit hash: 56fb136), and when I try to unnest a data.frame with a list-column, `unnest` throws the error: `Error: Can't slice a scalar`. 

If I create a tibble with a list-column rather than a data.frame, I am able to unnest. If I convert the list-col tibble back to a data.frame, I'm also able to unnest.

Here is a quick example:
```
library(tibble)

# create data.frame and corresponding tibble
df_1 <- data.frame(a = 1, b = I(list(1:2)))
tb_1 <- tibble(a = 1, b = list(1:2))

# fails
tidyr::unnest(df_1, cols = c(b))
#> Error: Can't slice a scalar

tidyr::unnest(as_tibble(df_1), cols = c(b))
#> Error: Can't slice a scalar

# succeeds
tidyr::unnest(tb_1, cols = c(b))
#> # A tibble: 2 x 2
#>       a     b
#>   <dbl> <int>
#> 1     1     1
#> 2     1     2

tidyr::unnest(as.data.frame(tb_1), cols = c(b))
#> # A tibble: 2 x 2
#>       a     b
#>   <dbl> <int>
#> 1     1     1
#> 2     1     2
```

**Comment by DavisVaughan** [comment]
I think part of the issue is that `I()` creates a special `AsIs` object, not a `list`. If you create that data.frame without using `I()`, everything works as expected. I'm not sure what `vec_slice()` should do with `AsIs` objects, maybe the current behavior is correct.

``` r
library(tidyr)
library(vctrs)

df_1 <- data.frame(a = 1, b = I(list(1:2)))

# `b` is AsIs. See `?I` for details
class(df_1$b)
#> [1] "AsIs"

# so you can't do this
unnest(df_1, b)
#> Error: Can't slice a scalar

# this error is a bit clearer
vec_slice(df_1$b, 1L)
#> `x` must be a vector, not a `AsIs` object

# don't use AsIs
df_2 <- data.frame(a = 1)
df_2$b <- list(1:2)

class(df_2$b)
#> [1] "list"

# everything works fine
unnest(df_2, b)
#> # A tibble: 2 x 2
#>       a     b
#>   <dbl> <int>
#> 1     1     1
#> 2     1     2

vec_slice(df_2$b, 1L)
#> [[1]]
#> [1] 1 2
```

<sup>Created on 2019-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
I think `vec_proxy.AsIs()` should probably strip off the `AsIs` class, and then call recursively. I'll file an issue in vctrs
