### ISSUE TITLE
Unnest shortcut

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#645]
If you have a list you have to first put it in a tibble (with a dummy column name), and then you have to `unnest` it using that name. Could we reduce into a single step?

**Comment by hadley** [comment]
Needs something like this:

```R
  if (inherits(data, "list")) {
    if (!missing(col)) {
      abort("`col` must be missing when `data` is a list.")
    }
    data <- tibble(data = data)
    col <- "data"
  }
```

But I can't yet see how to include in the 4 functions without duplicating code

**Comment by DavisVaughan** [comment]
Unnesting a list feels more programmatic oriented than data science oriented, so I wonder if we should just let `vctrs::vec_unchop()` handle this case

**Comment by hadley** [comment]
I still don't see how we could do this cleanly, so lets close.
