### ISSUE TITLE
Is it possible a labels_to option for pivot_longer?

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/tidyr#648]
I am using labelled package and have labelled variables. For example:
```
library(labelled)
var_label(iris) <- list(Petal.Length = "Length of petal", Petal.Width = "Width of Petal")
```
I would like, when I use `gather` or `pivot_longer`, to have the option of building a column of labels as I build the column of names with `key` or `names_to` respectively. For those variables without labels, the output value would be NA or NULL. 
Maybe it could be together with an option to introduce the "labels", so it could be used not only for them, but for any row or any vector of the same lenght of the gathered columns

Following with the example introduced above I would do
```
iris %>% 
    tidyr::pivot_longer(ends_with("Length"), names_to = "element", values_to = "length", labels_to = "lbl") %>% head()

# A tibble: 6 x 5   
    Sepal.Width Petal.Width Species   element      length         lbl
        <dbl>       <dbl>     <fct>   <chr>         <dbl>         <chr>
1         3.5        0.2    setosa  Sepal.Length    5.1            NA
2         3.5        0.2    setosa  Petal.Length    1.4       Length of petal
3         3          0.2    setosa  Sepal.Length    4.9            NA
4         3          0.2    setosa  Petal.Length    1.4       Length of petal
5         3.2        0.2    setosa  Sepal.Length    4.7             NA
6         3.2        0.2    setosa  Petal.Length    1.3       Length of petal
```
--
 
Thanks!

**Comment by hadley** [comment]
This is currently out of scope for tidyr.
