### ISSUE TITLE
Tibbles have significant issues with dates. Am I missing something?

### ISSUE THREAD

**Issue by TrentLobdell** [tidyverse/tidyr#659]
tibbles seem to regularly fail at the task of converting values with class "Date". tibbles also seem to not allow math to be applied to values of class "Date".

I regularly get this error when trying to work with Dates stored in tibbles:
_as.Date(tibble[1,1])
Error in as.Date.default(tibble[1,1]):
  do not know how to convert 'tibble[1,1]' to class "Date"_

Here is a reproducible example:
_ima_date_range <- tibble(start_date = "2019-06-16", end_date = "2019-06-28")_

_ima_date_range[1,1]
 A tibble: 1x1
  start_date
  chr
1 2019-06-16_

_as.Date(ima_date_range [1,1], format = "%Y-%m-%d")_

_Error in as.Date.default(ima_date_range[1,1]):
  do not know how to convert 'ima_date_range[1,1]' to class "Date"_

_as.POSIXct(ima_date_range [1,1], format = "%Y-%m-%d")_

_Error in as.POSIX.default(ima_date_range[1,1]):
  do not know how to convert 'ima_date_range[1,1]' to class "POSIXct"_

Here's the weird thing:
_as.Date(as.character(ima_date_range [1,1]))
[1] 2019-06-16_

**Comment by aosmith16** [comment]
I don't think this is an issue, which I'll explain below, but if it were the [GitHub repository for package **tibble**](https://github.com/tidyverse/tibble) would be the best place to report it.

Subsetting is one of the big differences between tibbles and data.frames, and I think that's what is tripping you up here.  You can see a nice discussion with examples in the "Subsetting" section [of the **tibble** vignette](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html).

Using `[` to subset a tibble always returns a tibble, 

You need `[[` to get a vector that you can turn into a date.

Here's some example code to demonstrate:

``` r
library(tibble)
ima_date_range <- tibble(start_date = c("2019-06-16", "2019-06-16"), end_date = "2019-06-28")

# Using [ returns tibble
class( ima_date_range[1, 1] )
#> [1] "tbl_df"     "tbl"        "data.frame"

# Using [[ returns vector
class( ima_date_range[[1, 1]] )
#> [1] "character"

# So does $ notation
class( ima_date_range$start_date )
#> [1] "character"

# Can convert vector to a date, not a tibble
as.Date(ima_date_range[[1, 1]], format = "%Y-%m-%d")
#> [1] "2019-06-16"
```

Created on 2019-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by TrentLobdell** [comment]
Thank you, aosmith16. I was not aware of that difference. I also appreciate the vignette you linked.
