### ISSUE TITLE
separate() converts character vector "NA" to <NA> when convert = TRUE

### ISSUE THREAD

**Issue by jeroenjanssens** [tidyverse/tidyr#660]
To use a real-world situation where this may arise, consider Dutch postal codes, which consist of four digits, a space, and two letters. For example,

``` r
library(tidyverse)

data <- tribble(~ postal_code,
                "1234 AZ",
                "1337 NA")
```

When using `tidyr::seperate(..., convert = TRUE)` the second row contains a `<NA>`. The following code reproduces this:

```r
# With convert = FALSE
separate(data, postal_code, c("digits", "letters"),
         sep = " ", remove = FALSE, convert = FALSE) %>%
  mutate(letters_na = is.na(letters))
#> # A tibble: 2 x 4
#>   postal_code digits letters letters_na
#>   <chr>       <chr>  <chr>   <lgl>     
#> 1 1234 AZ     1234   AZ      FALSE     
#> 2 1337 NA     1337   NA      FALSE

# With convert = TRUE
separate(data, postal_code, c("digits", "letters"),
         sep = " ", remove = FALSE, convert = TRUE) %>%
  mutate(letters_na = is.na(letters))
#> # A tibble: 2 x 4
#>   postal_code digits letters letters_na
#>   <chr>        <int> <chr>   <lgl>     
#> 1 1234 AZ       1234 AZ      FALSE     
#> 2 1337 NA       1337 <NA>    TRUE
```

I'm curious: is this a bug or a feature?

Thanks,

Jeroen

PS. Many thanks to the authors of `tidyr` and `reprex`. 

<sup>Created on 2019-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Mojave 10.14.4
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] forcats_0.4.0   stringr_1.4.0   dplyr_0.8.1     purrr_0.3.2    
#> [5] readr_1.3.1     tidyr_0.8.3     tibble_2.1.3    ggplot2_3.2.0  
#> [9] tidyverse_1.2.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.1       cellranger_1.1.0 pillar_1.4.1     compiler_3.6.0  
#>  [5] highr_0.8        tools_3.6.0      zeallot_0.1.0    digest_0.6.19   
#>  [9] lubridate_1.7.4  jsonlite_1.6     evaluate_0.14    nlme_3.1-139    
#> [13] gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.2  rlang_0.4.0     
#> [17] cli_1.1.0        yaml_2.2.0       haven_2.1.0      xfun_0.8        
#> [21] withr_2.1.2      xml2_1.2.0       httr_1.4.0       knitr_1.23      
#> [25] vctrs_0.1.0      hms_0.4.2        generics_0.0.2   grid_3.6.0      
#> [29] tidyselect_0.2.5 glue_1.3.1       R6_2.4.0         fansi_0.4.0     
#> [33] readxl_1.3.1     rmarkdown_1.13   modelr_0.1.4     magrittr_1.5    
#> [37] backports_1.1.4  scales_1.0.0     htmltools_0.3.6  rvest_0.3.4     
#> [41] assertthat_0.2.1 colorspace_1.4-1 utf8_1.1.4       stringi_1.4.3   
#> [45] lazyeval_0.2.2   munsell_0.5.0    broom_0.5.2      crayon_1.3.4
```

</details>

**Comment by jennybc** [comment]
Looking at the source of `separate.data.frame`, there doesn't seem to be a way to get at the `na.strings` argument of `type.convert()`, which is what's needed here. The default of `"NA"` is unfortunate in this case.

**Comment by jeroenjanssens** [comment]
Thanks for the explanation, @jennybc. Since there are ways to work around this, do you think we should close this issue?

**Comment by jennybc** [comment]
No because this might be interesting to think about in the context of vctrs.

**Comment by hadley** [comment]
This isn't quite vctrs; its more readr/vroom because we have a column of strings that we're parsing. But I doubt we'll want to be able to pass arbitrary parameters down to the underlying conversion, so I think if you want more control, you'll need to do it outside of tidyr.

**Comment by jeroenjanssens** [comment]
I agree that we don't need to be able to pass arbitrary parameters, but since this behaviour was unexpected (to me at least), would it make sense to either change the behaviour of `type.convert()` or add a note to the documentation?

**Comment by hadley** [comment]
I can be a bit more explicit about it, but basically when you're converting data from strings in R, `"NA"` is usually converted to `NA`.
