### ISSUE TITLE
Better error message when variables names don't have common type

### ISSUE THREAD

**Issue by atusy** [tidyverse/tidyr#663]
Currently, `pivot_longer` tells which variable does not have common type by `..n`.
This is not intuitive especially when cols are selected by numbers.
For example, if `cols = c(1, 5)` is specified and 1st and 5th column does not have common type, error says `no common type for ..1 and ..2`.

It would be helpful if error tells which variable does not have common type .
(e.g., `Sepal.Length` and `Species` in case of the example below)

``` r
tidyr::pivot_longer(iris, c(1, 5))
#> Warning: `vec_type_common()` has been renamed to `vec_ptype_common()`.
#> This warning is displayed once per session.
#> No common type for `..1` <double> and `..2` <factor<12d60>>.
```

<sup>Created on 2019-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This looks like an easy fix, but I need to think about it a bit more:

```R
val_type <- vec_type_common(!!!val_cols, .ptype = values_ptypes[[value]])
# ->
val_type <- vec_type_common(!!!setNames(val_cols, cols), .ptype = values_ptypes[[value]])
```

That yields

```
#> Error: No common type for `Sepal.Length` <double> and `Species` <factor<12d60>>
```
