### ISSUE TITLE
Need definition of "value column" in pivoting vignette

### ISSUE THREAD

**Issue by atusy** [tidyverse/tidyr#664]
In pivoting vignette, there is an uncommon term "value column".
It took a few days to understand "value column" means column(s) which cell values go into by pivoting.
But I want concrete definition.

I think there is another reason why "value column" being difficult that it first appears as "single value column" in L171.
This is tricky because readers may confuse if `single` modifies `value column` or `single value` modifies `column`.

https://github.com/tidyverse/tidyr/blob/master/vignettes/pivot.Rmd#L171

One possibility is to define "value column" together with `values_to` argument in the section "String data in column names".

**Comment by yutannihilation** [comment]
Probably, "Tidy data" vignette is the best place to explain the basic concepts and terms regarding to tidy data? I too feel "value column" (and "key column"?) should be defined a bit clearer to make it easy to understand what the vignettes say.

https://tidyr.tidyverse.org/dev/articles/tidy-data.html

**Comment by hadley** [comment]
Maybe just "column of values" would be better?

I'd prefer to rewrite to remove any mention of "key column"; I think that's just an accidental remnant from spread/gather terminology.

**Comment by atusy** [comment]
Would be better, but not enough.

There are two sentences using `value column`

> So far, we have been working with data frames that have a single value column.

> this tells pivot_longer() that that component of the variable name defines the name of the output value column.

For the latter case, I think `value column` can be replaced by `column to values`, but not for the former:

> So far, we have been working with data frames that have a single column of values.

This is no good because of ambiguity in data frames if they are input or output.

What about

> So far, we have been working with output data frames that have a single column of values.

or

> So far, we have been pivoting data frames so that values go into a single column.

**Comment by hadley** [comment]
Oh actually, I think that whole paragraph needs to be rewritten to use the same language as the heading:

> So far, we have been working with data frames that have one observation per row, but many important pivotting problems involve multiple observations per row. You can usually recognise this case because   name of the column that you want to appear in the output is part of the column name in the input.

(Still needs rewriting for clarity, but hopefully you get the idea)

**Comment by yutannihilation** [comment]
That makes sense to me. 👍

> I'd prefer to rewrite to remove any mention of "key column"; I think that's just an accidental remnant from spread/gather terminology.

So, does it mean the whole `tidy-data.Rmd` needs to be rewritten with `pivot_*()`? I'm wondering to what extent tidyr's documents will be revised before the actual CRAN release. For example, README still doesn't refer to `pivot_*()`.

(BTW, a spoiler: @atusy is translating the pivotting vignette into Japanese!)

**Comment by hadley** [comment]
@yutannihilation oh sorry, I missed that you were talking about a different vignette. Would you mind filing a separate issue for each place that we need to talk about the new pivot functions? They'd all be good dev day issues.

**Comment by yutannihilation** [comment]
Aw, sorry for talking about different vignettes... Sure, I will.

**Comment by yutannihilation** [comment]
Filed issues at #673 and #674.
