### ISSUE TITLE
Better error for pivot_longer() when no column names are given

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/tidyr#665]
As `pivot_longer()` accepts select helpers, it might be a common mistake to pass 0 columns to `cols` argument. I think this error message can be improved. (Might this be a good issue for tidy dev day?)

``` r
library(tidyr)

iris %>% 
  pivot_longer(matches("foo"))
#> Error in `[[<-.data.frame`(`*tmp*`, ".value", value = "value"): replacement has 1 row, data has 0
```

<sup>Created on 2019-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Good catch, thanks!
