### ISSUE TITLE
Inconsistent class dropping with unnest()

### ISSUE THREAD

**Issue by courtiol** [tidyverse/tidyr#672]
Hi all,
I am pleased to see that `purrr::pmap()` no longer drop classes. Nonetheless, for non trivial classes, the output of `pmap()` must be a `list`, which then need to be unnested (or flattened?). My issue is that it seems that the unnesting sometimes still looses the class (but not always):

``` r

library(magrittr)

## consistent output (list of correct class):
  
tibble::tibble(date = as.Date("2000/01/01"), duration = 1) %>%
  dplyr::mutate(new = purrr::pmap(list(duration, date), ~ ..2 + lubridate::duration(..1))) -> foo

foo
#> # A tibble: 1 x 3
#>   date       duration new       
#>   <date>        <dbl> <list>    
#> 1 2000-01-01        1 <dttm [1]>

tibble::tibble(date = as.Date("2000/01/01"), duration = 1) %>%
  dplyr::mutate(new = purrr::pmap(list(duration), ~ lubridate::duration(..1))) -> bar

bar
#> # A tibble: 1 x 3
#>   date       duration new       
#>   <date>        <dbl> <list>    
#> 1 2000-01-01        1 <Duration>


## inconsistent output with unnest (class only dropped for bar):

foo %>% tidyr::unnest()
#> # A tibble: 1 x 3
#>   date       duration new                
#>   <date>        <dbl> <dttm>             
#> 1 2000-01-01        1 2000-01-01 00:00:01

bar %>% tidyr::unnest()
#> Warning in combine_all(args[[1]]): Vectorizing 'Duration' elements may not
#> preserve their attributes
#> # A tibble: 1 x 3
#>   date       duration   new
#>   <date>        <dbl> <dbl>
#> 1 2000-01-01        1     1
```

<sup>Created on 2019-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The warning suggests that this is not a bug but perhaps you will think it is.
If this is not a bug I would appreciate a general work around.

Apologies, if this is covered by another issue, I browsed a lot of them and could not find one.

Best,
Alex

**Comment by aosmith16** [comment]
Have you tried this with the current development version of **tidyr**?   

Note there are same changes to the interface of `unnest()`, but when I run your code with the development version and unnest `bar` I get:

```r
bar %>% tidyr::unnest(col = new)
#> # A tibble: 1 x 3
#>  date       duration new           
#>  <date>        <dbl> <S4: Duration>
#> 1 2000-01-01        1 1s           
```

**Comment by courtiol** [comment]
You are right, the new implementation of `unnest()` solves addresses this limitation.
Well done and many thanks
