### ISSUE TITLE
feature request: names_suffix argument

### ISSUE THREAD

**Issue by kuriwaki** [tidyverse/tidyr#677]
It would be great to have a `names_suffix` argument available in `pivot_longer`, mirroring the `names_prefix` argument that already exists.

``` r
library(tidyr)
library(tibble)

samp <- tibble(
  i = 1:4,
  t1_y = rnorm(4),
  t2_y = rnorm(4)
)

## make it possible to do `names_suffix = "_y"` here? 
pivot_longer(samp, -i, 
             names_to = "time",
             values_to = "y") 
#> # A tibble: 8 x 3
#>       i time        y
#>   <int> <chr>   <dbl>
#> 1     1 t1_y   0.151 
#> 2     1 t2_y   0.224 
#> 3     2 t1_y   0.871 
#> 4     2 t2_y   0.189 
#> 5     3 t1_y  -0.0611
#> 6     3 t2_y   1.76  
#> 7     4 t1_y   0.112 
#> 8     4 t2_y   0.187
```

<sup>Created on 2019-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This seems like the perfect use case for `names_sep` and `.value`:

``` r
library(tidyr)
library(tibble)

samp <- tibble(
  i = 1:4,
  t1_y = rnorm(4),
  t2_y = rnorm(4)
)

pivot_longer(samp, -i, names_to = c("time", ".value"), names_sep = "_")
#> # A tibble: 8 x 3
#>       i time         y
#>   <int> <chr>    <dbl>
#> 1     1 t1     0.741  
#> 2     1 t2    -0.0180 
#> 3     2 t1     0.00457
#> 4     2 t2     0.251  
#> 5     3 t1     0.658  
#> 6     3 t2     1.38   
#> 7     4 t1    -0.985  
#> 8     4 t2    -0.788
```

<sup>Created on 2019-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think `names_suffix` is general enough to be worth adding.

**Comment by ericpgreen** [comment]
This works for me (thanks!), but I will say that `names_prefix` is intuitive and I assumed there was a `names_suffix`. It was my first attempt and I ended up here after a bit of searching to better understand how to use `names_sep`.
