### ISSUE TITLE
Installing dev version creates a value in global environment (ok = TRUE)

### ISSUE THREAD

**Issue by Myfanwy** [tidyverse/tidyr#681]
```r
devtools::install_github("tidyverse/tidyr", force=TRUE) # force arg added for confirmation that it occurred each time it's installed - it did

```
After package installation and testing finishes ("`* DONE (tidyr) `" message), value appears in global environment.  Screenshot:

![Screen Shot 2019-07-11 at 11 46 16 AM](https://user-images.githubusercontent.com/6519519/61076907-26261380-a3d2-11e9-9b16-3c63fe257c73.png)

![Screen Shot 2019-07-11 at 11 52 00 AM](https://user-images.githubusercontent.com/6519519/61076987-540b5800-a3d2-11e9-9d45-b0cc60ce5466.png)

**Comment by jennybc** [comment]
This is coming from processx (via devtools, so has nothing to do with tidyr) and a fix will appear on CRAN soon (9fad698128c79eaaad4a3f676a11f739d0bcf648).
