### ISSUE TITLE
Does unnest_*() handle multiple columns?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/tidyr#687]
While `unnest_*()` has select semantics for `col` argument, it seems no docs refer to the usages with multiple columns. For example, I'm wondering if the following is supposed to work or not (in any case, I feel the current result is not desired one). 

``` r
library(tidyr)

df <- tibble(id = c("a", "b"), val1 = vctrs::list_of(1L, 2:4), val2 = vctrs::list_of(5, 6:8))
df
#> # A tibble: 2 x 3
#>   id           val1        val2
#>   <chr> <list<int>> <list<dbl>>
#> 1 a             [1]         [1]
#> 2 b             [3]         [3]

# Will this work after #658 is fixed?
df %>% 
  unnest_longer(-id)
#> No common type for `x` <tbl_df<val2:double>> and `y` <double>.

# I want `val1` also unnested...
df %>% 
  purrr::modify(unclass) %>%
  unnest_longer(-id)
#> # A tibble: 4 x 3
#>   id    val1       val2
#>   <chr> <list>    <dbl>
#> 1 a     <int [1]>     5
#> 2 b     <int [3]>     6
#> 3 b     <int [3]>     7
#> 4 b     <int [3]>     8
```

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Maybe should I use `unchop()` here as suggested in https://github.com/tidyverse/tidyr/issues/658#issuecomment-508090071?

**Comment by hadley** [comment]
`unnest_longer()` and `unnest_wider()` only handle a single column — here we're using `tidyselect::var_pull()`, which turns `-id` into `-1` which means use the latest column.

And yes, `unchop()` is what you want here:

``` r
library(tidyr)
df <- tibble(id = c("a", "b"), val1 = vctrs::list_of(1L, 2:4), val2 = vctrs::list_of(5, 6:8))
df %>% 
  unchop(c(val1, val2)) 
#> # A tibble: 4 x 3
#>   id     val1  val2
#>   <chr> <int> <dbl>
#> 1 a         1     5
#> 2 b         2     6
#> 3 b         3     7
#> 4 b         4     8
```

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

At the time I wrote it, I remember deciding that `unnest_longer()` shouldn't need to take multiple columns for some reason that was obvious at the time. But now it's not clear, and I'm not sure when you're supposed to use `unchop()` vs. `unnest_longer()`.

**Comment by yutannihilation** [comment]
> here we're using `tidyselect::var_pull()`, which turns `-id` into `-1` which means use the latest column.

Aw, I got it... Thanks!

As `unnest()` takes multiple columns, this kind of mistake might be going to be a common one before we forget about `unnest()`. I don't know what to do to avoid the confusion, but I'll consider if I can improve some documentations.
