### ISSUE TITLE
Process revdep failures

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#692]
https://docs.google.com/spreadsheets/d/13XXN8sepsc0Ftl5nVz4YdJCONbD_k00HOZUxbPosThM/edit#gid=0

Each failure needs to be triaged and a resolution found; for failures related to the interface changes in `nest()` and `unnest()` the plan is to help individual package authors with the needed fixes. I'm reasonably confident the deprecation warnings should catch problems in existing scripts.

**Comment by jennybc** [comment]
I'm using some download stats to prioritize my efforts:

revdep-sitrep.R
================
jenny
2019-07-30

``` r
library(commonmark)
library(xml2)
library(tidyverse)
library(cranlogs)

new_problems_path <- here::here("revdep/problems.md")
md <- readLines(new_problems_path)
pkg <- md %>%
  str_subset("^#[^#]") %>%
  str_extract("[[:alnum:]]+")

dl <- cran_downloads(when = "last-month", packages = pkg)

dl %>%
  count(package, wt = count) %>%
  arrange(desc(n)) %>%
  mutate(
    prop = n / sum(n),
    cum_prop = cumsum(prop)
  ) %>%
  print(n = 20)
#> # A tibble: 68 x 4
#>    package           n    prop cum_prop
#>    <chr>         <dbl>   <dbl>    <dbl>
#>  1 modelr       205720 0.390      0.390
#>  2 ggpubr        94105 0.179      0.569
#>  3 recipes       93673 0.178      0.747
#>  4 survminer     18635 0.0354     0.782
#>  5 d3r           17290 0.0328     0.815
#>  6 sunburstR     15903 0.0302     0.845
#>  7 sjstats       14758 0.0280     0.873
#>  8 sjPlot        11225 0.0213     0.894
#>  9 tidyquant      5698 0.0108     0.905
#> 10 gutenbergr     4081 0.00774    0.913
#> 11 fuzzyjoin      3146 0.00597    0.919
#> 12 tibbletime     3092 0.00587    0.925
#> 13 widyr          2995 0.00568    0.930
#> 14 ggstatsplot    2955 0.00561    0.936
#> 15 tsibble        2928 0.00556    0.942
#> 16 bench          2671 0.00507    0.947
#> 17 broomExtra     2484 0.00471    0.951
#> 18 groupedstats   1846 0.00350    0.955
#> 19 ggalluvial     1789 0.00339    0.958
#> 20 anomalize      1640 0.00311    0.961
#> # … with 48 more rows
```

**Comment by jennybc** [comment]
# `tidyr::nest()` then `dplyr::mutate()`

`tidyr::nest()` now returns a grouped data frame, whereas previously it did not. This has implications for downstream calls to dplyr verbs, especially when referring to external objects, i.e. objects that aren't variables inside the primary data frame.

Here are some examples of how this problem presents and ways to fix re: `dplyr::mutate()`.

``` r
library(tidyverse)

df <- tibble(
  x = c("a", "a", "b", "b"),
  y = 1:4,
  z = c(NA, TRUE, NA, FALSE)
)

(df_nested <- df %>% 
    group_by(x) %>% 
    nest())
#> # A tibble: 2 x 2
#> # Groups:   x [2]
#>   x               data
#>   <chr> <list<df[,2]>>
#> 1 a            [2 × 2]
#> 2 b            [2 × 2]
```

What if we want to add a variable computed from the `data` list-col? It’s
tempting to compute outside the df, then add it, but that won’t work.

``` r
yo <- map_int(df_nested$data, nrow)
df_nested %>%
  mutate(n_rows = yo)
#> Error: Column `n_rows` must be length 1 (the group size), not 2
```

Solution: bring that `map()` inside `mutate()`, i.e. work inside the data
frame at all times.

``` r
df_nested %>% 
  mutate(n_rows = map_int(data, nrow))
#> # A tibble: 2 x 3
#> # Groups:   x [2]
#>   x               data n_rows
#>   <chr> <list<df[,2]>>  <int>
#> 1 a            [2 × 2]      2
#> 2 b            [2 × 2]      2
```

Alternative soluion: `tibble::add_column()` is a way to add a column that is
NOT computed from existing variables. We recommend the approach above, if
your new variable is derived from existing variables, although
`tibble::add_column()` will even work in the current example.

``` r
# works, but above solution is preferred
df_nested %>% 
  tibble::add_column(n_rows = yo)
#> # A tibble: 2 x 3
#> # Groups:   x [2]
#>   x               data n_rows
#>   <chr> <list<df[,2]>>  <int>
#> 1 a            [2 × 2]      2
#> 2 b            [2 × 2]      2

# this is right solution for truly external data
df_nested %>% 
  tibble::add_column(something = c("this", "that"))
#> # A tibble: 2 x 3
#> # Groups:   x [2]
#>   x               data something
#>   <chr> <list<df[,2]>> <chr>    
#> 1 a            [2 × 2] this     
#> 2 b            [2 × 2] that
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jennybc** [comment]
``` r
library(tidyverse)

df <- tibble(
  x = c("a", "a", "b", "b"),
  y = 1:4,
  z = c(NA, TRUE, NA, FALSE)
)

(df_nested <- df %>% 
    group_by(x) %>% 
    nest())
#> # A tibble: 2 x 2
#> # Groups:   x [2]
#>   x               data
#>   <chr> <list<df[,2]>>
#> 1 a            [2 × 2]
#> 2 b            [2 × 2]
```

What if we want to filter on an external variable? The grouped nature of `df`
is going to prevent that.

``` r
(keepers <- complete.cases(df))
#> [1] FALSE  TRUE FALSE  TRUE
```

Here are a few solutions. Some will work better that others in different
situations and we’re still discussing our general recommendations. More soon.

If this external variable is actually derived from the data, bring that
computation inside the data frame. Use `group_modify()` and friends.

``` r
df %>% 
  group_modify(~ filter(.x, complete.cases(.x)))
#> # A tibble: 2 x 3
#>   x         y z    
#>   <chr> <int> <lgl>
#> 1 a         2 TRUE 
#> 2 b         4 FALSE
```

If the result is going to become un-grouped anyway, `ungroup()` before the
`filter()` call.

``` r
df %>%
  ungroup() %>% 
  filter(keepers)
#> # A tibble: 2 x 3
#>   x         y z    
#>   <chr> <int> <lgl>
#> 1 a         2 TRUE 
#> 2 b         4 FALSE
```

In general, though, we think grouped-ness should be retained, to permit
proper `nest()` \<–\> `unnest()` roundtrips, so don’t use this solution just
because it looks easy.

You can also temporarily add an external variable using
`tibble::add_column()`, and then remove it.

``` r
df %>%
  add_column(keepers = keepers) %>%
  filter(keepers) %>% 
  select(-keepers)
#> # A tibble: 2 x 3
#>   x         y z    
#>   <chr> <int> <lgl>
#> 1 a         2 TRUE 
#> 2 b         4 FALSE
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jennybc** [comment]
I'll come back with an example but don't want to forget this point:

To remove `nest_()` calls *without* requiring dev (v1.0.0) tidyr, move the group specification into an upstream `group_by()` (or `group_by_at()`) then just call `nest()` with no args. Add note re: which version of dplyr this requires.

I did this in fuzzyjoin (https://github.com/dgrtwo/fuzzyjoin/commit/a39fc462c6030766b0ba77c916ba66d190b97df6).

**Comment by jennybc** [comment]
# Updating a call to `tidyr::nest()` or `nest_()`

Let's say you have the data frame `df`:

``` r
library(tidyverse)

df <- tibble(
  grp = c(1, 1, 2, 2, 2),
  x = 1:5,
  y = letters[1:5]
)

df
#> # A tibble: 5 x 3
#>     grp     x y    
#>   <dbl> <int> <chr>
#> 1     1     1 a    
#> 2     1     2 b    
#> 3     2     3 c    
#> 4     2     4 d    
#> 5     2     5 e
```

 and you want to nest it by `grp` or, to say it a different way, you want to nest the columns `x` and `y`. Furthermore, let's imagine you want the new list-column to be named "foofy".

Things to think about:

  * The cleanest code will target tidyr >= v1.0.0 specifically. If you want code that is backwards compatible, it will be less streamlined.
  * Consider whether to specify the columns to nest or group by or the columns to be nested, i.e. that end up in the list-column. One is probably easier than the other!
  * Think about whether you need to control the name of the new list-column.

## Example code with tidyr v0.8.3

``` r
packageVersion("tidyr")
#> [1] '0.8.3'

# works with with tidyr <= 0.8.3 (but not >= 1.0.0)
df %>% 
  nest(x, y) %>% 
  rename(foofy = data)
#> # A tibble: 2 x 2
#>     grp foofy           
#>   <dbl> <list>          
#> 1     1 <tibble [2 × 2]>
#> 2     2 <tibble [3 × 2]>

df %>% 
  nest(x, y, .key = "foofy")
#> # A tibble: 2 x 2
#>     grp foofy           
#>   <dbl> <list>          
#> 1     1 <tibble [2 × 2]>
#> 2     2 <tibble [3 × 2]>

df %>% 
  nest_(key_col = "foofy", nest_cols = c("x", "y"))
#> # A tibble: 2 x 2
#>     grp foofy           
#>   <dbl> <list>          
#> 1     1 <tibble [2 × 2]>
#> 2     2 <tibble [3 × 2]>
```

## Same code, running under dev tidyr ≈ tidyr v1.0.0

Running the code above with newer tidyr leads to a warning or, in the case of `nest_()`, an actual error.

``` r
packageVersion("tidyr")
#> [1] '0.8.3.9000'

# works with with tidyr <= 0.8.3 (but not >= 1.0.0)
df %>% 
  nest(x, y) %>% 
  rename(foofy = data)
#> Warning: All elements of `...` must be named.
#> Did you want `data = c(x, y)`?
#> # A tibble: 2 x 2
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]

df %>% 
  nest(x, y, .key = "foofy")
#> Warning: All elements of `...` must be named.
#> Did you want `foofy = c(x, y)`?
#> # A tibble: 2 x 2
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]

df %>% 
  nest_(key_col = "foofy", nest_cols = c("x", "y"))
#> Error: 'nest_' is defunct.
#> Use 'nest' instead.
#> See help("Defunct")
```

## Cleanest update using dev tidyr ≈ tidyr v1.0.0

Here's the nicest way to achieve our goal:

``` r
packageVersion("tidyr")
#> [1] '0.8.3.9000'

# works with tidyr >= 1.0.0 (but not <= 0.8.3)
df %>% 
  nest(foofy = c(x, y))
#> # A tibble: 2 x 2
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]
```

## Code that works for all relevant version of tidyr

Here's code that will work with tidyr v0.8.3 and dev / v1.0.0 (this was run with dev / v1.0.0).

``` r
df %>%
  group_by(grp) %>% 
  nest() %>% 
  rename(foofy = data)
#> # A tibble: 2 x 2
#> # Groups:   grp [2]
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]

df %>%
  group_by_at("grp") %>% 
  nest() %>% 
  rename(foofy = data)
#> # A tibble: 2 x 2
#> # Groups:   grp [2]
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]

df %>%
  group_by_at(1) %>% 
  nest() %>% 
  rename(foofy = data)
#> # A tibble: 2 x 2
#> # Groups:   grp [2]
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]

df %>%
  group_by_at(vars(-one_of(c("x", "y")))) %>% 
  nest() %>% 
  rename(foofy = data)
#> # A tibble: 2 x 2
#> # Groups:   grp [2]
#>     grp          foofy
#>   <dbl> <list<df[,2]>>
#> 1     1        [2 × 2]
#> 2     2        [3 × 2]
```

The key point is to lean on `dplyr::group_by()` or `group_by_at()` to specify the grouping or nesting variable, instead of `tidyr::nest()`.

**Comment by jennybc** [comment]
# Test continuously against released and devel tidyr

For maintainers already using Travis-CI, here's a `.travis.yml` that shows how to expand your build matrix to include a run that checks your package against the devel version of tidyr:

``` yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
bioc_packages: IRanges

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    name: tidyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
  - r: oldrel
```

Taken from: https://github.com/dgrtwo/fuzzyjoin/pull/60. Note that most packages will NOT need the `bioc_packages: IRanges` line.

You might not want an extra build in place all the time, but it can be handy in the period when a dependency, like tidyr, is building towards a major release with the potential for breaking changes.

Placeholder issue for general notes on how to manage version changes in a dependency:
https://github.com/tidyverse/principles/issues/95

**Comment by jennybc** [comment]
TODO for me: write the equivalent of this ggplot2 vignette section, but for `nest()` and `unnest()`:

https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html#using-aes-and-vars-in-a-package-function

**Comment by jennybc** [comment]
💡Need to adjust write ups above to reflect that `nest()` doesn't add grouping where there was none before. But it does preserve grouping. So when we use `group_by()` and `group_by_at()` prior to `nest()`, we create grouping as a side effect.

**Comment by jennybc** [comment]
I mark my own comments as resolved when they are incorporated elsewhere.
