### ISSUE TITLE
`unpack()` doesn't completely respect minimal name repair

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#697]
Minimal example:

``` r
library(tidyr)
x <- tibble(DUP = 1, df = tibble(DUP = 2))
unpack(x, df, names_repair = "minimal")
#> Column name `DUP` must not be duplicated.
#> Use .name_repair to specify repair.
```

This error has to do with the fact that `reconstruct_tibble()` does not pass the current `names_repair` option through to its call to `as_tibble()`

(This came up while processing tidyr revdep issues in strapgod. `unnest()` was called, which triggered this)

**Comment by hadley** [comment]
I think the root cause is that `as_tibble(out, .name_repair = names_repair)` doesn't actually do any name repair 😬
