### ISSUE TITLE
Issue with unnest() and NextMethod() black magic

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#699]
This is a painful issue (but hopefully an easy fix!). Notice that when:

- We have a method for `nest()`
- We then call `nest.grouped_df` from that method
- We have supplied _something_ in the `...`

Then we trigger the `.key is deprecated` warning _no matter what_.

I think this is an insane case where `NextMethod()` isn't resetting the value of `.key` like it it supposed to:

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)

mtcars <- as_tibble(mtcars)

mtcars_special <- structure(mtcars, class = c("special_df", class(mtcars)))

nest.special_df <- function(.data, ..., .key = "DEPRECATED") {
  class(.data) <- setdiff(class(.data), "special_df")
  .data <- group_by(.data, vs)
  # run the grouped df version of nest()
  nest(.data, ..., .key = .key)
}

# WAT
mtcars_special %>%
  nest(data = am)
#> Warning: `.key` is deprecated
#> # A tibble: 32 x 11
#> # Groups:   vs [2]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs  gear  carb         data
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <list<df[,1>
#>  1  21       6  160    110  3.9   2.62  16.5     0     4     4      [1 × 1]
#>  2  21       6  160    110  3.9   2.88  17.0     0     4     4      [1 × 1]
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     4     1      [1 × 1]
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     3     1      [1 × 1]
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     3     2      [1 × 1]
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     3     1      [1 × 1]
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     3     4      [1 × 1]
#>  8  24.4     4  147.    62  3.69  3.19  20       1     4     2      [1 × 1]
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     4     2      [1 × 1]
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     4     4      [1 × 1]
#> # … with 22 more rows

mtcars_special %>%
  nest()
#> # A tibble: 2 x 2
#> # Groups:   vs [2]
#>      vs            data
#>   <dbl> <list<df[,10]>>
#> 1     0       [18 × 10]
#> 2     1       [14 × 10]
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I think what _normally_ happens is that on this line `.key` is normally set to `"data"`
https://github.com/tidyverse/tidyr/blob/56116de14492679727ef941b0d9ebd8982fe15c4/R/nest.R#L140

But then when `NextMethod()` is called here, it gets reset to `"DEPRECATED"`
https://github.com/tidyverse/tidyr/blob/56116de14492679727ef941b0d9ebd8982fe15c4/R/nest.R#L146

So that this check in `nest.tbl_df` passes cleanly:
https://github.com/tidyverse/tidyr/blob/56116de14492679727ef941b0d9ebd8982fe15c4/R/nest.R#L120

BUT for whatever reason when it is called in this way the `.key` is not reset to `"DEPRECATED"` when `NextMethod()` is called. So `check_key("data")` is run from `nest.tbl_df` and we get the warning.

I think the fix is to just move this check into the `if(missing(...))` branch, but man this is a weird one.
https://github.com/tidyverse/tidyr/blob/56116de14492679727ef941b0d9ebd8982fe15c4/R/nest.R#L140

**Comment by hadley** [comment]
It's possible that doing `NextMethod(.key = .key)` here https://github.com/tidyverse/tidyr/blob/56116de14492679727ef941b0d9ebd8982fe15c4/R/nest.R#L146 will also work.

**Comment by hadley** [comment]
Oops that didn't work

**Comment by DavisVaughan** [comment]
should be in the `.grouped_df` method?

**Comment by hadley** [comment]
I don't think that helps. The problem is that those changes make this test fail:

```R
test_that(".key gets warning with new interface", {
  df <- tibble(x = c(1, 1, 1), y = 1:3)
  expect_warning(out <- nest(df, y = y, .key = "y"), ".key", fixed = TRUE)
  expect_named(df, c("x", "y"))
})
```

Made I should just delete this test?

**Comment by hadley** [comment]
Ok, no, maybe I'm just confused.

**Comment by hadley** [comment]
I should've just asked to to make a PR for this :/

**Comment by DavisVaughan** [comment]
🤣
