### ISSUE TITLE
Use lifecycle package

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#703]
Flagging experimental, maturing, and retired functions.

And make sure that lazyeval functions are flagged as deprecated.

**Comment by katrinleinweber** [comment]
In the cases of [gather](https://github.com/tidyverse/tidyr/blame/492ea30113da6d4b4072e73dd5c70ef2cfd9cbc6/R/gather.R#L4-L8) & [spread](https://github.com/tidyverse/tidyr/blame/492ea30113da6d4b4072e73dd5c70ef2cfd9cbc6/R/spread.R#L4-L8), the badge creates a bit of a dissonance:

![grafik](https://user-images.githubusercontent.com/9948149/66208445-5cafb980-e6b5-11e9-87e1-fd10dd35f4b0.png)

From that and from [#726](https://github.com/tidyverse/tidyr/issues/726#issuecomment-529105530) I'm getting the impression that the pivot functions might not yet be recommended after all. If so, how about using [`stable`](https://www.tidyverse.org/lifecycle/#stable) and something like "keep an eye on pivot_..." to avoid confusion.

**Comment by hadley** [comment]
My comment was confusing — `pivot_wider()` and `pivot_longer()` are stable; it's the `col_types` specification that is not.
