### ISSUE TITLE
If names_to contains multiple values with missing levels pivot_longer fails.

### ISSUE THREAD

**Issue by banfai** [tidyverse/tidyr#716]
If there are multiple values in `names_to`, but they don't define a full grid, then `pivot_longer()` fails correctly impute NAs for the missing levels.

``` r
library(tibble)
library(tidyr)
df <- tribble(
  ~id, ~x_1, ~x_2, ~y_2,
  "A",    1,    2,  "a",
  "B",    3,    4,  "b",
)
pv <- pivot_longer(df, -id, names_to = c(".value", "n"), names_sep = "_")
#> `nm` must be `NULL` or a character vector the same length as `x`
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Expect outcome would be this:

``` r
library(tibble)
library(tidyr)
df <- tribble(
  ~id, ~x_1, ~x_2, ~y_2,
  "A",    1,    2,  "a",
  "B",    3,    4,  "b",
)
pv <- pivot_longer(df, -id, names_to = c(".value", "n"), names_sep = "_")
pv
#> # A tibble: 4 x 4
#>   id    n         x y    
#>   <chr> <chr> <dbl> <chr>
#> 1 A     1         1 <NA> 
#> 2 A     2         2 a    
#> 3 B     1         3 <NA> 
#> 4 B     2         4 b
```

It's going wrong in lines 162 and 166 of pivot_long.R, please see my attempt to fix it here:
https://github.com/banfai/tidyr/commit/3a55be89e7ebace60e8fb29347f02c110bc9af86

Also tried to add a test for it (passes with my version, fails with the current):
https://github.com/banfai/tidyr/commit/c909e180155af20f0cf35e32d8451023f8125b69

Let me know if I should submit a PR or if you want to review this issue in more detail.

**Comment by banfai** [comment]
Sorry, duplicate of #684, but my commit fixes that error, too:

``` r
library(tidyverse)
df = tibble(
  id = 1:5,
  score_t1 = sample(1:10, 5),
  score_t3 = sample(1:10, 5),
  rating_t1 = sample(1:100, 5),
  rating_t2 = sample(1:100, 5),
  rating_t3 = sample(1:100, 5)
)

df %>%
  pivot_longer(
    cols = -id,
    names_to = c(".value", "time"),
    names_pattern = c("([a-z]+)_t(\\d)")
  )
#> # A tibble: 15 x 4
#>       id time  score rating
#>    <int> <chr> <int>  <int>
#>  1     1 1         2     63
#>  2     1 3         1     84
#>  3     1 2        NA     87
#>  4     2 1         7     52
#>  5     2 3         9     16
#>  6     2 2        NA     36
#>  7     3 1         8     86
#>  8     3 3         6     15
#>  9     3 2        NA    100
#> 10     4 1         9     69
#> 11     4 3        10     27
#> 12     4 2        NA     49
#> 13     5 1         4     97
#> 14     5 3         3     47
#> 15     5 2        NA     92
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Oh nice, thanks! A PR would've been great, but I need to release soon so it's a bit late now (sorry!) so I'll include it today.
