### ISSUE TITLE
pivot_wider

### ISSUE THREAD

**Issue by SchollJ** [tidyverse/tidyr#718]
In pivot_wider, is it possible to specify the order of columns?
Example matrix:
columns, A, B, C, Model
I want to spread it to wide so that the new columns are:
A_Model1 B_Model1 C_Model1 A_Model2 B_Model2 C_Model2 etc.
But what I get with pivot_wider is:
A_ Model1 A_Model2 A_Model 3 B_Model1 etc.
And I couldn't figure out how to change the order? 
Many thanks

**Comment by hadley** [comment]
You can my creating a manual spec: https://tidyr.tidyverse.org/dev/articles/pivot.html#manual-specs
