### ISSUE TITLE
unnest fails with quosure list

### ISSUE THREAD

**Issue by tklebel** [tidyverse/tidyr#719]
I am updating the package [jstor](https://github.com/ropensci/jstor) and stumbled into an issue which seems related to https://github.com/tidyverse/tidyr/issues/644.

For some reason I have a `tibble` with a list-column that contains quosures. `unnesting` another column of that tibble fails with the error:
> Error: Can't slice a scalar

Here is a quick reprex:

``` r
library(tidyr)

capture_functions <- function(...) {
  dots <- rlang::enquos(..., .named = T)
  dots
}

funs <- capture_functions(mean)

tibble::tibble(a = 1, b = funs) %>% 
  unnest(a)
#> Error: Can't slice a scalar
```

<sup>Created on 2019-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I know that I can use `unnest_legacy` to "fix" the problem, just wanted to let you know of the issue.

**Comment by hadley** [comment]
Part of https://github.com/r-lib/vctrs/issues/559
