### ISSUE TITLE
several issues with pivot_wider and unnest_wider

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/tidyr#737]
On SO I ran into an[ example](https://stackoverflow.com/questions/49689927/unnest-a-list-column-directly-into-several-columns/57932001#57932001) where `pivot_wider()`, `unnest_wider()` could unleash its powers but it didn't make my life easy because of several details, see below. 

**Input**

```
+----+---------+----------+------+------+------+
| id |  type   |   name   | var1 | var2 | var3 |
+----+---------+----------+------+------+------+
| 10 | Country | Norway   |  169 | 14   |  164 |
| 10 | Sport   | Skii     |  169 | 14   |  164 |
| 10 | Format  | Video    |  169 | 14   |  164 |
| 11 | Country | Spain    |  150 | 16   |  178 |
| 11 | Format  | Photo    |  150 | 16   |  178 |
| 11 | Sport   | Bike     |  150 | 16   |  178 |
| 11 | Sport   | Soccer   |  150 | 16   |  178 |
| 11 | Sport   | Basket   |  150 | 16   |  178 |
| 12 | Country | USA      |    0 | 0    |    0 |
| 12 | Format  | Video    |    0 | NA   |    0 |
| 12 | Sport   | Baseball |    0 | 0    |    0 |
+----+---------+----------+------+------+------+
```

**Expected output**

```
+----+------+------+------+---------+--------+----------+---------+---------+
| id | var1 | var2 | var3 | Country | Format | Sport_1  | Sport_2 | Sport_3 |
+----+------+------+------+---------+--------+----------+---------+---------+
| 10 |  169 |   14 |  164 | Norway  | Video  | Skii     | NA      | NA      |
| 11 |  150 |   16 |  178 | Spain   | Photo  | Bike     | Soccer  | Basket  |
| 12 |    0 |    0 |    0 | USA     | Video  | Baseball | NA      | NA      |
+----+------+------+------+---------+--------+----------+---------+---------+
```

**data** 

```
df1 <- structure(list(id = c(10L, 10L, 10L, 11L, 11L, 11L, 11L, 11L, 
12L, 12L, 12L), type = c("Country", "Sport", "Format", "Country", 
"Format", "Sport", "Sport", "Sport", "Country", "Format", "Sport"
), name = c("Norway", "Skii", "Video", "Spain", "Photo", "Bike", 
"Soccer", "Basket", "USA", "Video", "Baseball"), var1 = c(169L, 
169L, 169L, 150L, 150L, 150L, 150L, 150L, 0L, 0L, 0L), var2 = c(14L, 
14L, 14L, 16L, 16L, 16L, 16L, 16L, 0L, NA, 0L), var3 = c(164L, 
164L, 164L, 178L, 178L, 178L, 178L, 178L, 0L, 0L, 0L)),
class = "data.frame", row.names = c(NA, 
-11L))
```

## *1st issue : value_fn is applied even when not needed*

It comes from the fact its behavior is ruled by the source column and not the destination, here I need it only for `Sport` but I get values of `Format` and `Country` as well : 

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list))
#> # A tibble: 3 x 7
#>      id  var1  var2  var3     Country       Sport      Format
#>   <int> <int> <dbl> <int> <list<chr>> <list<chr>> <list<chr>>
#> 1    10   169    14   164         [1]         [1]         [1]
#> 2    11   150    16   178         [1]         [3]         [1]
#> 3    12     0     0     0         [1]         [1]         [1]
```

Shouldn't the aggregation happen only when the destination column has elements with length !=1 ?

By the way, typing `list(name=list)` is a bit annoying here, why not just `values_fn = list` ? dplyr's `_at` functions allow either functions or list of functions, I've already made the mistake several times, and in some cases, typing `values_fn = list(foo = list, bar = list, baz = list)` just not to get the verbose message is a bit frustrating.

## *2nd issue : I can only unnest_wider one column at a time*

I first think that the fact that Country and Sport are lists is not a problem because I will `unnest_wider()` everything. But as far as I can tell I can't `unnest_wider` several columns at the same time, this strikes me as odd given the otherwise extreme flexibility of the new functions.

So I try those but they fail with an unhelpful error, forcing me to (gasp), read the doc : 

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  unnest_wider(5:7)
#> Error in .subset2(x, i) : no such index at level 2

df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  unnest_wider(one_of("Country","Sport","Format"))
#> Error in .subset2(x, i) : no such index at level 2
```

## *3rd issue : I can't convert vctrs objects intuitively*

I'm thinking OK, though it can be annoying in the general case, here I can just convert `Format` and `Country` to character as anyway I really to `unnest_wider()` the `Sport` column only, but I end up with weird values "<chr>" in my `Format` and `Country` columns : 

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  mutate_at(vars(Country, Format), as.character)
  
#> # A tibble: 3 x 7
#>        id  var1  var2  var3 Country       Sport Format
#>     <int> <int> <dbl> <int> <chr>   <list<chr>> <chr> 
#>   1    10   169    14   164 <chr>           [1] <chr> 
#>   2    11   150    16   178 <chr>           [3] <chr> 
#>   3    12     0     0     0 <chr>           [1] <chr> 
```

I then realise this is a `vctrs` issue (a bug possibly ?), so I use `unlist()` instead and it works fine (using inserting a `mutate_all(., unclass)` step to get rid of the *vctrs* classes worked too).

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  mutate_at(vars(Country, Format), unlist)
  
#> # A tibble: 3 x 7
#>      id  var1  var2  var3 Country       Sport Format
#>   <int> <int> <dbl> <int> <chr>   <list<chr>> <chr> 
#> 1    10   169    14   164 Norway          [1] Video 
#> 2    11   150    16   178 Spain           [3] Photo 
#> 3    12     0     0     0 USA             [1] Video 
```

## *4th issue : I can't `unnest_wider()` a vctrs list column*

and I get a cryptic error :  

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  mutate_at(vars(Country, Format), unlist) %>%
  unnest_wider(Sport, names_sep = "_")
# New names:
# * `` -> ...1
# New names:
# * `` -> ...1
# * `` -> ...2
# * `` -> ...3
# New names:
# * `` -> ...1
# Error: No common type for `x` <tbl_df<...1:character>> and `y` <character>.
```

I understand that it is again a vctrs error so I decide to unclass it, but `unnest_wider()` seems to accept only symbols, so the following fails : 

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  mutate_at(vars(Country, Format,), unlist) %>%
  unnest_wider(unclass(Sport), names_sep = "_")
#> Error in .f(.x[[i]], ...) : object 'Sport' not found
```

So I add another step and finally get : 

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  mutate_at(vars(Country, Format,), unlist) %>%
  mutate_at("Sport", unclass) %>%
  unnest_wider(Sport, names_sep = "_")

# New names:
# * `` -> ...1
# New names:
# * `` -> ...1
# * `` -> ...2
# * `` -> ...3
# New names:
#   * `` -> ...1
# # A tibble: 3 x 9
#      id  var1  var2  var3 Country Sport_...1 Sport_...2 Sport_...3
#   <int> <int> <dbl> <int> <chr>   <chr>      <chr>      <chr>     
# 1    10   169    14   164 Norway  Skii       NA         NA        
# 2    11   150    16   178 Spain   Bike       Soccer     Basket    
# 3    12     0     0     0 USA     Baseball   NA         NA        
# # ... with 1 more variable: Format <chr>
```

## *5th issue : the "repaired names" look bad*

names are repaired when they don't need to, so I have to design my own (not very robust) repairing function and get my expected output: 

```
df1 %>%
  replace_na(list(var2=0)) %>%
  pivot_wider(names_from = "type", values_from = "name", values_fn = list(name=list)) %>%
  mutate_at(vars(Country, Format), unlist) %>%
  mutate_at("Sport", unclass) %>%
  unnest_wider(Sport, names_sep = "_", names_repair = ~sub("..." , "", ., fixed=TRUE))

# New names:
# * `` -> ...1
# New names:
# * `` -> ...1
# * `` -> ...2
# * `` -> ...3
# New names:
# * `` -> ...1
# # A tibble: 3 x 9
#      id  var1  var2  var3 Country Sport_1  Sport_2 Sport_3 Format
#   <int> <int> <dbl> <int> <chr>   <chr>    <chr>   <chr>   <chr> 
# 1    10   169    14   164 Norway  Skii     NA      NA      Video 
# 2    11   150    16   178 Spain   Bike     Soccer  Basket  Photo 
# 3    12     0     0     0 USA     Baseball NA      NA      Video
```

This is a trick that I had to use [there ](https://stackoverflow.com/a/57935520/2270475)as well.

## *6th issue : I cannot get rid of verbose message*

Unless I use a `SuppressMessages()` call, or `purrr::quietly()` etc, I have to keep this red ink and don't have a parameter to turn it off.

This is not specific to this issue as I encountered it already in : 

* https://stackoverflow.com/a/57935520/2270475
* https://stackoverflow.com/a/57932001/2270475

So I had this issue in 3 questions out of 3 that I've answered so far using `unnest_wider()`

 
*conclusion : what I would have liked to work silently*

```
df1 %>%
 replace_na(list(var2=0)) %>%
 # just mention list in the values_fn function, or have a global option to turn verbosity off 
  pivot_wider(names_from = "type", values_from = "name", values_fn =list) %>%
  # not convert columns, not repair names
  unnest_wider(Sport, names_sep = "_")
# # A tibble: 3 x 9
#      id  var1  var2  var3 Country Sport_1  Sport_2 Sport_3 Format
#   <int> <int> <dbl> <int> <chr>   <chr>    <chr>   <chr>   <chr> 
# 1    10   169    14   164 Norway  Skii     NA      NA      Video 
# 2    11   150    16   178 Spain   Bike     Soccer  Basket  Photo 
# 3    12     0     0     0 USA     Baseball NA      NA      Video
```

The functions are great and fun to play with and I believe the code I came up with is still better than what I could come up with alternatives, but I also believe there was unnecessary friction to get there in that case.

**Comment by batpigandme** [comment]
Hi @moodymudskipper,

Could you please separate out the pieces of this that are (for lack of a better word) separate? We triage and track GitHub issues, and close them by using [GitHub keywords](https://help.github.com/en/articles/closing-issues-using-keywords) in commits, etc.

It's unlikely that all of these issues will have a single fix (e.g. verbosity is unrelated to the ability to `unnest_wider()` multiple columns at a time). I'll leave it to your discretion as to how to best divvy things up — or you can feel free to wait on Hadley's response if you like. But, for future reference, do please create separate issues.

**Comment by moodymudskipper** [comment]
I understand, I thought this might be interesting for you to witness the thought process as it's sometimes harder to understand the relevancy of separate issues. But I'll chop this one into separate issues and reference it.
