### ISSUE TITLE
Use .data in pack()

### ISSUE THREAD

**Issue by yusuzech** [tidyverse/tidyr#759]
In `dplyr` functions, the first argument are mostly `.data` to prevent possible conflicts. But in ` tidyr`, most functions use `data` as the first argument. And it creates an issue that when setting `data` as column name.

For example:

Since `data` is already used as the first argument of `pack()` function, when using "data" as a column, it will throw an error message. 

```r
df <- tibble(x1 = 1:3, x2 = 4:6, x3 = 7:9, y = 1:3)
df %>% pack(data = c(x1, x2, x3), y = y) 
```
throws an error message:
```r
Error: All elements of `...` must be named
```

The same applies to at least `pack`, `unpack`, `chop` and `unchop`

**Comment by dpprdan** [comment]
> The first argument of `nest()` has changed from `data` to `.data`.
([from tidyr changelog](https://tidyr.tidyverse.org/news/index.html#tidyr-1-0-0))

🤔 why was this only changed for `nest()`, but not for `unnest()`, `pack()` etc.?

**Comment by hadley** [comment]
@dpprdan it clearly just slipped my mind

**Comment by dpprdan** [comment]
And here I was thinking that there is a totally valid reason that I just did not get. 😄 

Relatedly in the consistent argument naming department: [`tibble::tibble()`](https://tibble.tidyverse.org/reference/tibble.html), [`vctrs::vec_c()`](https://vctrs.r-lib.org/reference/vec_c.html), and [others](https://principles.tidyverse.org/names-attribute.html) have a `.name_repair` argument, whereas the `unnest()` function family uses a `names_repair` argument for the same purpose. (I personally don't mind the (missing) dot so much as the plural 's').

**Comment by hadley** [comment]
I think this only applies to `pack()` and `unnest()`, because `chop()`, `unchop()`, and `unpack()` don't have `...`.

**Comment by hadley** [comment]
And `...` is deprecated in `unnest()`, so `pack()` is the only function that needs a fix.
