### ISSUE TITLE
new nest() breaks Rcpp code

### ISSUE THREAD

**Issue by PMSeitzer** [tidyverse/tidyr#760]
In Rcpp, One might have a function like
```
DataFrame process_nested_obj(const DataFrame& nested_tidyR_obj){

NumericVector col1 = nested_tidyR_obj["column1"];

     for (unsigned int i =0; i < col1.size(); i++){

               List nestedCol = col1[i];

               NumericVector nestedCol1Numeric = nestedCol["nested_column1"]

               for (unsigned int j =0; j < nestedCol1Numeric.size(); j++){
                          //do something with nestedCol1Numeric[j], etc
                }

       }

      //TODO: do more stuff, meaningful return, etc

      return DataFrame::create();
}
```

This no longer seems to work with the new `nest()`, because the object is no longer a `List`.

I was able to get around this issue by using `nest_legacy()`, however, I would imagine that if `nest_legacy()` is eventually deprecated and dropped, this could be a problem.

I would advise that (1) people are made aware of this change, and (2) `nest_legacy()` is never deprecated / dropped.  If it were, that would mean that `process_nested_obj()` would have to be re-written.

**Comment by hadley** [comment]
Can you please provide a reprex? The list-column return by `nest()` _is_ a list.

**Comment by PMSeitzer** [comment]
Hi @hadley, sorry for the long delay. I spent some time trying to devise a simplified `reprex` but ran into some complications. I will keep working on it.

In the mean time, I have a hypothesis - I believe the issue only occurs when there has been multiple internal `nest()`s.  `nest_legacy()` uses `list` while the new `nest()` uses data frames. 

From this document:
https://teuder.github.io/rcpp4everyone_en/070_data_types.html#data.frame-list-s3-s4
```
DataFrame is a vector that its elements are Vectors, List is a vector that its elements are any kinds of data types. Thus, Vector, DataFrame, List has many common member functions in Rcpp.
```
If that is true, then when a `DataFrame` trying to access a non-`Vector` data type, it should throw an error.  

In any event, the problem case would be reproduce with something like 
```
src <-
'
#include <Rcpp.h>
using namespace Rcpp;
using namespace std;

// [[Rcpp::export]]
DataFrame process_nested_obj(const DataFrame& nested_tidyR_obj){

     NumericVector first = nested_tidyR_obj["first"];
     List secondThirdAndFourth = nested_tidyR_obj["second_third_and_fourth"];

     for (unsigned int i=0; i < first.size(); i++){

              List secondThirdAndFourthData = secondThirdAndFourth[i];
              
             for (unsigned int j =0; j < secondThirdAndFourthData.size(); j++){
                          List doubleNestedList = secondThirdAndFourthData[j]
              }

      }

      return DataFrame::create();
}
'

sourceCpp(code=src)
```

Sorry could not be more helpful!

**Comment by hadley** [comment]
I think this should be fixed in the dev version, because the dev version of vctrs now adds "list" to the classes of a `list_of` object.
