### ISSUE TITLE
pivot_longer() needs names_convert argument

### ISSUE THREAD

**Issue by stragu** [tidyverse/tidyr#763]
`gather()` can use the `convert` argument to automagically recognise if gathered variable names should be stored as something different to a character vector, using `type.convert()`.

<details>
Are there any plans to bring back that alternative to the precise, longer-form `names_ptypes` argument? Or did I miss an explanation why it shouldn't?

Maybe something like `names_ptypes = "auto"`, maybe?
</details>

**Comment by hadley** [comment]
It does already do the equivalent of “auto” (in a way that is safe) — can you please provide a reprex describing your precise problem?

**Comment by stragu** [comment]
Thanks, @hadley . Sorry about the lack or reprex, I hesitated to include one for some reason.

Here goes:

```r
library(tibble)
# not tidy
df <- tribble(
  ~`1987`, ~`1988`, ~`1989`,
  34, 35, 36,
  45, 46, 47,
  52, 53, 54
)
library(tidyr)
df_long <- pivot_longer(df,
                        `1987`:`1989`,
                        names_to = "year",
                        values_to = "value")
typeof(df_long$year)
```
I would expect this to turn the years into integers.

Is this a case of converting not being safe?

**Comment by hadley** [comment]
Ah yes, I was confused — there's no equivalent of `convert()` and it would be nice to have one. Would presumably be `names_convert = TRUE`.

``` r
library(tidyr)
df <- tribble(
  ~`1987`, ~`1988`, ~`1989`,
  34, 35, 36,
  45, 46, 47,
  52, 53, 54
)

typeof(gather(df, "year", "value")$year)
#> [1] "character"
typeof(gather(df, "year", "value", convert = TRUE)$year)
#> [1] "integer"
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
No, I was right earlier and I was confused just now 😄 

For this case, you need to use `names_ptype`; if you want to guess automatically, I'd recommend `readr::parse_guess()`:

``` r
library(tidyr)
df <- tribble(
  ~`1987`, ~`1988`, ~`1989`,
  34, 35, 36,
  45, 46, 47,
  52, 53, 54
)

df %>% pivot_longer(everything(), names_ptypes = list(name = integer()))
#> # A tibble: 9 x 2
#>    name value
#>   <int> <dbl>
#> 1  1987    34
#> 2  1988    35
#> 3  1989    36
#> 4  1987    45
#> 5  1988    46
#> 6  1989    47
#> 7  1987    52
#> 8  1988    53
#> 9  1989    54

df %>% 
  pivot_longer(everything()) %>% 
  dplyr::mutate(name = readr::parse_guess(name))
#> # A tibble: 9 x 2
#>    name value
#>   <dbl> <dbl>
#> 1  1987    34
#> 2  1988    35
#> 3  1989    36
#> 4  1987    45
#> 5  1988    46
#> 6  1989    47
#> 7  1987    52
#> 8  1988    53
#> 9  1989    54
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
