### ISSUE TITLE
Warning message says " `cols` is now required" but should be `col`

### ISSUE THREAD

**Issue by simazhi** [tidyverse/tidyr#764]
Hi, 
I just wanted to report that when you use `unnest()` the warning message says:

>`cols` is now required.

But the variable is ` col `.
So I hope this discrepancy between the function arguments and the warning message can be resolved. 

Thanks for the new rectangling functions :)

**Comment by batpigandme** [comment]
The parameter in `unnest()` is `cols`: 
https://github.com/tidyverse/tidyr/blob/4618116a9296e0f11337c416966ea0f5a62f3732/R/nest.R#L211-L221

See also on pkgdown site here: https://tidyr.tidyverse.org/reference/nest.html

Could you point out where this discrepancy is coming from? Are you using a variable named `col`? If so, the error message is referring to the function parameter, and not your specific variable.

Thanks!

**Comment by simazhi** [comment]
Aha, thank you for your reply.
So yes, you're right.
But it seems I was confused with the parameter for columns in the new functions of `unnest_longer` and `unnest_wider`.

So as you said: 
```
unnest <- function(data,
                   cols,
                   ...,
                   keep_empty = FALSE,
                   ptype = NULL,
                   names_sep = NULL,
                   names_repair = "check_unique",
                   .drop = deprecated(),
                   .id = deprecated(),
                   .sep = deprecated(),
                   .preserve = deprecated()) {
```

but for `unnest_longer` it says:

```
unnest_longer <- function(data, col,
                          values_to = NULL,
                          indices_to = NULL,
                          indices_include = NULL,
                          names_repair = "check_unique",
                          simplify = TRUE,
                          ptype = list()
                          ) {
```
and for `unnest_wider` too:

```
unnest_wider <- function(data, col,
                         names_sep = NULL,
                         simplify = TRUE,
                         names_repair = "check_unique",
                         ptype = list()) {
```
(I'm sorry, this my first time commenting and I can't figure out how to copy from the source code in here, so I just copied it manually).

My point is, I did probably have the wrong help file open as I was learning the new functions, but it would be slightly easier if the variable for 'column(s?)' had the same name in the three functions. Unless there is of course a specific reason -- say that you can't have `unnest_longer` or `unnest_wider` multiple columns (I haven't tried).

So other than the suggestion of using the same name for the argument, my issue is solved.
Thanks for your reply earlier.

**Comment by batpigandme** [comment]
Glad that cleared things up.

> Unless there is of course a specific reason -- say that you can't have unnest_longer or unnest_wider multiple columns

This is the case. 🙂
