### ISSUE TITLE
Regrettable error message

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyr#774]
This is what happens when `unnest_wider()` is going to produce a column name collision.

``` r
library(tibble)
library(tidyr)

(df <- tibble(
  id = 1:2,
  stuff = list(
    list(id = "one", foo = "a"),
    list(id = "two", foo = "b")
  )
))
#> # A tibble: 2 x 2
#>      id stuff           
#>   <int> <list>          
#> 1     1 <named list [2]>
#> 2     2 <named list [2]>

df %>%
  unnest_wider(stuff)
#> Column name `id` must not be duplicated.
#> Use .name_repair to specify repair.
```

This error comes from tibble and refers to `.name_repair`. But tidyr uses `names_repair`. So doing what the error message says also fails.

``` r
df %>%
  unnest_wider(stuff, .name_repair = "unique")
#> Error in unnest_wider(., stuff, .name_repair = "unique"): unused argument (.name_repair = "unique")
```

This succeeds, which requires reading the docs for `unnest_wider()`.

``` r
df %>%
  unnest_wider(stuff, names_repair = "unique")
#> New names:
#> * id -> id...1
#> * id -> id...2
#> # A tibble: 2 x 3
#>   id...1 id...2 foo  
#>    <int> <chr>  <chr>
#> 1      1 one    a    
#> 2      2 two    b
```

<sup>Created on 2019-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
I don't yet know how we're going to resolve this one. 

@lionel- do you have any ideas?

**Comment by lionel-** [comment]
We could wrap all tidyr implementations in `subclass_tidyr_errors()`. Ideally all arguments would have the same name. Given how packages are becoming intertwined, distant consistency is becoming as important as local consistency.

**Comment by lionel-** [comment]
Probably best to allow for a `names_repair_arg` condition field that the condition-message method would pick up from vctrs, this way the error message is still generated upstream.

**Comment by hadley** [comment]
The "good" news is that we no longer give a bad hint:

``` r
library(tidyr)

df <- tibble(
  id = 1:2,
  stuff = list(
    list(id = "one", foo = "a"),
    list(id = "two", foo = "b")
  )
)
df %>% unnest_wider(stuff)
#> Error: Column name `id` must not be duplicated.
```

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Trying to track down who used to be responsible for this. Was it tibble? https://github.com/tidyverse/tibble/issues/765. Was it vctrs? 

Or maybe tidyr should handle this case itself?

**Comment by hadley** [comment]
Somewhat more minimal reprex (since `pack()` is the root cause)

``` r
library(tidyr)

df <- tibble(
  id = 1:2,
  stuff = tibble(id = c("one", "two"))
)
df %>% unpack(stuff)
#> Error: Column name `id` must not be duplicated.
```

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
If I do it myself (instead of relying on tibble, I get the slightly more helpful):

```R
#> Error: Names must be unique.
#> x These names are duplicated:
#>   * "id" at locations 1 and 2.
```
