### ISSUE TITLE
No variable new column name in nest()?

### ISSUE THREAD

**Issue by kaneplusplus** [tidyverse/tidyr#779]
There is not a good way to provide a variable name for a nested column in the new `nest()` function.

For example, the following code does not produces a data frame with a nested column named "another name". Also, this can't be fixed by using `rlang`'s curly brackets since it's on the left side of the parameter assignment.

```{r}
df <- tibble(x = c(1, 1, 1, 2, 2, 3), y = 1:6, z = 6:1)

my_nest <- function(x, new_col_name, dots) { 
     x %>% nest(new_col_name = dots)
}

my_nest(df, "another name", c("y", "z"))
```

The only solution I've been able to come up with, which doesn't involve using deprecated functionality, is to write the expression `x %>% nest(new_col_name = dots)` as a string in the function, string substitute, parse, and eval. However, this seems like a step backwards from `nest()`'s previous incarnation.

**Comment by cderv** [comment]
I think you can use `{{ }}` for this usage. You'll just need to use with it the special operator `:=` to be able to unquote on the LHS. See [`?rlang::quasiquotation`](https://rlang.r-lib.org/reference/quasiquotation.html)
See also the vignette in dplyr about [setting variable name](https://dplyr.tidyverse.org/articles/programming.html#setting-variable-names)
``` r
library(tidyr)
df <- tibble::tibble(x = c(1, 1, 1, 2, 2, 3), y = 1:6, z = 6:1)

my_nest <- function(x, new_col_name, dots) { 
  x %>% nest({{new_col_name}} := dots)
}

my_nest(df, "another name", c("y", "z"))
#> # A tibble: 3 x 2
#>       x `another name`
#>   <dbl> <list<df[,2]>>
#> 1     1        [3 x 2]
#> 2     2        [2 x 2]
#> 3     3        [1 x 2]
```

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

For this type of question, do not hesitate to ask on https://community.rstudio.com, there is a broader community there ready to help you !
