### ISSUE TITLE
Incoherent group size in a nested tibble.

### ISSUE THREAD

**Issue by BillBlanc** [tidyverse/tidyr#786]
Hello,

The length of the group size is now wrong in a nested tibble ; therefore, `mutate()` is not possible.

Many thanks to the team for these SUP libraries.

Yours sincerely,
Bill Blanc

``` r
library(tidyverse)
library(dplyr)

# THE ERROR : 
(iris %>%
    group_by(Species) %>%
    nest() %>%
    mutate(num = 1:3))
#> Error: Column `num` must be length 1 (the group size), not 3


# A wrong group size ?
Iris <- iris %>%
  group_by(Species) %>%
  nest()

length(Iris$Species) 
#> [1] 3

# Is ungroup() mandatory prior to mutate() ?
(Oris <- iris %>%
    group_by(Species) %>%
    nest() %>%
    ungroup() %>%
    mutate(num = 1:3))

#> # A tibble: 3 x 3
#>   Species              data   num
#>   <fct>      <list<df[,4]>> <int>
#> 1 setosa           [50 x 4]     1
#> 2 versicolor       [50 x 4]     2
#> 3 virginica        [50 x 4]     3
```

<sup>Created on 2019-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
  
``` 

SessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

**Comment by jennybc** [comment]
You're bumping against a behaviour that was intentionally added in tidyr v1.0.0. Grouping is now retained after `nest()`.

There a section on this in the new vignette "In Packages". Don't be discouraged by the name; much of this content is relevant to non-package code as well:

<https://tidyr.tidyverse.org/articles/in-packages.html#nest-preserves-groups>

Here are some options for better ways to can introduce the vector `1:3`. The main theme is to try to compute "inside the data frame", as opposed to bringing in an external variable. That is, do something that guarantees the right elements end up in the right positions/rows.

  * Use a `mutate()` call that honours the group structure, i.e. works within the groups.
  * Join data in from a second table that explicitly maps new values to the grouping var(s).

``` r
library(tidyverse)

(iris_grouped <- iris %>%
    group_by(Species) %>%
    nest())
#> # A tibble: 3 x 2
#> # Groups:   Species [3]
#>   Species              data
#>   <fct>      <list<df[,4]>>
#> 1 setosa           [50 × 4]
#> 2 versicolor       [50 × 4]
#> 3 virginica        [50 × 4]

iris_grouped %>% 
  mutate(num = unclass(Species))
#> # A tibble: 3 x 3
#> # Groups:   Species [3]
#>   Species              data   num
#>   <fct>      <list<df[,4]>> <int>
#> 1 setosa           [50 × 4]     1
#> 2 versicolor       [50 × 4]     2
#> 3 virginica        [50 × 4]     3

lookup <- tribble(
  ~Species, ~num,
  "setosa",   1L,
  "versicolor", 2L,
  "virginica", 3L
)
iris_grouped %>% 
  left_join(lookup)
#> Joining, by = "Species"
#> Warning: Column `Species` joining factor and character vector, coercing
#> into character vector
#> # A tibble: 3 x 3
#> # Groups:   Species [3]
#>   Species              data   num
#>   <chr>      <list<df[,4]>> <int>
#> 1 setosa           [50 × 4]     1
#> 2 versicolor       [50 × 4]     2
#> 3 virginica        [50 × 4]     3

iris_grouped %>% 
  add_column(num = 1:3)
#> # A tibble: 3 x 3
#> # Groups:   Species [3]
#>   Species              data   num
#>   <fct>      <list<df[,4]>> <int>
#> 1 setosa           [50 × 4]     1
#> 2 versicolor       [50 × 4]     2
#> 3 virginica        [50 × 4]     3
```

<sup>Created on 2019-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

I ended with a very pragmatic option: use `tibble::add_column()`, which ignores the grouping. That still seems slightly better than another very pragmatic option, which is to `ungroup()`. Unless, of course, you really want to lose the grouping structure!

**Comment by BillBlanc** [comment]
At first, I left out the new vignette *In package* and I agree with you that much of its content is relevant to any piece of code ; is it appropriate to change this name ?

Indeed, Tidyr's response to the problem raised previously was confusing because false ; its origin difficult to guess wrt my present understanding of the library. 

I appreciate your detailed response and the philosophy of using nested list vectors. They seem to preserve valuable RAM in the case of structured randomization tests.
Many thanks,
Best regards
Bill

**Comment by BillBlanc** [comment]
Hello Jenny,

Thank you for your early reply.

At first, I left out the new vignette *In package *and without your express
recommendation, I probably would never have read it !

I agree with you that much of its content is relevant to any piece of code
; is it appropriate to change this name or some contents of the new Tidyr
vignette ?

Indeed, Tidyr's response to the problem raised previously was confusing
(the group length is not the group size) but its origin difficult to guess
wrt my present understanding.

I appreciate your detailed responses and the philosophy of using nested
list vectors. Also, `unnest ()` is useful in data augmentation within
nested group levels. The new features are easier to remember and it is a
pleasure to work with this new version that matures towards simplification.
The solutions being effective, I closed the issue.


Many thanks,
Best regards.
Bill
