### ISSUE TITLE
v1.0.0 blog post doesn't show up in main pkgdown site

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyr#787]
I see the v1.0.0 blog post is listed in `_pkgdown.yml`.

But it's only visible in the News dropdown on the dev site, presumably the version got bumped before the post was added.

**Comment by hadley** [comment]
Yeah, this is one of the problems with our current workflow - the blog post is always published after we have bumped the dev version.

**Comment by hadley** [comment]
But fixed as part of my google analytics repair
