### ISSUE TITLE
Fails to unnest list of matrices

### ISSUE THREAD

**Issue by jeffreypullin** [tidyverse/tidyr#788]
When you try to unnest a data.frame/tibble with a list column of matrices you get a rather scary looking `vctrs` error:

``` r
A <- matrix(1:4, nrow = 2, ncol = 2)
B <- 1:2
  
C <- tibble::tibble(a = list(A, A), b = list(B, B))

tidyr::unnest(C, cols = c(a, b))
#> Error in vec_rbind(!!!x, .ptype = ptype): Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```
<sup>Created on 2019-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think it's possible to unnest matrix columns sensibly (I was doing so by mistake) so I guess this should just error more informatively. 

Thanks for all your work on tidyr!

**Comment by DavisVaughan** [comment]
Likely related to https://github.com/r-lib/vctrs/issues/625

**Comment by jeffreypullin** [comment]
@DavisVaughan I'd say definitely - `vec_rbind` calls `df_assign` which calls `vec_assign_impl`!
