### ISSUE TITLE
pivot_longer is quadratic in number of input columns to reshape

### ISSUE THREAD

**Issue by tdhock** [tidyverse/tidyr#794]
Hi @lionel-  @hadley first of all thanks for your great package, it is really fascinating and inspiring!

I have been performance testing `tidyr::pivot_longer`, which seems to be quadratic in the number of input columns to reshape, when `names_to` contains `".value"` and several output columns are generated. but I expected the timings to be linear in the input size! Here is a figure that shows significant slowdowns after about 10,000 input columns:

![figure-iris-cols](https://user-images.githubusercontent.com/932850/67725382-6d470d00-f99f-11e9-907f-d93a2ade2e14.png)

- script to compute timings: https://github.com/tdhock/nc-article/blob/master/figure-iris-cols-data.R
- script to make figures: https://github.com/tdhock/nc-article/blob/master/figure-iris-cols.R

a simplified version of the timings script which only has tidyr code is:
```r
N.rep <- 10000
i.vec <- 1:N.rep
L <- lapply(i.vec, function(i)iris[, 1:4])
names(L) <- i.vec
L[["0"]] <- iris
some.iris <- do.call(data.frame, L)
pattern <- "X(.*)[.](.*)[.](.*)"
system.time({
  result <- tidyr::pivot_longer(
    some.iris,
    grep(pattern, names(some.iris)),
    names_to=c("before", ".value", "dim"),
    names_pattern=pattern)
})
```
I expected that computation time should be linear in `N.rep` but it appears to be quadratic. To fix that issue you may check into how `data.table` is doing it, because they seem to have implemented a linear time algorithm.

I also checked `pivot_longer` without `.value` in `names_to` and that seems to be linear:
![figure-who-cols-minimal](https://user-images.githubusercontent.com/932850/67726607-a6817c00-f9a3-11e9-99ac-9f55c2f93429.png)

**Comment by tdhock** [comment]
i confirm that fixes my issue, thanks for the help.
![figure-iris-cols-new](https://user-images.githubusercontent.com/932850/67802789-11d15980-fa49-11e9-947d-2653ae438f0d.png)

**Comment by lionel-** [comment]
Thanks for the nice report!
