### ISSUE TITLE
nest to reverse unnest's name_sep

### ISSUE THREAD

**Issue by dah33** [tidyverse/tidyr#797]
`unnest` includes `name_sep` which forms the names of the new columns by pasting together the outer column name with the inner names, separated by `names_sep`.

It would be great if `nest` had a feature to reverse this action: to remove the outer column name and the separator.

https://tidyr.tidyverse.org/reference/nest.html

**Comment by hadley** [comment]
``` r
library(tidyr)

df <- iris %>% 
  as_tibble() %>% 
  nest(Sepal = starts_with("Sepal"), Petal = starts_with("Petal"))

names(df$Sepal[[1]])
#> [1] "Sepal.Length" "Sepal.Width"
```

<sup>Created on 2019-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Same idea as #795, but for `nest()` rather than `pack()`
