### ISSUE TITLE
crossing() does not respect .name_repair

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/tidyr#798]
It seems that `crossing()` either does not respect the value of `.name_repair` or does not see this parameter:

``` r
vals <- c("v", "h")
tidyr::crossing(vals, vals, vals, vals, .name_repair = "unique")
#> Error: Column names `vals`, `vals`, `vals` must not be duplicated.
#> Use .name_repair to specify repair.
```

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`tibble()` does not fail in this situation:

``` r
vals <- c("v", "h")
tidyr::tibble(vals, vals, vals, vals, .name_repair = "unique")
#> New names:
#> * vals -> vals...1
#> * vals -> vals...2
#> * vals -> vals...3
#> * vals -> vals...4
#> # A tibble: 2 x 4
#>   vals...1 vals...2 vals...3 vals...4
#>   <chr>    <chr>    <chr>    <chr>   
#> 1 v        v        v        v       
#> 2 h        h        h        h
```

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This looks like a fairly straightforward fix — `expand()` needs to get a `.name_repair` argument that gets passed on to `flatten_nested()`, which needs to get a `.name_repair` argument that's passed on to `tibble()`. `expand()` and `expand_grid()` would also need similar treatment.
