### ISSUE TITLE
Error message when pivot_longer input has a name column and names_to is defaulted

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/tidyr#799]
If the input data frame has a column called `name` and `names_to` is not specified it will try to generate a second `name` column and give an error message which could be better ,  Right now it just refers to duplicated names even though the input does not have duplicated names.  Also it does not identify the duplicated column  name making it doubly mysterious.

```
Lines <- "pokedex_number name type1 type2 defense hp attack sp_attack sp_defense speed base_total
1 Bulbasaur grass poison 49 45 49 65 65 45 318"
DF <- read.table(text = Lines, as.is = TRUE, header = TRUE)


DF %>% pivot_longer(starts_with("type"), values_to = "type")
## Error: Failed to create output due to bad names.
## Choose another strategy with `names_repair`
## Parents:
##  -Names must be unique.
## Call `rlang::last_error()` to see a backtrace

```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by ggrothendieck** [comment]
reprex failed with this message.  (pandoc is installed and is on the path.)
```
Error: callr subprocess failed: pandoc document conversion failed with error 97
```

**Comment by hadley** [comment]
This is as expected — you need to choose a name repair strategy with `name_repair`:

``` r
library(tidyr)

Lines <- "pokedex_number name type1 type2 defense hp attack sp_attack sp_defense speed base_total
1 Bulbasaur grass poison 49 45 49 65 65 45 318"
DF <- read.table(text = Lines, as.is = TRUE, header = TRUE)

DF %>% 
  pivot_longer(starts_with("type"), values_to = "type")
#> Error: Failed to create output due to bad names.
#> * Choose another strategy with `names_repair`

DF %>% 
  pivot_longer(starts_with("type"), values_to = "type", names_repair = "unique")
#> New names:
#> * name -> name...2
#> * name -> name...10
#> # A tibble: 2 x 11
#>   pokedex_number name...2 defense    hp attack sp_attack sp_defense speed
#>            <int> <chr>      <int> <int>  <int>     <int>      <int> <int>
#> 1              1 Bulbasa…      49    45     49        65         65    45
#> 2              1 Bulbasa…      49    45     49        65         65    45
#> # … with 3 more variables: base_total <int>, name...10 <chr>, type <chr>
```

<sup>Created on 2019-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've never seen that reprex problem before; you might want to ask for help on the reprex repro, because providing reprexes makes it much easier for me to process issues.
