### ISSUE TITLE
Make pivot_longer and pivot_wider generic

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#800]

**Comment by chester-gan** [comment]
Specific feature request: please enable pivot_longer's values_ptypes argument to handle exceptional cases whereby the input columns used to generate the variables generated from values_to are not of the same type.

**Comment by hadley** [comment]
@chester-gan please file an issue with reprex; commenting on unrelated issues is not a good way to get help.

**Comment by chester-gan** [comment]
> @chester-gan please file an issue with reprex; commenting on unrelated issues is not a good way to get help.

Noted, filed under reprex.
