### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyr#805]
If you forget to specify the `col` which `unnest_wider()` should act on, it complains that `x` is missing. Feels like that should be `col`. It's not entirely clear to me if this is a tidyr or tidyselect problem

``` r
library(tidyverse)

df <- tibble(
  z = list(list(letter = "a"), list(letter = "b"))
)

df %>% 
  unnest_wider(z)
#> # A tibble: 2 x 1
#>   letter
#>   <chr> 
#> 1 a     
#> 2 b

df %>% 
  unnest_wider()
#> Error: argument "x" is missing, with no default
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

cc @lionel-

**Comment by lionel-** [comment]
I think we should compact missing arguments the same way we compact `NULL`.

```r
tidyselect::eval_select(quote(c(NULL, NULL)), iris)
#> named integer(0)

tidyselect::eval_select(quote(c(, )), iris)
#> Error: argument "x" is missing, with no default
```

But also tidyr should either give a default value of `NULL` to signal the argument is optional, or explicitly check that it is empty.

**Comment by jennybc** [comment]
I've been poking around other tidyr functions and many of them display the same problem (`unpack()`, other rectangling functions). Basically whenever a missing, e.g., `.col` is immediately handled via`enquo(.col)`, it prevents the standard message 'argument ".col" is missing, with no default' and, by the time it's emitted, the complaint is about "x".

**Comment by hadley** [comment]
@lionel- the code is currently:

```R
col <- tidyselect::vars_select(tbl_vars(data), !!enquo(col))
```

which will become:

```R
col <- tidyselect::vars_select(tbl_vars(data), {{ col }})
```

So it seems to me that it should be tidyselect's (or `{{`'s?) responsibility to trigger the correct error

**Comment by lionel-** [comment]
`{{` cannot give an error with missing arguments because it is valid to defuse them (and they can be inspected with `quo_is_missing()`).

I was thinking tidyselect would not treat it as an error, but as an empty selection. This makes `NULL` and missing arguments consistent. Then it makes sense for tidyr to make these explicitly optional by taking a default of `NULL`. If tidyr prefers to keep this an error, it'd have to check that the argument is missing.

**Comment by hadley** [comment]
@lionel- so you think I should be doing `if (missing(col)) abort("Argument `col` is missing with no default")`?

**Comment by hadley** [comment]
Can you help me understand why it's different to this?

``` r
library(rlang)

x <- expr()
expr(!!x)
#> Error in enexpr(expr): argument "x" is missing, with no default
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
In your example the missing argument is not wrapped in a quosure. Normally it would be wrapped via `enquo()` or `{{`.

```r
x <- quo()
expr(!!x)
#> <quosure>
#> expr: ^
#> env:  empty
```

**Comment by hadley** [comment]
Oh duh, yeah, still seems weird that I need to manually check that `col` exists.
