### ISSUE TITLE
nest strips off the class to `data.frame` if input is not a tibble

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/tidyr#818]
For example with a *data.table* : 

``` r
library(tidyverse, warn.conflicts = F)
library(data.table, warn.conflicts = F)
df  <- tibble(x = c(1, 1, 1, 2, 2, 3), y = 1:6, z = 6:1)
dt <- as.data.table(df)
df %>% nest(data = c(y, z)) %>% class()
#> [1] "tbl_df"     "tbl"        "data.frame"
dt %>% nest(data = c(y, z)) %>% class()
#> [1] "data.frame"
```

<sup>Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Some *tidyverse* functions don't modify the input's class and some coerce to `tbl_df`, I think it would be more intuitive to pick one of those 2 behaviors for `nest`.

**Comment by hadley** [comment]
This is a vctrs issue — https://github.com/r-lib/vctrs/issues/694
