### ISSUE TITLE
document difference between unnest_longer and unchop ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/tidyr#819]
The conceptual difference between them is not obvious to me and they don't refer to each other in their help pages, which I feel would be helpful.

> unchop() makes df longer by expanding list-columns so that each element of the list-column gets its own row in the output.

> unnest_longer() preserves the columns, but changes the rows, Or if you unnest_longer() a list of data frame, the number of columns must be preserved so it creates a packed column.

Contrasting examples would help too, as of now all examples of `unnest_longer()` can be done with `unchop()`, except for 1, and the latter contradicts the principle above as it adds a column.

My own fuzzy understanding is that I will have generally more flexibility with `unnest_longer()` thanks to the additional arguments, as long as my column elements are of the same type, if they're not, or if I want to strongly enforce that I won't create columns, or if I want to remove rows containing a zero length element in a given column, I should use `unchop()`.

**unnest_longer() example 1**

``` r
library(tidyr)
df <- tibble(
  character = c("Toothless", "Dory"),
  metadata = list(
    list(
      species = "dragon",
      color = "black",
      films = c(
        "How to Train Your Dragon",
        "How to Train Your Dragon 2",
        "How to Train Your Dragon: The Hidden World"
      )
    ),
    list(
      species = "clownfish",
      color = "blue",
      films = c("Finding Nemo", "Finding Dory")
    )
  )
)

identical(
  df %>%
  unnest_wider(metadata) %>%
  unnest_longer(films),
  df %>%
  unnest_wider(metadata) %>%
  unchop(films))
#> [1] TRUE
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**unnest_longer() example 2**

``` r
library(tidyr)
df <- tibble(
  x = 1:3,
  y = list(NULL, 1:3, 4:5)
)
identical(
  df %>% unnest_longer(y),
  df %>% unchop(y,keep_empty = T))
#> [1] TRUE
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**unnest_longer() example 3**

In this one `unnest_longer()` and  `unchop()` work differently, but `unnest_longer()` creates a new column, which goes against the bit quoted above  : 

``` r
library(tidyr)
df <- tibble(
  x = 1:2,
  y = list(c(a = 1, b = 2), c(a = 10, b = 11, c = 12))
)
df %>% unnest_longer(y)
#> # A tibble: 5 x 3
#>       x     y y_id 
#>   <int> <dbl> <chr>
#> 1     1     1 a    
#> 2     1     2 b    
#> 3     2    10 a    
#> 4     2    11 b    
#> 5     2    12 c
df %>% unchop(y)
#> # A tibble: 5 x 2
#>       x     y
#>   <int> <dbl>
#> 1     1     1
#> 2     1     2
#> 3     2    10
#> 4     2    11
#> 5     2    12
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**`unchop()` examples**

Examples 1 and 3 of `unchop()` are also equivalent or similar using `unnest_longer()`, 2nd example shows however that `unchop()` is tolerant to having different data types in a list column while `unnest_longer()` is not but it's not very clear why, and the error message is not very helpful (and I think there's a few words missing in the comment :) ) : 

``` r
library(tidyr)
# Incompatible types -------------------------------------------------
# If the list-col contains types that can not be natively              <<<-------- unfinished sentence
df <- tibble(x = 1:2, y = list("1", 1:3))
try(df %>% unchop(y))
#> Error : No common type for `..1$y` <character> and `..2$y` <integer>.
try(df %>% unnest_longer(y))
#> Error : No common type for `..1$y$y` <character> and `..2$y$y` <integer>.
df %>% unchop(y, ptype = tibble(y = integer()))
#> # A tibble: 4 x 2
#>       x     y
#>   <int> <int>
#> 1     1     1
#> 2     2     1
#> 3     2     2
#> 4     2     3
df %>% unnest_longer(y, ptype = tibble(y = integer()))
#> Error: No common type for `..1$y$y` <character> and `..2$y$y` <integer>.

```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
It's pretty easy to see what's going on if you look at the source code — `unnest_longer()` and `unnest_wider()` are wrappers around `unchop()` that call `vec_to_long()` or `vec_to_wider()` before unchop, and call `simplify_cols()` afterwards. I'll clarify that we don't expect most people to use `chop()`/`unchop()`.
