### ISSUE TITLE
Variable evaluation for value_fn list in pivot_wider

### ISSUE THREAD

**Issue by amirmazmi** [tidyverse/tidyr#826]
For pivot_wider, how can I dynamically refer to a column name for values_fn? I am aware of quosures but my attempts did not work. 

I have the following data:  

|| Datetime | MeasureValue | ObjectName |
|--- | --- | --- |--- |
2  | 2019-10-01 00:00:00  |  7.00000  |  Temp1 |
4  | 2019-10-01 00:00:00  |  7.00000  |  Temp2 |
6  | 2019-10-01 00:00:00  |  6.99875  |  Temp3 |
8  | 2019-10-01 00:00:00  |  6.96781  |  Temp4 |
10 | 2019-10-01 00:01:00  |  7.00000  |  Temp1 |
12 | 2019-10-01 00:01:00  |  7.00000  |  Temp2 |
14 | 2019-10-01 00:01:00  |  6.99875  |  Temp3 |
16 | 2019-10-01 00:01:00  |  6.96781  |  Temp4 |
18 | 2019-10-01 00:02:00  |  7.00000  |  Temp1 |
20 | 2019-10-01 00:02:00  |  7.00000  |  Temp2 |
22 | 2019-10-01 00:02:00  |  6.99875  |  Temp3 |
24 | 2019-10-01 00:02:00  |  6.96781  |  Temp4 |
26 | 2019-10-01 00:03:00  |  7.00000  |  Temp1 |
28 | 2019-10-01 00:03:00  |  7.00000  |  Temp2 |
30 | 2019-10-01 00:03:00  |  6.99875  |  Temp3 |
32 | 2019-10-01 00:03:00  |  6.96781  |  Temp4 |

<br>  

During analysis, the input for pivot_wider is below and it works
&nbsp; &nbsp; &nbsp; &nbsp; values_fn=list( MeasureValue=mean)

<br>  
Trying to assign it to a variable also works:  

```r
coln_select <- c("Datetime", "MeasureValue", "ObjectName")
mean_var <- quo( coln_select[2])
dfwide <- dflong %>%
                        # aggregate to minute first
                        mutate( Datetime=floor_date( ymd_hms(coln_select[1]),
                                                     unit="minute") ) %>%
                        pivot_wider(id_cols=coln_select[1],names_from=coln_select[3],
                                    values_from=!!mean_var, 
                                    values_fn=list( mean_var=mean ) ) 
```
<br>  
But when i try to wrap it into a function, this does not work. 

```r
pivotData <- function(dflong, columns, agg_period="minute"){
            coln_select <- columns
            mean_var <- quo( coln_select[2])
            dfwide <- dflong %>%
                    # aggregate to minute first
                    mutate( Datetime=floor_date( ymd_hms(coln_select[1]),
                                                 unit=agg_period) ) %>%
                    pivot_wider(id_cols=coln_select[1],names_from=coln_select[3],
                                values_from=!!mean_var, 
                                values_fn=list( mean_var=mean ) ) 
            return(dfwide)
}


pivotData( dflong, c("Datetime", "MeasureValue", "ObjectName") )
```
<br> 
The error i get is 

```r
Error in source("pivotscript.R") : pivotscript.R:74:60: unexpected '='
```
<br>  
or 

```r
Warning messages:
1: All formats failed to parse. No formats found. 
2: Values in `MeasureValue` are not uniquely identified; output will contain list-cols.
* Use `values_fn = list(MeasureValue = list)` to suppress this warning.
* Use `values_fn = list(MeasureValue = length)` to identify where the duplicates arise
* Use `values_fn = list(MeasureValue = summary_fun)` to summarise duplicates 
```

**Comment by hadley** [comment]
This is much easier in the development version, because you can just do `values_fn = list(mean)`.  For the current version, the easiest way to create a named list is with `setNames(list(mean), mean_var)`
