### ISSUE TITLE
unite()'s interface feels inconsistent now with nest() and pack()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyr#827]
I'm using `unite()` for the first time since helping with the v1.0.0 release and its interface now feels surprising relative to to how `nest()` works.

**Comment by hadley** [comment]
That's because `unite()` is more in the vein of `separate()` and `extract()` 😬

**Comment by hadley** [comment]
Another thought: `unite()` is now just paste with `mutate(.keep = "unusued")`

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tidyr::expand_grid(x = c("a", NA), y = c("b", NA))

df %>% tidyr::unite("z", x:y)
#> # A tibble: 4 x 1
#>   z    
#>   <chr>
#> 1 a_b  
#> 2 a_NA 
#> 3 NA_b 
#> 4 NA_NA

df %>% mutate(z = paste(x, y, sep = "_"), .keep = "unused")
#> # A tibble: 4 x 1
#>   z    
#>   <chr>
#> 1 a_b  
#> 2 a_NA 
#> 3 NA_b 
#> 4 NA_NA
```

<sup>Created on 2020-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I'm counting this as being part of #939, especially since it is explicitly mentioned as a bullet there already
