### ISSUE TITLE
group_by + nest seems very slow on big tibble with many groups

### ISSUE THREAD

**Issue by tangcxx** [tidyverse/tidyr#828]
It's a tibble with 7 million rows and 7 cols. The col for group_by has 300 thousands unique string value.

First I try this:
```r
df_nested <- df %>% group_by(key) %>% nest()
```
It runs more than two hours and still not finished. 
I thought there may be sth wrong. So I write a function to do this:

```r
f <- function(df, groupname, nbtch = 3000){
  keys <- unique(df[[groupname]])
  nkey <- length(keys)
  map_dfr(1:ceiling(nkey/nbtch), function(x){
    eval(parse(text = str_c("df %>% filter(df[[groupname]] %in% keys[(nbtch*x-nbtch+1):(nbtch*x)]) %>% group_by(", groupname,") %>% nest() %>% ungroup()")))
  })
}
```
This time it takes only a few minutes.

Is there sth wrong with nest()?

**Comment by hadley** [comment]
I'd recommend trying the dev version where we have already many some large performance improvements. See #751 for details
