### ISSUE TITLE
FR: Rectangling a list according to a specification

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#835]
Some time ago I have written a function for rectangling a nested list according to a given specification. I basically like `hoist()` but I think that something like my list parser could also be a nice addition.

A specification basically has the following form:

``` r
lcols(
  `col_name = lcol_*(pluck_specification)`,
  `col_name = lcol_*(pluck_specification)`,
  ...
)
```

(I'm not that keen on the name but didn't think of anything better yet). The functions `lcol_*` are like follows

* `lcol_lgl(path)`: creates a logical column.
* similarly `lcol_int/dbl/chr/fct`, `dat` for date, `dtt` for datetime, `hms`, `guess`.
* `lcol_lst_of`(path, .ptype): creates a list-of-<ptype> column.
* `lcol_df(path, ...)` creates a dataframe column where `...` are `lcol_*` functions again.
* `lcol_df_lst` similar to `lcol_df` but creates a list of dataframe column.

These functions all have the arguments:
* `.req`: if it is `TRUE` and the path is missing an error is thrown (basically `chuck` is used instead of `pluck`).
* `.parser` can be used for a custom conversion function. This can be especially useful for date or datetime columns

For example to parse the `discog` data from `repurrrsive` this could like below:

``` r
recordlist <- repurrrsive::discog

col_specs <- lcols(
  lcol_int("id"),
  first_artist_name = lcol_chr(list("basic_information", "artists", 1, "name")),
  artists_df_lst = lcol_df_lst(
    c("basic_information", "artists"),
    lcol_chr("join"),
    lcol_chr("name"),
    lcol_chr("role"),
    lcol_int("id")
  ),
  rating_list = lcol_lst_of("rating", .ptype = ""),
  info = lcol_df(
    "basic_information",
    lcol_int("id"),
    lcol_chr("title")
  ),
)

list_parse(recordlist, col_specs)
#> # A tibble: 155 x 5
#>         id first_artist_name   artists_df_lst rating_list info$id $title        
#>      <int> <chr>               <list<df[,4]>> <list<chr>>   <int> <chr>         
#>  1  7.50e6 Mollot                     [1 × 4]         [1]  7.50e6 Demo          
#>  2  4.49e6 Una Bèstia Incontr…        [1 × 4]         [1]  4.49e6 Observant Com…
#>  3  9.83e6 S.H.I.T. (3)               [1 × 4]         [1]  9.83e6 I             
#>  4  9.77e6 Rata Negra                 [1 × 4]         [1]  9.77e6 Oído Absoluto 
#>  5  7.24e6 Ivy (18)                   [1 × 4]         [1]  7.24e6 A Cat's Cause…
#>  6  1.31e7 Tashme                     [1 × 4]         [1]  1.31e7 Tashme        
#>  7  7.11e6 Desgraciados               [1 × 4]         [1]  7.11e6 Demo          
#>  8  1.05e7 Phantom Head               [1 × 4]         [1]  1.05e7 Let The Mirac…
#>  9  1.13e7 Sub Space (2)              [1 × 4]         [1]  1.13e7 Sub Space     
#> 10  1.17e7 Small Man (2)              [1 × 4]         [1]  1.17e7 Demo          
#> # … with 145 more rows
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think this approach has the following perks:
* the specification is concise and readable
* one can create dataframe columns and list of dataframe columns. I find them useful (especially the list of dataframe columns are sometimes basically required) and I didn't find an easy way to do this with `hoist()` and `unnest_*()`.
* in spirit of `jsonlite:::simplify()` and `readr::read_csv()` one could have an auto parser and print a copy-pastable specification (this is one of my favourite features of this approach!).
* one can have things like an argument `.default = "guess"` in `lcols` to auto parse all new unspecified fields.
* parsing of nested lists still works even when the nested field is missing.
* knowing the specification beforehand can make this quite fast.

Things missing:
* parameters to control unnesting in `lcol_df`.
* how to handle names of list elements.

**Comment by hadley** [comment]
A few thoughts:

* I think you'd be better off putting the names "inside" the individual elements
* Rather than having a suffix for each type, I think you'd be better off with a ptype argument
* I think you should error by default if an element is missing. You may want provide a `.default` argument, if (eg) an absent value represents 0.

Overall, it seems like a good idea. I'm unlikely to have time to give significant feedback or work on it myself in the near future.

**Comment by mgirlich** [comment]
Thanks for the feedback. Regarding your thoughts:

1. name "inside" the individual elements.
The reasons I prefer the names outside are:
* easy to read the spec: by just reading the names one already gets an idea of what the result is going to look like. As the name should be optional, it couldn't be the first argument. So, one would either have to read the pluck specification or search for the name argument.
* it feels more intuitive to me: this is more like `list()`, `tibble()`, and `mutate()` work, so this is what I would also expect in this case.
2. ptype argument
I do see the need for a general `lcol` function taking a `ptype` argument but I really like the 3 letter abbreviations for the common/base types as they are short, easy to write and easy to read.
3. missing element
This sounds like a good idea to me.

I might find some time to prepare a PR for this if you think it makes sense.

**Comment by mgirlich** [comment]
I created a package [listparser](https://github.com/mgirlich/listparser) for rectangling nested lists.
I tried to follow the principles in vctrs. In case you consider it a good approach I'd be happy to include it it `purrr` or `tidyr`.

**Comment by hadley** [comment]
My sense is that this is big enough that a separate package is probably the right place for it live. Maybe we could just link to it from the docs of `hoist()`?
