### ISSUE TITLE
Add .drop parameter to hoist

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#836]
Often, I don't want to extract every component of a list column but still drop it afterwards. In my opinion, this is actually the more common case, so I would even make .drop = TRUE the default.

**Comment by hadley** [comment]
Seems reasonable.

**Comment by jennybc** [comment]
It's a bummer that there would then be `.remove` and `.drop`. It feels like we're doubling down on a related problem in dplyr, where there's been a proliferation of arguments that don't make it very clear whether we're eliminating (or retaining) something in the row/group direction or column direction (e.g., `dplyr::filter(.preserve)` vs. `dplyr::group_by(.drop`)` vs. `dplyr::group_map(keep)`). For all of these, it feels very difficult for a user to remember whether it's remove, drop, preserve, or keep and which entity we're eliminating or retaining.

**Comment by hadley** [comment]
@jennybc any ideas for better names? `remove_elements` vs `remove_column`? 

Or maybe we make `.remove` more flexible? `.remove = c("column", "elements", "none")`?

**Comment by jennybc** [comment]
In this particular case (removing a `hoist()`ed column that has not been completely "used up" or `.remove`d, I basically think the user should just do it with `select(-hoistee)`. To me, having 3 options for `.remove` feels like the kind of detail I would always have to look up, whereas I never have to look up the syntax for `select()`.

**Comment by DavisVaughan** [comment]
From a programmatic standpoint, it makes me a little nervous that `hoist()` may or may not drop `.col`, depending on whether or not it has been completely used up

``` r
library(tidyr)

col <- list(
  list(a = 1, b = 1),
  list(a = 2, b = 2)
)

df <- tibble(col = col)

# has `col`
hoist(df, col, "a")
#> # A tibble: 2 × 2
#>       a col             
#>   <dbl> <list>          
#> 1     1 <named list [1]>
#> 2     2 <named list [1]>

# no more `col`. I'd prefer a `col` that is a list-col containing empty lists.
hoist(df, col, "a", "b")
#> # A tibble: 2 × 2
#>       a     b
#>   <dbl> <dbl>
#> 1     1     1
#> 2     2     2
```

We could make `.remove`:

- `"none"`, don't remove anything
- `"elements"`, remove elements from `col` AND never remove `col`
- `"column"`, remove `col`

For backwards compatibility, `FALSE` translates to `"none"` and `TRUE` translates to `"elements"`, with the minor breaking change that `.remove = TRUE` can no longer remove the `col` entirely if the hoist call empties it out.

**Comment by hadley** [comment]
I like your proposal for `.remove`; I agree with @jennybc that few people are likely to remember this, but it'll still be useful for experts.

**Comment by DavisVaughan** [comment]
We thought about this a little more, and it doesn't seem worth it to introduce a breaking change (that `.remove = TRUE` would no longer drop the column if it was emptied out) for a small type stability benefit.

So to be fully backwards compatible we'd have to have a 4th string option for the current `.remove = TRUE` behavior, but that seems hard to come up with, and makes everything a bit messier.

I think the best solution is to just use `hoist(col, .remove = FALSE) %>% select(-col)`. Obviously not ideal, but it should be good enough for this use case
