### ISSUE TITLE
automatically name unnamed pluckers in hoist

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#837]
Often one wants to name the columns produced by `hoist()` the same as the element in the list. So to make `hoist()` less verbose and more comfortable for interactive use I propose automatically naming the column as follows for unnamed arguments:

* if the last part of the pluck specification is a character use that
* if the last part of the pluck specification is a number paste the number to the last character part of the spec, e.g. `list("film", 1)` would produce the column name `film_1`.

**Comment by hadley** [comment]
This is an interesting idea. What would you do if the pluck spec is a number? Or the number comes first?

**Comment by mgirlich** [comment]
maybe there should be a short and a long name option, e.g. something like

pluck spec | short name | long name
----------- | ------------ | --------------
`list("people", "name")` | name | people_name
`list("people", "name", 1)` | name_1 | people_name_1
`list(1)` | ..1 | ..1
`list(1, 2)` | ..1..2 | ..1..2
`list(1, "people", "name")` | ..1_name | ..1_people_name

as the numbers in a spec will probably be small one might also use words for the, i.e. `list(1, "name")` gives `first_name`

**Comment by hadley** [comment]
That's starting to feel a bit too magical too me — I think there'd have to be one principle applied consistently.

**Comment by mgirlich** [comment]
Looking at it again I agree that it looks quite magical.

One easy principle would be to simply use `paste(pluck_spec, collapse = "_")` for the long name version. Unfortunately, this generates non-syntactic names for leading numbers. But this could be resolved by adding a `names_repair` argument, so the user can choose how to handle this.

For short names one would use basically the same strategy but keep all trailing numbers, i.e.
`list("people", "name", 1, 2)` would give `name_1_2`.

Do you like that better?

**Comment by jennybc** [comment]
The case that seems like a no-brainer and a great place to start is when you pluck a string. That covers so much of the pain IMO.

**Comment by hadley** [comment]
Ok, let's start with just naming single string pluckers.
