### ISSUE TITLE
FR: list of dataframe columns in hoist

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#838]
List of dataframe columns are sometimes basically required, e.g. in the `discog` data of the `repurrrsive` package one might be interested in the labels and artists but unnesting doesn't really make sense as they are unrelated and have unequal length. Using `tidyr` my approach would currently be the following:

``` r
library(tidyr)
components_df <- tibble(component = repurrrsive::discog[c(4, 35)]) %>% 
  hoist(
    component,
    instance_id = "instance_id",
    labels_lst = list("basic_information", "labels"),
    artists_lst = list("basic_information", "artists")
  ) %>% 
  dplyr::select(-component)

# parse labels_lst
components_df <- components_df %>% 
  unnest_longer(labels_lst) %>% 
  hoist(
    labels_lst,
    name = "name"
  ) %>% 
  dplyr::select(-labels_lst) %>% 
  nest(labels = c(name))

# parse artists_lst
components_df %>% 
  unnest_longer(artists_lst) %>% 
  hoist(
    artists_lst,
    name = "name"
  ) %>% 
  dplyr::select(-artists_lst) %>% 
  nest(artists = c(name))

# A tibble: 2 x 3
  instance_id         labels        artists
        <int> <list<df[,1]>> <list<df[,1]>>
1   351244906        [3 × 1]        [1 × 1]
2   350311710        [1 × 1]        [7 × 1]
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

With the `.drop` argument I could get rid of the (required) select statements but this still looks a bit too complicated to me. So, better support for this would be very nice.

**Comment by hadley** [comment]
Would you mind expanding a bit on what you're trying to do? I don't currently understand what you're asking for.

**Comment by hadley** [comment]
Closing for now. Happy to re-open if you provide more details.
