### ISSUE TITLE
FR: support extracting names in hoist()

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#840]
To get the names of the list column elements one needs an extra step with `mutate()`. To avoid this one could add the argument `indices_to` like in `unnest_longer()`.

``` r
df <- tibble(
  x = 1:2,
  y = list(first = c(1, b = 2), second = c(a = 10, b = 11, c = 12))
)

hoist(
  df, y,
  b = "b",
  indices_to = "names"
)

#> # A tibble: 2 x 4
#>       x names      b y           
#>   <int> <chr>  <dbl> <named list>
#> 1     1 first      2 <dbl [1]>   
#> 2     2 second    11 <dbl [2]>  
```

**Comment by hadley** [comment]
Does `hoist()` really need this feature? You can also get the names in a previous step:

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = 1:2,
  y = list(first = c(1, b = 2), second = c(a = 10, b = 11, c = 12))
)

df %>% 
  mutate(names = names(y)) %>% 
  hoist(y, b = "b")
#> # A tibble: 2 x 4
#>       x     b y            names 
#>   <int> <dbl> <named list> <chr> 
#> 1     1     2 <dbl [1]>    first 
#> 2     2    11 <dbl [2]>    second
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It feels a bit confusing in `hoist()` because the name of the index variable ends up on the right hand side, where for all the other arguments it's on the left hand side.

**Comment by mgirlich** [comment]
I agree that this argument feels a bit different but I also like that it works the same way as in `unnest_longer()`. Especially, as they are documented on the same help page and already share some arguments I would assume this for `.indices_to` as well. 
In the end I am happy with or without adding the argument.

**Comment by jennybc** [comment]
Yet another variation that takes advantage of auto-splicing + `tibble::enframe()`.

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = 1:2,
  y = list(first = c(1, b = 2), second = c(a = 10, b = 11, c = 12))
)

df %>% 
  mutate(tibble::enframe(y, value = "y_stuff"), .keep = "unused") %>% 
  hoist(y_stuff, "b")
#> # A tibble: 2 x 4
#>       x name       b y_stuff  
#>   <int> <chr>  <dbl> <list>   
#> 1     1 first      2 <dbl [1]>
#> 2     2 second    11 <dbl [2]>
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment]
I think given that there's at least a couple of ways to achieve this outside of `hoist()`, I'd prefer not to add another argument at this time.
