### ISSUE TITLE
pivot_longer: "lossy cast" when names_ptypes includes double

### ISSUE THREAD

**Issue by infotroph** [tidyverse/tidyr#842]
When asking pivot_longer to parse doubles out of column names, round-number values fail with a "lossy cast" error:

```r
ok <- tribble(~X1.1cm, ~X1.2cm, 1, 2)
fail <- tribble(~X1.0cm, ~X1.5cm, 1, 2)

pivot_longer(
    data = ok,
    cols = starts_with("X"),
    names_pattern = "X([\\d.]+)cm",
    names_ptypes = list(name = double()))
# # A tibble: 2 x 2
#    name value
#   <dbl> <dbl>
# 1   1.1     1
# 2   1.2     2

pivot_longer(
    data = fail,
    cols = starts_with("X"),
    names_pattern = "X([\\d.]+)cm",
    names_ptypes = list(name = double()))
# Error: Lossy cast from `x` <character> to `to` <double>.
# Locations: 1
# Run `rlang::last_error()` to see where the error occurred.

# workaround: pivot as character, then coerce
pivot_longer(
    data = fail,
    cols = starts_with("X"),
    names_pattern = "X([\\d.]+)cm") %>%
mutate(name = parse_number(name))
# # A tibble: 2 x 2
#    name value
#   <dbl> <dbl>
# 1   1       1
# 2   1.5     2
```

Looks like the complaint originates from a `!=` comparison inside `vctrs:::vec_cast.double.character`. I realize the cast technically *is* lossy (in the sense that `c("1.0", "1.1") != c(1.0, 1.1)` evaluates to `c(TRUE, FALSE)`), which is why I'm opening the issue here instead of in vctrs -- whether or not this is the intended behavior from `vec_cast.double.character`, I'd hope that `pivot_longer` would account for float precision when I give it an explicit float prototype.

**Comment by hadley** [comment]
With latest vctrs you now get:

``` r
library(tidyr)

ok <- tribble(~X1.1cm, ~X1.2cm, 1, 2)
fail <- tribble(~X1.0cm, ~X1.5cm, 1, 2)

pivot_longer(
    data = ok,
    cols = starts_with("X"),
    names_pattern = "X([\\d.]+)cm",
    names_ptypes = list(name = double()))
#> Error: Can't convert from <character> to <double>.
```

<sup>Created on 2020-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We may figure out a better solution in the long term, but in the short term, I think using `parse_number()` is the right approach.

**Comment by hadley** [comment]
Actually this turns out to be #921, so we need this for the next release.

**Comment by rcragun** [comment]
I am not sure if this is the same problem or needs a new report:

```
test = tibble(
  State = 1:3,
  `1960` = 4:6,
  `1970` = 7:9)

test %>%
  pivot_longer(
    `1960`:`1970`,
    names_to="Year",
    names_ptypes=list(Year=double()))

# Error: Can't convert <character> to <double>.
```

`Integer()` has the same problem.
