### ISSUE TITLE
Why is the replace argument of replace_na() so strict?

### ISSUE THREAD

**Issue by Ljupch0** [tidyverse/tidyr#843]
`replace`	    If `data` is a data frame, a named list giving the value to replace NA with for each column. If data is a vector, a single value used for replacement.

I believe that if the users puts a single value to replace NAs and inputs a data frame, the same replacement value should be applied across all columns. If however the user wants a more elaborate replacement pattern, a named list can be provided. I think the case where you replace NAs across the board is quite common.

**Comment by huftis** [comment]
If #912 was implemented, this could be written as:

```r
df %>% 
  replace_na(across(everything(), 0))
```

**Comment by hadley** [comment]
Closing as duplicate of #912 since this will be fixed by better documentation.
