### ISSUE TITLE
Proposal to change arguments order of pivot_wider()

### ISSUE THREAD

**Issue by msberends** [tidyverse/tidyr#844]
I imagine the (great!) new functions `pivot_wider()` and `pivot_longer()` have had a lot of thought, which is awesome. However, for the arguments order of `pivot_wider()`, I think some extra user-friendliness would improve convenience a lot.

For `pivot_wider()`, I would suggest to move the argument `id_cols` to a 5th place, after `data`, `names_from`, `values_from` and `values_fill`:
```r
# current
pivot_wider(data, id_cols = NULL, names_from = name,
  names_prefix = "", names_sep = "_", names_repair = "check_unique",
  values_from = value, values_fill = NULL, values_fn = NULL)

# suggested
pivot_wider(data, names_from = name, values_from = value, 
  values_fill = NULL, id_cols = NULL, names_prefix = "",
  names_sep = "_", names_repair = "check_unique", values_fn = NULL)
```

I have two arguments for this:

1. Since you softly force users to migrate from `spread()` as this function [is now retired](https://tidyr.tidyverse.org/reference/spread.html) which [will lead to future removal](https://www.tidyverse.org/lifecycle/), I guess most users expect the use of `pivot_wider()` to be somewhat as fast and easy as `spread()`. But `pivot_wider()` often requires manual and cumbersome definition of arguments, which in my experience is needed in almost all use cases. This means it is quite far from a drop-in replacement of `spread()`. With the suggested order, this would be solved immediately:
    ```r
    # old
    storms %>%
      count(year, status) %>%
      spread(status, n, 0)

    # current
    storms %>%
      count(year, status) %>%
      pivot_wider(names_from = status, values_from = n, values_fill = list(n = 0))

    # suggested
    storms %>%
      count(year, status) %>%
      pivot_wider(status, n, list(n = 0))
    ```

    For `values_fill`, I would additionally suggest to make it work more intelligently by picking `values_from` as a new list name at default so e.g. `pivot_wider(status, n, 0)` works, but that's another discussion.

2. You [added 4 use cases](https://tidyr.tidyverse.org/reference/pivot_wider.html#examples) to the documentation, that (as users can reasonably expect) shows best practises. Not a single one of them works with `id_cols`, which is now the second argument. Instead, all examples at least contain the manually set (and consequently typed!) `names_from` and `values_from`:
    ```r
    # (pasted from: https://tidyr.tidyverse.org/reference/pivot_wider.html#examples)

    fish_encounters %>%
      pivot_wider(names_from = station, values_from = seen)
    # Fill in missing values
    fish_encounters %>%
      pivot_wider(
        names_from = station,
        values_from = seen,
        values_fill = list(seen = 0)
      )

    # Generate column names from multiple variables
    us_rent_income %>%
      pivot_wider(names_from = variable, values_from = c(estimate, moe))

    # Can perform aggregation with values_fn
    warpbreaks <- as_tibble(warpbreaks[c("wool", "tension", "breaks")])
    warpbreaks
    warpbreaks %>%
      pivot_wider(
        names_from = wool,
        values_from = breaks,
        values_fn = list(breaks = mean)
      )
    ```

    At best, this makes users even wonder how `id_cols` works. But in my honest opinion, it strongly suggests that a reordering of arguments would improve convenience, decrease typing, fasten analysis and, most importantly, help users adapt to `pivot_wider()` in a most user-friendly way.

**Comment by hadley** [comment]
The goal is explicitly to force people to name these arguments. It makes the functions easier to change in the future, and I believe it makes the code easier to read.

**Comment by msberends** [comment]
Disagree on all points, but that’s taste I guess. 

So how should we work with the `id_cols` parameter then? 😉
