### ISSUE TITLE
pivot_wider() could not find function "vec_group_id"

### ISSUE THREAD

**Issue by MikeEdinger** [tidyverse/tidyr#852]
I've installed the development version of tidyr using the instructions in README.  When I try to use the pivot_wider() function, I get the following error

```
`library(vctrs)
package �vctrs� was built under R version 3.6.2
Attaching package: �vctrs�

The following object is masked from �package:lubridate�:

    new_duration

prod2 <- prod2 %>% pivot_wider(names_from = qtrmnth, values_from = Weight)
Error in vec_group_id(df_rows) : could not find function "vec_group_id"`
```

I think vec_group_id is a function in the vctrs package, which I've updated and ensured is loaded (but it's not showing up in my packages window in RStudio?). Not sure what else to do as search results were quite sparse regarding vec_group_id.

**Comment by hadley** [comment]
I think we may have accidentally broken tidyr with dev vctrs. I think the easiest way to get back to a working tidyr is to `install.packages(c("tidyr", "vctrs"))` and then just stick with the CRAN version of tidyr (which is basically identical to the github version at the moment)

**Comment by DavisVaughan** [comment]
I think you have the development version of tidyr, but a version of vctrs before `vec_group_id()` was implemented. You could also try keeping the development version of tidyr, and updating to the latest development version of vctrs with:

```r
devtools::install_github("r-lib/vctrs")
```

**Comment by MikeEdinger** [comment]
> I think we may have accidentally broken tidyr with dev vctrs. I think the easiest way to get back to a working tidyr is to `install.packages(c("tidyr", "vctrs"))` and then just stick with the CRAN version of tidyr (which is basically identical to the github version at the moment)

Ah, my apologies.  I had an error for pivot_wider() not found and google told me to install the development version of tidyr.  Going back to the most updated CRAN version for both packages fixed my issue.  Thanks for the help.
