### ISSUE TITLE
Programming with tidyr vignette

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#854]
Drawing from <http://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html> and <http://dplyr.tidyverse.org/dev/articles/programming.html>, but adapting examples to use tidyr functions.  tidyr mostly uses tidy-selection rather than data-masking, so that should be given higher priority.

**Comment by jennybc** [comment]
What's the intended relationship between this new "Programming with tidyr" vignette and the existing [In packages](https://tidyr.tidyverse.org/articles/in-packages.html) vignette we wrote for the v1.0.0 release?

**Comment by hadley** [comment]
More user focussed and problem-oriented, like the dplyr example.
