### ISSUE TITLE
Hoist fails to extract a complex element

### ISSUE THREAD

**Issue by lymanmark** [tidyverse/tidyr#863]
I was trying to use a workflow similar to that laid out on the second page of https://github.com/rstudio/cheatsheets/blob/master/purrr.pdf but check for warnings using purrr::quietly. I then wanted to use tidyr::hoist to extract the result and any warnings, but I got the error message below. Is extracting complex elements (like an lm object) not supported? I couldn't find anything about it in the documentation. In my actual situation I am using brms::brm, but I get the same error using lm

``` r
library(tidyverse)
cars_results <- mtcars %>%
  group_nest(cyl) %>%
  mutate(lm_result = map(data, quietly(lm), formula = mpg ~ disp)) %>%
  hoist(lm_result, warnings = "warnings", fit = "result")
#> Error: `x` must be a vector, not a `lm` object

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

**Comment by hadley** [comment]
Simpler reprex:

``` r
library(tidyr)

df <- tibble(
  x = 1:2,
  y = list(
    list(mod = lm(mpg ~ wt, data = mtcars)),
    list(mod = lm(mpg ~ wt, data = mtcars))
  )
)
df %>% hoist(y, model = "mod")
#> Error: Input must be a vector, not a `lm` object.
```

<sup>Created on 2020-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think we should just be able to wrap in a list here, but I'll need to think about it a bit to be sure.

**Comment by jennybc** [comment]
I am also seeing this exact problem, but in googlesheets4 development / noodling around.

One form I can return the data in is "one row per cell", with a list-column containing full gory detail on the cells. I would dearly love to be able to reach down in there and pull out, e.g., a serial date. But I can't because these cell objects happen to have a class.

Sorry for the lack of reprex, but it's a lot of googlesheets4 code to get to this point.

```
> (cells_ny <- range_read_cells(ss_ny, range = "2:2"))
Reading from "america-new-york"
Range "2:2"
# A tibble: 4 x 4
    row   col loc   cell      
  <int> <int> <chr> <list>    
1     2     1 A2    <CELL_DAT>
2     2     2 B2    <CELL_DAT>
3     2     3 C2    <CELL_DAT>
4     2     4 D2    <CELL_DAT>

> cells_ny$cell[[1]]
$effectiveValue
$effectiveValue$numberValue
[1] 43938.86

$formattedValue
[1] "2020-04-17 20:45:01"

$effectiveFormat
$effectiveFormat$numberFormat
$effectiveFormat$numberFormat$type
[1] "DATE_TIME"

$effectiveFormat$numberFormat$pattern
[1] "yyyy-mm-dd hh:mm:ss"

attr(,"class")
[1] "CELL_DATETIME" "SHEETS_CELL"  

> cells_ny %>%
+   hoist(cell, serial = c("effectiveValue", "numberValue"))
Error: Input must be a vector, not a `CELL_DATETIME/SHEETS_CELL` object.
```

**Comment by hadley** [comment]
This now works for me:

``` r
library(tidyr)

df <- tibble(
  x = 1:2,
  y = list(
    list(mod = lm(mpg ~ wt, data = mtcars)),
    list(mod = lm(mpg ~ wt, data = mtcars))
  )
)
df %>% hoist(y, "mod")
#> # A tibble: 2 x 2
#>       x mod   
#>   <int> <list>
#> 1     1 <lm>  
#> 2     2 <lm>
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So it must've been an upstream bug in vctrs. I'll add a tidyr test just to make sure it doesn't come back without us hearing about it.

**Comment by jennybc** [comment]
My example still doesn't work. (And yes I just updated everything and the `lm` example works for me.)

``` r
library(googlesheets4)
library(tidyr)
library(purrr)

gs4_deauth()

dat <- range_read_cells(
  gs4_example("cell-contents-and-formats"),
  sheet = "cell-contents-and-formats",
  range = "Sheet1!A2:A4"
)
#> Reading from "cell-contents-and-formats"
#> Range "'Sheet1'!A2:A4"

dat
#> # A tibble: 3 x 4
#>     row   col loc   cell      
#>   <int> <int> <chr> <list>    
#> 1     2     1 A2    <CELL_DAT>
#> 2     3     1 A3    <CELL_DAT>
#> 3     4     1 A4    <CELL_DAT>

dat %>%
  hoist(cell, serial = c("effectiveValue", "numberValue"))
#> Error: Input must be a vector, not a `CELL_DATETIME/SHEETS_CELL` object.
#> Backtrace:
#>      █
#>   1. ├─dat %>% hoist(cell, serial = c("effectiveValue", "numberValue"))
#>   2. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
#>   3. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   4. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   5. │     └─`_fseq`(`_lhs`)
#>   6. │       └─magrittr::freduce(value, `_function_list`)
#>   7. │         ├─base::withVisible(function_list[[k]](value))
#>   8. │         └─function_list[[k]](value)
#>   9. │           └─tidyr::hoist(., cell, serial = c("effectiveValue", "numberValue"))
#>  10. │             └─purrr::every(x, vec_is_empty)
#>  11. │               └─purrr:::.p(.x[[i]], ...)
#>  12. │                 └─vctrs:::.fn(...)
#>  13. │                   └─vctrs::vec_size(x) /Users/jenny/rrr/vctrs/R/size.R:98:2
#>  14. └─vctrs:::stop_scalar_type(...) /Users/jenny/rrr/vctrs/R/size.R:80:2
#>  15.   └─vctrs:::stop_vctrs(msg, "vctrs_error_scalar_type", actual = x) /Users/jenny/rrr/vctrs/R/conditions.R:551:2
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jennybc** [comment]
It's happening when trying to remove the hoisted elements. `vec_is_empty()` is unhappy about the fact that my elements have a class.

**Comment by hadley** [comment]
Converting that to `is_empty()` makes your example work. I'll need to convince myself that's an ok thing to do.

**Comment by jennybc** [comment]
Side observation: it also works if I add `"list"` to the class 😂

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(tidyr)

foofy <- function(x) {
  structure(list(x = list(x, 2)), class = "foofy")
}

df <- tibble(
  x = 1:2,
  y = list(foofy(1), foofy(2))
)

df %>% hoist(y, z = list("x", 2))
#> Error: Input must be a vector, not a `foofy` object.
```

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think the key is that you're reaching inside of some classed object, so really `.remove` shouldn't be true here

**Comment by jennybc** [comment]
Oh, yeah that's true / nice. So I suppose we could just leave this at "user error". It might be nice to share this insight in the error message or at least an example.

**Comment by hadley** [comment]
I convinced myself that switch to `is_empty()` is the right thing to do here, based on the implementation of `strike()`. It does feel weird, but I think that's because I didn't fully think through the behaviour of remove.

**Comment by lymanmark** [comment]
Thank you.
