### ISSUE TITLE
additionally tag v1.0.2 

### ISSUE THREAD

**Issue by dpastoor** [tidyverse/tidyr#880]
Given the accidental bump to 1.0.2 on CRAN, the github release itself was updated to 1.0.2, however, the git tag is still 1.0.1 only. Would it be possible to additionally tag that commit as 1.0.2 such that any tools that try to check out the repository via the tag that corresponds to the release number (such as for mirroring to RSPM etc) can appropriately find the correct tag.

Thanks!

**Comment by hadley** [comment]
Done
