### ISSUE TITLE
`separate_rows()` fails on 0-row data frames

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#884]
We have a test for when there are rows, but the 0 row case fails because dplyr doesn't like using lists as grouping vars

``` r
library(tidyr)

df <- tibble(x = 1, y = "a:b") %>% dplyr::group_by(x, y)

df %>% dplyr::group_by(y) %>% separate_rows(y)
#> # A tibble: 2 x 2
#>       x y    
#>   <dbl> <chr>
#> 1     1 a    
#> 2     1 b

df[0,] %>% dplyr::group_by(y) %>% separate_rows(y)
#> Error: Column `y` can't be used as a grouping variable because it's a list
```

<sup>Created on 2020-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think I know exactly what is wrong, and have an easy fix for this

**Comment by hadley** [comment]
This now works with dev dplyr, and fails in the same way for both cases for CRAN dplyr. I think that's reasonable.
