### ISSUE TITLE
`separate_rows()` fails if list columns are of unequal length.

### ISSUE THREAD

**Issue by JenspederM** [tidyverse/tidyr#894]
---

The separate_rows function behaves oddly when collapsed columns are of unequal length.

In some instances, the function throws an error, such as:
```
Error: No common size for `colX`, size 4, and `colY`, size 5.
```
and in other instances, it return just the first and last element as shown here:
```r
df <- tibble(id = c("a", "b", "c"), col1 = list(1:2, 1:5, NA), col2 = list(1:4, 1:2, 1))
separate_rows(df, -id)
``` 

It might just be my opinion, but the `separate_rows` function should have a `fill` argument, which I see was also mentioned in #413 , thereby always returning a tibble of the expected size, while allowing the user to define what should happen when columns are of unequal length. 

Maybe I just misunderstood the usecase of the `separate_rows` function. Please let me know, if that is the case.

**Comment by batpigandme** [comment]
FWIW, it works with the dev. versions installed with warnings. 
``` r
library(tidyverse)

df <- tibble(id = c("a", "b", "c"), 
             col1 = list(1:2, 1:5, NA), 
             col2 = list(1:4, 1:2, 1))

separate_rows(df, -id)
#> Warning in .f(.x[[i]], ...): argument is not an atomic vector; coercing

#> Warning in .f(.x[[i]], ...): argument is not an atomic vector; coercing
#> # A tibble: 5 x 3
#>   id    col1  col2 
#>   <chr> <chr> <chr>
#> 1 a     1     1    
#> 2 a     2     4    
#> 3 b     1     1    
#> 4 b     5     2    
#> 5 c     NA    1
```

The warnings come from the expectation that the column contains multiple delimited values like shown below:

``` r
df2 <- tibble(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  z = c("1", "2,3,4", "5,6")
)

separate_rows(df2, y, z)
#> # A tibble: 6 x 3
#>       x y     z    
#>   <int> <chr> <chr>
#> 1     1 a     1    
#> 2     2 d     2    
#> 3     2 e     3    
#> 4     2 f     4    
#> 5     3 g     5    
#> 6     3 h     6
```

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
