### ISSUE TITLE
Inconsistency of name repair arguments

### ISSUE THREAD

**Issue by lionel-** [tidyverse/tidyr#900]
The new `.name_repair` argument of `expand_grid()` is inconsistent with the plural `.names_repair` used in other functions.

**Comment by hadley** [comment]
It's consistent with `.name_repair` in `tibble()`. `pivot_longer()` etc uses `names` because all the other arguments do

**Comment by RobertMyles** [comment]
Related: this is an error from `pivot_wider()`:

```
Error: Column 1 must be named.
Use .name_repair to specify repair.
```

However, the documentation mentions `names_repair` only and not `.name_repair`, which I mistakenly used after seeing the error message.

**Comment by hadley** [comment]
Problem with error message is in #774. 

I'm pretty sure I'm consistent with the right thing here, but I've made a note to discuss in our weekly meeting.
