### ISSUE TITLE
dataframe is not fully unnested.

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/tidyr#902]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

--

Brief description of the problem
The data frame still has nested list. please advise.
```r
library(IMFData)
library(reprex)
queryfilter <- list(CL_FREQ = "A", 
                    CL_AREA_DOT = "US",
                    CL_INDICATOR_DOT = c("TXG_FOB_USD", # Goods, Exports, FOB, US Dollars
                                         "TMG_CIF_USD"), # Goods, Imports, CIF, US Dollars
                    CL_COUNTERPART_AREA_DOT = "")
e <- CompactDataMethod('DOT', queryfilter, '1990-01-01', Sys.Date()) %>% 
  unnest %>% 
  rename_all(. %>% gsub("@", "", ., fixed = TRUE))
#> Error in CompactDataMethod("DOT", queryfilter, "1990-01-01", Sys.Date()) %>% : could not find function "%>%"
unique(e$Obs)
#> Error in unique(e$Obs): object 'e' not found
readr::write_csv(e, paste0("IMF_DOTS_Data_", "US", ".csv"))
#> Error in is.data.frame(x): object 'e' not found
reprex()
#> No input provided and clipboard is not available.
#> Rendering reprex...

```

**Comment by hadley** [comment]
You don't appear to be using tidyr in your code, and you have failed to make a reprex correctly. Please try reading https://reprex.tidyverse.org/#usage again, and filing a new issue.
