### ISSUE TITLE
Data frame is not nested fully

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/tidyr#904]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
I am trying to download data from IMF using IMFData library, then try to save the dataframe to my computer, it gives me error, since Obs column is still have nested information. 
``` r
library(IMFData)
library(tidyr)
library(readr)
library(magrittr)
#> 
#> Attaching package: 'magrittr'
#> The following object is masked from 'package:tidyr':
#> 
#>     extract
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(reprex)
queryfilter <- list(CL_FREQ = "A", 
                    CL_AREA_DOT = "US",
                    CL_INDICATOR_DOT = c("TXG_FOB_USD", # Goods, Exports, FOB, US Dollars
                                         "TMG_CIF_USD"), # Goods, Imports, CIF, US Dollars
                    CL_COUNTERPART_AREA_DOT = "")
e <- CompactDataMethod('DOT', queryfilter, '1990-01-01', Sys.Date()) %>% 
  unnest(cols = "Obs")
unique(e$Obs)
#> [[1]]
#> NULL
#> 
#> [[2]]
#> [1] "1997"
#> 
#> [[3]]
#> [1] "0.4"
#> 
#> [[4]]
#> [1] "1991"
#> 
#> [[5]]
#> [1] "0.1"
readr::write_csv(e, paste0("IMF_DOTS_Data_", "US", ".csv"))
#> Error in stream_delim_(df, path, ..., bom = bom, quote_escape = quote_escape): Don't know how to handle vector of type list.
```

<sup>Created on 2020-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by msgoussi** [comment]
I am sorry it is my mistake to ask you....
