### ISSUE TITLE
drop_na() is removing attributes from columns

### ISSUE THREAD

**Issue by xtimbeau** [tidyverse/tidyr#905]
drop_na() does not keep attributes of columns as shown below. I think it should.
thanks

```
ttbl <- tibble(col1 = c(1,2, NA, 2))
attr(ttbl$col1, "attr")<- "A value"
ttbl$col1
drop_na(ttbl)$col1
```

**Comment by hadley** [comment]
This looks like an easy fix — we just need to switch from `[` to `vec_slice()`
