### ISSUE TITLE
drop_na() is recognised as drop_na_()

### ISSUE THREAD

**Issue by jjnote** [tidyverse/tidyr#907]
drop_na() produce error like below.

---

Brief description of the problem

```r
# insert reprex here
> df <- drop_na(df$Sensitivity)
Error in UseMethod("drop_na_") : 
  no applicable method for 'drop_na_' applied to an object of class "logical"
In addition: Warning message:
`drop_na_()` is deprecated as of tidyr 1.0.0.
Please use `drop_na()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
> df <- drop_na(df$Sensitivity)
Error in UseMethod("drop_na_") : 
  no applicable method for 'drop_na_' applied to an object of class "c('double', 'numeric')"
> str(df$Sensitivity)
 num [1:45242] 0.909 1 1 1 1 1 1 1 1 0.818 ...

```

**Comment by batpigandme** [comment]
Could you please turn this into a **self-contained** [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by jjnote** [comment]
GeneAnnot <- drop_na(GeneAnnot$Sensitivity)
#> Error in drop_na(GeneAnnot$Sensitivity): could not find function "drop_na"

Here is reprex converted one. I'm not sure I did it right.

**Comment by jjnote** [comment]
Self answer.
GeneAnnot <- drop_na(GeneAnnot, Sensitivity)

This works well. Sorry for that..
