### ISSUE TITLE
Hoist not working with tibble containing rsample splits

### ISSUE THREAD

**Issue by mattwarkentin** [tidyverse/tidyr#911]
Hi,

I have been staring at this for too long and can't seem to figure out why `hoist()` won't pull out columns from my list-column of data frames, meanwhile it works perfectly well on a list-column of tibbles. Am I doing something wrong here?

``` r
library(tidyr)
library(dplyr)
library(purrr)
library(rsample)
  
# Works
iris %>% 
  group_nest(Species) %>% 
  hoist(data, Sepal.Length = 'Sepal.Length')
#> # A tibble: 3 x 3
#>   Species    Sepal.Length data             
#>   <fct>      <list>       <list>           
#> 1 setosa     <dbl [50]>   <tibble [50 × 3]>
#> 2 versicolor <dbl [50]>   <tibble [50 × 3]>
#> 3 virginica  <dbl [50]>   <tibble [50 × 3]>

# Doesn't work
iris %>% 
  vfold_cv() %>% 
  mutate(train = map(splits, training)) %>% 
  hoist(train, Sepal.Length = 'Sepal.Length')
#> Error in if (details$repeats > 1) res <- paste(res, "repeated", details$repeats, : argument is of length zero
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattwarkentin** [comment]
Some discussions are ongoing [here](https://community.rstudio.com/t/hoist-not-working-for-named-list-of-data-frames/56194). So far the summary is that there are two tweaks to get this working. It seems like running the mutate line adds row names (indicated by an asterisk in the tibble), and you need to either remove the splits column, or convert the row names to a column variable. No idea why this behaviour is happening.
```r
iris %>% 
  vfold_cv() %>% 
  mutate(train = map(splits, training)) %>% 
  select(-1) %>% 
  hoist(train, Sepal.Length = 'Sepal.Length')
```
```r
iris %>% 
  vfold_cv() %>% 
  mutate(train = map(splits, training)) %>% 
  rownames_to_column() %>% 
  hoist(train, Sepal.Length = 'Sepal.Length')
```

**Comment by hadley** [comment]
Note that the error only happens when you print the result:

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)
library(rsample)


df <- iris %>%
  rsample::vfold_cv() %>%
  mutate(train = unname(purrr::map(splits, training))) %>%
  hoist(train, Sepal.Length = 'Sepal.Length')

df
#> Error in if (details$repeats > 1) res <- paste(res, "repeated", details$repeats, : argument is of length zero
```

<sup>Created on 2020-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I think you need to file this in rsample.
