### ISSUE TITLE
unnest 1.0.2 fails if dataframe doesn't contain list-cols

### ISSUE THREAD

**Issue by dpeterson71** [tidyverse/tidyr#918]
In tidyr versions < 1.0, issuing MYDATA %>% unnest() would simply return MYDATA if there were no list-cols present.  This made constructing generic functions very easy and transparent because one may not know whether the input function is nested or not.  For example, the data frame may have been unnested in a previous analysis step.

Now, if we use a simple unnest() on a previously unnested dataframe we get the warning to use "cols = c(data)" since cols is now required.  However it still returns the original input dataframe that will permit a workflow to continue.

If we heed the warning and try using unnest(cols = c(data)) we are instead presented with a fatal error that halts the workflow.

```r
library(tidyverse)
nestcars <- mtcars %>% group_by(cyl) %>% nest()
nestcars

nestcars %>% unnest(cols = c(data)) # works fine

mtcars %>% unnest() # sends warning, but still works
mtcars %>% unnest(cols = c(data)) # fails with error
```

**Comment by hadley** [comment]
If you want to restore this behaviour, you'll need to either use `unnest_legacy()` or write the if statement yourself. We've removed this behaviour because I don't think it's a good idea to blindly unnest everything that could be unnested.

**Comment by dpeterson71** [comment]
I think you missed the problem.  I actually agree that "blindly unnesting everything that can be" is probably a poor default.  I think that is a good design change.  I am not asking to restore an empty unnest function.

The issue is that if one tries to issue "unnest(c(data))" on a dataframe that does not contain the column "data" (presumably because it's been unnested earlier in the workflow) then it SHOULD NOT FAIL, but rather return the original dataframe.

**Comment by hadley** [comment]
Oh, if that's the behaviour you want, you could do `df %>% unnest(cols = any_of("data"))`; `any_of()` will silently drop any variables that don't occur in the input.

**Comment by dpeterson71** [comment]
Ahhh, fantastic!  Implementing `any_of()` should be a usable solution.  Of course it means changing to `"data"` instead of `data`, but I'm rewriting code snippets anyway.

Thanks,
-Don
