### ISSUE TITLE
`separate_rows()` error with dev vctrs, dev tidyr, cran dplyr

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#923]
Dev vctrs now implements `vctrs:::vec_restore.grouped_df()` which calls `grouped_df()`. In CRAN dplyr, this function validates if any grouping vars are lists, and errors if so.

A tidyr test tries to do this, which errors on dev vctrs + cran dplyr for me.

```r
library(dplyr)
library(tidyr)

df <- tibble(x = 1, y = "a:b") %>% group_by(x, y)
out <- df %>% separate_rows(y)
#> Error: Column `y` can't be used as a grouping variable because it's a list
```

`separate_rows()` uses `stringi::stri_split_regex()` on the grouping variable, which returns a list. It then runs through `unchop()` which eventually calls `vec_slice()` on this grouped-df that has a grouping variable that is a list. The restore method is called in `vec_slice()` and we get an error

Maybe `separate_rows()` should ungroup its input?

**Comment by hadley** [comment]
Yeah, this is why I think we need to remove the `grouped_df` methods from vctrs.

**Comment by hadley** [comment]
This seems to be working again.
