### ISSUE TITLE
`nest()` with subclassed tibble

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/tidyr#929]
With the most recent version of vctrs (r-lib/vctrs@7736275e4898f968fb437e4e6967050c80517742), there is an error in place which, I believe, shouldn't happen:

``` r
library(tidyr)

tbl_classed <- tibble(a = 1, b = 2)
class(tbl_classed) <- c("my_class", class(tbl_classed))

nest(tbl_classed, data = c(b))
#> Error: Can't combine `..1` <my_class<>> and `..2` <data.frame<>>.
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This seems to be tracked in r-lib/vctrs#981 and couple of other issues, but I decided to notify about another possible consequence of this behavior. Error pops up during execution of [this line](https://github.com/tidyverse/tidyr/blob/e05d09fa0631a9a2e4077306224fa20e3c7e66e6/R/nest.R#L177): there `u_keys` is subclassed but output of `new_data_frame()` is not.

**Comment by hadley** [comment]
Another issue isn't really helpful; we're aware of this problem and are working on a fix.
