### ISSUE TITLE
FR: Implement names_glue on pivot_wider

### ISSUE THREAD

**Issue by atusy** [tidyverse/tidyr#931]
Currently, names produced by `pivot_wider` can partly be controlled via `names_sep`.
Further controls require additional renaming by `dplyr::rename`.
I suggest to add `names_glue` option which glues names in the manner of glue package.
In the example below, `.value` is a special key word like that of `names_pattern` of `pivot_longer`

``` r
data.frame(
  x = c('a' , 'b'),
  y = 1:2,
  foo = 1:2,
  bar = 1:2
) %>%
  pivot_wider(
    names_from = c(x, y),
    values_from = c(foo, bar),
    names_glue = '{x}{y}_{.value}'
  )
```

| a1_foo| a1_bar| b1_foo| b2_bar|
|------:|------:|------:|------:|
|      1|      2|      1|      2|

**Comment by hadley** [comment]
I like it!

**Comment by hadley** [comment]
Do you think setting `names_glue` should override `names_prefix`?

**Comment by atusy** [comment]
I do think so
