### ISSUE TITLE
separate_rows takes significantly long time in R 4.0 compare w/ R 3.6

### ISSUE THREAD

**Issue by jjnote** [tidyverse/tidyr#946]
After I update to R 4.0, separate_rows take an extremely long time.
I tried to perform separate_rows with 500,000 rows, but every time I performed it, I failed to perform completely. 

Therefore, I change my R version to 3.6, it works normally. I guess that something is not compatible with 4.0/4.1(Devel ver).

**Comment by hadley** [comment]
Can you please provide a reprex? It's unlikely to related to R 4.0.0, but more likely to be related to the set of packages you have installed.

**Comment by hadley** [comment]
Likely to be this: https://github.com/r-lib/vctrs/pull/1057
