### ISSUE TITLE
The S3 unite() generic generates unexpected output with NextMethod()

### ISSUE THREAD

**Issue by stufield** [tidyverse/tidyr#948]
When writing your own S3 method to the `unite()` generic, the `col=` argument does not rename the resulting object with the appropriate column name. 

```r
reprex::reprex({
  library(tidyr)
  foo <- data.frame(a = 1:3, b = rnorm(3), c = LETTERS[1:3])
  class(foo) <- c("my_class", "data.frame")
  
  unite.my_class <- function(data, col, ..., sep = "_", remove = TRUE, na.rm = FALSE) {
    NextMethod()
  }
  
  # Resulting "united" column is named `col` not `bar`
  unite(foo, col = "bar", a, c)
})
```

**Comment by hadley** [comment]
This is because `NextMethod()` doesn't work well when tidy evaluation is in the mix. We're aware of the problem, and thinking about it, but we don't have fix yet. I created an issue over in rlang so there's something we can close when we figure it out.

**Comment by stufield** [comment]
Got it. Thanks!
