### ISSUE TITLE
pivot_longer() regression with tibble 3.0.1

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyr#949]
From https://github.com/tidyverse/tibble/issues/766, CC @mvazquezs.

Is the previous behavior correct? Do we need a better error message?

## tibble 2.1.3

``` r
library(tidyverse)

tibble(id = 1, x_1 = 1, x_2 = 2, y_1 = 1, y_2 = 2) %>%
  pivot_longer(
    cols = -id,
    names_to = c("x", "x_dil"),
    names_pattern = "(.+)_(.+)",
    values_to = c("mfi", "dil")
  )
#> # A tibble: 4 x 5
#>      id x     x_dil   mfi   dil
#>   <dbl> <chr> <chr> <dbl> <dbl>
#> 1     1 x     1         1    NA
#> 2     1 x     2        NA     2
#> 3     1 y     1         1    NA
#> 4     1 y     2        NA     2
```

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## tibble 3.0.1

``` r
library(tidyverse)

tibble(id = 1, x_1 = 1, x_2 = 2, y_1 = 1, y_2 = 2) %>%
  pivot_longer(
    cols = -id,
    names_to = c("x", "x_dil"),
    names_pattern = "(.+)_(.+)",
    values_to = c("mfi", "dil")
  )
#> Error: Assigned data `values_to` must be compatible with existing data.
#> x Existing data has 4 rows.
#> x Assigned data has 2 rows.
#> ℹ Only vectors of size 1 are recycled.
```

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Almost certainly a bug. But should be simple fix.

**Comment by hadley** [comment]
Looking at the code, I don't think there's any suggestion that `values_to` should be a vector, so I think this can just be a better error.

**Comment by hadley** [comment]
I _think_ the call should be more like this:

``` r
library(tidyr)

tibble(id = 1, x_mfi = 1, x_dil = 2, y_mfi = 1, y_dil = 2) %>%
  pivot_longer(
    cols = -id,
    names_to = c("x", ".value"),
    names_pattern = "(.+)_(.+)"
  )
#> # A tibble: 2 x 4
#>      id x       mfi   dil
#>   <dbl> <chr> <dbl> <dbl>
#> 1     1 x         1     2
#> 2     1 y         1     2
```

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mvazquezs** [comment]
The special .values name works fine and simplifies the code a lot. Thanks so much @hadley and @krlmlr for your help.
