### ISSUE TITLE
Inverse of drop_na? 

### ISSUE THREAD

**Issue by daranzolin** [tidyverse/tidyr#950]
I love drop_na. While working on a particular project, however, I tried to reach for the inverse, which I incorrectly assumed existed and would hypothetically return rows with NA, e.g.:

```
library(tidyr)
df <- tibble(x = c(1, 2, NA), y = c("a", NA, "b"))
df %>% only_na(y)
```
instead of:

```
df %>% filter(is.na(y))
```

Since tidyverse functions tend to come in pairs (count/uncount, replace_na/na_if, separate/unite), can we have `only_na` or `keep_na` or something? Or is this too fringe a use case?

**Comment by hadley** [comment]
`drop_na()` is a tidyr function so this is the wrong repo, but I think it's unlikely that we'd consider a `keep_na()` function, given that it's easy enough to achieve the same effect otherwise.

**Comment by daranzolin** [comment]
Ok, that makes sense. And apologies--I thought it would hypothetically reside here since there are other dplyr/tidyr inverse pairs (dplyr::count ~ tidyr::uncount, dplyr::na_if ~ tidyr::replace_na)

**Comment by stemangiola** [comment]
I second the request, as at least as personal use, every time I use drop_na, I will check where and why those NAs are there. So for me, drop_na would be as important as keep_na

**Comment by daranzolin** [comment]
@stemangiola keep_na is now exported in in the [hacksaw package](https://github.com/daranzolin/hacksaw#keeping-nas) but agree it would be a useful addition to the tidyverse.

**Comment by retodomax** [comment]
All can be done with `if_all()` and `if_any()`, but I think it is not so easy to remember the syntax. Would be nice to have an easier function which covers all these 4 cases

```
dat <- tribble(
  ~x, ~y,
  1 ,  2,
  3 , NA,
  NA, NA
)

## drop rows where any selected column is NA (drop_any)
dat %>% filter(if_all(everything(), ~ !is.na(.x)))

## drop rows where all selected columns are NA (drop_all)
dat %>% filter(if_any(everything(), ~ !is.na(.x)))

## keep rows where any selected column is NA (keep_any)
dat %>% filter(if_any(everything(), is.na))

## keep rows where all selected columns are NA (keep_all)
dat %>% filter(if_all(everything(), is.na))
```

The function `drop_na()` covers only the first case. Maybe a function like this

```
filter_na(data, ..., method = "drop_any")
```

where `...` allows you to tidy-select the columns and method can be set to `drop_any` (default), `drop_all`, `keep_any` and `keep_all` would be nice.

**Comment by daranzolin** [comment]
> given that it's easy enough to achieve the same effect otherwise.

I'm a huge tidy advocate, but this reasoning would obviate ~50% of the tidyverse. Still hoping for a reconsider.
