### ISSUE TITLE
Using unite(na.rm = TRUE) on all NA rows results in "" 

### ISSUE THREAD

**Issue by kiernann** [tidyverse/tidyr#951]
Using `tidyr::unite()` with `na.rm = TRUE` on entirely `NA` rows results in "" rather than `NA`, which seems more expected.

``` r
library(tidyverse)
packageVersion("tidyr")
#> [1] '1.0.2'
dat <- tribble(
  ~a, ~b, ~c,
  "a", "b", "c",
  NA, NA, NA,
  "a", NA, "c",
)

(dat <- unite(
  data = dat,
  col = abc,
  a, b, c,
  na.rm = TRUE
))
#> # A tibble: 3 x 1
#>   abc    
#>   <chr>  
#> 1 "a_b_c"
#> 2 ""     
#> 3 "a_c"
```

The easiest solution is to use `dplyr::na_if()`, but this doesn't work if there are any date type columns. Then you need to use a scoped `dplyr::mutate()`, which is a hassle.

```r
na_if(dat, "")
#> # A tibble: 3 x 1
#>   abc  
#>   <chr>
#> 1 a_b_c
#> 2 <NA> 
#> 3 a_c

dat %>% 
  mutate(d = Sys.Date()) %>% 
  na_if("")
#> Error in charToDate(x): character string is not in a standard unambiguous format
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think this is correct — if you remove all non-missing values you get `character()` and `paste(character(), collapse = "_")` gives `""`.

**Comment by kiernann** [comment]
Ah, makes sense when you put it that way. Still kind of unexpected.

**Comment by hadley** [comment]
It's also consistent with `sum(c(NA, NA, NA), na.rm = TRUE)`
