### ISSUE TITLE
Document which functions work with grouped data

### ISSUE THREAD

**Issue by gregorp** [tidyverse/tidyr#952]
On the `?fill` help page, there is no statement that `fill` knows to respect groups from `dplyr::group_by`. (The last example does demonstrate this.) Same on the `?expand` and `?complete` help pages, possibly other functions too. It would be great if there was a standard sentence or phrase that was part of the `Description` section for all non-`dplyr` functions that know what to do with a `grouped_df`. Perhaps "Respects tibble groupings".

I think this would both serve as a good reference (I constructed a little example before posting thing to check on `expand`... I was pretty sure it respected groups but needed to check to see), and also for those new users who read help pages it might help cement the concept that `group_by` isn't magic that works with every function, only specially constructed functions.

**Comment by DavisVaughan** [comment]
https://github.com/tidyverse/tidyr/pull/1300 mentions in the docs that `complete()` and `expand()` work with grouped data frames, and adds examples
