### ISSUE TITLE
Want to use predicates to select columns.

### ISSUE THREAD

**Issue by jam1015** [tidyverse/tidyr#957]
---

I was running this code

```r
[irrelevant code]  %>%  pivot_longer(cols = is.numeric, names_to = "sample")
[irrelevant code]  %>%  pivot_longer(cols = force(is.numeric), names_to = "sample")

```

and got this error message both times: 

```r
Error: This tidyselect interface doesn't support predicates yet.
ℹ Contact the package author and suggest using `eval_select()`.
```

So here I am contacting you!  Will try to figure out eval_select() later but don't have time now.  My apologies if StackOverflow would be a better outlet for this issue.

**Comment by hadley** [comment]
This is implemented in the development version.
