### ISSUE TITLE
`replace_na` fails on a tibble when a variable is named `0`

### ISSUE THREAD

**Issue by mstackhouse** [tidyverse/tidyr#963]
---

When using `tidyr::replace_na`, if a you're using the `replace` parameter for a list with multiple variables, if one of those variables in the named list is `0` then the function fails. It seems to interpret the variable name of `0` as an index rather than a variable name, despite properly recognizing the other numeric variable names (called using back ticks) as explicit variable names. 

I'm actually unsure if this is an issue with `tidyr` or `tibble` - because this issue didn't exist in `tibble_2.1.3` but was introduced when I updated to `tibble_3.0.1`. 

``` r
dat <- tibble::tibble(
  `2` = c(1, NA, 2), 
  `1` = c('a', NA, 'b'), 
  `0` = c(1, NA, 2)
)

tidyr::replace_na(dat, replace=list(
  `2` = 0,
  `1` = ''
  )
)
#> # A tibble: 3 x 3
#>     `2` `1`     `0`
#>   <dbl> <chr> <dbl>
#> 1     1 "a"       1
#> 2     0 ""       NA
#> 3     2 "b"       2

tidyr::replace_na(dat, replace=list(
  `2` = 0,
  `1` = '',
  `0` = 0
  )
)
#> Error: Must extract column with a single valid subscript.
#> x Subscript `var` has value 0 but must be a positive location.
```

<sup>Created on 2020-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Looks like this is a bug in tibble: https://github.com/tidyverse/tibble/issues/774

**Comment by krlmlr** [comment]
Upstream issue: https://github.com/r-lib/vctrs/issues/1131.
