### ISSUE TITLE
output for unnest_wider doesn't look quite like example in docs

### ISSUE THREAD

**Issue by gershomtripp** [tidyverse/tidyr#976]
Example in tidyr [docs](https://tidyr.tidyverse.org/reference/hoist.html) `df %>% unnest_wider(y, names_sep = "_")` says output should look like this:
```
# A tibble: 3 x 4
      x   y_1   y_2   y_3
  <int> <int> <int> <int>
1     1    NA    NA    NA
2     2     1     2     3
3     3     4     5    NA
```

When in fact output looks like this:
```
# A tibble: 3 x 4
      x y_...1 y_...2 y_...3
  <int>  <int>  <int>  <int>
1     1     NA     NA     NA
2     2      1      2      3
3     3      4      5     NA
```
I could submit pull request with corrected output, but maybe you want the output to look like the example, and would thus prefer a code fix? I'm not sure I can help in the latter case.

**Comment by hadley** [comment]
Given that the docs are automatically generated from the package, I suspect it's you who is seeing the incorrect results. Have you installed tidyr 1.1.0?

**Comment by gershomtripp** [comment]
You're correct. I didn't realize tidyr in tidyverse isn't necessarily the most up-to-date version.
