### ISSUE TITLE
separate_rows not handling numerical values that use scientific notation 

### ISSUE THREAD

**Issue by esriis** [tidyverse/tidyr#978]
Brief description of the problem

If separate_rows is used on list of numerical values and a value is of order < 1e-5, i.e. 3e-6, then separate_rows returns two separate observations, "3e" and "-6", rather than "3e-6".

```r
test <- data.frame("vec" = c(0.0034,0.0000005))
output <- tidyr::separate_rows(test,'vec')
```

**Comment by hadley** [comment]
You'll need to change the default `sep` argument.
