### ISSUE TITLE
no context menu when entering function arguments (tidyr 1.1.0)

### ISSUE THREAD

**Issue by saraikinuv** [tidyverse/tidyr#979]
After I updating to tidyr version 1.1.0 no context menu when entering function arguments
![pic_01](https://user-images.githubusercontent.com/62558934/83631517-4c364280-a5a6-11ea-97bf-9f210f86720c.png)
![pic_02](https://user-images.githubusercontent.com/62558934/83631542-58ba9b00-a5a6-11ea-8138-d4236896f417.png)

---
```r
df <- tibble(id = 1, wk1 = 0, wk2 = 4, wk3 = 9, wk4 = 25)
```

**Comment by hadley** [comment]
I can't reproduce this unfortunately.

<img width="409" alt="Screenshot 2021-02-18 at 12 09 45 PM" src="https://user-images.githubusercontent.com/4196/108401662-31623780-71e2-11eb-8180-7d615b842826.png">
