### ISSUE TITLE
Feature request: Add detail to error messages with `names_repair`

### ISSUE THREAD

**Issue by billdenney** [tidyverse/tidyr#987]
When using `pivot_wider()`, I accidentally created duplicate column names.  That was not my intent, but the error message provided made it take a bit more effort to find what the underlying problem was.

It would help if `names_repair` provided specific error messages indicating what was bad about the names (and possibly how to fix it).

For the toy example below, it would be helpful if the message were something like:

```
Error: Failed to create output due to bad names:  The name "A" is duplicated.
* Choose another strategy with `names_repair`
```

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
pivot_wider(
  data.frame(A=1, B="A", C=3),
  names_from="B",
  values_from="C"
)
#> Error in pivot_wider(data.frame(A = 1, B = "A", C = 3), names_from = "B", : could not find function "pivot_wider"
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Actual reprex:

``` r
library(tidyr)

df <- tibble(A = 1, B = "A", C = 3)
pivot_wider(df, names_from = "B", values_from = "C")
#> Error: Failed to create output due to bad names.
#> * Choose another strategy with `names_repair`
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
FWIW tibble throws some fairly specific errors around name repair:

`error_column_names_must_be_unique()`:

https://github.com/tidyverse/tibble/blob/ba6b95ee0a55430fe66f61312276c8e9ae1f23b5/R/names.R#L27

The test output looks pretty close to what @billdenney is hoping for here:

```
> error_column_names_must_be_unique("a", repair = FALSE)
<error/tibble_error_column_names_must_be_unique>
Column name `a` must not be duplicated.

> error_column_names_must_be_unique(letters[2:3], repair = TRUE)
<error/tibble_error_column_names_must_be_unique>
Column names `b` and `c` must not be duplicated.
Use .name_repair to specify repair.

> error_column_names_must_be_unique(LETTERS, repair = TRUE)
<error/tibble_error_column_names_must_be_unique>
Column names `A`, `B`, `C`, `D`, `E`, and 21 more must not be duplicated.
Use .name_repair to specify repair.
```

**Comment by hadley** [comment]
Just needs an update to `wrap_error_names()` now that vctrs can generate the message with custom arg name:

```R
wrap_error_names <- function(code) {
  withCallingHandlers(
    code,
    vctrs_error_names = function(cnd) {
      cnd$arg <- "names_repair"
      cnd_signal(cnd)
    }
  )
}
```
