### ISSUE TITLE
Clarify `drop_na` and `replace_na` descriptions

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverse/tidyr#991]
The description for `drop_na` is;
> Drop rows containing missing values

As an end-user, `list(NA)` and `c(NA)` seem to exhibit equal degrees of "missing"-ness.  But the behavior of `drop_na` and `replace_na` treats them differently.  Instead for list columns, "missing" is to be interpreted as `NULL`, but that is non-obvious.

What is a "missing value"?  Well I can't seem to find anything concrete referring to what "missing" should mean in a list column of a data-frame.  The relevant section from [An Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Missing-values) only discusses missing-ness in regards to vectors, and doesn't even mention `NULL`.  

Looking deeper, the [R Language Definition](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Constants) has
> NULL is used to indicate the empty object. NA is used for absent (“Not Available”) data values. Inf denotes infinity and NaN is not-a-number in the IEEE floating point calculus (results of the operations respectively 1/0 and 0/0, for instance).

In any case, I think the documentation should be revised to define what is considered "missing".

**Comment by DavisVaughan** [comment]
Could link to `vctrs::vec_equal_na()` once we start using that for precise details
