### ISSUE TITLE
reciprocate of `hoist()` ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/tidyr#993]
I find it odd that this function doesn't have a reciprocate, it's also quite hard to achieve it by other ways : 

``` r
library(tidyr)
df <- tibble(x=1:2, listcol = list(list(a=3, b =4, c=5), list(a=6, b =7, c=8)))
print.data.frame(df) # as.data.frame just for printing
#>   x listcol
#> 1 1 3, 4, 5
#> 2 2 6, 7, 8
x <- hoist(df, listcol, "b")
print.data.frame(x)
#>   x b listcol
#> 1 1 4    3, 5
#> 2 2 7    6, 8
```

Say from here I want to modify the `b` column and put it back to its place, wouldn't it be handy to have something like : 

    unhoist(df, listcol, "b", .after = 1) # or `.after = "a"`, or `.before = "c"`

**Comment by jennybc** [comment]
Reminds me a bit of this conversation https://github.com/tidyverse/tidyr/issues/341, which is the `hoist()` origin story.

**Comment by hadley** [comment]
Currently these tools are specifically aimed at rectangling; and turning rectangles back into trees is out of scope for tidyr.

**Comment by moodymudskipper** [comment]
Ah... It seems it was indeed named specifically not to be tempted to think of this features.

But I'd like to comment on the reason though:

> The goal of tidyr is to help people move towards the golden path of useful data structures in R, not away from it.

* We might need to edit data and feed it back to a system in its original format (some json like format for instance)

* Say my list column contains a named list of parameters for each observation, potentially dozens of them, but many of them missing.  Any of these parameters once extracted will create a sparse column and distract from the more important columns of my table. It's not clear in that case that the rectangle is the best representation, but it's useful for some temporary manipulations as our brain struggle more with trees.
