### ISSUE TITLE
`crossing()` a zero-row data frame

### ISSUE THREAD

**Issue by burchill** [tidyverse/tidyr#994]
I believe it used to be that `tidyr::crossing(x=1:3, data.frame())` would return a value equivalent to `data.frame(x=1:3)`, but now it seems that `tidyr` returns a zero-row data frame with the column `x`.

I personally find the idea that crossing something with an empty data frame and returning the original value (in data frame format) to be more intuitive and much more useful.  It also would parallel behavior with a `NULL` argument.  Unless there's a principled decision behind this that I'm now aware of?

**Comment by hadley** [comment]
I think the principle is that `nrow(crossing(x, y))` should equal `nrow(x) * nrow(y)`, so if either `x` or `y` is a 0 row data frame the output will be a zero row data frame.

**Comment by burchill** [comment]
Though technically (and less succinctly), you mean the number of _unique_ rows in x times the number of _unique_ rows in y though, right?  I guess it makes more sense when considering the original `expand_grid()` function, thanks!

**Comment by hadley** [comment]
Ah yes, I always forget that about `crossing()` 😄
