### ISSUE TITLE
hoist(): simplify only works for all columns or none

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#995]
The `.simplify` argument doesn't allow to choose which columns should be simplified. One can only choose between all columns (`TRUE`) or none (`FALSE`). It would be nicer if one could choose which columns should be simplified.

**Comment by hadley** [comment]
I think that's reasonable, but it's not clear what the interface should be. A logical vector? A character vector of variables to simplify? A tidyselect specification?

**Comment by mgirlich** [comment]
Tidyselect specification
\+ flexible
\+ known to users
\- very different from how to specify `ptype` and `transform`

Character vector
\- feels mostly like an inferior version of the tidyselect specification

(Named) logical vector
\+ more similar to `ptype` and `transform`
\- less flexible than tidyselect

I like the flexibility one gains with the tidyselect specifiation but as `ptype` and `transform` do not provide it and tidyselect isn't used in other parts of the functions I'd go with a logical vector.

**Comment by hadley** [comment]
@DavisVaughan named list solution sounds good.
